cyrusimap/cyrus-imapd

- lib/cyrusdb.c
> cyrusdb_generic_archive: skip unreadable databases

- imap/message.c
This addresses #21.  
Pull request rather than just pushing to master, cause I'd like more eyes on this -- it's deep code and I don't know with certainty that I haven't missed a detail.
Cassandane test for this (Fetch.duplicate_headers) is already on master.
> use last occurrence of headers, not first

- cmulocal/perlmake.m4
> perlmake.m4: change to use perl instead of sed for portability

- docsrc/conf.py
- docsrc/imap/reference/manpages/commands.rst
- docsrc/imap/reference/manpages/systemcommands/ptdump.rst
- docsrc/imap/reference/manpages/systemcommands/ptexpire.rst
- docsrc/imap/reference/manpages/systemcommands/ptloader.rst
Fleshed out details for ptexpire(8), ptdump(8) and ptloader(8)
to replace the skeleton files which were there.
Moved these man pages from "work in progress".
> Update man pages for the PTS group of commands.

- docsrc/imap/reference/manpages/systemcommands/squatter.rst
Man page for squatter updated to accord with proper usage, as per @rsto update in 4643639.  Further to #1826
> Update squatter man page to match actual usage.

- docsrc/imap/download/upgrade.rst
Add steps for using translatesieve during the upgrade process.
Also move around some sections and provide explicit instructions
on copying data and state information from old instance to new, etc.
> Add translatesieve steps to update.rst, etc.

- docsrc/imap/reference/manpages/systemcommands/squatter.rst
Following discussion in #1833, i've removed the Sphinx notes from squatter.rst.
> Removed SPhinx-specific notes from squatter man page.

- docsrc/imap/reference/admin/locations/mailspool.rst
- docsrc/imap/reference/admin/locations/searchtiers.rst
- docsrc/imap/reference/admin/sop/splitting-metadata.rst
Complete the mailspool location doc and add a new locations doc
for Xapian search tiers.
> Complete the mailspool location doc, etc.

- docsrc/imap/reference/manpages/configs/cyrus.conf.rst
- master/README
Add information about new DAEMON section to man page and sample
for cyrus.conf(5) file.
> Update cyrus.conf(5) man page and sample

- docsrc/conf.py
- docsrc/imap/reference/manpages/commands.rst
- docsrc/imap/reference/manpages/systemcommands/cyr_userseen.rst
Create a man page for the cyr_userseen command.
> Replace empty man page for cyr_userseen

- docsrc/conf.py
- docsrc/imap/release-notes/index.rst
- docsrc/index.rst
supporting /<version> and /<dev>
> 2.5 directory restructure shuffle

- imap/mboxlist.c
> Correctly calculate INBOX for user names containing a dot character

- imap/lmtpengine.c
> Unbreak delivery to shared mailboxes if using virtdomains

- docsrc/assets/mailspool-parts-explain.rst
- docsrc/assets/metadata-parts-explain.rst
- docsrc/imap/concepts/features.rst
- docsrc/imap/concepts/features/archiving.rst
- docsrc/imap/concepts/features/mail-spool-partitions.rst
- docsrc/imap/concepts/features/mailbox-metadata-partitions.rst
- docsrc/imap/reference/admin/locations.rst
- docsrc/imap/reference/admin/locations/archive-partitions.rst
- docsrc/imap/reference/admin/locations/mailspool.rst
Add new Concepts/Features/Archiving and Reference/Admin/Archive-partitions
pages.
Split some verbage out of the meta-data and mail spool partitions
into new asset documents, and incorporate back where they were and
elsewhere.
> Add documentation for Archiving and related partitions.

- docsrc/imap/reference/admin/sop/replication.rst
This is to address issue #1928.
Note: This shouldn't be in SOP.  There must be a better place...
> Updated replication.rst for more completeness.

- docsrc/assets/cyrus-user-group.rst
- docsrc/assets/services.rst
- docsrc/imap/developer/basicserver.rst
- docsrc/imap/developer/github-guide.rst
- docsrc/imap/developer/installguide.rst
- docsrc/imap/developer/libraries/imclient.rst
- docsrc/imap/developer/namespaces.rst
- docsrc/imap/developer/process.rst
- docsrc/imap/developer/releasing.rst
I'm just testing the waters. Typically I'd send a huge spelling PR, but I'd like to have a sense of the project and some guidance before I start such a task.
> Doc cleanup

- lib/util.h
> lib/util.h include stdint.h

- .gitignore
- configure.ac
- libcyrus_imap.pc.in
- libcyrus_min.pc.in
- libcyrus_sieve.pc.in
> Pkgconfig pc

- doc/legacy/install-admin-mb.html
> site: Mulberry

- perl/imap/IMAP/Shell.pm
- perl/imap/cyradm.sh
Added examples and notes on use of getmetadata and setmetadata
commands in cyradm.
> Updated cyradm and other Perl docs for get/setmd

- docsrc/imap/developer/basicserver.rst
Add notes on how, in Debian, to recreate ephemeral directories
following reboot, from within init script.
This was written up in response to @mobeats question on IRC:
>  trying to get stable cyrus 3 running on Debian Jesse following the basicserver guide - what is the fix for /var/run/cyrus being deleted after a reboot please?
> Add notes to basicserver.rst on preserving /var/run

- .travis.yml
- README.md
Also display the build status in the README
> [ci] Add .travis.yml and enable CI

- .travis.yml
- README.md
Just build `xapian` and install the rest of the dependencies using the
package manager.
> [ci] travis.yml cleanups.

- imap/cyr_expire.c
This patch does a fair bit of tidying up `cyr_expire`:
* Add a wrapper functino for verbose printing.
* Cleanup in signal handler (avoid checking if singal has been handled)
* Refactor the argument parsing, initialisation and cleanup code.
> cyr_expire: Cleanup.

- .travis.yml
As per this blog: https://blog.travis-ci.com/2017-06-19-trusty-updates-2017-Q2
> Update travis.yml for trusty.

- .travis.yml
Enable travis integration with slack. The credentials are encrypted as per
instructions available here[1].
[1] - https://docs.travis-ci.com/user/notifications/#Configuring-slack-notifications
> [ci] Travis slack integration.

- docsrc/imap/reference/faqs/o-annotations.rst
- docsrc/imap/reference/manpages/systemcommands/cyr_expire.rst
`cyr_expire` has additional annotations.
see commit 757e6cb3a20c26da798a844ed12f918787e5e19f
> [docs] Update documentation for cyr_expire.

- .travis.yml
> [travis] Do not notify pull requests.

- docsrc/assets/cyrus-user-group.rst
- docsrc/conf.py
- docsrc/imap/download/installation/http/caldav.rst
- docsrc/imap/download/installation/http/carddav.rst
- docsrc/imap/download/installation/http/jmap.rst
- docsrc/imap/download/installation/http/rss.rst
- docsrc/imap/download/installation/http/webdav.rst
- docsrc/imap/download/installation/manage-dav.rst
> [Docs] Show that included snippets are just defaults.

- imap/jmap_mail.c
`jmapmsg_from_body()` uses an integer for `is_embeded` variable, changing that
to an enum for clarity.
> [imap] Use an enum in jmapmsg_from_body().

- imap/autocreate.c
The autocreate_sieve() function needed a little bit of love.
> [sieve] Cleanup clutter in autocreate_sieve().

- docsrc/conf.py
- docsrc/imap/download/release-notes/3.0/x/3.0.3.rst
- docsrc/imap/download/release-notes/3.0/x/3.0.4.rst
These were missing from master.
> Release notes for 3.0.3 and 3.0.4.

- docsrc/_templates/layout.html
- docsrc/index.rst
> [Docs] Freshen front page and fix menu bar links.

- imap/search_xapian.c
This patch uses 2 locks for Xapian search:
* The current `activefile` lock that we use
* A new named lock.
The named lock will be on a file whose name looks like
$XAPIAN<userid>.lock.
Details about the implementation are available here[1].
[1] https://github.com/cyrusimap/cyrus-imapd/blob/master/doc/internal/locking.txt
> [xapian] Locking rewrite in Xapian search module.

- docsrc/imap/reference/manpages/systemcommands/squatter.rst
The squatter.8 man page was vague about differences between the
squatter command and the old SQUAT search engine.  Comments have
been added to clarify this.
Notes have been added or strengthened in regards to SQUAT vs.
Xapian indexing; requirements for rolling operation; where in
cyrus.conf to invoke squatter; etc.
The example for incremental operation used the wrong flag, -s
rather than -i.
Addresses #2234
> Update squatter.8 manpage for clarity

- lib/imapoptions
How's this look, wrt discussion in #2234?
> imapoptions: improve docs for sync_log_channels

- docsrc/overview/cyrus_roadmap.rst
https://github.com/cyrusimap/cyrus-imapd/pull/2223
https://datatracker.ietf.org/wg/jmap/documents/
> Clarify status of JMAP support

- doc/internal/cyrusdb-api.html
As per suggestion from elliefm. Should close #2573
> Update documentation of cyrusdb_sync function

- imap/lmtp_sieve.c
@elliefm I think that this will fix #2449
> Fix #2449: null user ID on sieve mail reject

- configure.ac
- lib/imapoptions
- lib/util.c
- lib/util.h
> Add support for changing the group used by Cyrus

- imap/carddav_db.c
- imap/mailbox.c
When making changes to contacts, either by adding or removing them in
the addressbooks or pinning the contact, make sure to update the
`vcard_emails` and `vcard_groups` tables.
> carddav: Update groups and ispanned status.

- configure.ac
- lib/imapoptions
- lib/util.c
- lib/util.h
See https://github.com/cyrusimap/cyrus-imapd/issues/2639#issuecomment-461779653.
> Add support for changing the group used by Cyrus (again)

- docsrc/imap/reference/manpages/systemcommands/squatter.rst
• State, that -v can be used in any mode except indexfrom.
• State, that in squatter -u *users* and squatter *mailboxes* the items are space separated.
• In the synopsis, consistently surround options with spaces
> Update documentation for squatter (3.0)

- .gitignore
Commit 345744ca50 moved vzic from cyrus-imapd to cyrus-timezones.
> .gitignore: remove vzic/

- imap/xapian_wrap.cpp
For iterators, prefer ++it over it++.  The former creates a copy of the iterator, modifies the original and returns the copy.  The latter modifies the original and returns it, without creating copies.
In the constructor of CyrusSearchStemmer pass "en" directly to the member stem of type Xapian::Stem, which will call the Xapian::Stem constructor, instead of creating a Xapian::Stem("en") object, and copying its result in the member stem.
In xapian_snipgen_add_match: abolish variable r.
Change the type of make_lang_count_key to accept as second parameter const std::string&.  This avoids converting std::string to char* and constructing from it a temporary std::string, instead of using all the time the original string.
In xapian_snipgen_begin_doc: avoid calling two constructors for snippet.
> imap/xapian_wrap.cpp: C++ tweaks

- docsrc/imap/concepts/deployment/authentication_and_authorization.rst
- docsrc/imap/concepts/deployment/databases.rst
- docsrc/imap/concepts/deployment/deployment_scenarios.rst
* replace \&mdash; with ---, as the latter form works with non-HTML output, like epub
* state that the annotations database also stores WebDAV properties
> state that the annotations database also stores WebDAV properties (master)

- docsrc/imap/concepts/deployment/authentication_and_authorization.rst
- docsrc/imap/concepts/deployment/databases.rst
- docsrc/imap/concepts/deployment/deployment_scenarios.rst
- docsrc/imap/reference/manpages/systemcommands/master.rst
* replace \&mdash; with ---, as the latter form works with non-HTML output, like epub
* state that the annotations database also stores WebDAV properties
> state that the annotations database also stores WebDAV properties (3.0)

- imap/index.c
Status code can be trampled inside `http_read_response` in certain failure conditions, so it being non-zero is not enough of an indicator of success.
```
019-09-19T15:05:15.553914-04:00 imap99 sloti99d1t03/squatter[879305]: indexing mailbox user.robntest@fastmail.fm...
2019-09-19T15:05:15.554285-04:00 imap99 sloti99d1t03/squatter[879305]: extractor_connect(http://localproxy:9871/extract)
2019-09-19T15:05:15.554291-04:00 imap99 sloti99d1t03/squatter[879305]: extractor_connect: ping existing connection
2019-09-19T15:05:15.554350-04:00 imap99 sloti99d1t03/squatter[879305]: extractor_ping: HEAD /extract: failed (-1964266953): Unable to read status-line from backend
2019-09-19T15:05:15.554354-04:00 imap99 sloti99d1t03/squatter[879305]: extractor_disconnect(0x24f37f0) …
```
> index: handle extractor ping failure properly

- imap/http_admin.c
- imap/http_caldav_sched.c
- imap/http_tzdist.c
- imap/httpd.c
- lib/times.c
- lib/times.h
- netnews/remotepurge.c
and put that variable (wday/monthname) into read-only segment.
> lib/times: consolidate month and weekday names into one variable

- com_err/et/com_err.texinfo
- doc/examples/cyrus_conf/murder-backend.conf
- doc/legacy/changes.html
- doc/legacy/install-murder.html
- docsrc/imap/download/release-notes/2.2/2.2.x.rst
- docsrc/imap/reference/manpages/systemcommands/chk_cyrus.rst
- docsrc/imap/reference/manpages/systemcommands/ctl_mboxlist.rst
- docsrc/imap/reference/manpages/systemcommands/reconstruct.rst
- docsrc/imap/reference/manpages/systemcommands/restore.rst
- imap/chk_cyrus.c
- lib/imapoptions
- sieve/bc_generate.c
- sieve/interp.c
- sieve/interp.h
- sieve/script.c
- sieve/sieve_err.et
- sieve/sieve_interface.h
Hi,
updated patch (fixes: #2842).
> Fix some spelling errors

- doc/legacy/changes.html
- doc/legacy/overview.html
- docsrc/imap/download/release-notes/2.0/2.0.x.rst
- imap/spool.c
- perl/imap/IMAP/Shell.pm
- perl/sieve/managesieve/managesieve.xs
- sieve/test.c
Hi,
some new spelling errors reported by Lintian _([Debian](https://www.debian.org) quality assurance tool)_.
Cheers,
Xavier
> Spelling errors reported by Lintian

- docsrc/imap/support/feedback-mailing-lists.rst
Not clear what to do with "Anonymous IMAP" label...
> Removing dead links

- imap/imapd.c
- imap/imapparse.c
- imap/imapparse.h
- imap/index.c
- imap/sequence.c
> Imap esort

- imap/lmtp_sieve.c
- imap/lmtpd.c
- imap/lmtpd.h
- sieve/bc_eval.c
- sieve/message.c
- sieve/message.h
- sieve/script.c
- sieve/sieve_interface.h
Possible solution to issue #3023
> Sieve: the last keep / fileinto "INBOX" should always win

- imap/sync_support.c
Hi Ken, bloody intermediates again.  This one goes along with the sync-intermediates branch on cassandane, which tests the case.
CREATE INBOX.folderA.folderB.folderC
RENAME INBOX.folderA INBOX.folderZ
And ensures that replication is clean and the uniqueid remains with it.
> Sync intermediates

- imap/jmap_mail.c
This PR only allows downloading BIMI blobs.  Blob/copy won't work, just like iCalendar/vCard blobs.  If we need /copy it will take some more work
> Jmap bimi blobs

- imap/jmap_calendar.c
Recently introduced https://github.com/cyrusimap/cyrus-imapd/commit/9aeb3d9794c4be941c5359c514c3ff9fdd9af89d only sets the ACL for owner and admin on newly created users. This causes the following case the fail: user A shares their account with B, B creates a calendar in account A.
We probably don't even want to support that use case, but we currently have breaking Cassandane tests which assume we can!
> jmap_calendar: ignore ACL when updating newly created calendar

- cunit/conversations.testc
- imap/conversations.c
- imap/message.c
See https://github.com/cyrusimap/cyrus-imapd/issues/2873
This is a WIP until we have agreed on the final regex.
> Normalise non-ASCII subject replies and filter brackets

- Makefile.am
- configure.ac
- imap/cyr_buildinfo.c
> Remove cld2 dependency checks

- imap/jmap_api.c
- imap/jmap_api.h
- imap/jmap_contact.c
- imap/jmap_mail.c
- imap/jmap_mdn.c
Start of uniform handling of blobs.
Now need to move handling of "smart" blobIds into jmap_findblob() and out of Blob/get
> Jmap blob handling

- imap/xapian_wrap.cpp
We limit the indexed term size to be at most 200 bytes (in UTF-8), but it turns out that this check only is applied by Xapian to the unstemmed term. For a couple codepoints the stem in Cyrus search form can be substantially longer, and we return an empty string as a stem in this case to make Xapian ignore that stem.
There's a test for that at https://github.com/cyrusimap/cassandane/tree/xapian_unicode_fdbx
> xapian: don't index stemmed terms larger than max term size

- imap/jmap_contact.c
We declare the /get /query and /changes methods to support shared cstates, but this breaks if try to create the default addressbook. This patch makes Cyrus bail out early if the account has no addressbook at all.
> jmap_contact: don't create default addressbook with shared cstate

- imap/jmap_calendar.c
That's just a rehash of what we just did in https://github.com/cyrusimap/cyrus-imapd/pull/3132
> jmap_calendar: don't create default calendar with shared cstate

- imap/http_caldav.c
- imap/http_caldav.h
- imap/http_caldav_sched.c
- imap/http_dav.c
- imap/http_dav.h
- imap/jmap_calendar.c
- imap/mboxname.c
There's Cassandane tests at https://github.com/cyrusimap/cassandane/tree/caldav_scheddefault_move
> CalDAV: support PROPPATCH for default-scheduling-calendar property

- imap/index.c
As promised Robert, the indexer "retry 3 times" logic.  I'll put some comments in to describe why I did things.
> index: try three time to POST to the extractor

- imap/sync_client.c
- imap/sync_support.c
This is designed to make sure that we don't get "mailbox changed" errors back from renamed mailboxes.
> Sync rename redo

- imap/xapian_wrap.cpp
Also, don't try again for every subject is there's no stemmer!
> xapian_wrap: doclang is a set

- docsrc/imap/developer/compiling.rst
> compiling.rst: add explanation for CLD2 dependency

- imap/jmap_api.h
- imap/jmap_core.c
- imap/mboxname.c
As requested by Rob M - a way to get at usercounters via JMAP to avoid having to make an IMAP connection for session setup :)
> Usercounters

- docsrc/imap/reference/manpages/systemcommands/squatter.rst
- imap/jmap_mail_query.c
- imap/search_engines.c
- imap/search_engines.h
- imap/search_xapian.c
- imap/squatter.c
- imap/xapian_wrap.cpp
- imap/xapian_wrap.h
Quite tested now - it's been running very happily on production for a while :)  One bug which I'll push a commit for.  I don't think we need to rebase it all together.
> Reindex chunk

- Makefile.am
- backup/restore.c
- docsrc/imap/reference/manpages/systemcommands/sync_client.rst
- imap/http_dav.c
- imap/http_jmap.c
- imap/httpd.c
- imap/imapd.c
- imap/lmtpd.c
- imap/lmtpengine.c
- imap/nntpd.c
- imap/pop3d.c
- imap/sync_client.c
- imap/sync_log.c
- imap/sync_log.h
- imap/sync_server.c
- imap/sync_support.c
- imap/sync_support.h
- lib/imapoptions
This branch is now hopefully ready to run.  It does real time replication of many things, and still works with fallback as well.  It won't do anything until we deploy the config changes to turn it on.
> Sync rightnow

- imap/http_caldav_sched.c
This PR does two things:
1. When STATUS:CANCELLED is set by the organizer, METHOD:CANCEL iTIP messages are sent to attendees rather than METHOD:REQUEST iTIP messages
2. iTIP replies to STATUS:CANCELLED instances are ignored
Both of these issues were discovered by @rjbs via some manual testing.
With this PR applied, all Cass tests still pass as usual.  I have a new test for #1.  Working on a test for 2
> http_caldav_sched.c: Properly handle STATUS:CANCELLED

- imap/annotate.c
- imap/imapparse.c
- imap/jmap_backup.c
- imap/jmap_core.c
- imap/jmap_mail.c
- imap/jmap_mailbox.c
- imap/mboxname.c
- imap/message.c
- imap/search_xapian.c
- imap/xapian_wrap.cpp
- sieve/script.c
… because buf_release(x) calls buf_free(x).
> buf_free(x) after buf_release(x) does not do anything

- imap/tls.c
- imtest/imtest.c
otherwise OpenSSL will eventually garbage collect it out from under us, causing a crash when we try to reuse it.  Also free it properly when we're done with it.
Same also for imtest.
Fixes #3191, and maybe #2979
> tls: make sure saved session is refcounted

- docsrc/imap/download/installation/http/caldav.rst
- docsrc/imap/reference/manpages/systemcommands/ctl_zoneinfo.rst
- imap/ctl_zoneinfo.c
I do not know what '-w file' does.
> ctl_zoneinfo: update documentation

- imap/mailbox.c
This hopefully fixes the lock ordering crap
> mailbox: release mboxname lock while taking conversations lock

- imap/sync_support.c
- imap/sync_support.h
- lib/imapoptions
Cache mailbox state and use the cache where possible!
> Sync cache

- imap/jmap_mailbox.c
I've got Cassandane tests for this over at:
https://github.com/cyrusimap/cassandane/pull/97
> Jmap name safety

- imap/annotate.c
- imap/imapd.c
- lib/libconfig.c
- lib/libconfig.h
Tested in https://github.com/cyrusimap/cassandane/commit/f23d7ad9b440530f445651b4d204488c8050bf80
> imapd: allow to override search_fuzzy_always by annotation

- imap/xapian_wrap.cpp
Nibbling away at converting existing IOERRORs to use xsyslog.  This time, xapian_wrap.cpp.
There's a few spots where I'm not quite sure what to do and have added XXX comments, feedback/discussion would be appreciated!
Please read closely, but also build/test, just in case your compiler finds problems that mine doesn't.
> xapian_wrap: use xsyslog for IOERRORs

- imap/sync_server.c
- imap/sync_support.c
> sync: use xsyslog for IOERRORs

- lib/mappedfile.c
More xsyslog conversions...
I'm particularly interested in thoughts about the lseek errors' "offset" argument.  At first blush I thought the casting was just an old workaround for not having a format string for `off_t`, so I converted them to use `OFF_T_FMT`.  But I've since noticed they were printing in hex too, which is lost by using `OFF_T_FMT`.
So the question is, do we care about these offsets being printed as hex?  It's worth observing that `off_t` is signed, and the signedness is lost when we print as hex...
> mappedfile: use xsyslog for IOERRORs

- lib/sqldb.c
More xsyslog conversions.  Please make sure this builds, in case your compiler finds things mine doesn't.
> sqldb: use xsyslog for errors

- imap/mboxlist.c
More xsyslog conversions.  Please build this, in case your compiler catches anything mine missed.
> mboxlist: use xsyslog for errors

- imap/http_dav_sharing.c
@elliefm …just something I saw in the wild while on my rounds.  I think this is right but haven't even compiled.
> dav sharing: xsyslog-ify an error seen in the wild

- lib/cyrusdb_skiplist.c
More of this.  As usual, please try building this too, in case your compiler finds something mine didn't.  Thanks!
> cyrusdb_skiplist: use xsyslog for errors

- imap/message.c
More of this.  Please try building it, in case your compiler catches things mine doesn't.  Thanks :)
> message: use xsyslog for errors

- cunit/message.testc
- doc/legacy/ag.html
- doc/legacy/install-upgrade.html
- docsrc/imap/concepts/features/server-aggregation.rst
- docsrc/imap/download/installation/manage-dav.rst
- docsrc/imap/download/release-notes/1/1.x.x.rst
- docsrc/imap/download/release-notes/2.2/2.2.x.rst
- docsrc/imap/download/release-notes/3.2/x/3.2.0.rst
- docsrc/imap/reference/admin/locations/searchtiers.rst
- docsrc/imap/reference/admin/murder/murder-concepts.rst
- docsrc/imap/reference/architecture.rst
- docsrc/imap/reference/manpages/systemcommands/master.rst
- docsrc/imap/reference/manpages/usercommands/installsieve.rst
- docsrc/imap/rfc-support.rst
- imap/userdeny_db.c
- lib/imapoptions
- lib/imclient.c
- lib/times.c
- perl/imap/IMAP.pm
- perl/imap/IMAP/Admin.pm
backport from master: 6b16e98cec9a820e41c856c,  6cbab17b2ecff3466ea3062, a7502f6b8bf02ac96f18d65, and 13c7bc60ac03728d540db66.
> 3.4 - Typos

- changes/next/contact_blobid
- imap/http_jmap.c
- imap/jmap_api.c
- imap/jmap_api.h
- imap/jmap_calendar.c
- imap/jmap_contact.c
- imap/jmap_mail.c
- imap/jmap_sieve.c
Matching PR for Cassandane exists
> Contact blobid: Always return 'blobId' in /set{create.update} and  /get responses.

- lib/cyrusdb_twoskip.c
More of this.  Please try to build it, in case your compiler finds stuff mine doesn't.
There's a couple of log lines where I'm not sure what the variables being logged represent, which makes it hard to name them well.  I've annotated these with XXX comments, guidance would be appreciated!
> cyrusdb_twoskip: use xsyslog for errors

- imap/jmap_ical.c
Fixes a bug where libical returns NULL for empty property values, causing Cyrus to crash.
> jmap_ical: gracefully handle empty property values

- imap/jmap_calendar.c
- imap/jmap_contact.c
- imap/jmap_util.c
- imap/jmap_util.h
Consolidates encoding and decoding of blobIds for raw iCalendar/vCard data
> Jmap rawdata blobids

- imap/index.c
Until now, if a message only has a single text/calendar part as top-level, we only indexed the iCalendar data and ignored the MIME headers. Tested in https://github.com/cyrusimap/cassandane/commit/5adee7dc322a4ff741a58417d23c432941de01c3
> index: index MIME headers also for text/calendar messages

- lib/cyrusdb.c
- lib/cyrusdb_flat.c
- lib/cyrusdb_quotalegacy.c
- lib/cyrusdb_sql.c
More of this.  Please fetch and build this branch, in case your compiler finds problems mine doesn't
> convert remaining cyrusdb modules to use xsyslog

- changes/next/create_no_intermediates
- imap/imapd.c
Relevant Cass changes are here: https://github.com/cyrusimap/cassandane/pull/111
> Create no intermediates

- imap/index.c
We have two ancient existing issues open for this so maybe we should just fix it finally...
RFC 4314 says:
> STORE operation SHOULD NOT fail if the user has rights to modify
> at least one flag specified in the STORE, as the tagged NO
> response to a STORE command is not handled very well by deployed
> clients
This changes the rights check in index_store as follows:
* if we are trying to change a flag, but don't have the correct permission for it, remove that flag from the set to change
* if, after removing disallowed flags from the set to change, the set is now empty, then fail with permission denied
These behaviours only apply for "STORE +flags" and "STORE -flags" because these are the only ones it made sense for, though the RFC isn't clear that it should only apply to these.
If the …
> index: handle STORE flags acls per rfc 4314

- imap/notify.c
There's a lot and they mean nothing!
> notify: don't log successful response from notifyd

- imap/http_jmap.c
- imap/jmap_api.c
Tests added in https://github.com/cyrusimap/cassandane/pull/112
> Jmap shared upload collection

- imap/jmap_mail.c
Tested in https://github.com/cyrusimap/cassandane/commit/9a458dab9a777aa8eff9b348063f0fffc3c87aa8
> jmap_mail: email updates must result in non-empty mailboxIds

- imap/mboxname.c
- imap/sync_support.c
- lib/util.c
- sieve/rebuild.c
As usual, please also build this, not just eyeball it.
This one might be on the edge of too big to review in one go.  Let me know if that's the case and I'll split it up a bit.
This one required Cassandane updates because a bunch of our replication tests want to check for specific things in syslog.  But I have already made those updates in a backward-compatible fashion and merged them to master, so as long as your Cassandane is up to date, it should still pass as usual.
> more xsyslog conversions

- imap/http_caldav.c
Tested in https://github.com/cyrusimap/cassandane/commit/4e85bbac482b432a1645725b0b3fc1c562fab847
> http_caldav: scheduled resource must set both ORGANIZER and ATTENDEE

- changes/next/ws_timeout
- imap/http_h2.c
- imap/http_h2.h
- imap/http_jmap.c
- imap/http_ws.c
- imap/http_ws.h
- imap/httpd.c
- imap/httpd.h
- lib/imapoptions
This branch sits on top of the ws_h1_fix branch
> Add a timeout to WS connections

- changes/next/ws_jmap_push
- changes/next/ws_timeout
- imap/http_h2.c
- imap/http_h2.h
- imap/http_jmap.c
- imap/http_ws.c
- imap/http_ws.h
- imap/httpd.c
- imap/httpd.h
- lib/imapoptions
This branch sits on top of the ws_timeout branch
> Implement JMAP/WS push

- imap/jmap_contact.c
and consolidate address, email, phones gathering code into a single for loop
> jmap_contact.c: strip weird Apple (localization?) wrapper from labels

- imap/jmap_mailbox.c
Mailbox renames result in two mboxlist entries with the same uniqueid and modseq, one of them being deleted. Until now, Mailbox/changes either reports this mailbox id in `updated` or `destroyed`, depending on mboxlist traversal order. This patch changes this to always prefer reporting equal modseq changes in `updated` over `created` or `destroyed`.
Tested in https://github.com/cyrusimap/cassandane/commit/08d5b4227964c43b5986a7e6e2dbfe4c2d34acf1
> jmap_mailbox: prefer to report changes in updated if modseqs match

- imap/append.c
As usual, please both read and build test.
@ksmurchison, gut feeling suggests this one in particular might conflict with the uuid branch.  If that's the case, I'm happy to leave it unmerged until we're ready to deal with it, lmk.
> append: use xsyslog for IOERRORs

- imap/jmap_contact.c
- lib/vparse.h
As it says on the tin.
Tested in https://github.com/cyrusimap/cassandane/tree/jmap_contact_xabadr
> jmap_contact: map X-ABADR property to address.countryCode

- imap/jmap_backup.c
This fixes the problem where drafts in a thread wouldn't be restored.  Using CID exclusively was faulty logic.
Tested with https://github.com/cyrusimap/cassandane/pull/128
> jmap_backup.c: when restoring drafts track actual Message-ID rather than conversation ID

- imap/jmap_calendar.c
- imap/jmap_contact.c
Tested in https://github.com/cyrusimap/cassandane/pull/129
> JMAP: enforce unique uid in Contact and CalendarEvent /set{create}

- imap/jmap_contact.c
- imap/vcard_support.c
Better handling of missing mediatype on vCard PHOTO property
> Contact avatar mediatype

- imap/ical_support.c
Fixes issue with events created/sent by Exchange
> ical_support.c: add missing END:VCALENDAR

- imap/jmap_ical.c
An early version of the jscalendar-icalendar RFC mapping draft included the experimental SUBSECOND parameter to store fractional seconds in iCalendar.
This parameter now got removed from the spec, so let's do the same in our implementation. The JMAP Calendars code in the current Cyrus releases is experimental and we are not aware of any application actually using fractional seconds.
A standard for storing fractional seconds in iCalendar is worked on at https://datatracker.ietf.org/doc/draft-douglass-icalendar-fractional-time/
Also updates Cassandane tests at https://github.com/cyrusimap/cassandane/pull/136
> jmap_ical: remove experimental SUBSECOND parameter

- imap/jmap_ical.c
Rewrites the overrides_from_ical function to read overrides from a pre-filled list, rather than looking them up within the function.
Passes all JMAP Email and Calendar tests.
> jmap_ical: use lookup table for VEVENT recurrence exceptions

- imap/jmap_ical.c
Similar to what we did in https://github.com/cyrusimap/cyrus-imapd/pull/3550 this patch organizes the old main VEVENT and overrides in a hash table for efficient lookup. Previously, this code could suffer from performance degradation for large VCALENDAR data.
This is an internal refactor, it passes all calendar regression tests, including Valgrind.
> jmap_ical: hash previous VEVENT versions by uid and recurid

- imap/imapd.c
- imap/mailbox.c
- imap/mboxlist.c
- imap/mboxname.c
- imap/mboxname.h
- imap/search_engines.c
- imap/search_engines.h
- imap/search_xapian.c
- imap/sync_reset.c
- imap/sync_support.c
- imap/sync_support.h
- imap/user.c
- imap/user.h
> UUID user_deletedata() fix

- imap/jmap_mail.c
Turns out we were calculating how much MORE to cache rather than what to cache up to, but the "loadn" API takes "up to here", not "this much more".  Doh.
> jmap_mail: load the cache correctly

- imap/http_h2.c
There are fewer instances to leave stream open than to close it so
changing the logic to reflect this seems to make sense
> http_h2.c: reverse end of headers logic

- imap/http_caldav.c
- imap/http_caldav_sched.c
Tested with https://github.com/cyrusimap/cassandane/pull/141 (a small tweak to a test written by @rsto)
> A change to ATTACH properties should trigger scheduling messages

- imap/autocreate.c
- imap/ctl_mboxlist.c
- imap/http_caldav.c
- imap/http_carddav.c
- imap/http_dav.c
- imap/http_dav_sharing.c
- imap/http_jmap.c
- imap/http_webdav.c
- imap/imapd.c
- imap/jmap_backup.c
- imap/jmap_calendar.c
- imap/jmap_mail_submission.c
- imap/jmap_mailbox.c
- imap/jmap_notes.c
- imap/lmtp_sieve.c
- imap/mboxlist.c
- imap/mboxlist.h
- imap/message.c
- imap/reconstruct.c
- imap/sync_support.c
@brong Just making sure that we're on the same page before I really dig into this.  mboxlist_createmailbox_full() will eventually become just mboxlist_createmailbox() and all callers will have to be changed similar to what I did with mboxlist_createmailbox_opts()  and mboxlist_createsync()
> New mboxlist_create() api

- imap/mboxlist.c
This should fix an issue we currently have where multiple processes try to upgrade the subscriptions DB at once.
By using the user_namespacelock, we make sure two processes don't upgrade at the same time!
We also check the xVERx key exactly rather than doing a foreach and hoping we never create an earlier key in the database, and check it again after taking the namelock to be sure that it hasn't been upgraded by a racing process.
> lock user namespace while upgrading 

- lib/cyrusdb_twoskip.c
This fixes a crasher when there was no DB file!  The `myclose(db)` call didn't check for NULL, and was aborting.
Also: we don't need to DBERROR if the file's not there, just quietly notice that it went away
> twoskip: don't abort if no database when delayed checkpointing

- imap/mboxlist.c
We can't just lock the userlock, because it might have
been readonly locked by a JMAP readonly action, and we
can't upgrade that!
We don't need this for FM prod any more, because it's all
been upgraded - but this makes the code future-safe
> mboxlist: lock a different name for subscription upgrade

- imap/mailbox.c
> mailbox: don't leak header name!

- lib/cyrusdb_twoskip.c
- lib/libcyr_cfg.c
Two annoying memory leaks introduced by my delayed actions work :(  Found by valgrind.
> Memory leaks

- imap/jmap_backup.c
This fixes a "use after free" when releasing and recreating the
mailbox where `struct mailbox *mailbox` pointed at the old copy.
> jmap_backup: always use the rrock mailbox pointer

- imap/mailbox.c
As discussed in the call.  This just switches the lock name itself to be the uniqueid.
> mailbox: make the mailbox namelock be by uniqueid

- imap/jmap_ical.c
Depending on libical settings an empty-valued ORGANIZER or ATTENDEE property may return NULL or an empty string as
calendar address. This patch unifies handling such values as NULL values.
Tested in https://github.com/cyrusimap/cassandane/tree/jmap_ical_ignore_empty_caladdress
> jmap_ical: ignore ORGANIZER and ATTENDEE if value is empty

- imap/http_ischedule.c
http_ischedule.c: don't leak XML response
> Plug iSchedule leak

- imap/carddav_db.c
Before, it erroneously used the mailbox uniqueid as username to lookup contact groups.
We already had a test for shared addressbooks but it did not make it on the main branch: https://github.com/cyrusimap/cassandane/pull/168
> JMAPEmail: fix broken fromContactGroupId filter for shared addressbooks

- imap/jmap_calendar.c
> jmap_calendar: log acl error before deallocating

- imap/jmap_backup.c
- imap/jmap_calendar.c
- imap/jmap_contact.c
- imap/jmap_core.c
- imap/jmap_mdn.c
- imap/jmap_sieve.c
- imap/jmap_vacation.c
as suggested by clang -Wmissing-variable-declarations
> Make jmap_*_methods_(non)standard static

- docsrc/imap/developer/process.rst
>  Fix a typo in process.rst 

- imap/http_err.et
No real reason for this other than I stumbled across it and figured I'd add it for completeness
> http_err.et: add missing 510 (Not Extended)

- imap/http_carddav.c
carddav_store_resource() should just store the resource.  carddav_put() should do data sanity checks itself as they (and any performance hit) aren't needed by COPY/MOVE.
This commit will be used by the vcard4 PR to sanity check the PUT Content-Type against the vCard VERSION itself.
> CardDAV PUT code reorganization

- docsrc/imap/support/feedback-meetings.rst
> docs: update weekly meeting time

- imap/carddav_db.c
- imap/http_caldav.c
- imap/http_carddav.c
- imap/http_dav.c
- imap/http_dav.h
- imap/http_dav_sharing.c
- imap/http_jmap.c
- imap/http_webdav.c
- imap/httpd.c
- imap/httpd.h
- imap/vcard_support.c
- imap/vcard_support.h
- lib/vparse.c
Beginnings of #3715 .  Conversion functions need a lot more work
> vCard v4 Support

- imap/jmap_calendar.c
Feel free to merge and delete the branch after approval.
> jmap_calendar: ignore scheduling mailboxes in event /query and /get

- cassandane/Cassandane/Cyrus/Caldav.pm
Start of testing the full CalDAV managed attachments API
> Caldav.pm: add test_managed_attachments

- imap/squatter.c
> squatter.c: don't index CalDAV schedule Inbox

- cassandane/Cassandane/Cyrus/TestCase.pm
By moving the eval from `_setup_http_service_objects()` up a layer, to encapsulate both calls.
This diff will be much easier to read if you add ?w=1 to the url (equivalent to `git diff -w`), since most of the lines changed are just indentation level changes.
Fixes a particular edge case where a failure late in `_start_instances()` would leave things partially started without cleaning up, and then later tests would fail due to the port they wanted to use being already in use.
> TestCase: clean up properly when _start_instances fails

- imap/json_support.c
- imap/json_support.h
Add json_is_date() function for future use (will be used by jmap_files branch)
> json_is_date()

- cassandane/Cassandane/Cyrus/JMAPMailbox.pm
- imap/jmap_mailbox.c
Also sanitizes the code of the according Cassandane test.
> jmap_mailbox: log count of destroyed messages in Mailbox/set{destroy}

- imap/caldav_alarm.c
protect from triggering alarms for deleted/replaced event resources
> caldav_alarm.c: ensure alarm record corresponds to current version of event

- imap/jmap_calendar.c
- imap/jmap_ical.c
All regression tests pass correctly.
> JMAP Calendars: workaround stale dav.db data and fix empty links property

- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
- imap/jmap_calendar.c
> jmap_calendar: ignore dead standalone instances in CalendarEvent/get

- imap/jmap_ical.c
Reading the component-scoped sequence timestamp inside the
ATTENDEE loop messes up the libical-internal iterator.
> jmap_ical: do not implicitly reset libical iterator

- docsrc/conf.py
Signed-off-by: Quanah Gibson-Mount <quanah@symas.com>
> Prepare for Cyrus-SASL 2.1.28

- cassandane/Cassandane/Cyrus/Sieve.pm
- imap/lmtp_sieve.c
Add a debug syslog() to processimip and add an iMIP test which creates an override
> Debug imip overrides

- lib/vparse.c
Pretty simple, self-explanatory commit
> Add restrictions for RFC 6474 vCard properties

- imap/jmap_calendar.c
This prevents Cyrus cloning the same iCalendar data over and
over again.
> jmap_calendar: cache recurrence instances in CalendarEvent/get

- cassandane/Cassandane/Cyrus/Sieve.pm
This just adds a regression test for something that's already working.
> Sieve: add test that iTIP invites get merged into existing event

- Makefile.am
- imap/jmap_notif.c
- imap/jmap_util.c
Couple of nits that were breaking 'make distcheck'
> Fix up distribution problems

- imap/carddav_db.c
- imap/carddav_db.h
- imap/mailbox.c
Add and use carddav_update() when only \Flagged has changed on a record.
This saves us having to parse the vCard unnecessarily
> carddav_update()

- lib/acl_afs.c
Also include negative rights in is_system_user()
> Negative system user rights

- imap/jmap_calendar.c
Calendar/set{create} must return myRights
> Calendar/set{create} myRights

- imap/caldav_alarm.c
Make sure we don't move the awakened message into a mailbox that we can't/shouldn't
> Sanity check moveToMailboxId at awaken time

- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
- imap/jmap_ical.c
The JMAP spec loosened restrictions on 'created'.
> jmap_ical: allow to change 'created' property value

- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
- imap/caldav_alarm.c
- imap/http_caldav.c
- imap/ical_support.c
- imap/ical_support.h
- imap/jmap_calendar.c
Also encodes recurrenceId as JMAP LocalDateTime.
> caldav_alarm: set main event id in Alert.calendarEventId property

- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
- imap/itip_support.c
- imap/jmap_calendar.c
The default scheduling calendar defined in CalendarPreferences
must be writable, as does any calendar that Cyrus picks internally
if no default calendar is set. This change also updates
CalendarPreferences/set to immediately pick a new default calendar,
if the user explicitly sets the defaultCalendarId property to null.
> jmap_calendar: default scheduling calendar must be writable

- imap/caldav_util.c
free property after removing it
> Plug remove property leak

- cassandane/Cassandane/Cyrus/Sieve.pm
- imap/itip_support.c
Per RFC 5545, Section 4.4.7:  remove overrides if not included with reschedule of master
> iTIP Reschedule Fix

- cassandane/Cassandane/Cyrus/Sieve.pm
- imap/itip_support.c
- imap/lmtp_sieve.c
> Support receiving iMIP METHOD:ADD

- imap/itip_support.c
Assume that the recipient is an attendee when we get into the deliver_merge_*() functions.  This should be verified at a higher level. 
The removed check was preventing cancels from being processed if the ATTENDEE was an alias for the owner of the Sieve script doing the iMIP processing.
> Check recipient vs attendee in schedule_deliver_local() or higher

- imap/http_caldav_sched.c
- imap/http_jmap.c
- imap/jmap_calendar.c
> Clang fixes

- imap/imapd.c
> imapd: fix cmd_xapplepushservice leak

- cassandane/Cassandane/Cyrus/JMAPContacts.pm
- imap/vcard_support.c
Adds support for decoding data URIs
Probably best to review by ignoring whitespace changes
> Support decoding vCard v4 image properties

- cassandane/Cassandane/Cyrus/Sieve.pm
- sieve/bc_eval.c
- sieve/script.c
Second attempt at fixing this, which also doesn't break handling of IMAP flags on implicit keep
> Sieve include and implicit keep fix (bis)

- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
Recent change 2f04693efb updates Cyrus to not create a
CalendarEventNotification for unshared calendars. But
the test did not reflect this.
> JMAPCalendars: fix CalendarEventNotification/changes test

- cassandane/Cassandane/Cyrus/Caldav.pm
- imap/http_caldav_sched.c
Switching between DTEND/DURATION with no actual change to a VEVENT's duration should NOT trigger an iTIP REQUEST
> Swapping DTEND <-> DURATION shouldn't trigger iTIP

- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
- cassandane/Cassandane/Cyrus/JMAPContacts.pm
- cassandane/Cassandane/Cyrus/JMAPCore.pm
- cassandane/Cassandane/Cyrus/JMAPEmail.pm
- cassandane/Cassandane/Cyrus/JMAPSieve.pm
- imap/jmap_core.c
This adds the new Blob/upload JMAP endpoint and updates all the tests to use it
> Jmap blob 09

- imap/http_caldav.c
> Actually fetch DURATION property when checking duration

- imap/http_tzdist.c
- imap/ical_support.c
- imap/ical_support.h
- imap/smmapd.c
Just upgraded OS on my laptop which came with newer GCC
Should be fix for #4085
> squash GCC 12.1.1 complaints

- cassandane/Cassandane/Cyrus/JMAPEmail.pm
No changes to the actual Cyrus codebase.
> JMAPEmail: add DNF-complexity regression test for contact filters

- imap/mailbox.c
- imap/mailbox.h
- imap/mboxlist.c
Fixes to deal with missing uniqueids and to be more crash resilient #4035
> mboxlist_upgrade() fixes

- Makefile.am
- cassandane/Cassandane/Cyrus/Sieve.pm
- imap/css3_color.c
- imap/css3_color.h
- imap/http_caldav_sched.c
- imap/ical_support.c
- imap/ical_support.h
- imap/itip_support.c
- imap/itip_support.h
> Strip event color from incoming/outgoing iTIP

- imap/jmap_mail_query.c
> jmap_mail_query: ignore config_search_maxsize if zero

- cassandane/Cassandane/Cyrus/JMAPEmailSubmission.pm
- imap/caldav_alarm.c
- imap/jmap_mail_submission.c
- imap/jmap_util.c
- imap/smtpclient.c
- imap/smtpclient.h
For https://github.com/cyrusimap/cyrus-imapd/issues/3694
> Fix EmailSubmission/set identityId handling

- imap/jmap_api.c
- imap/jmap_api.h
- imap/jmap_calendar.c
- imap/jmap_contact.c
- imap/jmap_mail.c
- imap/jmap_mail_submission.c
- imap/jmap_mailbox.c
Finally do what the comments in the code say
> JMAP: refactor jmap_getstate to return a string

- cassandane/Cassandane/Cyrus/Quota.pm
- imap/annotate.c
This adds the `raw quota` as an annotation fetch item, which can be fetched even if conversation quotas are turned on.
> Quota raw fetch

- cassandane/tiny-tests/JMAPEmail/email-set-header-control
- imap/jmap_mail.c
Also checks header contents to be valid UTF-8
> jmap_mail: reject control characters in Email headers

- backup/backupd.c
- backup/lcb_internal.c
- cassandane/Cassandane/Cyrus/Archive.pm
- cassandane/Cassandane/Cyrus/Replication.pm
- cassandane/Cassandane/Cyrus/TestCase.pm
- changes/next/3830-sync-to-archive
- docsrc/imap/reference/manpages/systemcommands/sync_client.rst
- imap/append.c
- imap/dlist.c
- imap/dlist.h
- imap/imap_proxy.c
- imap/imap_proxy.h
- imap/imapd.c
- imap/notify.c
- imap/protocol.h
- imap/sync_client.c
- imap/sync_server.c
- imap/sync_support.c
- imap/sync_support.h
- lib/imapoptions
This is @robn's #4073, but extended with a couple of Cassandane tests.  If you have already reviewed that, please focus on the new commits from me here; if you haven't, please review the whole thing.
This will want rebasing onto current master before being merged, as the original PR is a few months old, but for now I've kept the history unaltered.
Closes #3830 and #4073
> Replicate to archive, with tests

- cassandane/Cassandane/Cyrus/JMAPEmail.pm
- cassandane/tiny-tests/JMAPEmail/email-query-notes
- imap/jmap_mail.c
- imap/search_query.c
Email/query was locating messages in Notes folder
> jmap_mail.c: Email/* should ignore Notes folder

- cassandane/Cassandane/Cyrus/SyncProto.pm
- perl/imap/Cyrus/AccountSync.pm
- perl/imap/Cyrus/DList.pm
- perl/imap/Cyrus/Mbentry.pm
- perl/imap/Cyrus/Mbname.pm
This is mostly adding some Perl magic that can be used to dump and undump entire users for building future tests around.  Doesn't touch the C code at all.
> Sync proto tooling

- imap/http_dav_sharing.c
(and don't try to use a NULL mbentry resulting from a bad URI)
Fix an issue seen on prod
> http_dav_sharing.c: need to URL decode shared resource URI

- imap/http_jwt.c
I was compiling without OpenSSL to test #4232 and http_jwt.c failed to compile
> http_jwt.c: allow compilation without OpenSSL

- cassandane/Cassandane/Cyrus/JMAPCore.pm
- imap/jmap_core.c
- lib/md5.h
- lib/xsha1.h
This adds digest support per the latest jmap blob draft
> Jmap blob 13

- imap/mailbox.c
Hoping this fixes unique constraint errors we're seeing in cyr_expire, but this change makes sense regardless.
> mailbox.c: don't bother updating DAV record if we're just archiving

- imap/jmap_calendar.c
jmap_mbentry_from_dav may return NULL if a user attempts to load the mailbox list entry for a shared calendar for which that user does not have the required ACLs. This is a legit condition but the Calendar/Event/set code did not handle it properly.
> jmap_calendar: handle jmap_mbentry_from_dav returning NULL

- cassandane/doc/README.deps
Digest::CRC was missing
Fixes #4255
> docs: update cassandane README.deps

- imap/http_jmap.c
Seeing "deadlock avoided" messages during concurrent JMAP upload and API requests.  Hoping this might fix it
> http_jmap.c: open conv.db early for JMAP upload

- changes/next/4196-long-options
- changes/next/4226-imapoptions-bytesize
I realised belatedly that I had forgotten to include changes/next files in #4196 and #4226, so here they are now.
This isn't a comprehensive audit of everything that's potentially missing, just a couple that occurred to me
> add some missing changes files

- backup/lcb_append.c
- imap/caldav_util.c
- imap/http_caldav_sched.c
- imap/http_dav_sharing.c
- imap/index.c
Fixes a bunch of memory leaks found by @dilyanpalauzov 
Fixes #4247
Fixes #4248
Fixes #4249
Fixes #4250
Fixes #4252
> various: mem leak fixes

- imap/http_caldav.c
- imap/http_caldav_sched.c
- imap/ical_support.c
https://github.com/libical/libical/issues/585
Backport of https://github.com/cyrusimap/cyrus-imapd/pull/4278
> 3.4: Last parameter of icalcomponent_vanew() must be NULL, not 0

- imap/http_caldav.c
- imap/http_caldav_sched.c
- imap/ical_support.c
https://github.com/libical/libical/issues/585
Backport of https://github.com/cyrusimap/cyrus-imapd/pull/4278
> 3.2: Last parameter of icalcomponent_vanew() must be NULL, not 0

- cassandane/Cassandane/Cyrus/CaldavAlarm.pm
This test fails without the #4304 fix and succeeds with it
> CaldavAlarm.pm: add test_simple_attendee_no_partstat

- cassandane/Cassandane/Cyrus/Search.pm
- changes/next/imap-multisearch
- imap/imapd.c
- imap/imapd.h
- imap/imapparse.c
- imap/index.c
- imap/mailbox.c
- imap/mailbox.h
- imap/promdata.p
This needs a set of Cassandane tests, but I need to get familiar with IMAPTalk
> IMAP Multi-Mailbox Search (RFC 7377)

- imap/jmap_calendar.c
The commit messages say it all.
> jmap_calendar: fix memory issues

- imap/http_ws.c
For differentiating a simple GET request from a long-running WS connection.  Helps with tooling that might need to terminate long-running connections for a user.
> http_ws.c: proc_register() a WebSocket connection with cmd="WS"

- imap/imapd.c
The out-of-alpha-order capabilities and allof the per-capa special handling in capa_response() was bothering me for some reason.  All of the conditionals/formatting is now specified in base_capabilities[]
> imapd.c: rewrite of capa_response() using config in base_capabilities

- docsrc/imap/rfc-support.rst
- imap/imapd.c
- imap/imapd.h
- imap/imapparse.c
- imap/index.c
Brought RFC 4551/5162 implementation up to RFC 7162
> IMAP extensions audit

- imap/dav_db.c
Need a write lock so we can delete stale index records
> mailbox_add_dav() write lock

- cassandane/Cassandane/Cyrus/Caldav.pm
- imap/http_caldav_sched.c
Adding an attendee to an existing override, with no other changes, was failing to send an iTIP request
> http_caldav_sched.c: adding an attendee to an override must send iTIP

- imap/imapd.c
- imap/index.c
- imap/index.h
- imap/nntpd.c
- imap/search_query.c
> index_finduid(): new mode param determines return value for nonexistent UID

- imap/ctl_mboxlist.c
> ctl_mboxlist: support uuid mailboxes in ctl_mboxlist -v

- CONTRIBUTING.md
I think the change speaks for itself: we should say "tests unless omitting them makes sense", not "tests are nice if you can."
> CONTRIBUTING: strengthen the assertion that we want tests

- cassandane/Cassandane/Cyrus/Caldav.pm
- imap/http_caldav.c
- imap/http_carddav.c
- imap/http_dav.c
- imap/http_dav.h
- imap/http_dav_sharing.c
- imap/http_webdav.c
Tested by hand but needs Cass tests
> Implement sync-collection REPORT on home-set collections

- cassandane/Cassandane/Cyrus/Sieve.pm
- sieve/bc_eval.c
@brong do you have a machine currently using Australia/Melbourne that you can test this on (Sieve.date* tests)?
> bc_eval.c another local time fix (local offset changes with DST - duh!)

- cassandane/tiny-tests/JMAPEmail/email-copy-snoozed
- imap/jmap_mail.c
Fixes a bug uncovered by FM UI
> jmap_mail.c: allow snoozed:null in Email/copy

- imap/jmap_calendar.c
This PR does what is says on the tin, and in the comment/function that it replaces.
> jmap_calendar.c: Calendar/get only needs to iterate over INBOX.#calendars

- imap/jmap_calendar.c
Found while working on jmap_contacts + libicalvcard
> jmap_calender.c: plug potential leak in jmap_calender_capabilities()

- backup/cyr_backup.c
- imap/idled.c
- imap/itip_support.c
- imap/jmap_calendar.c
- imap/jmap_mail.c
- imap/mboxevent.c
- lib/charset.c
- sieve/bc_eval.c
- timsieved/parser.c
- timsieved/timsieved.c
This fixes a bunch of errors that valgrind found while running Cassandane tests.
> Fix valgrind errors found during Cassandane testing

- cassandane/Cassandane/Cyrus/Simple.pm
Regression test for #4506
This is almost identical to #4508, except that the expected default value is different now, and there's no bug fix because the bug doesn't exist anymore
> Simple: add tests for APPENDLIMIT capability

- cassandane/Cassandane/Cyrus/Annotator.pm
- cassandane/Cassandane/Cyrus/Backups.pm
- cassandane/Cassandane/Cyrus/Caldav.pm
- cassandane/Cassandane/Cyrus/ClamAV.pm
- cassandane/Cassandane/Cyrus/CtlMboxlist.pm
- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
- cassandane/Cassandane/Cyrus/JMAPCore.pm
- cassandane/Cassandane/Cyrus/JMAPEmail.pm
- cassandane/Cassandane/Cyrus/Quota.pm
- cassandane/Cassandane/Cyrus/RelocateById.pm
- cassandane/Cassandane/Cyrus/Replication.pm
- cassandane/Cassandane/Cyrus/TestCase.pm
- cassandane/Cassandane/Cyrus/TesterCalDAV.pm
- cassandane/Cassandane/Cyrus/TesterCardDAV.pm
- cassandane/Cassandane/Instance.pm
- cassandane/Cassandane/Net/SMTPServer.pm
- cassandane/Cassandane/Util/Slurp.pm
- cassandane/tiny-tests/JMAPEmail/blob-download
- cassandane/tiny-tests/JMAPEmail/email-bimi-blob
- cassandane/tiny-tests/JMAPEmail/email-bimi-blob-as-contact-avatar
- cassandane/tiny-tests/JMAPEmail/email-blob-set-singlecommand
- cassandane/tiny-tests/JMAPEmail/email-import-issue2918
- cassandane/tiny-tests/JMAPEmail/email-import-issue3122
- cassandane/tiny-tests/JMAPEmail/email-query-attachmentname
- cassandane/tiny-tests/JMAPEmail/email-query-attachments
- cassandane/tiny-tests/JMAPEmail/email-query-unicodefdfx
- cassandane/tiny-tests/JMAPEmail/email-set-blobencoding
- cassandane/tiny-tests/JMAPEmail/misc-upload-bin
... and dedup the many many times we've hand-rolled (or copy-pasted) this
**reviewers:** this has lots of small, similar (but not always identical) changes, might be easiest to review commit-by-commit
> cassandane: add slurp_file() function

- .github/workflows/main.yml
What it says on the tin.  Requested by @wolfsage
> github actions: report cyrus version

- imap/jmap_api.c
This was posted to IRC, and it's clearly correct.  Doh.
> Fix invalidResultReference error (as mentioned on IRC!)

- cassandane/tiny-tests/JMAPCalendars/calendarevent_get_baseeventid
- cassandane/tiny-tests/JMAPCalendars/calendarevent_set_baseeventid
- imap/jmap_calendar.c
This property got added some time ago in the JMAP Calendars RFC draft.
> jmap_calendar: add CalendarEvent.baseEventId property

- cassandane/Cassandane/Cyrus/Caldav.pm
- imap/mailbox.c
This fixes an assert() on an empty resource name due to not checking for the RFC5987 parameter name
> mailbox.c: properly handle DAV URLs with percent-encoded UTF-8 chars

- imap/jmap_mail.c
It thinks part is NULL and then part->date is dereferenced.
> jmap_mail.c:_email_get_headers() silence clang static analyzer

- imap/imapd.c
The formatting of this table was bothering me while looking at #4560
> imapd.c: uncomment but disable unimplemented capabilities

- docsrc/imap/developer/compiling.rst
> docs: we don't support Link Time Optimization

- cassandane/Cassandane/Cyrus/Carddav.pm
- imap/carddav_db.c
- imap/http_carddav.c
- imap/vcard_support.c
also concatenate all NICKNAMEs for carddav_db record
> http_carddav.c: CardDAV:addressbook_query using libicalvcard

- cassandane/Cassandane/Cyrus/Annotator.pm
- cassandane/Cassandane/Cyrus/Conversations.pm
- cassandane/Cassandane/Cyrus/JMAPMailbox.pm
- cassandane/Cassandane/Cyrus/JMAPTestSuiteWS.pm
- cassandane/Cassandane/Cyrus/SearchSquat.pm
- cassandane/Cassandane/IMAPMessageStore.pm
- cassandane/Cassandane/Instance.pm
- cassandane/Cassandane/Util/Log.pm
- cassandane/tiny-tests/JMAPEmail/email-set-update-too-many-mailboxes-lowlimit
- docsrc/imap/developer/developer-testing.rst
- imap/conversations.c
This PR contains all the miscellaneous fixes I need to debug and then fix the build/test issues under Debian Bookworm on x86_64.  Best reviewed commit-by-commit.
@rsto IIRC you're on the new Apple platform rather than x86_64.  Can you build and test this on your Bookworm VM and see if it works there too?  Thanks!
> bookworm fixes

- cassandane/tiny-tests/JMAPContacts/contact-update-grouped-property
- lib/vparse.c
fixes a Contact/set{update} bug
The Cass test confirms the fix
> vparse_get_entry: better handling of group

- cassandane/Cassandane/Cyrus/JMAPMailbox.pm
- imap/mboxlist.c
This broke the tests- sorry @elliefm.  Reverting the offending commits
> Revert folder modseq bump

- backup/ctl_backups.c
- com_err/et/init_et.c
- cunit/annotate.testc
- cunit/http_jwt.testc
- imap/annotate.c
- imap/ctl_mboxlist.c
- imap/cyr_virusscan.c
- imap/dav_util.c
- imap/http_caldav.c
- imap/http_dav.c
- imap/http_dav_sharing.c
- imap/index.c
- imap/jmap_sieve.c
- imap/lmtpd.c
- imap/mailbox.c
- imap/mboxevent.c
- imap/nntpd.c
- imap/prometheus.c
- imap/promstatsd.c
- imap/search_xapian.c
- sieve/message.c
This contains a bunch of fixes for things found by the GCC static analyzer.  It fixes a bunch of things that were definitely wrong, and also adds a few assertions where we assume things.
It does not address everything the static analyzer complained about.  The rest is in #4730
> fixes found by gcc static analyzer

- docsrc/imap/developer.rst
- docsrc/imap/developer/major-releasing.rst
- docsrc/imap/developer/releasing.rst
- docsrc/imap/developer/snapshot-releasing.rst
Documentation for how we do major releases.
Not quite complete yet -- still some details to flesh out.  But y'all might as well start having a look now, and I'll keep tinkering in the meantime.
Theoretically someday any of us should be able to do this stuff, so please sing out if anything isn't clear so I can clarify it.
> docs: add major release process

- imap/ctl_zoneinfo.c
- imap/http_dav.c
- imap/http_dav_sharing.c
- imap/http_ischedule.c
- imap/vcard_support.c
- imap/xcal.c
This is required for libxml2 2.12.0 and above.
> Add libxml/parser.h include

- cassandane/tiny-tests/JMAPContacts/card-get-v4
- imap/vcard_support.c
> vcard_support.c: handle data: URIs even if VALUE=X

- imap/http_client.c
- imap/http_err.et
- imap/http_jmap.c
- imap/http_proxy.c
- imap/jmap_api.c
This is nothing but a book-keeping nit.
> http_err.et: update 413 status code to match RFC 9110 & IANA registry

- cassandane/tiny-tests/UIDonly/unsolicited
Test tweak to make sure we are returning UID and not msgno
> IMAP UIDONLY unsolicited test: tweak test so msgno != UID

- cassandane/Cassandane/Cyrus/Sieve.pm
- imap/message.c
Fixes an uninitialized access crash in extract_convdata.
> message: fix uninitialized access in extract_convdata

- cassandane/tiny-tests/UIDonly/fetch
- imap/imapd.c
- imap/index.c
(per draft-ietf-extra-imap-uidonly-05)
> IMAP UIDONLY: UIDFETCH response should include UID msg-att if requested

- imap/mailbox.c
> Minor vCard cleanup

- cunit/message.testc
- imap/message.c
This is the follow-up PR to https://github.com/cyrusimap/cyrus-imapd/pull/4771
> Message parse received date invalid read

- imap/imapd.c
Just busy work that I noticed while working on PARTIAL
> imapd.c: add a couple of capabilities in EXTRA WGLC

- imap/imapd.c
> imapd.c: cleanup sending CREATE args to backend

- imap/jmap_contact.c
> jmap_contact.c: tweak street building in jmap_contact_from_vcard()

- cunit/charset.testc
- lib/charset.c
- lib/charset.h
I will first integrate this into Sieve and then investigate how/if to use this for IMAP I18NLEVEL=1 (RFC 5255)
> Implement the i;unicode-casemap collation (RFC 5051)

- sieve/bc_eval.c
Should help performance and will be also leveraged so we don't have do i;unicode-casemap transformation on patterns multiple times
> bc_eval.c: prepare (regcomp, etc) patterns once, not per value string

- cassandane/doc/running_tests.txt
- cassandane/doc/setting_up.txt
> docs: update some cassandane docs

- cassandane/doc/running_tests.txt
Very small update to the docs to clarify that multiple tests can be selected.
> Enhance test runner commandline docs

- imap/sync_support.c
This fixes mmap size issues with just using the script as a string
> sync_support: duplicate the sieve script

- cassandane/Cassandane/Cyrus/JMAPCore.pm
- imap/http_jmap.c
This originated from a request to response with 507 and a Problem Details for over quota rather than a 500.
Over quota can no longer happen due to unrelated bugfixes, but it seemed like a good idea to output Problem Details for any upload failure.
> http_jmap.c: create Problem Details Object on JMAP upload failure

- cassandane/tiny-tests/JMAPCalendars/calendarevent_copy_state
- cassandane/tiny-tests/JMAPContacts/card_copy_state
- cassandane/tiny-tests/JMAPContacts/contact_copy_state
- cassandane/tiny-tests/JMAPEmail/email_copy_state
- imap/jmap_api.c
- imap/jmap_api.h
- imap/jmap_calendar.c
- imap/jmap_contact.c
- imap/jmap_mail.c
None of this was implemented per RFC 8620
> Foo/copy: add support for if[From]InState, destroyFromIfInState, old/newState

- cassandane/tiny-tests/Carddav/put_get_v3_v4
- cassandane/tiny-tests/JMAPContacts/card_set_create_media
- imap/carddav_db.c
- imap/jmap_contact.c
- imap/vcard_support.c
- imap/vcard_support.h
- lib/vparse.c
- lib/vparse.h
This PR will fail CI until we update to the latest libical vCard branch
> More vCard v3 <-> v4 translations

- cassandane/Cassandane/Cassini.pm
- cassandane/Cassandane/Instance.pm
- cassandane/Cassandane/Test/Core.pm
- cassandane/cassandane.ini.example
Improves cassandane's core file detection a little, and also makes the core pattern it searches for configurable so that we don't need to handle every possible eventuality programmatically.
> cassandane: configurable core pattern

- imap/mailbox.c
- imap/sync_support.c
This will hopefully help us debug the issue with sieve mailbox CRC errors!
> Crc logging

- docsrc/imap/reference/manpages/systemcommands/smmapd.rst
- imap/smmapd.c
Does lmtp with `autocreate_post:1` create mailboxes, different from `INBOX`, when the envelope recipient is a plus-address?
> imap/smmapd: utilize the userdeny database and possibly skip plus addressing

- cassandane/tiny-tests/Caldav/invite_change_organizer_recur
This tests a bug we suspected might have existed, but can't reproduce!
> Caldav: test changing organiser and overwriting including removing recurrences

- imap/sync_support.c
This is a big ugly, but if we're not in is_repeat for sync_client's update_mailbox_once, we shouldn't take a write lock at all, that way we can keep syncing from a read-only filesystem.
> sync_support; use read-only lock for first pass

- changes/next/calalarm-suppress
- imap/caldav_alarm.c
- lib/imapoptions
This came up from a server having a filesystem issue at Fastmail, we'd like to make it "quiet" while we investigate, and part of that is stopping automatic processing on the machine.
> Calalarm suppress

- imap/sync_support.c
Avoid fully parsing and allocating memory for all the records we don't need during copy_remote
> sync_support: copy_remote speedup

- cassandane/Cassandane/Cyrus/CyrusDB.pm
- cassandane/Cassandane/Cyrus/Delivery.pm
- cassandane/Cassandane/Cyrus/Reconstruct.pm
- cassandane/Cassandane/Instance.pm
- cassandane/tiny-tests/JMAPEmail/searchsnippet_search_maxsize
- cassandane/tiny-tests/SearchFuzzy/squatter_attachextract_nolock
- cassandane/utils/syslog_probe.c
- imap/cyr_buildinfo.c
- imap/http_h2.c
- imap/httpd.c
- imap/imapd.c
- imap/jmap_calendar.c
- imap/mbexamine.c
- imap/vcard_support.c
This fixes a SIGABRT during the imapd capabilities response when Cyrus was compiled with [glibc source fortification](https://www.gnu.org/software/libc/manual/html_node/Source-Fortification.html) enabled, due to a bad printf format string.  This is not our first time introducing and having to fix this kind of problem (e.g. #1981)
Also fixes a bunch of warnings that are detected when compiled with -O3, because I initially mistook optimisations for the cause and needed to get it building to test it.  Thanks @ksmurchison for a few extra fixes here for warnings that newer GCC's report but mine didn't.
Also smooths out some Cassandane issues with our syslog replacement: we can't reliably inject our syslog replacement when source fortification is enabled, but nor can we reliably detect whether …
> fix imapd capabilities crash when built with source fortification

- imap/annotate.c
- imap/mailbox.c
- imap/mailbox.h
I think this is a simpler/cleaner solution than #4981
> annotate: don't re-read mbentry every time if mailbox is open

- cassandane/cassandane/tiny-tests/Carddav/put_bday_noyear
- cassandane/cassandane/tiny-tests/JMAPContacts/card_set_create_bday_noyear
- cassandane/cassandane/tiny-tests/JMAPContacts/contact_set_create_bday_noyear
The tests require libical PRs #718-720
This is also dependent on #4906
> vcard_support.c: properly handle X-APPLE-OMIT-YEAR parameter

- imap/http_caldav.c
When an iCalendar object is created for a user and the user has already an iCalendar object with the same UID, in any of its collections, return CalDAV:unique-scheduling-object-resource precondition, instead of the CalDAV:no-uid-conflict precondition.
Fixes https://github.com/cyrusimap/cyrus-imapd/issues/2345 for 3.0.
> http_caldav: return unique-scheduling-object-resource instead of no-uid-conflict

- docsrc/imap/reference/manpages/systemcommands/squatter.rst
See https://lists.andrew.cmu.edu/pipermail/cyrus-devel/2019-June/004487.html
> squatter.rst: write down that -F is broken for 3.0

- imap/imapd.c
- imap/mboxlist.c
- lib/imapoptions
> Add option to allow special-use subfolders

- docsrc/imap/download/release-notes/3.4/x/3.4.0-beta1.rst
- docsrc/imap/download/release-notes/3.4/x/3.4.0-beta2.rst
- docsrc/imap/download/release-notes/3.4/x/3.4.0-beta3.rst
- docsrc/imap/reference/architecture.rst
This shall be backported to the 3.4 branch.
> Update 3.4.0-beta release notes

- lib/cyrusdb.c
- lib/cyrusdb.h
- lib/cyrusdb_flat.c
- lib/cyrusdb_quotalegacy.c
- lib/cyrusdb_skiplist.c
- lib/cyrusdb_sql.c
- lib/cyrusdb_twoskip.c
- lib/cyrusdb_zeroskip.c
This isn't actually needed for anything right now, so I separated it out into its own PR.
I think it's a useful API to have still.
> Cyrusdb lock

- cassandane/tiny-tests/JMAPEmail/email_copy
- imap/jmap_api.c
- imap/jmap_api.h
- imap/jmap_mail.c
As it says on the tin.  
An alternative to #5021 
I'm sure I missed something and/or we need more tests.
> jmap_email.c: refactor Email/copy to use _email_bulkupdate

- imap/caldav_util.c
- imap/http_carddav.c
- imap/jmap_sieve.c
- imap/lmtp_sieve.c
- imap/spool.c
- imap/spool.h
- sieve/test.c
- sieve/test_mailbox.c
Based on our discussion on this week's Cyrus call.
> spool.c: use a struct buf in struct hdrcache_t for lowercasing header names

- .gitignore
as of 348a8fb27b36c48180d2993806f745b46dc77085
> .gitignore: update for http_cal_abook_admin_js.h

- imap/http_caldav_sched.c
Analogue to https://github.com/cyrusimap/cyrus-imapd/pull/5050
> http_caldav_sched.c:imip_send_sendmail() - do not send lonely LF

- imap/caldav_alarm.c
- imap/fetchnews.c
- imap/http_caldav.c
- imap/http_proxy.c
- imap/http_rss.c
- imap/ical_support.c
- imap/imapd.c
- imap/index.c
- imap/itip_support.c
- imap/jmap_backup.c
- imap/jmap_blob.c
- imap/jmap_calendar.c
- imap/jmap_mail.c
- imap/jmap_mail_submission.c
- imap/lmtp_sieve.c
- imap/nntpd.c
- imap/sync_log.c
- imap/sync_support.c
- imap/user.c
- imtest/imtest.c
- lib/cyrusdb_flat.c
- lib/cyrusdb_skiplist.c
- lib/imclient.c
- lib/retry.c
- master/service.c
- perl/sieve/lib/isieve.c
- sieve/test.c
As found by clang version 14.0.6.
> Fix clang -Wconditional-uninitialized warning errors

- cassandane/Cassandane/Cyrus/Simple.pm
- cassandane/Cassandane/Instance.pm
This fix prevents a huge mess from occurring if Cassandane tries to `run_command()` something that isn't executable for whatever reason.  Also adds a new test, Simple.fork_noexec, which invokes the failure condition and verifies as best it can that Cassandane hasn't chewed itself to bits.
We saw this from the new LibCyrus tests when Cassandane's rootdir is on a noexec filesystem, which means the compiled libcyrus examples can't be executed.  I'll also try to update LibCyrus to skip its tests in that situation, but I'll do that as a separate PR.  This one just fixes the infrastructure bug.
> cassandane: clean up properly after _fork_command exec failure

- imap/http_h2.c
At one point, there WAS a reason why I was copying the data, but I BELIEVE that reason became obsolete when I added a call to http2_output() inside resp_body_chunk().
HTTP/2 still works for me locally.  I don't think we allow direct client access to Cyrus @ Fastmail, so I guess we will see if anyone in the community stumbles upon a failure mode.
> http_h2.c: don't copy response body data

- cassandane/Cassandane/IMAPMessageStore.pm
Splitting out a couple of changes to some Cassandane stuff cause I need it in two different WIPs
> small IMAPMessageStore improvements

- cassandane/Cassandane/Cyrus/MurderIMAP.pm
- imap/imapd.c
I think this is a much simpler fix than #5138.  If approved, we should close #5138 #5139 #5140
> imapd.c: fix proxying UID Search (issue #5047)

- cassandane/Cassandane/Cyrus/QResync.pm
- imap/index.c
As found, the QRESYNC vanished version of fetch '$' failed
> index: parse '$' in vanished as well

- docsrc/overview/cyrus_bylaws.rst
- docsrc/overview/cyrus_roadmap.rst
This requires approval of the board, and I have also asked Alexey to vote.
> update the core developer list

- .github/workflows/main.yml
- cassandane/cassandane.ini.dockertests
...but keep --sysctl net.ipv6.conf.all.disable_ipv6=0
> import new testing from master branch to 3.10

- .github/workflows/main.yml
- cassandane/cassandane.ini.dockertests
...but keep --sysctl net.ipv6.conf.all.disable_ipv6=0
> import new testing from master branch to 3.8

- cassandane/tiny-tests/Caldav/calendar_query_dtend_tzid
This test requires cyruslibs v63 in order to pass
> Add Caldav.calendar_query_dtend_tzid

- cassandane/tiny-tests/JMAPCore/eventsource_disabled
- cassandane/tiny-tests/JMAPCore/websocket_push_disabled
- imap/http_jmap.c
Also, jmap_push_poll:0 should disable EventSource
> http_jmap.c: allow EventSource without WebSocket

- Makefile.am
- configure.ac
- imap/global.h
- imap/httpd.c
- imap/imapd.c
- imap/jmap_ical.h
- imap/lmtpd.c
- imap/lmtpengine.c
- imap/mupdate.c
- imap/nntpd.c
- imap/pop3d.c
- imap/saslclient.c
- imap/sync_client.c
- imap/sync_server.c
- imtest/imtest.c
- perl/sieve/lib/isieve.c
- timsieved/timsieved.c
Fixes a couple of issues that showed up compiling Cyrus with clang version 19.
> Fix Cyrus builds for clang version 19

- imap/mailbox.c
Right now it can silently just not record things if it fails to open the DB for whatever reason
> mailbox: assert fail if conversations open error

- cassandane/Cassandane/Cyrus/Conversations.pm
- changes/next/conversations-versions
- imap/conversations.c
- imap/conversations.h
- imap/ctl_conversationsdb.c
Adds a "-U" upgrade that allows us to bump a version number to force recalc in an idempotent way.
> Conversations upgrade

- docsrc/imap/reference/manpages/systemcommands/cyr_expire.rst
- imap/cyr_expire.c
This makes it easier to do larger batches when cleaning up a mess on a replica!
> cyr_expire: add batchsize

- imap/jmap_contact.c
Easier to review if you hide whitespace
> jmap_contact.c: fix declaration after label

- .github/workflows/main.yml
Add an asan make check phase to CI
> Sanitizer ci

- imap/http_ws.c
rather than doing gymnastics with a read-only struct buf
> http_ws.c: use a fixed-size protstream for H2 data

- imap/index.c
do not run if there are no deleted messages
> index_expunge optimization

- imap/http_dav_sharing.c
xml_add_shareaccess() and propfind_shareaccess() call
> if (mboxname_userownsmailbox(fctx->req_tgt->userid, fctx->mbentry->name)) …
where req_tgt->userid and mbentry are both set based on the requested path.  In turn mboxname_userownsmailbox() is always true.
Since the ACL and PROPFIND on DAV:acl http verbs are supposed to return answer only if the user has admin rights, and since add_shareaccess() and propfind_shareaccess() return the same information, as PROPFIND on DAV:acl, this patch changes propfind_shareaccess() to return NO_PRIVILEGES, when the requesting user has no admin rights.
xml_add_shareaccess() and propfind_shareaccess() return now sharing information, if the authenticated user has admin rights on the mailbox.
> tautology in http_dav_share: xml_add_shareeaccess() and propfind_shareaccess()

- README.md
This is a band-aid.  This should be better automated.
> README: bump supported version

- configure.ac
- tools/hard-tab-tool
Nothing really interesting here.  I was reading this file and noticed hard tabs.  I confirmed they could be spaces, so I did that.
> configure.ac: expand tabs to spaces and add to the tab checker

- docsrc/imap/developer/compiling.rst
> docs: update libical version listed in compiling.rst

- cassandane/Cassandane/Cyrus/Fetch.pm
- changes/next/imap-preview-issue-4665
- imap/imapd.c
- imap/index.c
> imapd.c: only advertise/accept PREVIEW when properly configured

- lib/imapoptions
> imapoptions: document LIST and SELECT parameters of "allowdeleted"

- cassandane/Cassandane/Cyrus/TestCase.pm
- cassandane/tiny-tests/JMAPCore/cors_preflight
- imap/http_jmap.c
> http_jmap.c: allow CORS preflight if httpallowcors is enabled

- docsrc/imap/installing.rst
- lib/imapoptions
- lib/setproctitle.c
- tools/translatesieve
This is some of the small fixes that I just did on-the-fly as we were reviewing tickets today
> some small fixes

- cassandane/Cassandane/Instance.pm
> Instance: add id() for use by xlog

- cassandane/Cassandane/Cyrus/Prometheus.pm
- imap/promstatsd.c
This PR changes the timestamps in the promstatsd "service" report to reflect the time the values were examined and known to be correct at (i.e. the time the report was generated), rather than the time the value in question last changed.  This will stop Prometheus from whinging about old timestamps for certain statistics that almost never change.  It also updates a couple of tests to verify the new behaviour.
The "master" and "usage" reports already handled timestamps like this, and don't need to be updated.
For "gauge" statistics, which can vary both up and down, we will no longer be able to differentiate between ones whose value has not changed since the last report, and ones whose value did change but then changed back.  The difference between these cases used to be whether or not the …
> prometheus: timestamp is current-as-of time, not value-last-changed time

- imap/jmap_contact.c
This patch includes two improvements when converting vCards to JMAP. It uses an heuristic to determine the size of hash tables that are used for group label lookups, rather than hardcoding a predefined value. It also caches X-ABADR property values for translation of country codes.
This change does not change or add JMAP Contact features or elements, so no Cassandane test is added.
> jmap_contact.c: calculate hash table sizes from vCard

- lib/charset.c
> charset: needs stdbool.h for bool type

- .github/workflows/main.yml
- cassandane/Cassandane/Cyrus/ALPN.pm
- cassandane/Cassandane/Cyrus/Alpaca.pm
- cassandane/Cassandane/Cyrus/Info.pm
- cassandane/Cassandane/Cyrus/MboxEvent.pm
- cassandane/Cassandane/Cyrus/MurderIMAP.pm
- cassandane/Cassandane/Cyrus/StartTLS.pm
- cassandane/Cassandane/Cyrus/TestCase.pm
- cassandane/Cassandane/Instance.pm
- cassandane/testrunner.pl
- cassandane/tiny-tests/JMAPCore/echo_tls
- imap/jmap_calendar.c
- imap/sync_support.c
This adds an ASAN Build to all Pull Req / mainline CI runs.
Regular tests take about 17minutes, the asan build takes 22m total.
> Asan CI Builds

- imap/httpd.c
#5432 probably also need this PR in order for for CI to run clean.
> httpd.c: free txn context when receiving shutdow signal

- cassandane/testrunner.pl
to rerun entire suites for failed tests
> testrunner.pl: add --rerun-suite option

- lib/twom.c
This fixes twom to create the file rather than aborting if it finds a zero byte file.  This can happen if a process was killed between creating the file and writing the twom header.
> Twom zero files

- cassandane/Cassandane/Cyrus/Search.pm
- imap/imapd.c
This fixes an assert() that was seen in production
> imapd.c: open user cstate once for IMAP MULTISEARCH

- cassandane/Cassandane/Config.pm
- cassandane/Cassandane/Cyrus/JMAPEmail.pm
- cassandane/Cassandane/Cyrus/Reconstruct.pm
- cassandane/tiny-tests/JMAPEmail/email_legacy_ids
- cassandane/tiny-tests/JMAPMailbox/mailbox_legacy_ids
...and make it easy to test with twoskip (or something else) instead
> cassandane: use twom for most db backends

- cassandane/Cassandane/Cyrus/Search.pm
- cassandane/tiny-tests/FastMail/cyr_expire_rename_safe
- imap/cyr_expire.c
- imap/index.c
- imap/mailbox.c
- imap/mailbox.h
- imap/reconstruct.c
This fixes an issue where renamed users would have their per-user data wiped a week later!  Ouch.
> Cyr expire safety

- imap/index.c
This eliminates allocating/freeing buffers for every message for which we are fetching items.
This will have to be rebased after #5561 is merged
> index.c: reusable buffers for mmaped messages and fetch item values

- cassandane/tiny-tests/JMAPContacts/card_get_v3
- cassandane/tiny-tests/JMAPContacts/card_get_v4
- cassandane/tiny-tests/JMAPContacts/card_set_create_online
- imap/jmap_contact.c
To be compatible with Apple until they support the latter
> jmap_contact.c: generate X-SOCIALPROFILE rather than SOCIALPROFILE

- cassandane/Cassandane/Cyrus/TestCase.pm
Oops, I missed a case when deduplicating
> cassandane: remove a warning from TestCase
