cyrusimap/cyrus-imapd

- Makefile.am
- imap/imap_err.et
- imap/lmtp_sieve.c
- imap/sync_support.c
- sieve/rebuild.c
- sieve/sieve_interface.h
(From an old phabricator task: https://git.cyrus.foundation/T114)
This stops replication of binary sieve bytecode files.  Instead, bytecode files are compiled by the replica on upload of the plain text script, or on activation via sync protocol.  Attempts to replicate bytecode files are silently ignored.
A new sync protocol error is introduced, IMAP_SYNC_BADSIEVE, which will result if a replicated sieve script fails to parse/compile.  This makes it important to ensure your master and replica servers have the same sieve extensions enabled.
Also, lmtpd now recompiles sieve bytecode files (if missing or stale) on demand.  So a temporary parse/compile failure during replication is somewhat self-healing if the sieve script needs to actually be invoked later.
If an old master (without this …
> t114 dont replicate compiled sieve bytecode

- docsrc/concepts.rst
- docsrc/developers.rst
- docsrc/download.rst
- docsrc/imap/admin.rst
- docsrc/imap/deployment.rst
- docsrc/imap/deployment/deployment_scenarios.rst
- docsrc/imap/deployment/mailbox_creation_distribution.rst
- docsrc/imap/deployment/overview_and_concepts.rst
- docsrc/imap/faq.rst
- docsrc/imap/features.rst
- docsrc/imap/installation/diy.rst
- docsrc/index.rst
- docsrc/quickstart.rst
- docsrc/reference.rst
- docsrc/sasl/authentication_mechanisms.rst
- docsrc/sasl/auxiliary_properties.rst
- docsrc/sasl/faq.rst
- docsrc/sasl/pwcheck.rst
- docsrc/sitemap.rst
- docsrc/support.rst
Making the initial left hand navigation simpler, easier to follow and faster to locate information as it's less cluttered.
Splitting up the old concepts guide into Concepts and Admin, and removing leftover html cruft that was from a time long ago.
Restructuring some of the content to get the hierarchy easier to read and navigate.
> Doc restructure: a simpler hierarchy

- cunit/mboxname.testc
- imap/mboxname.c
mboxname_user_mbox() and mboxname_to_userid() did not correctly take in to account that a userid may contain dots in the local part (i.e. 'john.doe@example.org').
> Correctly translate dotted userids between internal and external

- Makefile.am
libtool sometimes be confused to link shared library when linking with
static in-place library, and only generate static library.
> Change to build in-place libcrc32 library with libtool

- configure.ac
- lib/util.h
"__compare_fn_t" for qsort(3) compare function prototype is not a
GCC feature, but a internal private type for glibc and some other
libc implementations.
Change to detect the type with configure script.
fixes #64 #1721
> Fix condition for missing __compare_fn_t

- imap/backend.c
Such flags may not be defined, especially fallback implementation in lib/gai.h.
Additionally, *BSD has own valid flag mask pattern as AI_MASK,
so use it too.
fixes #62
> imap/backend.c: fix to build without AI_V4MAPPED and AI_ADDRCONFIG

- docsrc/imap/concepts/deployment/databases.rst
- docsrc/imap/concepts/features/namespaces.rst
- docsrc/imap/developer/basicserver.rst
- docsrc/imap/download/installation.rst
- docsrc/imap/download/installation/distributions/debian.rst
- docsrc/imap/download/installation/diy.rst
- docsrc/imap/download/upgrade.rst
- docsrc/imap/reference/admin/access-control/rights-reference.rst
@elliefm @brong ( @rsto ) Can you please eyeball this guide?
This is a first cut of the 3.0 upgrade guide. It assumes (correctly? incorrectly?) that people will maintain two physical installations (one of existing, one of new 3.0) until they're ready to actually cut over. Is that assumption correct? (It does mention you can replicate to a 3.0 install, but for more info I might need ellie to write that bit)
It assumes that someone doing this will know where certain files (config/sieve/databases/spool/etc) live and being told explicitly is overkill. Is that reasonable or should I spell out the default locations?
> [Docs] 3.0 upgrade guide.

- docsrc/imap/reference/manpages/usercommands/imtest.rst
- docsrc/imap/reference/manpages/usercommands/lmtptest.rst
- docsrc/imap/reference/manpages/usercommands/mupdatetest.rst
- docsrc/imap/reference/manpages/usercommands/nntptest.rst
- docsrc/imap/reference/manpages/usercommands/pop3test.rst
- docsrc/imap/reference/manpages/usercommands/sivtest.rst
- docsrc/imap/reference/manpages/usercommands/smtptest.rst
Hi,
I found out option '-w passwd' is missing from manual pages, but it is in help. This commit will fix it.
> Adding -w option to man pages

- docsrc/imap/concepts/features/namespaces.rst
- docsrc/imap/download/upgrade.rst
- docsrc/imap/reference/admin/sop/altnamespace.rst
- docsrc/imap/reference/manpages/configs/cyrus.conf.rst
Added new content to upgrade.rst based upon actual experience
performing an upgrade (2.4.18 => 3.0.0rc1).
Add clarifying information to cyrus.conf manpage in regards
to missing 'host' declaration in listen portion of SERVICE commands.
> Update the 'upgrade' document & cyrus.conf manpage

- docsrc/imap/installation/diy.rst
Updated git clone command.  The git clone command doesn't work (at least not for me) in its current form.
Updated markup on all other commands meant to be issued in *nix shell so they are formatted correctly.
> Updated git clone command

- docsrc/imap/reference/manpages/systemcommands/cyr_info.rst
- imap/cyr_info.c
The man page for cyr_info(8) listed commnd names which didn't match
the actual program.
Also, cyr_info.c had a typo for the "conf-default" command.
This is a second attempt, with a clean git tree.
> Fixed cyr_info.rst to match actual command names

- docsrc/imap/reference/manpages/systemcommands/cyr_info.rst
- imap/cyr_info.c
The "reid" command for cyr_info program was not documented.  This
has been added both to cyr_info(8) man page and to the usage.
> Add "reid" command information to cyr_info

- docsrc/imap/reference/manpages/systemcommands/cyr_info.rst
Different sub-commands require different arguments, so re-did
for clarity.
> Rearrange cyr_info(8) man page for clarity.

- docsrc/imap/concepts/overview_and_concepts.rst
- lib/imapoptions
- perl/imap/IMAP/Shell.pm
Expanded treatment of Qutoas & ACLs in overview & concepts document.  Also fixed a typo in lib/imapoptions in re: default value of quota_db_path, and section of Shell.pm cyradm POD documentation on quota types supported by Cyrus.
> Onlight cyr/gendoc

- imap/http_admin.c
Some *BSD systems has `qsort_r` function with different signature
than glibc's one.  Add macros resolving such differences.
Additionally, add glibc `qsort_r` compatible function for others
with GCC compiler.
partially resolve #63
> Add supports to build on missing glibc extension `qsort_r`

- docsrc/imap/concepts/deployment/databases.rst
- docsrc/imap/concepts/features/access-control.rst
- docsrc/imap/concepts/features/mail-spool-partitions.rst
- docsrc/imap/concepts/features/mailbox-metadata-partitions.rst
- docsrc/imap/concepts/features/namespaces.rst
- docsrc/imap/concepts/overview_and_concepts.rst
- docsrc/imap/reference/admin.rst
- docsrc/imap/reference/admin/access-control.rst
- docsrc/imap/reference/admin/access-control/combining-rights.rst
- docsrc/imap/reference/admin/access-control/defaults.rst
- docsrc/imap/reference/admin/access-control/identifiers.rst
- docsrc/imap/reference/admin/locations.rst
- docsrc/imap/reference/admin/locations/configuration-state.rst
- docsrc/imap/reference/admin/locations/hashing.rst
- docsrc/imap/reference/admin/locations/mailspool.rst
- docsrc/imap/reference/admin/quotas.rst
- docsrc/imap/reference/admin/quotas/quotaroots.rst
- docsrc/imap/reference/admin/quotas/quotatypes.rst
Major redo of docsrc/reference/admin section, with addition of two new subdirectories -- quotas and locations -- and addition of many new references into other files, such as databases.rst, so as to facilitate cross-section linkage.
> Onlight cyr/gendoc refactor

- docsrc/imap/reference/manpages/systemcommands/translatesieve.rst
- tools/translatesieve
The tools/translatesieve utility is quite needed for the 2.X > 3.X
transition, given that unixhierarchysep and altnamespace now default
to "on." However, the old utility didn't handle all scenarios.
This version is more robust and has useful help, etc.
Also updated the manpage for same.
UPDATE: New commit, clean of cyr_info cruft.
UPDATE 2: Added new -C option to command (and documentation) for handling imapd.conf file.
> Translatesieve updated for 3.0

- docsrc/_static/cyrus.css
- docsrc/imap/developer/basicserver.rst
- docsrc/imap/developer/installguide.rst
- docsrc/imap/download/installation.rst
- docsrc/imap/download/installation/distributions/debian.rst
- docsrc/imap/download/installation/diy.rst
- docsrc/imap/download/upgrade.rst
Aim: 1) get the basic install guide(s) to the point where even a newbie admin could install Cyrus and get to the point where someone can send a test email.
2) Update the upgrade guide now that typical upgrade paths are better understood.
NOT DONE: finish off CalDAV/CardDAV config/install/test instructions. (In my testing, my curl based queries were still failing with a 404 mailbox not found, and my imap client also couldn't see the mailbox)... ACLs?
> Docs. Upgrade and install docs update

- Makefile.am
- docsrc/conf.py
- docsrc/imap/reference/administration-tools.rst
- docsrc/imap/reference/manpages/commands.rst
- docsrc/imap/reference/manpages/systemcommands/cyr_virusscan.rst
Address lack of man page for cyr_virusscan, as identified by @hagedose in #1837
> Docedit cyr virusscan

- docsrc/imap/reference/manpages/systemcommands/cyr_info.rst
- docsrc/imap/reference/manpages/systemcommands/mbtool.rst
- imap/cyr_info.c
- imap/mbtool.c
It's always struck me as odd that re-IDing a mailbox is a job for
cyr_info, rather than for mbtool.  From their respective man pages:
- **cyr_info** is a tool for getting information from Cyrus.
- **mbtool** is a tool for performing various actions on the indexes of a list of mailboxes.
Wouldn't the "reid" action then fall under the purview of mbtool?  Granted it's not an "index" operation, however, but that's just semantics.
It looked to me as though it should be pretty easy to move it, so I've tried just that.  Man pages are updated, too.
**Note:** I am by no means a C programmer, so please treat as a proof of concept, not final goods.  However, I have tested it and it does work as expected.
> Move the REID operation from cyr_info to mbtool

- imap/mailbox.c
Ensure the directory hierarchy is created for an empty mailbox that is renamed.
When using metadata partitions, seperating the mailbox metadata files from the mail spool, and empty mailbox (no messages) would result in an empty directory in the filesystem hierarchy.
When such mailbox is renamed, the original filesystem directory hierarchy would be deleted, but no new hierarchy would.
However, transferring a mailbox does rely on the mailbox's folder being present on the filesystem.
This pull request ensures the directory for the mailbox is created, despite there being no records within the mailbox to attempt to copy over.
Please advise on the desire or necessity to include this fix in master as well, as this chunk of logic seems to have changed quite a bit
> Ensure the directory hierarchy is created for an empty mailbox

- docsrc/imap/reference/admin.rst
- docsrc/imap/reference/admin/ports-sockets.rst
- docsrc/imap/reference/admin/ports/services.rst
- docsrc/imap/reference/admin/ports/sockets.rst
- docsrc/imap/reference/manpages/configs/cyrus.conf.rst
- docsrc/quickstart.rst
New pages describe ports and sockets needed by Cyrus in such a way
that the information may easily be included into other pages.
Fix typo in cyrus.conf.rst
Augment "quickstart" guide.
> Build new pages for port & socket info.

- Makefile.am
We've moved these into docs/examples, so no longer need them in the Makefile explicitly.
> Remove old cyrus.conf samples from master/ in Makefile.am

- docsrc/assets/README.md
- docsrc/assets/cyrus-build-devpkg.rst
- docsrc/assets/cyrus-build-reqpkg.rst
- docsrc/assets/cyrus-user-group.rst
- docsrc/assets/services.rst
- docsrc/assets/setup-dir-struct.rst
- docsrc/assets/setup-sasl-sasldb.rst
- docsrc/assets/setup-sendmail.rst
- docsrc/conf.py
- docsrc/imap/developer/basicserver.rst
- docsrc/imap/download/installation/diy.rst
- docsrc/imap/download/packagers.rst
- docsrc/imap/reference/admin/ports/services.rst
- docsrc/quickstart.rst
Split basicserver.rst into bits and place these in new 'assets'
top level directory.  Then include those bits back into main file.
Modify conf.py to ignore the '/assets' directory.
Create more assets and update other docs to use them.
Add more steps to quickstart.rst, using assets.
Fix typos.
> Disassemble basicserver.rst into bits

- docsrc/assets/setup-postfix.rst
- docsrc/quickstart.rst
Add simple instructions to configure Postfix for LMTP delivery
to Cyrus.  Add this as an option in the Quickstart guide.
> Add new assets/setup-postfix.rst

- imap/version.c
This will help with my crash reporting work.
```
$ gdb -batch -ex 'p cyrus_version_str' /usr/cyrus-future/lib/libcyrus_imap.so
$1 = 0xd9500 "future-fmjessie43922-14953-git-future-14953"
```
> version: make cyrus_version accessible to the debugger

- docsrc/imap/download/installation/diy.rst
- docsrc/imap/download/release-notes/2.5/x/2.5.1.rst
- docsrc/imap/download/release-notes/2.5/x/2.5.5.rst
- docsrc/imap/download/release-notes/2.5/x/2.5.6.rst
- docsrc/imap/reference/admin/backups.rst
- docsrc/imap/reference/admin/eventsource.rst
- docsrc/overview/what_is_cyrus.rst
Leave emdash alone, but genuine configure options are now
escaped.
GH #1879
> [Docs] Ensure --configure options are escaped.

- docsrc/assets/cyrus-more-memory-post23.rst
- docsrc/imap/download/release-notes/2.5/x/2.5.0.rst
- docsrc/imap/download/upgrade.rst
This is added to 2.5.0 release notes and 3.0 upgrade docs.  A new
"asset" is added.  This will require that 2.5.0 have new asset
directory, too.
Addresses issue #1937
> Add note explaining increased memory footprint.

- perl/imap/Makefile.PL.in
Not inheriting the GCOV_LIBS and linker flags, results in undefined
`gcov_*` references in `IMAP.so`
Fixes #1968.
> Bug 1968 - Inhert GCOV flags for imap perl module.

- libcyrus.pc.in
- perl/imap/Makefile.PL.in
- perl/sieve/managesieve/Makefile.PL.in
We don't seem to use `librt` anymore, so removing references to it from
the repo.
> Remove references to `librt`.

- configure.ac
- imap/caldav_alarm.c
This patch provides configure option to enable static builds. (Actually
it just uses the `--enable-static` and `--enable-shared` options
provided by `autoconf`). When configured statically, we ensure that we
link with `libstdc++` which is a dependency since, we link with
`libxapian`.
What does it actually mean to build Cyrus statically?
Only the binaries and libraries we build(`libcyrus_*) as a part of
`cyus-imapd` are built and linked statically. Only static archives(`.a`)
are built. All the external libraries are still dynamically linked.
> Option to build Cyrus statically. 

- imap/jmap_mail.c
The `fprintf()` is missing a format specifier. This patch makes sure we
add one with CRLF.
> jmap_mail.c: Add missing format specifier.

- imap/index.c
- imap/index.h
This patch improves the `index_fetch` code to do single-pass inline
unsolicited `FETCH`es.
Fixes #1971.
> [Bug 1971] New and Improved(tm) "tell exists count".

- README.md
Since we have build status for 2 branches, master and stable, add a
title against the badge to clarify the branch the badge is displaying
status of.
> Show titles against badges.

- docsrc/_static/cyrus.css
- docsrc/_templates/layout.html
- docsrc/conf.py
- docsrc/exts/themes/cyrus/buildstatus.html
- docsrc/exts/themes/cyrus/layout.html
- docsrc/exts/themes/cyrus/theme.conf
- docsrc/index.rst
Put travis-version in conf.py for travis builds.
Requires conf.py be kept updated for each branch, but the templates can stay templated.
> [Docs] Add Travis build status marker to sidebar

- imap/annotate.c
- imap/cyr_expire.c
`cyr_expire` already has annotation for `expire`, this patch adds support for
`archive` and `delete` operations.
> [Bug 1988] Add per folder annotation for cyr_expire

- imap/mailbox.c
- imap/mailbox.h
It will make life easier when trying to decode the flags. 
As per suggestion from @robmueller
> Log sysflags and oldflags as string values.

- imap/lmtpd.c
- imap/mailbox.c
- imap/message.c
- lib/imapoptions
This commit removes the `internaldate_heuristic` imap option. We now instead
rely on the date derived from stat of the maibox file, during reconstruct,
which is a lot more appropriate to use.
Fixes #2041
> [Bug 2041] Change reconstruct behaviour around file dates.

- docsrc/conf.py
- docsrc/exts/sphinxlocal/sitemap.py
Add new extension sphinxlocal.sitemap to conf.py
Add new config value sitemap_website to conf.py
Produces sitemap.xml in build/<target>/
where <target> is either man or html, depending on output format
being generated
[Docs] Sitemap generator
Only generate if output is html.
Support multiple webroots.
> [Docs] Generate google sitemap.xml

- cunit/times.testc
- lib/times.c
- lib/times.h
This commit adds support for RFC5322 date time parsing as per this[1].
We should eventually nuke the `time_from_rfc822()` and `time_from_rfc3501()`
functions.
[1] - https://tools.ietf.org/html/rfc5322#section-3.3
> [lib] RFC5322 date time parser.

- lib/times.c
A previous commit[1] had a unused varilable in the function `skip_ws`. I'm
now tying it to `__attribute__((unused))`.
[1] - 55cdf51025aa94875c729fb380a06c3e44643408
> [lib] Fix warnings in times.c

- imap/cyr_expire.c
The commit[1] had a stray LOG_NOTICE instead of LOG_DEBUG resulting in a
lot of noise in the syslogs. This patch fixes that.
Thanks to Ellie and Bron for noticing this.
[1] 757e6cb3a20.
> Turn off noise about annotation lookups in cyr_expire.

- cunit/times.testc
- imap/annotate.c
- imap/carddav_db.c
- imap/cyr_virusscan.c
- imap/http_caldav.c
- imap/http_caldav_sched.c
- imap/http_dav.c
- imap/http_jmap.c
- imap/http_rss.c
- imap/httpd.c
- imap/imapd.c
- imap/index.c
- imap/jmap_calendar.c
- imap/jmap_mail.c
- imap/lmtp_sieve.c
- imap/lmtpd.c
- imap/lmtpengine.c
- imap/mbexamine.c
- imap/mbtool.c
- imap/message.c
- imap/nntpd.c
- imap/notify.c
- lib/times.c
- lib/times.h
- notifyd/notify_mailto.c
- sieve/bc_eval.c
Use `time_from_rfc5322()` which complies with the RFC5322.
Fixes #2044
> [Bug 2044] Date header parsing compliance with RFC5322

- imap/annotate.c
- imap/index.c
`INTERNALDATE` expects date to be seprated by '-' where as RFC5322 date uses
' '(space) as separator. Using RFC3501 implementation for INTERNALDATE for
now.
> Use rfc3501 for internaldate.

- imap/cyr_virusscan.c
- imap/http_caldav_sched.c
- imap/lmtp_sieve.c
- imap/lmtpengine.c
- imap/mbexamine.c
- imap/mbtool.c
- imap/nntpd.c
- imap/notify.c
Although, both `RFC5322_DATETIME_MAX` and `RFC822_DATETIME_MAX` have the same
buffer sizes, we should use `RFC5322_DATETIME_MAX` since we eventually
deprecate the rfc822* functions in favour of rfc5322* functions.
> [imap] Use RFC5322_DATETIME_MAX instead of RFC822_DATETIME_MAX.

- imap/http_ischedule.c
In `meth_get_ischedule()` a `struct stat` buffer is used to generate the ETag.
But the stat buffer used is never initialised. This patch fixes that.
Possibly broken because of changes in 7ae6fee12e09bb171438f3dd7624b1c0b9511e41
> [ischedule] Use a valid struct stat buf.

- configure.ac
- imap/append.c
- imap/ctl_mboxlist.c
- imap/http_admin.c
- imap/http_caldav.c
- imap/http_carddav.c
- imap/http_dav.c
- imap/http_ischedule.c
- imap/http_rss.c
- imap/http_tzdist.c
- imap/httpd.c
- imap/imapd.c
- imap/jcal.c
- imap/squatter.c
- imap/xcal.c
- lib/murmurhash.c
- lib/util.h
- lib/vparse.c
- master/service.c
- sieve/bc_eval.c
- sieve/sieved.c
- sieve/tree.c
- sieve/variables.c
This patch fixes the warnings when compiling `cyrus-imapd` with gcc 7.
Primarily address thing fallthrough cases in `switch` statements[1].
[1] https://gcc.gnu.org/onlinedocs/gcc-7.1.0/gcc/Statement-Attributes.html
> GCC 7 compilation fixes.

- imap/squatter.c
Squatter when run with `-h` displayed the usage of `-U` twice. Only show
the correct one.
> [squatter] Fix usage.

- imap/tls.c
- lib/imapoptions
We don't check CRL's in TLS and this patch adds support for that. An
imap option called `IMAPOPT_TLS_CRL_FILE` is available to specify the
path of the CRL PEM file.
This patch is based of the work done by `stacy@millions.ca`.
> [Bug 1155] Check CRL's in TLS.

- docsrc/imap/reference/manpages/usercommands/installsieve.rst
- perl/sieve/lib/request.c
We shouldn't be truncating filenames of files with extensions `.script`
when uploading.
This patch was originally submitted by Дилян Палаузов.
Fixes #1907.
> [sieve] Don't truncate .script extentions when uploading.

- imap/annotate.c
- imap/annotate.h
- imap/imapd.c
- imap/lmtp_sieve.c
Currently when setting the special value of a folder twice to same
value, the `setmetadata` command is rejected. This patch checks if the
mailbox we are trying to set the special use flag on is the same
folder(with the same flag), we don't error, and return a success instead.
> [Bug 2086] Should be able to set special value twice.

- docsrc/overview/cyrus_roadmap.rst
3.0 is out, with JMAP, CalDAV and CardDAV support so indicate it. And obviously, these will improve so specify in "Future" section.
> Updating Roadmap

- Makefile.am
The man pages are included anyway in the tarball upon make dist, as they
are part of dist_man8_MANS. The automake conditionals are irrelevant in
this regard.
Patch from Дилян Палаузов.
> Makefile.am: overused EXTRA_DIST for man pages.

- docsrc/imap/download/release-notes/3.1/index.rst
- docsrc/imap/download/release-notes/3.1/x/3.1.1.rst
- docsrc/imap/download/release-notes/index.rst
Some documentation outlining the odd and even approach
in our release versioning. Odd = development only, even= stable.
Flagging the odd releases with big warning messages so
nobody can be surprised at what they're seeing.
> [Docs] Odd-even release cycle versioning.

- Makefile.am
- configure.ac
`make distcheck fails in the Debian testing because of this[1] change in
`ExtUtils::MakeMaker`.
To workaround that problem, this commit adds the `MANIFEST` files to the
build src directories using `AC_CONFIG_FILES`. I tried with
`AC_CONFIG_LINKS` but since the resulting symbolic links point to read
only files, that didn't work. So using `AC_CONFIG_FILES` instead.
Using `AC_CONFIG_FILES` results in a couple of warnings from automake
saying there is a circular dependency issues and that rule isn't being
ignored.
At this point there are too many workarounds in place for autotools to
work with the perl modules in Cyrus. Perhaps it is time to rethink how
we work with the perl modules.
[1] -
https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/commit/5742aeb93564a24634adc6055aa2a745d228d287 …
> [build] Workarounds to work with makemaker.

- imap/sync_support.c
Assuming that SYNCERROR means what I think it (should mean), namely "I
can't possible continue and will need an operator to intervene", all the
cases that are recoverable by doing a full resync should only warn.
The only thing I'm not sure about is if a full resync can ever fail for
one of these reasons. If it can, then there's now nothing to alert the
operator, and this patch probably should be applied as-is (at the cost
of someone getting woken up :/ )
> sync_support: downgrade recoverable SYNCERRORs to SYNCNOTICE

- docsrc/imap/reference/manpages/systemcommands/reconstruct.rst
- imap/cyr_expire.c
- imap/cyr_info.c
- imap/cyrdump.c
- imap/reconstruct.c
Show better help when run on the command line with the `-h`. This patch
updates the following tools:
* cyr_expire
* cyr_info
* cyrdump
* reconstruct
This patch uses `basename()` function from `libgen.h`.
> Update help for multiple cyr tools.

- Makefile.am
- imap/mailbox.c
- imap/mailbox.h
- imap/mailbox_header_cache.gperf
- imap/mailbox_header_cache.h
Use the generated perfect hash table(using `gperf`), for lookups.
> [mailbox] Cached header lookup improvements.

- imap/sync_support.c
I saw this today while recovering after a disk crash. It did not recover
by itself. I don't know if it should be recoverable by a full sync (and
this code should return IMAP_SYNC_CHECKSUM), but as long as requires
operator interventions, is should log a SYNCERROR.
> sync_support: emit a SYNCERROR on unexpected mailbox uniqueid change

- imap/append.c
- lib/imapoptions
Add separate config variable to control use of annotator during append.
Fixes #2109
> [Annotator] Control use of annotator during append

- imap/http_caldav.c
- imap/http_caldav_sched.c
- imap/http_tzdist.c
`icalproperty_get_tzid()` can return NULL if TZID has no entry. Ensure
that we check that we have a non-NULL `tzid` before using it.
> [caldav] Check for return of icalproperty_get_tzid().

- imap/jmap_calendar.c
Helps us with debugging. We've done it already in most places, except
for the couple of locations that this patch fixes.
> [jmap calendar]Log when throwing an internal error

- doc/examples/imapd_conf/murder-backend.conf
- doc/examples/imapd_conf/murder-frontend.conf
There was an error regarding the use of "proxyservers:" in the example
configuration files for murder frontends.  This commit fixes it.
Closes #2099
> Fix imapd.conf example files for murder

- lib/signals.c
The error message when the SIGUSR2 handler fails to be installed said
SIGTERM when it should have said SIGUSR2.
> Fix error message about failing to install SIGUSR2 handler

- imap/tls.c
- lib/imapoptions
This is based on a patch by @MASHtm in #2186 -- I've made it configurable.
Can I get some eyes on this please? :)
> tls: support reading dhparam from discrete file (tls_server_dhparam)

- docsrc/imap/reference/admin/sop/replication.rst
Added verbiage to documentation noting the requirement that all partitions from master instance must also exist on replica instances.  Addresses #2120
> Add note about partition requirements to SOP/replication

- docsrc/imap/concepts/features/mail-spool-partitions.rst
- docsrc/imap/reference/admin/locations.rst
- docsrc/imap/reference/admin/locations/searchtiers.rst
- lib/imapoptions
This is a first attempt to clear up some confusion in regards to the
nameing of partitions and the use of the various "partition-name"
configuration directives in imapd.conf(5).
It's my goal to eliminate all use of common words like "default" or
"archive" in the names of partitions in samples and descriptive
language, lest people perceive such use to mean that those names
*must* be used.
For example, rather than using the following:
defaultpartition: default
partition-default: /var/spool/cyrus
we can use:
defaultpartition: part1
partition-part1: /var/spool/cyrus
The file /lib/imapoptions has been lightly modified in service to this
cause, and to correct typos in the definition of searchpartition-name
settings.
Note: There had been some trailing white space in /lib/imapoptions which my …
> Try to clarify documentation in re: Partitions

- lib/libconfig.c
This should help make self-diagnosis of cases like #2120 a little easier
> libconfig: warn about lookups of nonexistent partitions

- timsieved/parser.c
This happens when a connection is made as an admin-user without a
mailbox (`sieveshell --authname cyrus localhost`)
See issue #855.
> Fix segfault due to unitialized local variable in timsieved.

- imap/sync_support.c
Reverting f51610c2 / #2159. It seems that most of the time it does recover, it just didn't in one particular case.
> sync_support: don't SYNCERROR on mailbox uniqueid change

- master/CYRUS-MASTER.mib
Corrections for issue #2197 .
Some warnings were not corrected:
./CYRUS-MASTER.mib:86: [2] {description-missing} description missing in object definition
./CYRUS-MASTER.mib:97: [2] {description-missing} description missing in object definition
./CYRUS-MASTER.mib:108: [2] {subtype-illegal} subtyping not allowed
./CYRUS-MASTER.mib:160: [2] {index-element-no-range} index element `serviceId' of row `serviceEntry' must have a range restriction
> Running smilint on the module file

- docsrc/imap/reference/manpages/systemcommands/squatter.rst
Add further clarification to squatter.rst to reflect interactions
with sync_log and related settings.
Also clarify that squatter should be listed in DAEMON section of
cyrus.conf, not in START.
Addresses issues raised in #2234
> More fixes to squatter.8 manpage

- docsrc/imap/reference/admin/sop/replication.rst
- docsrc/imap/reference/manpages/systemcommands/squatter.rst
The Cyrus IMAP replication subsystem assumes a default sync_log
channel named "" (the two-character string U+22 U+22).  If one modifies
the sync_log_channels: directive with a name for another sync_log
channel, such as "squatter" then the default "" channel vanishes, unless
it is also specified explicitly. [issue #2248]
This commit is a first draft at making this clear.  Changes are made to
both the manpage for squatter(8) and to the Admin Guide, Replication
pages.
I feel that we actually need to produce more generalized documentation
of the sync_log mechanism, and then link to that from all points
which deal with sync_log usage, as these will no doubt grow due to the
usefullness of the sync_log functionality.
Addresses #2248.
> Clarify documentation regarding default sync_log

- docsrc/imap/developer/install-xapian.rst
- docsrc/imap/reference/faqs/o-annotations.rst
- docsrc/imap/reference/manpages/configs/cyrus.conf.rst
- docsrc/imap/reference/manpages/systemcommands/squatter.rst
- imap/squatter.c
Add documentation for -Z to usage message in squatter.c
In squatter.rst:
* Update synopsis to include all instances where -u, -S and -Z may be
used.
* clarify freshness of indexes for different scenarios.
* clear up some language
* detail which options are specific to Xapian
* add a note to the HTML version referring users to install-xapian
documentation.
Generalize description of "/vendor/cmu/cyrus-imapd/squat" annotation in
the FAQ.
Updated install-xapian.rst to clear up some "default"-isms.
Update cyrus.conf.rst to clarify the nanny aspect of master(8) for
those items listed in the DAEMONS section of cyrus.conf(5).
Addresses #2234 & #2250
> More updates to squatter.rst to clarify operations.

- imtest/imtest.c
Check if mechlist is null is redundant because it's initialized in
ask_capabilities flow. As the result some capabilities may be lost and
reported as not advertised
Keeping (now reduntant) null check to avoid regressions in the future
This is regression in 9fd201ba2b4ab58eda3372fb6765e1d5d8f027b4
Bug-Url: https://bugzilla.redhat.com/1543481
> Check if mechlist buffer is not empty

- ptclient/ldap.c
allow users to just connect with their UID.
this patch adds functionality to search each existing domain for the user UID via LDAP.
fixes #2282
> ptclient: implement canonification across multiple domains.

- docsrc/imap/reference/manpages/configs/cyrus.conf.rst
- docsrc/imap/reference/manpages/systemcommands/squatter.rst
Add missing option -S to synopsis 1 in squatter.rst
Add note on effect of -D option for master(8) to cyrus.conf.rst.
Addresses further issues in issue #2234
> More doc edits: squatter.rst & cyrus.conf.rst

- imap/search_engines.c
- imap/search_engines.h
- imap/search_squat.c
- imap/search_xapian.c
- imap/squatter.c
This was needed when the Sphinx engine had its own separate
daemon that needed hand-holding.  The Sphinx engine is no more.
Closes #2242
> squatter: get rid of undocumented '-c' argument

- imap/tls.c
LibreSSL 2.7 adds OpenSSL 1.1 API leading to conflicts in method names
Patch also applies to 2.4 and 2.5
See also: https://bugs.freebsd.org/227166
Signed-off-by: Bernard Spil <brnrd@FreeBSD.org>
> Fix build failure with LibreSSL 2.7

- Makefile.am
The man page was (incorrectly) only included when squat was compiled in, not if squatter was being used e.g. with another search engine.
> Include squatter.8 if SQUATTER, not if USE_SQUAT

- lib/cyrusdb_lmdb.c
Mentioned by kworr on freenode #cyrus
Most of the syslog lines in the file were already cyrusdb but a few said cryusdb. This PR makes them all the same.
> cyrusdb_lmdb.c: Fixes a repeated typo cryusdb

- imap/http_admin.c
- imap/http_applepush.c
- imap/http_caldav.c
- imap/http_carddav.c
- imap/http_dav.c
- imap/http_dblookup.c
- imap/http_h2.c
- imap/http_ischedule.c
- imap/http_jmap.c
- imap/http_prometheus.c
- imap/http_rss.c
- imap/http_tzdist.c
- imap/http_webdav.c
- imap/httpd.c
- imap/httpd.h
- imap/promdata.p
- imap/promdatagen
- imap/prometheus.c
- imap/prometheus.h
This adds two kinds of metrics to httpd:
* basic connection level stuff (total connections, active connections, ready listeners, shutdown statuses)
* general method/namespace stuff (introspectively)
I expect at some point we will want to enrich the statistics we gather for some protocols that sit on top of httpd -- I'm thinking particularly of JMAP here.  There's no reason that each `imap/http_[namespace].c` file cannot track its own metrics in addition to the generic ones `imap/httpd.c` tracks: just set them up and count them appropriately.  I'd suggest naming such metrics `cyrus_jmap_...` or whatever, so they're clearly distinct from `cyrus_http_...`
In the meantime though, here's the bones.  I think this is also a pretty good demo of how to add new metrics to services we're not …
> add prometheus metrics for httpd

- imap/prometheus.c
- imap/prometheus.h
- master/master.c
This adds a mechanism by which master can include its service metrics into the prometheus metrics, while only depending on code already in libcyrus_min.
I'm particularly interested in suggestions for what these metrics should be named, their help strings, and most importantly, whether they're actually useful.  I've also left out the "nconnections" stat for now cause I'm not really clear what it's actually counting.
I consider this pull request to be a work in progress at the moment.
> master: report service metrics for prometheus

- imap/promdatagen
- imap/prometheus.c
- imap/promstatsd.c
This PR labels metrics with the ident of the service counting them. For example if your cyrus.conf has both "imap" and "imaps" services, the `cyrus_imap_foo` metric will be split up into `cyrus_imap_foo{service="imap"}` and `cyrus_imap_foo{service="imaps"}`, even though the same binary is used for both services.
To avoid reporting metric/service combinations that will never be seen (e.g. `cyrus_lmtp_foo{service="imap"}`), this PR: 
* no longer automatically initialises the last_updated field of metrics during `prometheus_init()`, instead leaving it as zero; and
* only reports metrics that have a non-zero last updated
A consequence of this is that a newly started Cyrus instance will report very few statistics at all, but the report will gradually thicken out as interesting events occur and …
> prometheus: service labels based on config_ident

- imap/promstatsd.c
This PR builds upon #2102 and must be merged after it.
This adds usage information (per partition) to the prometheus report:
* number of user accounts
* number of deleted mailboxes
* number of shared mailboxes
* quota commitments
The quota commitments are tricky, because there is no hard relationship between quota roots and disk partitions.  If a quota root crosses partition boundaries, its quota commitments will be counted towards each partition it affects, making it hard to infer anything useful from the data.  (Quota roots that cross partition boundaries are hard to work with in plenty of other ways, so my advice here is "just don't do that then".)
This does not count actual on-disk usage or free space; get those from your operating system metrics if you want to calculate percentages …
> promstatsd: report usage information

- imap/idled.c
- imap/promstatsd.c
- imap/squatter.c
This allows master to restart it, so that configuration is reloaded.
Fixes #2096
We don't have Cassandane tests for DAEMON processes (https://github.com/cyrusimap/cassandane/issues/48) yet, so this will need manual testing before it's merged.
> idled, promstatsd, squatter: exit on SIGHUP when started as DAEMON

- docsrc/imap/reference/manpages/systemcommands/reconstruct.rst
Reconstruct man page lists the -V option, but doesn't provide a usage synopsis, nor mention it in the description.  This fixes those oversights.
> Add missing -V option to reconstruct manpage.

- backup/ctl_backups.c
Static analizers report this as memory leak issue.
> Close backup on failure.

- imap/imapd.c
- imap/promdata.p
- imap/pushstats.snmp
- lib/imapoptions
Brings back the ANNOTATEMORE capability and SETANNOTATION and GETANNOTATION commands, hidden behind a new config item `annotate_enable_legacy_commands` (default: off).  This is for #2525.
Requesting code review as Cassandane doesn't exercise these commands directly, so we have no real tests for it, and I dunno how useful it is writing a bunch of brand new tests for a feature we keep trying to get rid of...  
(It looks like maybe Cassandane used to exercise these commands implicitly through calls to cyradm, but cyradm has since been updated to use the METADATA extension.)
> bring back SETANNOTATION/GETANNOTATION, behind config

- backup/lcb.c
Make static code analizers happy.
If stat() failed for some reason it may lead backup fd unclosed.
> Close file descriptior in case of error

- ptclient/ldap.c
Make cleanup more consistence to prevent leaks of memory pointed by
filter/base/res
> Replace simple return with cleanup flow

- imap/httpd.c
See https://tools.ietf.org/html/rfc6455#section-4.2.1 point 3:
3.   An |Upgrade| header field containing the value "websocket",
treated as an ASCII case-insensitive value.
> WS: Upgrade header value 'websocket' should ignore case

- tools/fixsearchpath.pl
In this code:
my $x = '';
use lib $x . "...";
The assignment of the empty string to $x happens *after* the
`use $x . " ..."`, so you get a warning.
To get around that you have to:
my $x;
BEGIN {
$x = '...';
}
use lib $x . "...";
> Fix "Use of uninitialized..." warnings in installsieve

- imap/idle.c
This fixes having side effects inside of assert calls. Issue #2564 
Nothing critical about this, just seeing this in the code bugged me.
> Take idle socket setup out of assert wrapper.

- imap/imapd.c
- imap/imapd.h
- imap/index.c
Implements the first stage (FETCH) of #2547 
```
C: 5 fetch 1 (X-MAILBOXID)
S: * 1 FETCH (X-MAILBOXID (INBOX))
S: 5 OK Completed (0.000 sec)
C: 6 create INBOX.target
S: 6 OK [MAILBOXID (b265a82e-9a73-4aa5-873a-8e7a42dcea3b)] Completed
C: 7 copy 1 INBOX.target
S: 7 OK [COPYUID 1542073619 1 1] Completed
C: 8 fetch 1 (X-MAILBOXID)
S: * 1 FETCH (X-MAILBOXID (INBOX INBOX.target))
S: 8 OK Completed (0.000 sec)
```
Cassandane tests here: https://github.com/cyrusimap/cassandane/compare/master...elliefm:v31/2547-imap-labels
I'm not wedded to the spelling `X-MAILBOXID` -- in fact, the more I see it, the more I dislike it.  I initially used the `X-` prefix because gmail's similar `X-GM-LABELS` does, but none of our other non-standard FETCH extensions use an `X-` prefix, so it's a bit out of place in …
> Labels via IMAP

- imap/lmtp_sieve.c
Create a mailshare with _email mailshare@domain.tld_ and set sieve script with redirection like:
`if allof ( address :contains ["to", "cc"] "sender") {
redirect :copy "target@domain.tld";
stop;
}`
Got a LMTP segmentation fault when receiving mail matching sieve rule:
`Nov 28 12:53:46 cyrus-vm postfix/qmgr[10701]: CDDAD800E1: from=<sender@domain.tld>, size=74989, nrcpt=1 (queue active)
Nov 28 12:53:46 cyrus-vm cyrus/master[11265]: process type:SERVICE name:lmtp path:/usr/lib/cyrus/lmtpd age:9.817s pid:11291 signaled to death by signal 11 (Segmentation fault)
Nov 28 12:53:46 cyrus-vm postfix/lmtp[11344]: CDDAD800E1: to=<+mailshare@domain.tld>, relay=172.16.20.51[172.16.20.51]:24, delay=165587, delays=165587/0.02/0/0.06, dsn=4.4.2, status=deferred (lost connection with …
> LMTP segmentation fault on mailshare with sieve redirections

- Makefile.am
- imap/cyr_virusscan.c
minor change is required to imap/cyr_virusscan.c to support clamav-0.101.0.
Also pass CLAMAV_CFLAGS when building imap/cyr_viursscan.c
> support clamav-0.101.0 and apply CLAMAV_CFLAGS

- imap/mbexamine.c
Partial Fixes #2606 by removing the chdir from do_examine and do_quota.
The the function do_compare still needs a fix.
> remove chdir for do_examine and do_quota

- lib/imapoptions
- ptclient/ldap.c
The switch statement uses `%R` for the domain part starting with `@`.
Add the missing `%R` line to *imapoptions*.
> Align docs to code

- docsrc/imap/concepts/deployment/authentication_and_authorization.rst
Corrected a typo in the ldap attribute example and used a bit of markup to
highlight the code examples in text a bit more. Finally use mdash instead of
ndash and simple dashes, when they are used to split subsentences.
> Tiny improvements to docs

- ptclient/ldap.c
It was probably meant to use filter as the second argument.
> Duplicate argument in log message

- ptclient/ldap.c
This fixes an regression, that was introduced with 61f5296c0d727faee4726525a6812b200d946d83.
Back then the logic was changed from `ldap_count_values(vals) != 1` to two `if` clauses
`ldap_count_values(vals) < 1` and `ldap_count_values(vals) > 1`
which logged errors and an else clause (which matched the correct number
of `ldap_count_values(val) == 1`) that got the old error handling code.
> Return correct group names when groups are resolved by filter

- imap/jmap_mail.c
Fixes #2668.
Tests doubtless need to be updated for this, but I’m not sure where they are. The update should be straightforward.
> Set a Mime-Version header on created emails

- imap/webdav_db.c
Obvious bug, obvious fix.
Of more interest is that there's no tests that tickle this. We only found it once it had almost made it to production, via Apple CalDAV clients accessing the notifications collection.
> webdav_db: fix GETFIELDS query syntax

- imap/cyr_virusscan.c
This PR uses a different approach for 09b5bf11e12185727d53a6ae06d71a767952a537.
As `LIBCLAMAV_MAJORVER` is only set in `clamav-config.h` which is not being installed by `make install` the devel-packages of clamav don't contain that macro. So the majorver switch point doesn't work – at least with RHEL/CentOS/SL using EPEL's clamav or Fedora. Not sure regarding other distributions, though.
IMHO it is quite easier checking for the existence of `CL_SCAN_STDOPT`.
> rely on CL_SCAN_STDOPT instead of LIBCLAMAV_MAJORVER

- imap/conversations.h
Permit `#include <imap/conversations.h>` in C++ programs.
> imap/conversations.h: C++ interface

- imap/mailbox_header_cache.gperf
It's likely something needs to be done to generate the gperf magic, but I'm not really set up to do that.
> cyrus.cache: don't cache Topicbox-specific headers

- imap/conversations.c
Every alternation adds a couple of stack frames for backtracking, and since we're only taking one space at a time, a long run of spaces can easily blow the stack.
Its still possible to break this by doing a long run of non-breaking spaces, or alternating simple whitespace & nbsp, and there's not an easy way to fix that because you can't include the \xC2\xA0 sequence in a character class. Improvements might include use of `[:space:]` or `\p{Z}` if PCRE's POSIX compat mode supports, or use of things like atomic groups if we were willing to switch to using PCRE proper.
Related: #2729.
> whitespace_re: take as much "simple" whitespace as possible before recursing

- imap/xapian_wrap.cpp
This fixes a compile error, "template with C linkage"
Fixes #2749
> include unicode/ucnv.h outside of extern C wrapper

- imap/cyr_virusscan.c
https://github.com/Cisco-Talos/clamav-devel/commit/048a88e changed
the handling of scan options, removing the CL_SCAN_STDOPT macro.
This change is already in the cyrus-imapd-3.0 branch as
09b5bf11e12185727d53a6ae06d71a767952a537 and fd72fcef79a09cc3e349ee36bef1904e6e8e1030
but missing from the still maintained 2.5 branch.
> allow building against clamav >= 0.101

- docsrc/imap/reference/admin/locations/searchtiers.rst
- docsrc/imap/reference/manpages/systemcommands/squatter.rst
- imap/squatter.c
• State, that -v can be used in any mode
• State that in squatter -u *users* and squatter *mailboxes* the items are space separated.
• In the synopsis, consistently surround options with spaces.
• Remove references of “squatter -I"
• Mention -A and -P options.
> Update documentation for squatter

- Makefile.am
This is essential for VPATH builds.
> Makefile.am: make sure the output directory for fig2dev exists

- configure.ac
Otherwise cunit/registers.h is not built during “make distcheck” and the latter fails.
> configure.ac: enable implicitly the unit tests, if cunit is found

- imap/lmtp_sieve.c
- lib/imapoptions
- sieve/bc_emit.c
- sieve/bc_eval.c
- sieve/bc_generate.c
- sieve/bc_parse.c
- sieve/bytecode.h
- sieve/interp.c
- sieve/interp.h
- sieve/sieve-lex.l
- sieve/sieve.y
- sieve/sieve_interface.h
- sieve/sieved.c
- sieve/test.c
- sieve/tree.h
- timsieved/timsieved.c
Adds a `x-cyrus-log` capability, which adds a simple `log STRING` action. When encountered, sends the text along with user and message info to the server log.
This script:
```sieve
require "x-cyrus-log";
log "hello";
```
yields:
```
2019-04-13T20:59:36.695849-04:00 fastmail1 slotf1t01/lmtp[1369640]: sieve log: userid=robn@fastmaildev.com messageid=<ad564e7f-24ba-41c3-8968-a8efaae7e18d@www.fastmaildev.com> text=hello
```
I am not committed to naming of either the capability or the action.
There's no rate limiting or other controls, as it wasn't really obvious what any given deployment would want. Obviously there's little value in allowing users to write their own log actions. The value comes from script generators, which can now arrange for additional information to be logged so they can …
> sieve: add x-cyrus-log capability and log action

- imap/jmap_mail.c
Otherwise we attempt to free invalid memory and segfault.
> _thread_changes: Initialize conv before we hit a goto

- imap/jmap_mail.c
> _email_query: emailsearch_getcachepath() takes no arguments

- imap/jmap_mail.c
...so we don't try to free them later without initializing them.
> _email_import: Initialize variables before we hit a goto

- cunit/charset.testc
- doc/legacy/anoncvs.html
- doc/legacy/install-configure.html
- doc/legacy/install-upgrade.html
- docsrc/imap/reference/manpages/systemcommands/ctl_backups.rst
- docsrc/imap/reference/manpages/systemcommands/deliver.rst
- docsrc/imap/reference/manpages/systemcommands/fud.rst
- docsrc/imap/reference/manpages/systemcommands/imapd.rst
- docsrc/imap/reference/manpages/systemcommands/master.rst
- docsrc/imap/reference/manpages/systemcommands/nntpd.rst
- docsrc/imap/reference/manpages/usercommands/installsieve.rst
- imap/append.c
- imap/autocreate.c
- imap/conversations.c
- imap/ctl_mboxlist.c
- imap/imapd.c
- imap/mailbox.c
- imap/mboxlist.c
- imap/mupdate-client.c
- lib/imapoptions
- lib/libconfig.c
- lib/vparse.c
- perl/imap/IMAP.pm
- tools/vzic/README
- tools/vzic/vzic-dump.pl
- tools/vzic/vzic-output.c
- tools/vzic/vzic-test.pl
- tools/vzic/vzic.c
Hello,
this little patch fixes some spelling errors reported by [Lintian](https://lintian.debian.org/) _([Debian](https://debian.org/) QA tool)_. This fixes #2753.
> Fix some spelling errors (Closes: #2753)

- imap/httpd.c
All other software uses slashes, like: ` Cyrus-HTTP/3.0.10 Cyrus-SASL/2.1.27 OpenSSL/1.1 Zlib/1.2.11 Brotli/1.0.7 LibXML2.9.9 SQLite/3.29.0 LibiCal/3.0 ICU4C/63.1 Jansson/2.12 Server at …`
> httpd: print slash after LibXML in the version info footer (3.0)

- imap/http_caldav.c
Only a few lines earlier, the code calls annotatemore_lookup(fctx->mailbox->name, …), after checking that fctx->mailbox is not NULL.  At the place that is checked here, fctx->mailbox can be null.
> http_caldav.c:propfind_timezone: don’t crash, if the mailbox does not exist (3.0)

- configure.ac
… at the end of ./configure’s output.
> configure: print NO when libzstd is not found

- imap/mboxlist.c
- imap/mboxlist.h
Exposes the 'p' callback from the cyrusdb_foreach API via the mboxlist_find* APIs, so that if you need to do a cheap custom check on matches before calling the expensive callback, you can.
Nothing uses this at the moment, so all the interesting changes in this PR are the ones in mboxlist.[ch], everything else is just noise due to the number of params changing.
It'll be useful for #2833 and closes #2834
> mboxlist: add 'p' callback to mboxlist_find*() API

- imap/promstatsd.c
This is basically the same as #2219 (with a conflict fixed), but with the syslogs in the hot loops removed.
This _should_ remove the main barrier we had to enabling this at FM, but the only "realish-load" test we've seen was with the syslog IO load killing it, so it might still be inadequately performant for some other reason.
There's some additional optimisations still to be had, but they require supporting work in underlying APIs (e.g. #2834), which will be separate PRs as they shake out.
> promstatsd: report usage information (take 2)

- imap/caldav_alarm.c
- imap/jmap_mail_submission.c
- imap/mailbox.c
Hi Ken, popping this one up for your review before it goes live.  We discovered that cancel was storing UNLINKED which breaks replication and made things sad - so I reviewed and came up with this proposal.  Also talked to Neil about whether we wanted EmailSubmission objects to persist past the submission and he said yes.  We'll probably have to make cyr_expire clean them up eventually, but that's future-us' problem.
> Emailsubmission useflags

- imap/conversations.c
- imap/conversations.h
So there is no point to declare it in imap/openconversations.h.
> conversations.[ch] open_conversations is needed only in conversations.c

- imap/conversations.c
- imap/conversations.h
So there is no point to declare it in imap/openconversations.h.
> conversations.[ch] open_conversations is needed only in conversations.c (3.0)

- cunit/buf.testc
- docsrc/imap/reference/manpages/systemcommands/cyr_virusscan.rst
- imap/cyr_virusscan.c
- imap/message.c
- lib/imapoptions
- lib/util.c
- lib/util.h
Adds two new imapd.conf options, for the notification subject and a template digest chunk respectively.  The defaults are the same as the old version, but converted to use the template style message construction.
Fixes the "From:" field of the digest chunks to look like a normal from header, instead of a dlist straight out of mailbox cache.
Fixes how the "mailbox" is reported to calculate an extname correctly
Failure to append a notification is now logged(!), and the template is checked early so if it looks un-appendable, we can bail out before deleting messages, instead of deleting them then being unable to notify that we did so
Notification messages are now properly MIME-encoded (I think!), so non-ascii mailbox names won't produce an invalid notification, and the custom template is …
> configurable cyr_virusscan notification text

- docsrc/imap/support/feedback-meetings.rst
According to <https://lists.andrew.cmu.edu/pipermail/cyrus-devel/2019-August/004505.html> weekly meetings now happen on Zoom.
> [docs] Update URL for weekly meetings

- docsrc/conf.py
- docsrc/exts/sphinxlocal/builders/manpage.py
- docsrc/exts/sphinxlocal/roles/cyrusman.py
- docsrc/exts/sphinxlocal/writers/manpage.py
This allows the documentation to be generated using version 2 of Sphinx – which is particularly handy on rolling release distros like Arch where version 2 is the only version conveniently available from the repositories. Nearly all of the changes are directly based on changes in upstream Sphinx, however they have been adapted to also keep compatibility with version 1.3.2 (which is the minimum version required by the current configuration and not much older than 1.3.6 – the version used to generate the website. On that note, the conf.py in master incorrectly states a minimum version of 1.2, so I updated that while I was at it). Should that much backwards compatibility not actually be necessary, I could also simplify the changes quite a bit. I *think* with a minimum version of 1.6 none of …
> Add compatibility for Sphinx 2 (fixes #2732)

- imap/mboxevent.c
as the macro expands to several statements and calling it immediately after *if* executes only the first statement of `FILL_STRING_PARAM` conditionally and the remaining statements uncondionaly.
> imap/mboxevent.c: wrap macro FILL_STRING_PARAM in {…} (3.0)

- docsrc/index.rst
In order not to confuse the beginning of Cyrus it is important to note that Cyrus has been under development since late 1993 and early 1994 as reported in the code history https://www.openhub.net/p/cyrus-imap/commits/summary
> Modification of the year of the launch of Cyrus' development

- lib/cyr_lock.h
- lib/lock_fcntl.c
- lib/lock_flock.c
- lib/map.h
- lib/map_nommap.c
- lib/map_shared.c
- lib/map_stupidshared.c
- lib/nonblock.h
- lib/nonblock_fcntl.c
- lib/nonblock_ioctl.c
So that the users of the libraries do not get their own copy for the lock_method_desc, map_method_desc and nonblock_method_desc symbols.
> libcyrus(_min).so: move *_method_desc to read-only segments

- lib/imapoptions
In the server/client model, one side is called client, and the other side is called server.  It is not correct to name both ends “server”.
• Clarify for tls_server_cert, that a file containing the full chain to the certificates, known to the client, must be presented.
> imapoptions:tls_server_*: reword server/client terminology

- lib/imapoptions
In the server/client model, one side is called client, and the other side is called server.  It is not correct to name both ends “server”.
• Clarify for tls_server_cert, that a file containing the full chain to the certificates, known to the client, must be presented.
> imapoptions: reword server/client terminology (3.0)

- doc/examples/cyrus_conf/cmu-backend.conf
- doc/examples/cyrus_conf/cmu-frontend.conf
- doc/examples/cyrus_conf/murder-backend.conf
- doc/examples/cyrus_conf/murder-frontend.conf
- doc/examples/cyrus_conf/normal-master.conf
- doc/examples/cyrus_conf/normal-replica.conf
- doc/examples/cyrus_conf/normal.conf
- doc/examples/cyrus_conf/prefork.conf
- doc/examples/cyrus_conf/small.conf
Currently the example configuration files for cyrus.conf and imapd.conf use different socket paths, even though the imapd.conf examples themselves explicitly state that they should match. This PR adjusts the paths in cyrus.conf examples (/var/imap/socket) to match those in imapd.conf examples (/run/cyrus/socket), since the latter seem to be a bit more commonly referred to in the documentation.
> Make sure socket paths in example configuration match

- Makefile.am
- configure.ac
- perl/imap/Makefile.PL.in
Right now, the IMAP perl module is linked with libcyrus_min, which, if enabled, uses libcap, however the Perl module is _never_ linked to libcap. This leads to an error when loading the module:
```console
$ cyradm
Can't load '/usr/lib/perl5/5.30/vendor_perl/auto/Cyrus/IMAP/IMAP.so' for module Cyrus::IMAP: /usr/lib/perl5/5.30/vendor_perl/auto/Cyrus/IMAP/IMAP.so: undefined symbol: cap_set_proc at /usr/lib/perl5/5.30/core_perl/DynaLoader.pm line 193.
at /usr/lib/perl5/5.30/vendor_perl/Cyrus/IMAP/Admin.pm line 43.
Compilation failed in require at /usr/lib/perl5/5.30/vendor_perl/Cyrus/IMAP/Admin.pm line 43.
BEGIN failed--compilation aborted at /usr/lib/perl5/5.30/vendor_perl/Cyrus/IMAP/Admin.pm line 43.
Compilation failed in require at /usr/lib/perl5/5.30/vendor_perl/Cyrus/IMAP/Shell.pm line …
```
> Fix missing libcap in Perl module

- configure.ac
- imap/httpd.c
-- ./configure --disable-http2 disables HTTP/2 even when libnghttp2 is installed
-- when nghttp/2 is not enabled/installed, don't send
Connection: Upgrade
Upgrade:
headers
> httpd: enable support for no HTTP/2

- docsrc/imap/concepts/deployment/databases.rst
- docsrc/imap/reference/admin/sop/userdeny.rst
- docsrc/imap/reference/manpages/systemcommands/cyr_dbtool.rst
- docsrc/imap/reference/manpages/systemcommands/cyr_deny.rst
Recommend cyr_deny instead of cyr_dbtool for managing user_deny.db.
Do not use the online documentation for cyrus imap 2.4.17 to reference the user_deny database format.
> Update documentation for user_deny.db

- docsrc/imap/concepts/deployment/databases.rst
- docsrc/imap/reference/admin/sop/userdeny.rst
- docsrc/imap/reference/manpages/systemcommands/cyr_dbtool.rst
- docsrc/imap/reference/manpages/systemcommands/cyr_deny.rst
Recommend **cyr_deny** instead of **cyr_dbtool** for managing *user_deny.db*.
Do not use the online documentation for cyrus imap 2.4.17 to reference the *user_deny* database format.
> Update documentation for user_deny.db (3.0)

- cunit/message.testc
- cunit/sieve.testc
- imap/append.c
- imap/imapd.c
- imap/jmap_mail.c
- imap/lmtp_sieve.c
- imap/lmtpd.c
- imap/message.c
- imap/message.h
- lib/cyr_lock.h
- lib/mkgmtime.h
- lib/retry.h
- sieve/test.c
- sieve/test_mailbox.c
If you've got opinions on the text of the error messages, sing out
I haven't yet tried to backport this for 3.0, but once it lands on master I'll look at that (and if it's easy and unintrusive to backport, I'll do so).
This closes #2782
> include file name (where known) in errors from message_parse functions

- lib/imapoptions
- master/master.c
This is the least-overthinky implementation of #2902 
Questions presently unanswered:
* should errors from the other socket-setup calls (socket(2), listen(2)) on this code path also be fatal with this option, or only bind(2)?
* does a bind on one getaddrinfo result ever fail when a bind on a subsequent result would have succeeded? (I don't think so)
* if the bind fails while setting up new services in an existing master process (i.e. after SIGHUP to provoke a cyrus.conf reread), should this situation be treated differently somehow?
* if there are already service processes running, should these be shut down?
> master: option to treat bind errors as fatal

- Makefile.am
- configure.ac
- docsrc/imap/developer/compiling.rst
- imap/caldav_db.c
- imap/dav_db.c
- imap/http_caldav.c
- imap/http_caldav_sched.c
- imap/http_ischedule.c
- imap/httpd.c
- imap/ical_support.c
- imap/ical_support.h
- imap/icu_wrap.cpp
- imap/index.c
- imap/jcal.c
- imap/xapian_wrap.cpp
- imap/xcal.c
- imap/xcal.h
- sieve/sieved.c
This bumps our minimum supported libical up to 3.0.0+ (removing a lot of feature-detection and workarounds going back to pre-1.0), and consolidates our icu usage and making it explicitly mandatory at configure time.
It also fixes some stuff that didn't build right with `--disable-jmap`, because that was on the circuitous path I needed for testing this.
This works great on my machine (tested with both the cyruslibs libical, and also a vanilla libical-3.0.0 from the release tarball), but we're all running different compilers and different library environments, so I'd appreciate if y'all could try this branch out in your own environment(s) before I merge it down, in case there's some platform-specific detail I've missed.
Thanks!
> make libical 3.0.0+ and libicu mandatory

- lib/retry.c
So, I think any issues that we may have seen with this function is if the initial writev() failed and returned -1.  We would then use that value in adjusting the iov which would result in an invalid iov_base pointer
> retry.c: rewrite retry_writev() to properly handle an initial failure

- lib/util.c
- master/master.c
Fixes #2974. I’ve tested it only on 3.0.13, but I see no reason why it wouldn’t also work on newer versions.
> Add compatibility with recent versions of libcap

- docsrc/imap/rfc-support.rst
https://lists.andrew.cmu.edu/pipermail/cyrus-devel/2020-March/004587.html
Per RFC 5465 page 7, the server-side support is announced with “ S: * OK [CAPABILITY IMAP4REV1 NOTIFY]”.  The CAPABILITY answer is generated in imap/imapd.c using “static struct capa_struct base_capabilities[]” in capa_response().  The latter contains no code to generate NOTIFY.
> docsrc/: Remove support for RFC 5465 IMAP NOTIFY Extension

- imap/index.c
- imap/jmap_mail.c
- imap/mboxlist.c
- imap/sync_client.c
- imap/sync_log.h
- imap/sync_support.c
There's more to do here still, but I'll open this PR now so it can be reviewed iteratively.
This first stage bundles MAILBOX updates by user, instead of processing them purely in the order they were seen.  Within each user, their MAILBOX order is preserved (though this doesn't make much difference in practice, I don't think: the whole list ends up as a single GET MAILBOXES call further down the stack).  However, the user list is processed in no particular order (i.e. hash table enumeration order -- I don't think this is a problem: we're already making user-ordering fairly meaningless by clustering mailboxes by user).
Instead of splitting operations into batches of exactly 1000 mailboxes, we collect user/mailbox operations one-whole-user at a time until we've accumulated 1000+ mailboxes, …
> sync improvements

- imap/http_cgi.c
From the standard specifications, it must be declared by the user if
it is to be used directly.
> imap/http_cgi.c: exactly declare `extern char **environment`

- imap/jmap_mail_query.c
- imap/search_xapian.c
- imap/xapian_wrap.cpp
- imap/xapian_wrap.h
- lib/imapoptions
- lib/util.c
- lib/util.h
We came to realize that the in-memory Xapian database is way less efficient than the on-disk backends. Let's switch to using the default backend when evaluating a message against a JMAP Sieve rule. Cyrus installations should point their imapd.conf temp_path option to a tmpfs filesystem.
> Matchmime tempdir

- imap/jmap_api.h
- imap/jmap_core.c
- imap/jmap_mail.c
This is the full 3.2 fix for #3056 
@ksmurchison can you please cast an eye across this?  I think it's complete, but I'd like a second opinion :)
> 3.2: protect Blob/get and Email/matchMime behind jmap_nonstandard_extensions

- imap/http_jmap.c
- imap/httpd.c
- imap/httpd.h
- imap/imap_err.et
- imap/imapd.c
- imap/index.c
- imap/jmap_api.c
- imap/pop3d.c
- lib/imapoptions
Here's another review :)  This one creates a "readonly" mode.  I haven't added it to nntpd, because... meh.
It also doesn't do CalDAV, CardDAV, etc.  We could probably do those just by banning meth_post, meth_delete, meth_put, etc.
Can you please especially review the cmdloop entries and see if I got all the things that try to write.  I'm tempted to add a syslog if it tries to take a writelock on any database!
> Readonlyimap

- configure.ac
- imap/httpd.c
This is a proposed fix for platforms that don't yet have a version of zlib that has deflatePending() (e.g. OpenBSD).
In my brief testing, none of the paths to zlib_compress() (length-delimited response, chunked response, WebSockets PMCE) triggered avail_out == 0, but I didn't want to remove the condition entirely.  I chose a fallback of pending=7 because its >6 per the comment, but we could bump this to 16/32/1024/etc.
I'd like to deploy this on a FM test server for a while to see if I broke anything.
> httpd.c: zlib_compress() rewrite to handle lack of deflatePending()

- docsrc/imap/rfc-support.rst
- imap/imapd.c
The IMAP Capabilities Registry was updated to state that the capability in RFC 5524 is not URLFETCH=BINARY but URLAUTH=BINARY.
> imap: URLAUTH=BINARY clarifications

- imap/jmap_calendar.c
This was raised by reports of people seeing "so and so shared a calendar with you" when they didn't mean to!  Any calendar creation.
I looked at the logs and the newly created mailbox got some "shared to everyone" ACLs before things were cleaned up a few seconds later, due to domain.com!user.foo.#calendars having an 'lr' ACL for everyone who has any calendar shared to them from that user, which is used for something else.  Doh.
Anyway, this horrible patch avoids that happening, at the expense of yet more open-coded ACL management.
> Sharewith safety

- imap/caldav_alarm.c
- imap/jmap_mail.c
- imap/lmtp_sieve.c
This adds error handling to unsnooze.  In particular, if it fails it tries again in 5 minutes rather than stopping forever, and if it fails at all, it aborts the mailbox changes.
This means it has to reopen the mailbox every time (or at least commit and relock!) because otherwise the conversations DB and mailbox state can get out of sync because something got aborted from one and not the other.  *sigh*.  Roll on single DB.
> Snooze error handling

- imap/jmap_mail.c
This patch adds support for allInThreadHaveKeyword, someInThreadHaveKeyword, noneInThreadHaveKeyword Email/query filter criteria to guidsearch.
The Cassandane test is at: https://github.com/cyrusimap/cassandane/tree/jmap_guidsearch_threadkeywords
> jmap: support inThreadHaveKeyword criteria in guidsearch

- cunit/vparse.testc
- lib/vparse.c
As seen in the wild: a VERSION property ` 3.0` (note that leading whitespace). This patch silently accepts this bogus value. It does not rewrite the property value. We could make it so if `carddav_repair_vcard` is enabled, but this option is not enabled currently and we should first agree on if this is dead code, actually.
> carddav: leniently accept whitespace in VCARD VERSION property

- imap/imapd.c
- imap/imapd.h
- imap/index.c
This PR along with the following patch would've caught the "not replicating \Snoozed flag" bug a lot sooner:
diff --git a/Cyrus/CheckReplication.pm b/Cyrus/CheckReplication.pm
index 038215f..7ec6420 100755
--- a/Cyrus/CheckReplication.pm
+++ b/Cyrus/CheckReplication.pm
@@ -321,8 +321,8 @@ sub CheckFolderFlags {
my $Repeat = 0;
RepeatCheck:
-  my $s1Flags = $Self->do_fetch($IMAPs1, $CyrusName, 'flags') || return;
-  my $s2Flags = $Self->do_fetch($IMAPs2, $CyrusName, 'flags') || return;
+  my $s1Flags = $Self->do_fetch($IMAPs1, $CyrusName, 'flags+') || return;
+  my $s2Flags = $Self->do_fetch($IMAPs2, $CyrusName, 'flags+') || return;
my %ids = (%$s1Flags, %$s2Flags);
> imapd.c: Added FLAGS+ FETCH item to include Cyrus internal flags

- cunit/vparse.testc
- imap/http_carddav.c
- imap/index.c
- imap/vcard_support.c
- imap/vcard_support.h
- lib/imapoptions
- lib/vparse.c
- lib/vparse.h
We introduced VCARD reparation about 3 years as optional, but today decided to make Cyrus unconditionally repair bogus input in VCARD (as far as we can). This patch updates the VCARD parser to leniently skip control characters in VCARD input.
The unit tests have been updated to reflect this change. For a list of test cases see https://github.com/cyrusimap/cyrus-imapd/blob/d69a61c946f2d8c719061a12bbed5929c2d69cd6/cunit/vparse.testc#L63
> vparse: unconditionally repair control characters in VCARD

- cunit/conversations.testc
- imap/conversations.c
We reworked conversation subject normalisation recently (4c643deb98e5cbcf47371eb1ee0ab74dbc4ba987) but the new regex did not work for builds with `--disable-pcre`. This patch rewrites the regex to be POSIX-compliant.
> conversations: make subject normalisation regex not require PCRE

- imap/cyr_expire.c
- imap/imapd.c
- imap/mboxlist.c
- imap/sync_support.c
- imap/user.c
Hi Ken,
This is an exciting one!  It comes from all the bits that odd_mailboxes.pl and audit_slot.pl are finding still broken on our servers.
It fixes UNUSER to not wipe the DELETED mailboxes, then switches all deletes to all UNUSER so the meta files are cleaned up right.  It also fixes intermediate handling on deletion, due to me adding tests for all that in: https://github.com/cyrusimap/cassandane/pull/90
Hoping to run this in anger tomorrow :)
Cheers,
Bron.
> Sync rename delete safety

- cunit/bitvector.testc
- imap/jmap_mail.c
- lib/bitvector.c
- lib/bitvector.h
This PR fixes a bug in guidsearch using twoskip as a backend for conversations.db. If one of the xxxInThreadKeywords filter criteria was used, then the original code loaded conversation records from within the callback of guid_foreach. This worked fine for skiplist, but messed up the database-internal iterator state for twoskip.
The patch refactors guidsearch to first obtain all results from Xapian by use of the guid_foreach callback. Only after that, it reduces the result set by evaluating non-Xapian filter expression. This fixes the issue of interleaved conversation.db calls. However, where the original code could reuse one instance of a guidsearch_msg, the patched code now has to maintain a guidsearch_msg for each G record returned by Xapian.
To not get penalized for probably thousands …
> Refactor guidsearch to postprocess non-Xapian filter criteria

- imap/search_engines.c
- imap/search_engines.h
- imap/squatter.c
Currently, a message has index level 3 if an extractor url is configured (regardless if that message actually contains attachments). If no extractor url is configured, then Cyrus falls back to using the legacy index level 1 for that message, meaning: "We don't know if that message contains attachments with text". As a consequence, installations may have databases with mixed index levels 1 and 3 if they turned the extractor url config on and off over time.
The new -L argument for squatter allows to reindex all messages that are below a certain index level. As it currently stands, it only makes sense to pass -L 3 to force reindexing messages that have indexlevel 1.
As an exception, this patch does not have a corresponding Cassandane test. There's too many dependencies and assumptions to …
> squatter: add -L option to reindex messages by minimum index level

- imap/xapian_wrap.cpp
Some mail services use HTML tags in the phrase part of RFC2919
List-Id header values (and tend to forget the closing angle
bracket on the actual list-id). Treating the last '<' character
as starting angle bracket allows us to propertly extract the
list-id value from such headers.
This also works nicely with variants where clients cannot make
up their mind if their list-ids should be RFC2919 or Groups-style.
> xapian: look for starting list-id angle bracket from end of string

- imap/conversations.c
- imap/jmap_backup.c
- imap/mailbox.c
- imap/mboxlist.c
- imap/mboxname.c
- imap/mboxname.h
- imap/sync_support.c
Calling Mailbox/destroy with onDestroyRemoveMessages deletes all messages in that mailbox and the mailbox itself, as expected. However, a subsequent call to Email/changes does not report emails that were either destroyed or updated due to the mailbox destruction.
This patch bumps the deleted modseq counters in delayed mailbox deletion, as moving a mailbox in the DELETED namespace throws away requirement information to calculate email changes. This causes Email/changes to return "cannotCalculateChanges". Mailbox/changes still has the required mailbox tombstone and continues to work as currently. Only when a mailbox is deleted from the filesystem the folderdeleted modseq is bumped in counters, also invalidating Mailbox/changes.
Similarly, the calendars and contacts JMAP code is updated. …
> JMAP: bump modseq of alive JMAP emails in Mailbox/destroy

- cunit/message.testc
- cunit/sieve.testc
- imap/http_rss.c
- imap/jmap_mail.c
- imap/jmap_mail_query.c
- imap/jmap_mail_query.h
- imap/lmtp_sieve.c
- imap/lmtpd.c
- imap/lmtpd.h
- imap/lmtpengine.h
- imap/message.c
- imap/message.h
- lib/imapoptions
- sieve/test.c
- sieve/test_mailbox.c
Only parse the message once, no matter how many JMAP queries there are to run!
> Matchmime cache

- cunit/parseaddr.testc
- imap/xapian_wrap.cpp
- lib/parseaddr.c
This showed up while debugging a failing JMAP query sieve script: a message with a stray CR in the (non-ASCII) email address name part was indexed properly in Xapian. But when matching the same email address in a Sieve JMAP query the filter failed. This is because the message.c code handles lone CR and LFs, but our email address parser in Xapian did just pass the bogus header value on to parseaddr.
I suggest we make parseaddr lenient with regards to control characters: it preserves TAB, replaces lone CR and LR with space and ignores all other control characters.
> parseaddr: ignore control characters in quoted names

- imap/xapian_wrap.cpp
It is almost always empty for our use cases anyway.
> xapian: do not log Xapian error context

- Makefile.am
Build failure while building on Ubuntu 20.04.1 LTS. I added the dependency into `Makefile.am` and the build passed. I might not have added the dependency in the correct place, though?
Ubuntu 20.04.1 LTS VM.
Behaviour the same on imapd-cyrus-3.2.2 and master (d037fc409).
git repository used.
N/A
Not relevant.
Not relevant.
I built from a clean clone as follows:
```bash
git clone https://github.com/cyrusimap/cyrus-imapd.git
cd cyrus-imapd
git checkout cyrus-imapd-3.2.2 # Missed this step when building from master
export CYRUSLIBS=/usr/local/cyruslibs
export PKG_CONFIG_PATH="$CYRUSLIBS/lib/pkgconfig:$PKG_CONFIG_PATH"
export LDFLAGS="-Wl,-rpath,$CYRUSLIBS/lib -Wl,-rpath,$CYRUSLIBS/lib/x86_64-linux-gnu"
export XAPIAN_CONFIG="$CYRUSLIBS/bin/xapian-config-1.5"
autoreconf -i
./configure …
```
> Add xml_support.c to ctl_zoneinfo dependencies

- imap/squatter.c
- lib/imapoptions
This is related to the 'pendingdelete' users that we create at Fastmail to rename users to when we delete them and support undo for a week.
Right now, we wind up reindexing the entire user when we rename it, even though we'll reindex it AGAIN when we rename back - this is wasteful, so let's just stop it.  I added the users option as well just because it parallels nicely.
this will be paired with a 'search_index_skip_domains: pendingdelete' imapd.conf setting.
> squatter: add search_index_skip_domains and search_index_skip_users

- lib/cyr_qsort_r.c
This is the fix for #3154, in which we discovered that we were accidentally (by way of macro expansion in cyr_qsort_r.c) replacing the real `qsort_r()` with our last resort fallback function, instead of simply having it as a last resort fallback.
The patch is fairly trivial and I think obviously correct (and works fine for me), BUT it has the "side effect" that we're now definitely using the real `qsort_r()`, whereas before we might not have been (depending on link order, I guess).
So I'd appreciate if we could all give this a thorough test before we merge it, just in case some new edge case shakes out from switching underlying implementations.
> cyr_qsort_r: only compile fallback function if we need it

- configure.ac
- lib/util.c
- lib/util.h
The `futimes()` function is not standardised and only available in Linux and some BSDs.
Check if it exists before using it, and fall back to alternatives.
The TIMESPEC_TO_TIMEVAL() macro is also not available on all platforms.
> Not all systems have futimes() or TIMESPEC_TO_TIMEVAL()

- imap/append.c
- imap/jmap_contact.c
- imap/mailbox.c
- imap/mboxlist.c
- imap/squatter.c
- imap/sync_support.c
- imap/tls.c
- lib/cyrusdb_twoskip.c
- lib/util.c
- lib/util.h
- sieve/script.c
This is a prototype of the syslog wrapper we've been talking about for standardising Cyrus's log output.
We've talked about this a few times recently, and each time the details of what we want have been slightly different.  I've thrown something together that broadly seems to do what we want, expecting that some of the specifics will be subject to further discussion and refinement.
I've called it `xsyslog()`, because I want to be able to naively search sources for "syslog" and find legacy and new kinds of log output, and because I want the casual reader to understand that this macro is roughly analogous to `syslog()`.
Some points for consideration:
* Automatic inclusion of the file and line number, but not the function name.  I'm reluctant to clutter it up with too much noise, and the …
> WIP syslog wrapper

- imap/user.c
This is the minimally-intrusive fix for #3169 that I plan to roll out for 3.2, and I would like to also add it to master so we don't get out of sync.  A real fix will probably take some surgery in the mbname API, which would be nice to do, but not for 3.2.
The problem hereby solved manifests when replicating from 2.4 with unixhierarchysep, which caret-escapes localpart dots in the sync USERID fields(!).  It's mostly quietly glossed over and not a problem; but if you're replicating sieve scripts specifically and you have fulldirhash enabled, then a modern-day replica hashes the caret-escaped version of the userid instead of the real userid, and puts the uploaded/activated scripts in the wrong on-disk location, where nothing else can find them.
My patch has been confirmed to fix the problem …
> user_sieve_path() needs to work around caret-escaped userids

- cunit/buf.testc
- imap/annotate.c
- imap/annotate.h
- imap/ctl_cyrusdb.c
- imap/ctl_mboxlist.c
- imap/cyr_expire.c
- imap/http_dav.c
- imap/imapd.c
- imap/jmap_backup.c
- imap/jmap_calendar.c
- imap/jmap_mailbox.c
- imap/lmtp_sieve.c
- imap/mboxlist.c
- imap/mboxlist.h
- imap/nntpd.c
- imap/sync_reset.c
- imap/sync_support.c
- lib/util.c
- lib/util.h
This patch makes mailbox role updates in Mailbox/set more sophisticated:
- Similar to changes to the mailbox tree, it predicts the final state of Mailbox roles after all operations in the Mailbox/set method were applied.
If the final state is valid, it suppresses Cyrus regular specialuse checks during mailbox renames and deletes, so that all operations can be applied.
If the final state is invalid, it rejects all operations that would alter a mailbox with specialuse, even if some of these operations would be valid.
IMAP specialuse rules and JMAP roles semantically differ and they impose different rules. This patch only accepts a final mailbox state to be valid if the restrictions of both IMAP and JMAP are satisfied. As a consequence a single role update might require the caller to first …
> JMAP: handle role updates in Mailbox/set

- imap/jmap_mail.c
We need this for inMailboxOtherThan to work.
I added a second part to this to also label the mailbox as not existing!
There's a related test over in Cassandane: https://github.com/cyrusimap/cassandane/tree/notes-guidsearch
> jmap_mail: add non-mail folders to foldernum_by_mboxname

- imap/httpd.c
Somehow a typo escaped in the code that only activates on OpenBSD
> httpd.c: deflatePending-free workaround typo

- imap/jmap_ical.c
Tested at https://github.com/cyrusimap/cassandane/commit/5669d91cc52ad8960cc34ecfff2b4dec76318a13
> jmap_ical: unescape iCalendar X-parameter TEXT values

- imap/conversations.c
- lib/cyrusdb.h
- lib/cyrusdb_twoskip.c
This allows conversationsdb to skip the CRC32 checks when in shared mode (i.e. reading only).  This is because we have users with millions of emails where over 50% of the CPU usage is just crc32 despite us using a really efficient one - so this skips doing those checks when it's just a read, while still having the checks when we're doing writes.
> Conversations read nocrc

- imap/httpd.c
- remove useless 'else' after 'return'
> httpd.c:meth_get(): variable 'ret' is not used

- imap/ctl_zoneinfo.c
It is called `ctl_zoneinfo` and not `zoneinfo_reconstruct`.
> imap/ctl_zoneinfo.c: update synopsis

- imap/index.c
- imap/jmap_mail.c
- imap/sync_log.h
- imap/sync_support.c
886ee1537c1ef4527b573dd0917661e4260972a0 replaced all calls to `sync_log_mailbox_double()` with a new macro, `sync_log_rename()`, and added improved atomicity of replication of mailbox renames.
But, not all occurrences of `sync_log_mailbox_double()` were mailbox renames! Some were copies or moves of messages between folders -- which got confusing when reviewing sync_log, because it looked like lots of bad renames were happening when it was just people moving messages between folders.
This PR brings back `sync_log_mailbox_double()`, for use when two mailboxes need to be replicated together (but not due to a rename).
`sync_log_rename()` remains for actual renames
> sync_log: bring back sync_log_mailbox_double for copy/move

- imap/squatter.c
This just looks easy :)
I already put magic in to index_one to handle precisely this case, it just does 'goto again' if there's more to do, so I think just passing the batch flag is all good.
> squatter: make batch mode always be on #3203

- cunit/annotate.testc
- imap/annotate.c
Per RFC, annotations are meant to be case-insensitive, but if the `annotation_definitions` option is set to a file of additional server-defined annotation definitions, the case in the file is currently preserved.  Our case insensitivity is implemented by expecting the definitions to be lowercase, but the examples in the RFC are in uppercase for some reason, which causes problems for admins who base their custom definitions on the examples (#3043).
It's trivially fixed by `lcase()`ing each annotation definition as it's loaded from the file, which is the primary purpose of this PR.  But our DAV annotations are case-sensitive.  Is this going to be a problem?  Is it useful for an admin to define custom DAV annotations, which need case sensitivity?
This PR also adds a unit test to prove the …
> load server-defined annotation definitions file case-insensitively

- imap/xapian_wrap.cpp
> xapian_wrap:get_stopper() use the cached stoppers

- imap/cyr_expire.c
- imap/quota.c
Affects `cyr_expire [...] -p mboxprefix` and `quota [...] mboxprefix` (no `-u`).
Mostly only noticeable when unixhierarchysep and/or virtdomains is in use?
Fixes #1699
> treat cyr_expire and quota cmdline mboxprefix as admin namespace, not internal

- imap/caldav_alarm.c
- imap/carddav_db.c
- imap/http_dav.c
- imap/mailbox.c
- imap/mailbox.h
- imap/message.c
- imap/webdav_db.c
This allows compiler optimizations, leads to smaller binaries, smaller table of exported symbols and faster so-library loading.
> Mark some functions as HIDDEN

- imap/fud.c
A refinement of the previous change
Original author: Antoine Jacoutot, openbsd/ports@cb3a0ef
> fud: don't redefine MAXDOMNAME/MAXLOGNAME if already defined

- imap/conversations.c
- imap/conversations.h
- imap/http_jmap.c
- imap/httpd.c
- imap/imapd.c
- imap/jmap_api.c
- imap/jmap_mail_submission.c
- imap/mailbox.c
- imap/mailbox.h
- imap/mboxname.c
- imap/mboxname.h
- imap/pop3d.c
- imap/user.c
- imap/user.h
This puts a user namespace lock into either conversations.db or mailbox, whichever opens first!  Since that blocks either of the other from opening, it means we can't have lock ordering problems, I hope!
The most complex bit is in mailbox_lock_index(), where the lock could have been dropped, because mailbox_unlock_index() drops it to mean long running IMAP fetches don't block other actions.  This means that if there's no namespacelock, we need to drop everything and relock.  There's already logic for that when changing locktype, so I hooked this in.  Pretty sure it's correct.
> fix up locking for conversations DB

- configure.ac
- lib/memrchr.c
I've just finished packaging Cyrus imapd for OmniOS which is an illumos (née OpenSolaris) distribution.
There were a few small compatibility changes needed, this is the first.
> Not all systems have memrchr()

- imap/xapian_wrap.cpp
Tested in https://github.com/cyrusimap/cassandane/commit/adf8902013e02412c83d488c94978acbb0fd375a
> xapian: search for wildcard in email query instead of parsed address

- imap/jmap_mail.c
We're inside a userlock which will stop anything else writing to it,
but if we're holding the seen lock then the append will fail to addseen.
See test case: https://github.com/cyrusimap/cassandane/pull/98
> jmap_mail: don't use seen_lockread

- timsieved/actions.c
Upon `UNAUTHENTICATE` and another `AUTHENTICATE` the variable sieved_userid is set to a new value and the old value is leaked.
In timsieved/actions.c:actions_setuser() there is no need for local variable ‘user’, which does the same as the static variable ‘sieved_userid’.
> timsieved:actions_setuser(): sieved_userid can be leaked

- imap/message.c
We have seen email messages with a Content-Type: name= parameter value which is unencoded UTF8(?)  This just blindly allows these chars.  We could also properly encode them as UTF8 as we build the MIME structure but then the IMAP envelope wouldn't match the raw message.
> message.c: allow 8-bit chars in MIME parameter values

- imap/mailbox.c
- lib/util.h
I'm trying to keep these changes in small batches, cause they need very close review (we have no test coverage for most of our errors), and the changes are all very similar and eye-glazey.
Here's the updates for the IOERRORs in mailbox.c.  I also added a format attribute to the xsyslog definition, like our other printf-alike functions, so we get a bit of compiler noise for the class of mistakes the compiler can detect.
This would benefit from a compile test, in case your compiler has newer/better warnings than mine.
> mailbox.c IOERROR xsyslog updates

- imap/jmap_mail.c
Tested in https://github.com/cyrusimap/cassandane/commit/c0e0b2a2888785186bec895369d0a5e96e2986f6
All Email/parse tests valgrind OK.
> jmap_mail: fix Email/parse to correctly parse top-level message

- cunit/charset.testc
- lib/charset.c
This resolves a customer issue where they edit a To: header which contains a character that needs encoding.  We can't just blindly QP encode the entire header without breaking it for clients.  This patch encodes only the display-name portion of name-addrs, and leaves addr-spec, angle-addr, the "," separating the addresses, and any surrounding whitespace alone.
> charset.c: properly QP encode address-list headers

- cunit/jmap_util.testc
- imap/jmap_contact.c
- imap/jmap_mail.c
- imap/jmap_util.c
- imap/jmap_util.h
This patch changes Contact/get to handle invalid UTF-8 data in VCARD fields such as EMAIL, N, FN, etc.
However, in contrast to Email/get this does not allow for repairing bogus data: a couple of tests on libchardet reveal that it is likely to incorrectly guess the charset for very short text such as email addresses and other contact data. In contrast to Email/get the Contact/get method does not allow indicate to the client if any of the text values may have character encoding issues. To err on the safe side, this patch instructs the charset detector to always fall back to UTF-8 replacement characters for any invalid UTF-8 sequences. A Cassandane test highlights this issue https://github.com/cyrusimap/cassandane/commit/56ab4804233d560cbb7be793ae5a1b591c96727b (where we could repair the …
> jmap_contact: decode VCARD text values to UTF-8

- configure.ac
[This fixes some annoying warnings from clang on OpenBSD.  We were trying to do the right thing, but weren't quite there.]
Missing support is only a compiler warning, so we need to force
-Werror on to be able to detect it.
Convert to AC_COMPILE_IFELSE and AC_LANG_PROGRAM so we can fiddle
with CFLAGS, and also convert to AC_CACHE_CHECK since we're
refactoring anyway...
Part of #3265
> configure.ac: improve detection of optimisation support

- imap/search_engines.h
- imap/search_xapian.c
- imap/squatter.c
- imap/xapian_wrap.cpp
New squatter -D option allows to skip duplicate part check.
Tested in https://github.com/cyrusimap/cassandane/commit/c0c5d37ce3c9e8b6cc47f9a8e684214396f29c69
> xapian: skip indexing of already indexed body parts

- cmulocal/cyr_inttype.m4
- configure.ac
- imap/caldav_alarm.c
- imap/conversations.c
- imap/http_admin.c
- imap/http_caldav.c
- imap/http_caldav_sched.c
- imap/http_carddav.c
- imap/http_dav.c
- imap/http_dav_sharing.c
- imap/http_h2.c
- imap/http_ischedule.c
- imap/http_rss.c
- imap/http_tzdist.c
- imap/http_ws.c
- imap/httpd.c
- imap/index.c
- imap/mailbox.c
- imap/mbexamine.c
- imap/seen_db.c
- imap/sync_support.c
- imap/zoneinfo_db.c
- imtest/imtest.c
- lib/auth_pts.c
- lib/prot.c
- master/master.c
- notifyd/notify_mailto.c
- sieve/sieved.c
@elliefm, @obache, all,
I tried to pay a lot of attention to the details, but please check this PR exhaustively, each change separately, as there are many small details with a single char changing the entire meaning.
@elliefm, also please test-run this PR on as much platforms and OS as possible.
On the other hand, I have some observations:
* please check the commit msg of the 1st commit in the PR. The `configure.am` checks don't make much sense for a _real_ detection of the specifier, but I proceeded as was suggested by @elliefm.
* **imap/mailbox.c**, **imap/sync_support.c**, etc.: it was `%lu`, now it is `%ld`/`%lld`, i.e. signed/unsigned change. Not sure why it was unsigned as `time_t` is a signed data type.
* **imap/mbexamine.c** line 259: why was that cast instead of `time_t`?
* …
> Format specifier fixes

- imap/http_jmap.c
JMAP Session object requires a `eventSourceUrl` property, but Cyrus does not implement push events. This patch adds a stub that always returns HTTP 501 (Not Implemented) for the advertised event source URL. Also see #3272
Tested in https://github.com/cyrusimap/cassandane/commit/de17790b8525a3cee0087a15d86f84b8c2463c2a
> jmap_core: add http handler stub for eventSourceUrl

- tools/translatesieve
This is necessary on FreeBSD otherwise it goes back up a directory and gets lost.
> Ignore . and .. while iterating through the directories holding usernames

- configure.ac
Currently although you enable SRS in configure, SRS is not enabled
There is because there is a missing AC_DEFINE in configure.ac not generating the "USE_SRS" define.
> Fix SRS enable funcionality

- imap/sievedir.c
- imap/sync_support.c
Found by Sentry.  What happened was that sync_client went to build a list of the current sieve scripts for a user, while an update was being applied to (one of) that user's script(s).  `sieve_foreach()` saw the "websieve.script.NEW" in `readdir()` and passed it through to the callback; the callback called `sievedir_get_script()` on it, which returned NULL because that filename was already gone; and then the callback crashed because it didn't expect a NULL there.
This does three things:
* The `list_cb()` callback now ignores NULL returns from `sievedir_get_script()` instead of crashing (but perhaps it should also log them?)
* The `sievedir_foreach()` function now ignores filenames ending in ".NEW" -- I believe we don't want this API to see them.  Is that right?
* Fixes an unrelated memory …
> fix sync_client crash when racing against script updates

- imap/squatter.c
This shushes the IOERROR from squatter when the mailbox it's trying to index doesn't exist anymore.  It's usually prevented anyway by the `if (!should_index(mboxname)) continue;` a few lines up, but sometimes it loses that race and the mboxname still existed when `should_index()` checked, but is gone a moment later when `index_one()` gets to it.
We still want to know if something real goes wrong here, but if it's merely that the mailbox isn't there anymore, it's not interesting.
I believe this will fix the sporadic CI errors from the JMAPTestSuite.t:Mailbox:set:... tests, which have a tendency to tickle this case by doing a few renames in quick succession (and then Cassandane complains about the IOERROR).
> hush IOERROR from squatter in uninteresting case

- imap/mboxname.c
- imap/mboxname.h
This is to prepare deployments of the master branch for the upcoming merge with the jmap-calendars-01 feature branch.
The notifications counter will always be zero until the remaining changes are merged.
> mboxname: add jmapnotifications counters

- imap/squatter.c
And more!  This one's tiny, and would have been way down my list, but @rjbs requested it specifically because one of them comes up a lot.
> squatter: use xsyslog for errors

- imap/backend.c
- imap/backend.h
- imap/mupdate-client.c
- imap/mupdate.h
This PR resolves two use after free conditions in cyrus-imapd 2.4 concerning the libsasl callback data structures, which lead to arbitrary segfaults.
> Fix two use after free segfaults

- imap/index.c
- imap/jmap_mail.c
- imap/jmap_mail_query.c
- imap/search_engines.h
- imap/search_squat.c
- imap/search_xapian.c
If clients requested SearchSnippets with the non-standard partIds argument, then we now return a new field in the response:
the `attachments` property includes the file name and type of all attachments that matched the query. If the query text matches the attachment file name, then the `name` property of the respective AttachMatch is highlighted.
This patch bears a slight risk of regression:
- We change the API for search callbacks, so there is a potential to introduce bugs in the indexing process. However, the changes are small: rather than passing the content guid of the indexed body part along with the indexed search part, we have a new API call that passes the content guid.
- Previously, we passed a NULL content guid for non-body search parts. Now we check the search party type when …
> jmap_mail: return AttachmentMatch in SearchSnippet/get

- imap/jmap_mail.c
It has optimized AND(A,OR(B,C)) mailbox queries to IMAP mailbox search expressions, effectively always producing an empty set.
~~The updated code only attempts to reduce the first ANDed jmap_folders expression to an IMAP search expression. Consequently, an email query that does not contain such an expression will convert to a global scan expression. This might degrade latency for the sake of correctness. If need be, we can improve the now correct query optimization further by identifying queries that reduce to a mailbox subset.~~
The updated code converts the search expression to DNF, then attempts to convert as many jmap_folder expressions to IMAP folder search as possible.
Tested in https://github.com/cyrusimap/cassandane/commit/52225cf937d387c990b9dd2509d5fe9f2e275446
> jmap_mail: rewrite email query folder-search optimizer to use DNF

- imap/search_engines.c
- imap/search_engines.h
- imap/search_expr.c
- imap/search_query.c
- imap/search_squat.c
- imap/search_xapian.c
This PR aims to fix #2598 . As a consequence of the rewrite of the search API for Cyrus v3, text match search expressions were only regarded as indexed if the search operator is a FUZZYMATCH. Consequently, if Cyrus is configured to use the squat search backend, then all text queries are handled as MATCH expressions any text search results in a global scan rather than making make use of squat indexes.
The patch in this PR fixes the issue for the current master branch. I plan to backport it to the upcoming v3.5 release, but had trouble building it due to incompabilities with the sasl API. Is this a known issue, @elliefm ?
The branch https://github.com/cyrusimap/cassandane/tree/fix_squat_search adds a new SearchSquat test module which contains simple regression tests that assert if the squat …
> squat: fix broken squat engine integration for indexed search

- imap/jmap_mail_query.c
- imap/search_xapian.c
- imap/xapian_wrap.cpp
- imap/xapian_wrap.h
Couple of years ago we experimented with indexing email body parts solely with their content guid. That didn't work out well with queries that filter by both email headers and bodies. We quickly introduced a new version index version 5 that undid the bug, but kept code to deal with the bogus index. Now it is time to get rid of it, as we don't want to keep dead code.
@elliefm this patch cherry-picks cleanly on the 3.4 branch. It passes JMAPEmail and SearchFuzzy tests on both the master and 3.4 branches.
> xapian: remove support for experimental v4 legacy indexes

- imap/index.c
This patch makes search text extraction more resilient for attachment extracting. Previously, we only a subset of all extractors gracefully if partial message indexing is enabled. Now we treat all extractor errors the same. In addition, we now log erroneous messages to help with debugging.
> index: make error handling in getsearchtext more verbose and resilient

- imap/mboxlist.c
- imap/userdeny_db.c
- lib/cyrusdb_flat.c
- lib/cyrusdb_quotalegacy.c
- lib/cyrusdb_skiplist.c
- lib/test/rnddb.c
I find that running `listmailbox` in cyradm causes the servicing imapd process to immediately exit with an assertion failure.  (Running v3.2.5 on Arch Linux, but same with older versions on FreeBSD.)  I have a twoskip subscription database.
Looking in gdb, the problem seems to be that mboxlist_sublist() provides its callback pointer to cyrusdb_foreach() in the wrong position.  Parameters four and five to cyrusdb_foreach() are both callback pointers, but only parameter four may be null; the twoskip myforeach() asserts this is true, resulting in an assertion failure (in myforeach() in lib/cyrusdb_twoskip.c) if the subscription database is twoskip.
I guess most people don't see this since the subscription database is not twoskip by default.
This pull request swap arguments four and five in …
> Fix assertion failure in imapd listing subscriptions from twoskip db

- cunit/strarray.testc
- imap/annotate.c
- imap/mboxlist.c
- lib/imapoptions
- lib/strarray.c
Adds a "specialuse_nochildren" imapd.conf option and a corresponding check in `mboxlist_create_namecheck()`.  If the immediate parent of the mailbox to be created has a special-use attribute listed in `specialuse_nochildren`, the create is rejected (IMAP_PERMISSION_DENIED).
This restriction does not apply to admins (so replication to a server with different configuration can still succeed), but does apply to ordinary users with implicit admin rights to their own mailboxes.
To-do: we talked about restricting attempts to setmetadata special-use attributes in this list on mailboxes that already have children.  I'm not yet sure where to hook this in; guidance appreciated!
Open questions:
* should we somehow prevent/complain/ignore if "\Inbox" is set in this list?
* any weird cases I haven't …
> configurable special-use mailboxes that may not contain children

- tools/config2header
This resolves the annoying problem of needing to guess what the next Cyrus release version will be when making changes in `lib/imapoptions`, and then needing to keep this updated in your branch if new releases are made before it's merged -- which is becoming more of a nuisance now as our work is likely to sit in a PR for a while before it lands on master.
From now on (well, once this is merged), if you're adding, changing, or deprecating an imapd.conf option, instead of trying to anticipate the next version number, just enter it as the magic string `"UNRELEASED"`.  This works equally well for both the "last_modified" field and the "deprecated_since" field.  Note that the double quotes are required, just as they are for normal version strings.
Part of the process for future releases will …
> allow "UNRELEASED" as imapoptions version string

- imap/sync_support.c
Well, I think its a debug log. Its certainly very noisy, and not
operationally useful.
> sync_support: downgrade a debug log

- imap/search_expr.c
We want to get rid of it soon, but until then we at least want to when this process-scoped counter exceeds the allowed maximum.
> search_expr: log warning if static nnodes exceeds configured max

- imap/http_caldav.c
When on subsequent (not the first) real component DTSTART/DTEND have different value types, fail in the same way, as this is done for the first real component.
DTSTART is the inclusive start, DTEND is the non-inclusive end, so DTSTART cannot be equal to DTEND.  A CUA can unintentionally upload VEVENT where [DTSTART is the same as DTEND](https://gitlab.gnome.org/GNOME/evolution/-/issues/1073) .
> http_caldav:caldav_put() further checks for DTSTART and DTEND

- configure.ac
* in the summary at the end print the wslay and nghttp2 status, even when --with-http was not passed to ./configure
* remove AC_MSG_NOTICEs.  The summary at the end has the purpose to substitute these.
* when zstd is disabled, do not cause any run-time overhead.  The rationale is that no http client (CUA) uses Zstandard currently.
Besides, when httpd runs behind a reverse proxy, the proxy server can take care of the compression, which it does any way for other stuff, so this change makes httpd lighter.
> configure.ac: permit explicitly turning off brotli and zstd

- changes/next/search_nonstatic_nnodes
- imap/jmap_mail.c
- imap/search_expr.c
**NOTE**: we might not want to push this ever on the master branch and rather remove the nnodes checks from the search code altogether. This pull request should help us identifying if we can do that safely.
**Description**
Static variable nnodes increments whenever a search expression is allocated. Its purpose is to keep track of the number of search expressions that are created during search expression tree normalisation. While uid-based search resets the counter each time it is called, it may accumulate in process memory as long as only guidsearch is executed.
This could introduce hard-to-track bugs, as the JMAP email search code uses the search expression normalisation code independently from uid-based search.
To avoid this, let's make nnodes a function argument.
> search_expr: make nnodes a non-static variable

- changes/next/jmap_getblob_handlers_v2
- imap/conversations.c
- imap/http_jmap.c
- imap/http_jmap.h
- imap/jmap_api.c
- imap/jmap_api.h
- imap/jmap_calendar.c
- imap/jmap_contact.c
- imap/jmap_mail.c
- imap/jmap_mail.h
- imap/jmap_mail_submission.c
- imap/jmap_mdn.c
- imap/jmap_sieve.c
This has multiple changes related to Contacts avatars all with the goal of allowing blobIds of any type to be used for an avatar (e.g. BIMI header blobIds).  To do this the getblob handlers have been made to put the blob content in a struct buf, with the output for an actual download to be handled by jmap_download().  It also gets rid of the hack to conv.db 'G' records to keep track of blobIds for vCard PHOTO properties, which has now been moved to a variant of the 'V' smart blobIds.  As as result, we need to report out that the blobId for an avatar changes from a 'G' or 'H' blobId to a new 'V' blobId during /set{create,update}.
> Jmap getblob handlers v2

- lib/auth_unix.c
- lib/charset.c
lib/auth_unix.c:allowedchars and lib/charset.c:base_64.
> lib/: move some symbols to the Read-Only segment

- changes/next/squatter_long_options
- configure.ac
- docsrc/imap/reference/manpages/systemcommands/squatter.rst
- imap/squatter.c
We've nearly exhausted the alphabet for squatter command-line arguments, and we already prepare to add even more options. This patch adds support for long argument options, and preserves all existing short options.
For reviewers: please have a look at the chosen long argument names. Do they make sense to you? Do you prefer something else?
> squatter: support long command-line argument options

- imap/xapian_wrap.cpp
> xapian_wrap:get_stopper(): skip ctor calls, when the function returns early

- netnews/remotepurge.c
The label 'after_search' was never ever used by goto.
> netnews/remotepurge.c: remove compiler warning

- imap/mboxevent.c
Found by [deheader](https://gitlab.com/esr/deheader/).
> imap/mboxevent.c: remove double #include’d headers

- tools/mkimap
config_read_file() contains:
```c
if (*p != ':') {
snprintf(errbuf, sizeof(errbuf),
"invalid option name on line %d of configuration file %s",
lineno, filename);
fatal(errbuf, EX_CONFIG);
}
*p++ = '\0';
/* remove leading whitespace */
while (*p && Uisspace(*p)) p++;
```
so it accepts zero spaces after the colon.  Extend mkimap to accept zero
spaces after the colon in imapd.conf and to terminate fast when imapd.conf
contains no 'configdirectory:'  or does not define partition.
> tools/mkimap: report clearly missing 'configdirectory:' in imapd.conf

- changes/next/message_cache_quotedaddr
- cunit/message.testc
- imap/mailbox.h
- imap/message.c
This patch fixes a bug where email addresses with quoted-string names were stored in the index cacherecord without quotes. If such an cached address is reparsed, then the parseaddr lib drops the invalid atoms from the name. In other words: the result of reading an address from cache may differ from the address that was written. This has shown to be a problem in search indexing, but it may just as well have resulted in bugs in other parts of Cyrus.
The cunit tests were updated. In addition, the mailbox minor cache version was bumped.
Addendum: Independently, we may want to make parseaddr more lenient with regards to invalid [atext](https://tools.ietf.org/html/rfc5322#section-3.2.3) names.
> message: cache mail address names as quoted-string, if necessary

- imap/backend.c
- imap/mupdate-client.c
- imap/mupdate.h
This is the same thing as #3312 (2.4), but for master, which already had some, but not all, of the fixes it contained.
* fixes use after free crash in mupdate-client
* fixes memory leaks in backend when sasl_client_new or sasl_setprop fail
Once this is reviewed and merged I'll cherry-pick it to the other branches
Closes #3320
> fix sasl callback cleanup

- docsrc/exts/sphinxlocal/writers/manpage.py
Sphinx 1.8 deprecates sphinx.util.osutil.ustrftime and https://github.com/sphinx-doc/sphinx/commit/61098a0ae2e696a804 removes the method.
- update docsrc/exts/sphinxlocal/writers/manpage.py to compile with Sphinx-doc 3.2.1.
> docsrc: update for Sphinx 3.x

- imap/calalarmd.c
- imap/caldav_alarm.c
- imap/caldav_alarm.h
- imap/caldav_db.c
- imap/carddav_db.c
- imap/dav_db.c
- imap/dav_db.h
- imap/mailbox.c
- imap/webdav_db.c
This adds extra smarts around the audit tool for dav-reconstruct, so we know which slot it's running on and which user it's for from the command line.
This will be paired with a Perl tool which can then read said config and actually diff the two databases.
> Dav reconstruct audit

- changes/next/3360-apply-message-write-failure-desync
- imap/dlist.c
- imap/imapd.c
- imap/sync_support.c
- lib/imapoptions
* Fixes loss of protocol sync in APPLY MESSAGE by adding a `sync_eatline()` that can also consume the remaining dlist file literals correctly
* Also fixes a quiet bug whereby imapd would eatline() twice on sync failures, discarding the next command as well
* And adds a new imapd option "debug_writefail_guid" for simulating write failures for the given guid, to enable regression testing for this case
Corresponding Cassandane tests are here: https://github.com/cyrusimap/cassandane/compare/master...elliefm:v35/3360-apply-message-write-failure-desync
Fixes #3360
> fix loss of replication protocol sync when APPLY MESSAGE fails to write to disk

- imap/httpd.c
Issue #2882
Tell Firefox/Thunderbird to prefer SPNEGO over BASIC WWW-Auth.
Backport of 0d691d9322e7299f6d
> 3.2 - httpd.c: reorder auth_schemes[] in descending order of security properties

- imap/xapian_wrap.cpp
Backport of 3ffaf02fba9a09b20
Broken since 8733b0bb3a.
> 3.2 - xapian_wrap:get_stopper() use the cached stoppers

- fix_write_searchaddr_quoted
- imap/message.c
The original code overwrote the previous buffer for every recipient that required quotes around recipient names. This effectively truncated the list of recipients.
This bug got introduced in https://github.com/cyrusimap/cyrus-imapd/commit/171bbe6396d3eac4e3b5c544ad9d1e38377c2234
Tested in https://github.com/cyrusimap/cassandane/commit/e2f17363c34208e01c94f0afaf00688436a3483c
> message: fix mailbox cache for To: headers with quoted recipients

- Makefile.am
- cunit/dynarray.testc
- lib/dynarray.c
- lib/dynarray.h
dynarray is a more cache-friendly variant of good old ptrarray. In almost all cases, we currently use ptrarray with same-sized members. Each member is alloced and freed separately, resulting in both CPU overhead and memory fragmentation. dynarray addresses both of the deficiencies by keeping its members in a contiguous memory buffer.
dynarray got introduced in the jmap-calendars-01 branch but I find it more and more useful to also include in other feature branches already.
> dynarray: add dynamic array helper for same-sized members

- imap/http_dav.c
Evolution calls MKCOL with the user-provided Calendar-Name as WebDAV-Collection name, percent encoded when needed.  The percent encoded collections are rejected by Cyrus IMAP.  This change improves the error message returned to the CUA.
As far as I checked the code, `mboxname_policycheck()` validates, whether the mailbox name is valid.  It applies the same rules for IMAP and WebDAV mailboxes. `Modified UTF-7` as WebDAV collection name would be accepted, but percent encoded URL are rejected.
> calcarddav_parse_path: clearer error message on % encoded URLs in MKCOL

- imap/httpd.c
This change saves debugging, trying to find the server-side error.  The error appears, when Thunderbird sends
> Authorization: Basic Og==
> httpd: clearer error message on emtpy BASIC authorization id

- timsieved/actions.c
buf_release() does call buf_free().
Remove variable `ret`.
> timsieved:actions_setuser() remove buf_free() after buf_release()

- changes/next/sync-server-bye
- imap/sync_server.c
- imap/sync_support.c
* When sync_server is shut down cleanly by a signal from master, it now writes "BYE shutting down" to the client socket, if it's connected, before shutting down normally.
* When sync_client sees "BYE shutting down" from sync_server, it knows to expect to be disconnected, and exits cleanly itself (instead of logging a lot of useless IOERRORS).
There are tests here (including infrastructure fixes to make this testable at all): https://github.com/cyrusimap/cassandane/compare/master...elliefm:v35/3401-sync-server-bye
This is upgrade safe:  when the master Cyrus is older than the replica, and doesn't recognise BYE, it IOERRORs about a bad command and bails out (without the BYE, it would have IOERRORed about the zero length command, and bailed out).  When the replica Cyrus is older, and doesn't …
> send BYE from sync_server on clean shutdown

- imap/quota.c
I typed -j instead of -J and then saw that neither was in the error message!
> quota.c: mention -J and -n in usage message

- Makefile.am
- cunit/syslog.c
- cunit/timeofday.c
- imap/ctl_conversationsdb.c
- imap/httpd.c
- imap/icu_wrap.cpp
- imap/message_test.c
- imap/search_test.c
- imap/xapian_wrap.cpp
This fixes the linking issues raised in https://cyrus.topicbox.com/groups/devel/Tf544987d7d6a54fd-M64b7419c76035feff7fb6a22
The Makefile.am changes only apply to imap_libcyrus_imap_la, because that is currently the only target we build that has C++ sources.  If we start including C++ sources in other targets, we'll need to set their target_CXXFLAGS similarly.  Which we would need to do anyway, and now there's a good example to copy from.
> fix up explicit symbol visibility

- changes/next/sync-client-retry-wait-limit
- imap/sync_client.c
- lib/imapoptions
Adds a configurable upper limit to the exponential backoff in sync_client's connection retry loop, with a default of 20 mins.
There's a cassandane test for it here: https://github.com/cyrusimap/cassandane/compare/master...elliefm:v35/3419-sync-client-retry-wait-limit
Fixes #3419
> sync_client: maximum wait between connection retries

- changes/next/guidsearch_mixed_clauses
- imap/jmap_mail.c
Fixes a bug in guidsearch where a query may return false results if its DNF clauses contain divergent non-Xapian criteria.                                                                                       
This reduces the number of queries that can be handled by guidsearch and may result in search latency regressions for such queries. 
Tested in https://github.com/cyrusimap/cassandane/commit/89616c9787881e3b20004b66e3d5429e0ec678b5
> jmap_mail: do not use guidsearch for divergent non-Xapian criteria

- imap/append.c
This looks like the minimal fixes :)  There's no point trying to link the copy on archive, because the spool is always on data for now.  A better fix would be to discover the copy on data, and spool there so there's no data copying, but that's for another day.
> Append guid archive

- docsrc/imap/download/installation/manage-dav.rst
-- state that the BASIC authentication does not depend on Cyrus SASL plugin.
-- do not repeat which authentication schemata are implemented (⇔ say the same with less words).
> documentation: reword httpd authentication

- cunit/spool.testc
- imap/spool.c
This mainly fixes stuff like this:
```
Message-ID:
<foo@whatever>
```
being misparsed as `" <foo@whatever>"` rather than `"<foo@whatever>"` –  i.e. the leading whitespace was not eaten if it was also folded.  
One consequence of this was bad formatting of auditlogs for affected messages; another (user visible!) was that duplicate suppression would fail to detect the duplication if one copy was folded and the other not.
The misparsing of folded leading whitespace affects all headers in theory, but other headers usually contain other whitespace, and end up folded later instead of right at the start.  Message-ID is exceptional both in that it doesn't usually contain any other whitespace (so if the sender is going to fold it, they can only fold at the leading whitespace), and in that the …
> fix parsing of folded leading whitespace in headers

- docsrc/imap/installing.rst
Delete the text describing how to set up a self-signed certificate.  Nowadays everybody setting up any form of server shall understand PKI and the terms private key and full chain.
> doc/installing: prefer Let’s Encrypt over self-made certificate

- docsrc/exts/sphinxlocal/builders/manpage.py
The file docsrc/exts/sphinxlocal/builders/manpage.py extends the file sphinx/builders/manpage.py from the Sphinx 1.4 source.  The origin contains
from sphinx.environment import NoUri
and its code does raise the NoUri exception.  Later versions of Sphinx do not contain this line in sphinx/builders/manpage.py .
Per https://www.sphinx-doc.org/en/master/extdev/deprecated.html sphinx.environment.NoUri is deprecated and shall be replaced
by sphinx.errors.NoUri.  Sphinx 1.4 does not have sphinx.errors.NoUri.
While inteded for removal in 4.0, sphinx.environment.NoUri was in fact removed in a previous version: https://github.com/sphinx-doc/sphinx/issues/9032
That said:
- docsrc/exts/sphinxlocal/builders/manpage.py does not use sphinx.environment.NoUri, but contains it because of copy-paste …
> Make docsrc/exts/sphinxlocal/builders/manpage.py compilable.

- imap/http_caldav.c
- imap/http_caldav_sched.c
- imap/http_dav.c
- imap/http_ischedule.c
- imap/http_rss.c
- imap/httpd.c
These were converted to `&#13;` in XML.
> Remove terminating \r\n in DAV error descriptions

- Makefile.am
The imap/caldav_js.h and carddav_js.h files are generated by xxd from caldav.js and carddav.js .  xxd is not required as build dependency, therefore the files caldav_js.h and carddav_js.h must be included in the tarball on "make dist". Mentioning the files in imap_httpd_SOURCES achieves exactly this.
Mentioning the files in nodist_imap_httpd_SOURCES means the opposite: do not include the files in the "make dist” tarball.
As a matter of fact, the files were included in both nodist_imap_httpd_SOURCES and imap_httpd_SOURCES.
"make distclean" deletes files created by ./configure.  Since the caldav_js.h files are from the tarball and not generated
by ./configure, they shall not be clean by “make disclean” but by “make maintainer-clean”.
> Makefile.am: remove http_caldav_js.h from nodist_imap_httpd_SOURCES

- Makefile.am
- cunit/arrayu64.testc
- cunit/bufarray.testc
- cunit/dynarray.testc
- imap/conversations.c
- imap/message.c
- lib/arrayu64.c
- lib/arrayu64.h
- lib/bufarray.c
- lib/dynarray.c
- lib/ptrarray.c
- lib/strarray.c
This changes our dynamic array types to double in size each time they need to grow, rather than always growing by 16 elements at a time.  This potentially costs a little more memory usage, but reduces reallocation overheads.  The first allocation is still always 16 elements -- we're not wasting time stepping up through 1, 2, 4, 8 first!
Specifically, these modules have been changed to double in size:
- lib/arrayu64.c
- lib/bufarray.c
- lib/dynarray.c
- lib/ptrarray.c
- lib/strarray.c
I have left lib/bitvector.c alone for now, even though its growth is similar (256 bits at a time), because it's more complicated and I'm not sure it's useful to change -- though let me know if you disagree!
I've added tests for arrayu64 and bufarray, which previously didn't have any, and dynarray, which had …
> grow dynamic arrays by doubling, rather than fixed size

- imap/imapd.c
- imap/jmap_mail.c
- imap/jmap_sieve.c
- imap/lmtp_sieve.c
- imap/lmtpd.c
- imap/mboxname.h
We were missing the header definitions for 'mboxname_isjmapnotificationmailbox' and the inclusion in isnonimapmailbox - but also imapd had the list hard-coded too!  Fix both of those.
Found by inspection on Fastmail dogfood server :)
> Imapd no jmapnotification

- imap/index.c
Before,the raw RTF file including control words could end up in a search snippet preview.
Tested in https://github.com/cyrusimap/cassandane/commit/a95a1b05c1d418104c223bba7d08fe920b620968
> index: use attachment extractor for text/rtf message bodies

- imap/jmap_calendar.c
- imap/jmap_ical.c
This fixes two issues with the current JSCalendar implementation that shouldn't need to wait until we land the jmap-calendars-01 branch:
- Previous draft versions defined empty string default values for name and description properties, but this changed to optional properties in the current spec. We should empty values both when reading and writing iCalendar data.
- The current implementation conflates the Participant.email and Participant.sendTo{imip} properties, but they really a separate things. We shouldn't use Participant.email for scheduling and this patch fixes that. We still use Participant.email to validate the custom participantId property, though
Tested in https://github.com/cyrusimap/cassandane/tree/jmap_ical_fixes
> Fix JSCalendar default values and use of Participant.email property

- imap/idle.c
- lib/cyrusdb_quotalegacy.c
- lib/util.c
The new `xsyslog()` automatically includes a `syserror=<...>` field when `errno` is non-zero at the time the message was logged, which means we don't need to explicitly log `%m` anymore.
But, it's exposing places where some syscall has failed and been ignored, and the irrelevant errno value left lying around to trip over later.  We can't deal with this from within `xsyslog()`, because it doesn't know the context where `errno` was set.
Generally, if we call something that will set `errno` on failures, and then treat some of those failure cases as successes, we should also reset `errno = 0` in those cases to indicate to our future selves that the "failure" has been handled.  The next successful syscall will usually reset it to zero (or to whatever error _it_ detected), so, if you're …
> improve our errno discipline

- imap/annotate.c
- imap/sync_support.c
We ran into a production bug where a client was setting a per-server annotation to track some config for itself (a JSON blob).  It turns out that replication died on that.  Ouch.
This fixes this issue, and a related permissions issue found by the associated cassandane tests in https://github.com/cyrusimap/cassandane/pull/114
> Server annotation replication

- changes/next/search_large_text
- cunit/charset.testc
- imap/global.c
- imap/global.h
- imap/index.c
- imap/jmap_mail.c
- imap/jmap_mail_query.c
- imap/search_engines.h
- imap/search_squat.c
- imap/search_xapian.c
- lib/charset.c
- lib/charset.h
- lib/imapoptions
This updates the indexing and search snippet code to stop extracting text when at most `search_maxsize` limit octets have been read. Any bytes after that limit already have been ignored during indexing and snippet generation, but the decoder ran through the complete message part, before throwing away the excess bytes.
Before, the limit was hardcoded to 4MB, now it is configurable in imapd.conf.
For discussion: this patch also changes the limit to apply not the the total bytes extracted from a message, but to each message part separately. This has the potential to increase the search index database, but prevents text being omitted depending on the order in which message parts are processed.
Tested in https://github.com/cyrusimap/cassandane/tree/search_large_text
> search: do not extract text after the search_maxsize limit

- Makefile.am
- changes/next/mboxevent_jmap_email
- imap/jmap_api.c
- imap/jmap_api.h
- imap/jmap_mail.c
- imap/jmap_util.c
- imap/jmap_util.h
- imap/mboxevent.c
- imap/mboxevent.h
- lib/imapoptions
Redo of previous PR.
Adds the 'vnd.cmu.jmapEmail' selector to the 'event_extra_params' option
which will includes a JMAP Email object in the event message.
Also fixes header:asDate to return a Date type rather than a UTCDate type.
Fix for existing Cass test is here: https://github.com/cyrusimap/cassandane/pull/116
> Mboxevent jmap email v2

- imap/jmap_api.c
We shouldn't look at #jmap, #notifications, etc when determining shared accounts.
Tested with https://github.com/cyrusimap/cassandane/pull/117
> jmap_api.c Skip special use folders when finding JMAP accounts

- imap/http_jmap.c
- imap/jmap_api.c
- imap/jmap_api.h
Adds handlers to handle various stages of the JMAP request processing pipeline. This is an extract from https://github.com/cyrusimap/cyrus-imapd/pull/3460 which we want to land earlier than the email-specific changes.
> jmap_api: add event handlers to JMAP settings

- lib/byteorder.h
- lib/crc32.c
This macro is provided by glibc, not gcc, so using it winds up implicitly checking for "gcc+glibc" rather than just "gcc".
Fixes #3462
Need this for 3.4... I would just push it directly to both branches, but I wanted to submit a PR to make sure the DCO exception for org members is working correctly
> misc: don't use __GNUC_PREREQ() when checking for GCC features

- imap/mboxlist.c
Hi,
ctl_cyrusdb exits during startup:
% /usr/local/cyrus/sbin/ctl_cyrusdb -r
fatal error: Internal error: assertion failed: lib/cyrusdb_skiplist.c: 1469: db && tid
% /usr/local/cyrus/sbin/cyr_info version
cyrus-imapd 3.4.0
% uname -ro
FreeBSD 13.0-RELEASE
I believe this is due to mboxlist_set_racls() and mboxlist_set_runiqueid() may not have done any changes to the mailbox database, e.g. when reverse acls are enabled and have the latest version. In 3.2.x, tid is never NULL set as cyrusdb_fetch() is always called.
BR Felix
> ctl_cyrusdb -r assertion on startup when mboxlist_db = skiplist

- imap/jmap_mail.c
- lib/times.h
This updates 3.4 to pass the JMAPTestSuite.t:Email:get:header-header-field-name test, which was recently updated to expect Date objects rather than UTCDate objects.
I tried simply cherry-picking the relevant commit from master (e354baa53abf3a714f1c34b68a68e4b8d1b68d7b), but there is a whole rabbit trail of other commits it's dependent on, so instead of spending the day tracking them down, I just rewrote the same changes to the 3.4 code instead.
But, since I re-wrote it rather than just cherry-picking it, I'd like some eyes on it before I land it please. :)
> (3.4) use Date rather than UTCDate

- imap/jmap_mail.c
- imap/message.c
- imap/message.h
- imap/search_expr.c
This patch fixes an issue where search for "email" and "message/rfc822" did not return any results. As these content types are not indexed in Xapian, this patch lets search fall back to the cached bodystructure. It also fixes an invalid cast from void in contenttype_match.
> JMAP: support Email/query for attachmentType=email

- imap/jmap_mail.c
Also fixes a memory leak for early returns.
> jmap_mail: fix break condition for unsupported guidsearch rank

- imap/jmap_calendar.c
Tested in updated test https://github.com/cyrusimap/cassandane/pull/121/files
> jmap_calendar: allow to destroy Default calendar

- imap/http_h2.c
- imap/http_h2.h
- imap/http_jmap.c
- imap/http_ws.c
- imap/http_ws.h
- imap/httpd.c
- imap/httpd.h
This removes an ugly hack where each WS connection would create its own new txn, separating itself from the txn used to bootstrap the WS connection.  The warts that forced this hack have been removed in previous commits on master.
Based on https://github.com/cyrusimap/cyrus-imapd/pull/3477
> WS: use the actual txn for the stream/connection rather than creating a new one

- imap/mailbox.c
What it says on the tin.  This would have been useful for @robmueller in tracking down some user quota issues, if it had already existed; here it is now.
There's a couple of new Cassandane tests here: https://github.com/cyrusimap/cassandane/compare/master...elliefm:v35/auditlog-size-field
> mailbox: add size field to auditlog append and expunge

- changes/next/squatter_s_argument_required
- docsrc/imap/reference/manpages/systemcommands/squatter.rst
- imap/squatter.c
It didn't work with optional arguments anyway.
Fixes #3496
> squatter: change -s option to require an argument

- backup/backupd.c
- backup/lcb.c
- backup/lcb_append.c
- backup/lcb_compact.c
- backup/lcb_read.c
- backup/lcb_verify.c
As usual, please both read and build test this.  This is the old replication-backups stuff, not the JMAP one.
> backups: use xsyslog for IOERRORs

- imap/jmap_ical.c
VEVENTs may contain only ORGANIZER or ATTENDEEs and the JMAP code currently rejects these events when written back to iCalendar.
This patch allows to update such events. It still does reject such events during creation in JMAP.
Tested in https://github.com/cyrusimap/cassandane/commit/9879f08e72acd47d54b46c5dec6665606ee94fa9 and https://github.com/cyrusimap/cassandane/commit/65c2e29abddd70e9f15e2276ad4166097ca43c09
> jmap_ical: round-trip ORGANIZER-only and ATTENDEE-only events

- lib/charset.c
So... it turns out that IETF's mail forwarder broke on a line with a single dot:
```
ACTION: discussion on list to confirm cases work, then clear AUTH48 ASAP=
.
```
Now, that's bogus.
But - be conservative in what you send.  If the next character is the end of line, then don't wrap.
> charset: don't QP wrap for a single character

- Makefile.am
- cunit/smallarrayu64.testc
- imap/jmap_mail.c
- imap/search_engines.h
- imap/search_query.c
- imap/search_query.h
- imap/search_squat.c
- imap/search_xapian.c
- imap/squatter.c
- lib/imapoptions
- lib/smallarrayu64.c
- lib/smallarrayu64.h
Replaces the on-disk Email/query cache with an in-memory cache. This allows to speed up consecutive email queries that page through the overall result.
As the cache is stored in memory, this only benefits requests over web sockets or kept-alive HTTP connections.
Config changes:
Deprecates the `jmap_emailsearch_db_path` option.
Introduces the `jmap_querycache_max_age` option.
Tested in https://github.com/cyrusimap/cassandane/tree/jmap_emailquery_cache_inprocess
> jmap_mail: replace Email/query on-disk cache with in-memory

- imap/search_query.c
The test was broken by 5f6bc5eaaeca1fcc65fb3f55352a21a2a5c097ce, which among other things removed an `SEOP_MATCH:` case from `search_build_query()`.  I don't understand why it was removed, maybe it was accidental?  Restoring it seems to fix the broken test, while not breaking anything else.
> Possible fix for failing SearchSquat.simple test on master

- imap/http_ws.c
Sending an invalid JMAP Request payload leaves string data in the transaction buffer. Do not assert its length to be zero, but rather reset the contents before logging.
> http_ws: don't assert transaction buffer zero length for logging

- imap/lmtpd.c
Plus address delivery to shared mailboxes (e.g. `<+shared/foo@domain.com>`, with no localpart) has been broken since we started locking the user's conversations database during delivery, since shared mailboxes don't have a conversations database.
This fixes it by only locking the conversations database if `mbname_userid(...)` is non-NULL.
Regression test is here: https://github.com/cyrusimap/cassandane/compare/master...elliefm:v35/3488-lmtp-shared-mailbox
Fixes #3488
> fix broken delivery to shared mailboxes

- imap/jmap_mail.c
This changes the _next functions to only return a single item at a time, and will only process exactly as many records as needed to fill the requested window.
> Jmap cache one at a time

- Makefile.am
- imap/jmap_vacation.c
- imap/sievedir.c
Make would fail in imap/jmap_vacation.c and imap/sievedir.c when configured with --disable-sieve and --enable-jmap, because they were pulling in sieve headers that would try to include sieve_err.h, which hadn't been generated.
It looks like both of these source files are already conditionalised to handle sieve being unavailable, so I've just done the same for the sieve header includes.
Needed to update some Cassandane tests that would crash out during setup when timsieved didn't exist, those fixes are already merged.  Seems to pass everything else.
Fixes #3527
> Fix --disable-sieve --enable-jmap build

- imap/jmap_mail.c
- imap/search_query.c
The current uidsearch inMailboxOtherThan filter unnecessarily checks every potentially matching message in conversations.db. This can result in search timeouts for very large mailboxes, and generally wastes too much time doing unecessary checks.
This patch fixes the uidsearch variant of inMailboxOtherThan to only check these messages, that actually are part of the filtered mailbox. For all others is trivially evaluates to true. In addition, rather than string comparing the message's mailboxes against the filter, it uses a bitset populated with the conversation.db-internal numeric mailbox ids.
The same bitvector is used in guidsearch.
This PR is built on #3460
This PR also includes a code hygiene commit that removes the leading underscore from the static emailsearch function names.
> jmap_mail: improve performance of inMailboxOtherThan queries 

- imap/mbpath.c
Fixes a memory leak in mbpath. In a perfect world, jansson would provide us with an API to transfer ownership of string values to their JSON type. But [this section](https://github.com/akheron/jansson/blob/master/src/value.c#L747) in the upstream source suggests we won't get that. Defining our own `json_stringm` in json_support.h would allow us to fake this API, but this might mislead callers to assume no allocations are made.
> mbpath: free string returned by user_hash_meta after use

- imap/append.c
- imap/cyr_ls.c
- imap/imapd.c
- imap/mailbox.c
- imap/mboxlist.c
- imap/sync_support.c
- sieve/test_mailbox.c
This fixed MOST of the legacy paths handling.
There's still a serious bug with user_deletedata, where it doesn't know the correct paths any more because we've already nuked the mailboxes.db entry.  In general, we're going to have to change all the underlying APIs so we can get a clean userid -> path mapping cheaply and reliably.  Possibly even store the user's uniqueid into every mailbox header file.
> UUID legacy paths

- imap/jmap_mail.c
As suggested - moving the "loadn" loop into the per-backend functions, so we don't have a call per record.  This is even cheaper than the batched version, and doesn't take much more code!
> jmap_mail: move the 'filln' logic into the inner loops

- imap/jmap_mail.c
- imap/search_expr.c
This patch adds a new `seen` search attribute which correctly determines if to read the `\Seen` flag from the index record or seen database. The Email/query `hasKeyword:$seen` filter is updated to make use of this new attribute.
The implementation is somewhat lacking in that it opens the seen database for each inspected mailbox. This unnecessarily incurs CRC check costs. However, the current search attribute design does not allow for stateful attributes across a whole query. We might need to come up with such, if the CRC checks are proofing to be to costly. 
Tested in https://github.com/cyrusimap/cassandane/pull/131
> jmap_mail: fix 'hasKeyword:$seen' queries for shared mailboxes

- imap/mboxlist.c
Since ff1442271ae144fb84fcf58f0e258f54d8c11164 we have only stored RACL entries where the ACL contained the 'r' permission.  IMAP LIST needs to be able to return mailboxes where the user has 'l' but not 'r', but when reverseacls is enabled, it can't see them at all because there's no RACL entry.
This fix addresses the issue by creating RACL entries if either the 'r' or 'l' permission is present.
Added a lot of tests for this specific case: https://github.com/cyrusimap/cassandane/compare/master...elliefm:v34/3528-list-lookup-only
It doesn't seem to break anything else, by which I mean, none of our existing tests break with this change.  But if you can think of something that might break with this, we should add a test for it!
I thought RACL and RUNQ were versioned, and thought I might need …
> mboxlist: allow RACL entries where 'l' permission exists

- imap/http_caldav_sched.c
- imap/http_caldav_sched.h
- imap/http_ischedule.c
This came up today with calendar invitations on shared calendars being rejected because they were authenticated as the person creating the request rather than the calendar owner.
Given how calendar requests are created, I think the correct answer is to just authenticate as the calendar owner.  You can only send as them if you have the `8` ACL on their Outbox, but after that the email is coming from the calendar owner for all intents and purposes, so the system should authenticate as them.
> caldav_sched: pass the acting userid through to the imip sender

- imap/index.c
This speeds up index_msgdata_load for the very common request which the Fastmail UI uses to load every single mailbox!
```
"sort": [
{
"property": "snoozedUntil",
"isAscending": false,
"mailboxId": "567d9ea54215e1e9"
},
{
"isAscending": false,
"property": "receivedAt"
}
],
```
Instead of having to do a strcmp of the mailbox_uniqueid against the parameter for every single record in the mailbox, it's done just once at the top of the loop.
I also picked out the other two cases where we do string comparisons that aren't going to change for every message in the mailbox, because why not!
> preload string comparisons that will the same for every message

- imap/jmap_mail.c
This goes along with some magic in lmtpprox at Fastmail to fetch the previous event via JMAP when an update arrives, and store the content base64 encoded in the header.
> jmap_mail: add 'previousCalendarEvent' fetcher

- imap/jmap_mail.c
- imap/jmap_mail_query.c
- imap/jmap_mail_query.h
This patch replaces the current logic to set the `hasAttachment` property with a Cyrus-custom heuristic.
The JMAP spec recommends the `Email.hasAttachment` property to be set if its `attachments` property includes at least one bodypart. Cyrus dissects body parts in `textBody`, `htmlBody` and `attachments` according to the reference algorithm in the [JMAP Email spec](https://jmap.io/spec-mail.html#properties-of-the-email-object), but this may miss a couple of cases which we expect to be attachments.
Tested in https://github.com/cyrusimap/cassandane/pull/132
> jmap_mail: use custom heuristic for Email.hasAttachment property

- cunit/buf.testc
Gcc's stack protector picked this up in the buf cunit tests.
> cunit: clamp snprintf arguments to their expected format width

- imap/jmap_contact.c
This was missed when adjusting EMAIL, ADR, TEL property labels
> jmap_contact.c: use length of adjusted Apple label for URL property

- imap/proxy.c
This fixes a double-free crash on cleanup because the same backend was being cached multiple times, introduced in #3560.
I _think_ this is the only place this needs to be changed, but I'm not entirely certain, so even though this is only a one-line fix, please look closely 😅
> proxy: don't cache the same backend multiple times

- imap/append.c
- imap/conversations.c
- imap/conversations.h
- imap/index.c
- imap/jmap_api.c
- imap/jmap_core.c
- imap/jmap_mail.c
- imap/jmap_mailbox.c
- imap/mailbox.c
- imap/mboxlist.h
- imap/search_xapian.c
This seems like a much nicer central cache, and it means we can always get the name or the uniqueid and we don't need to prework if not asked for it.
> conversations: cache altrep (uniqueid or name) in the conversations object

- imap/jmap_mail.c
Resets the mailbox name iterator when we deallocate its memory.
> jmap_mail: reset mboxname iterator in email_append

- imap/http_dav.c
- imap/http_dav.h
- imap/httpd.c
This might aid in diagnosing client issues without having to enable telemetry
> httpd.c: add precondition error to log line

- imap/conversations.c
This fixes that squatter bug on west (and more generally) - ouch.
> conversations: need to get uniqueid when convdb is by name!

- changes/next/message_parse_bogus_charset_params
- cunit/message.testc
- imap/jmap_mail.c
- imap/message.c
- imap/message.h
The Content-Type header may have at most one charset parameter, but at least one MUA generates header values such as:
Content-Type: text/plain; charset=text/plain; charset=UTF-8
Note both the bogus first parameter value and the duplicate charset parameters. Cyrus now leniently accepts such header values, and falls back to cache the last valid charset parameter value.
Bonus point: it unifies charset parameter parsing to single function, rather than three implementations in the same codebase.
Fixes #3576
JMAP test at https://github.com/cyrusimap/cassandane/commit/7ded3114bf5d355ff9ca10e8113952f462da68ba
> message: use last valid charset parameter in Content-Type header

- docsrc/exts/themes/cyrus/buildstatus.html
The repository was migrated from travis-ci.org to travis-ci.com. The old page now displays: "This repository was migrated and is now building on travis-ci.com".
> Doc: update Travis CI links

- imap/http_jmap.c
- imap/httpd.c
- imap/httpd.h
This allows us to remove meth_options_jmap() in lieu of stock meth_options() and to be more inline with the other modules.
I will also be able to leverage the meth_connect() changes for #3564
Note that this allows both /jmap and /jmap/ as valid URLs.  Current Cyrus issues a 301 for the former, but I don't see that as being necessary
> Give jmap_parse_path() a parse_path_t signature

- imap/message.c
xsyslog reports a syserror that's unrelated to the logged message. See #3576
> message: reset spurious errno value before xsyslog

- imap/http_jmap.c
(this fixes a breakage introduced in 21dbeb8cedef51eac7108c08670b3461c9c741fe)
> http_jmap.c: MUST allow read (GET) on WS endpoint for HTTP/1.1

- imap/httpd.c
This fixes a crasher when compression is enabled and the client requests gzip transfer-encoding.
The only clients that I'm aware of that can/do request gzip transfer-encoding are curl and libwww-perl
> HTTP transfer encoding fix

- imap/mboxlist.c
This is quite urgent!  Well, the two bugfixes are.  The boring syslog line fixer isn't.
This fixes two observed bugs when upgrading a server.
1) the name-history 'dbname' field was storing intname instead of dbname values.
2) when a DELETED mailbox was created by sync_server, it wasn't correctly finding that the INBOX was still legacy, because INBOX isn't a parent of the DELETED namespace.
> UUID bugfixes

- imap/annotate.c
- imap/annotate.h
- imap/caldav_alarm.c
- imap/http_dav.c
- imap/index.c
- imap/jmap_backup.c
- imap/jmap_calendar.c
- imap/jmap_mailbox.c
- imap/mailbox.c
- imap/mailbox.h
- imap/mbdump.c
- imap/msgrecord.c
- imap/nntpd.c
- imap/sync_support.c
It's probably worth looking at the diffs independently here.  Two are of particular interest - one changes the _annotate_getdb API, and the other splits the annotatemore_findall API.
There's still more work to do, but this is a couple of big ones :)
> Improve the efficiency of annotations DB lookups

- imap/annotate.c
- imap/sync_support.c
This was just a bad piece of API usage - sorry I clearly didn't run the cunit test after I finished refactoring this API call.
> annotate: fix bug with server-level annotations in lookup

- imap/http_caldav.c
This fixes a bug where the ORGANIZER in the master component is "MAILTO:foo@example.com" and the ORGANIZER in an override is "mailto:foo@example.com"
> http_caldav.c: skip "mailto:" when comparing ORGANIZERs in components

- imap/http_caldav.c
- imap/http_caldav_sched.c
This fixes 2 bugs:
- The first patch fetches the user's schedule_addresses for comparison against the ORGANIZER property in the request, so we can properly set 'isyou'
- The second patch properly sets the scheduling userid of local users (strip domain from CUA) when virtdomains is disabled or defaultdomain is set
Tested with https://github.com/cyrusimap/cassandane/pull/143
> CalDAV Scheduling busytime query fixes

- cunit/charset.testc
- cunit/jmap_util.testc
- imap/carddav_db.c
- imap/http_jmap.c
- imap/jmap_api.c
- imap/jmap_api.h
- imap/jmap_calendar.c
- imap/jmap_contact.c
- imap/jmap_mail.c
- imap/jmap_sieve.c
- imap/jmap_util.c
- imap/jmap_util.h
- imap/search_expr.c
- imap/search_expr.h
- lib/charset.c
This fixes a bunch of memory issues found by valgrind when running the following Cassandane test suites:
- JMAPBackup
- JMAPCalendars
- JMAPContacts
- JMAPCore
- JMAPEmail
- JMAPEmailSubmission
- JMAPMailbox
- JMAPSieve
> Fix valgrind issues in the JMAP code

- imap/http_caldav.c
At least one stupid client tries to store resources with an empty ORGANIZER property, which we need to protect against if libical was compiled to allow empty props (until libical is fixed to only allow empty text props)
> http_caldav.c: protect against empty ORGANIZER properties

- imap/jmap_calendar.c
Fixes the CalendarEvent.blobId for users which did not get relocated to uuid. Passes all regression tests.
> jmap_calendar: fix CalendarEvent.blobId property for non-uuid

- imap/imapd.c
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1708981
The likelyhood that a client is waiting on this data and
won't issue a NOOP or otherwise check for it is much lower
than the likelyhood that the client won't think to look in
the status response to a different mailbox for an update to
the index state.
If we are doing a STATUS on the selected mailbox, we still
need to do the `index_check` though, because that will make
sure the data is up-to-date.
... this passes all the Cassandane tests (ImapTest, Idle and Expunge being the most interesting probably)
> imapd: don't check index if status on a different mailbox

- imap/imapd.c
This fixes a crash when you try to STATUS a folder that doesn't exist, introduced by 6a00f5b0b0402d7023bc7e5e6c0c49d23567c5a8
> status: need to not dereference mbentry on error

- imap/sync_support.c
This fixes an issue where intermediates got promoted with different uniqueids on master and replicate.  They don't have any email in them, so just overwriting with the new uniqueid is totally fine!
It also tidies up the locking with errors if they namespacelocks don't actually take.
Tested by https://github.com/cyrusimap/cassandane/pull/145
> sync_support: allow delete and recreate a folder that's never had email

- imap/mboxlist.c
This caused a problem for a user with a mailbox that's exactly 490 characters long!  The name got trimmed by one character by this function because `snprintf` needs the entire space PLUS an extra byte for the `\0`.  The size to `snprintf` should be the entire size of the buffer, not one fewer.
```
The functions snprintf() and vsnprintf() write at most size bytes (including the terminating null byte ('\0')) to str.
```
This fixes the broken user sync.
> mboxlist: make space for a full 490 character folder name

- imap/message.c
- lib/util.c
This prevents confusion caused when automated diagnostic stuff (especially _wrong_ diagnostic stuff, like leaked errno values) winds up in informational log messages.
So far we've mostly used xsyslog for error conditions, but this makes it a little nicer to use for everything else too.
For whatever it's worth, the full set of syslog log levels is:
- LOG_EMERG      system is unusable
- LOG_ALERT      action must be taken immediately
- LOG_CRIT       critical conditions
- LOG_ERR        error conditions
- LOG_WARNING    warning conditions
- LOG_NOTICE     normal, but significant, condition
- LOG_INFO       informational message
- LOG_DEBUG      debug-level message
And I think we still want syserror=<> and func=<> for all of these, except LOG_NOTICE and LOG_INFO.
This also reverts a commit …
> xsyslog: don't log syserror/func fields for LOG_NOTICE/LOG_INFO

- cunit/annotate.testc
- imap/annotate.c
- imap/http_caldav_sched.c
- imap/imapd.c
- imap/jmap_backup.c
- imap/mailbox.c
- imap/mailbox.h
- imap/mboxlist.c
- imap/mboxlist.h
- imap/mboxname.c
- imap/quota.c
- imap/reconstruct.c
- imap/relocate_by_id.c
- imap/search_xapian.c
- imap/sync_support.c
- imap/user.c
This fixes the issues identified by:  https://github.com/cyrusimap/cassandane/pull/146
There's also a bunch of other small improvements to the safety and behaviour of renames in uuidland, including:
* you can rename a subfolder, and it will still detect the right INBOX
* per-mailbox annotations won't get nerfed
* replication will detect and repair renamed folders so long as the change happened on the master first
> Quota rename

- imap/sync_support.c
This has two commits.
One fixes the sort order so that diff_annotations and apply_annotations is actually reliable, and the other makes sure that we only copy annotations from the replica if the replica is newer and we're copying everything else from the replica too!
I have a separate commit to make the value a dlist, but it turns out that binary values and dlistsax don't work, so I have to fix that first.
> Annotate improvements

- imap/imapd.c
- lib/imapoptions
This adds a `sessionid=<...>` field to the "cmdtimer:" log lines, which was requested by @robn in #3592.  I also switched it to xsyslog while I was in there anyway.
I was briefly confused as to why the `commandmintimer` option (which controls this behaviour) was doing its own value parsing, rather than being an OPT_DURATION, until I realised this option accepts a floating point value.  So I also updated the docs for the option to make this clear.
Added a basic test in: https://github.com/cyrusimap/cassandane/pull/144
Since this is also an xsyslog conversion, which we know are prone to subtle typos, please do a build test of this -- in case your compiler catches anything mine didn't.
Thanks!
> Add sessionid field to cmdtimer: logs

- imap/ical_support.c
- imap/jmap_ical.c
This has been a long-standing request: some CalDAV clients, e.g. Apple implementations, may dump bogus IANA VTIMEZONEs in a VEVENT. This patch changes Cyrus to prefer using its internal timezone database for IANA timezone identifiers, rather than the embedded VTIMEZONEs.
It also updates recurrence expansion accordingly, to make sure that the preferered UTC start/end of the event is stored in dav.db
Tested in https://github.com/cyrusimap/cassandane/tree/jmap_ical_prefer_cyrus_tz
Passes all JMAP and CalDAV tests.
> Prefer Cyrus IANA timezones over embedded VTIMEZONEs

- changes/next/propfind_caltransp
- imap/http_caldav.c
The value of the schedule-calendar-transp property is not a string with possible text values “transparent” or “opaque”, but an XML element in the CalDAV namespace: https://tools.ietf.org/html/rfc6638#section-9.1.
- on PROPPATCH of the transarent property validate the namespace of the value
> PROPFIND <c:schedule-calendar-transp>

- docsrc/assets/setup-sasl-sasldb.rst
testsaslauthd will complain with "connect() : No such file or directory" if it doesn't know the socket path via (-f).
> testsaslauthd needs socket path info (-f)

- imap/conversations.c
- imap/jmap_backup.c
- imap/mailbox.c
- imap/mailbox.h
Process messages in batches so we don't deadlock and/or hold locks for a long time.  All Cass tests succeed even with a batch size of 1
> JMAP Backup relaxed locking

- changes/next/invalid_rrule_handling
- configure.ac
- imap/http_caldav.c
- lib/imapoptions
Adds a setting to accept invalid RRULEs (e.g. FREQ=WEEKLY;BYMONTHDAY=15) rather than rejecting them.
> Add 'caldav_accept_invalid_rrules' option.

- imap/carddav_db.c
- imap/carddav_db.h
- imap/jmap_mail.c
- imap/jmap_mail_query.c
- imap/jmap_mail_query.h
- imap/jmap_sieve.c
- imap/lmtp_sieve.c
- sieve/test.c
The Cyrus JMAP email extension supports lookup of emails, where a sender (recipient) may match any contact of that user, including shared addressbooks. However, shared addressbook lookup was broken, both because
- the carddav API was still using mailboxnames for lookup
- the shared addressbook routines where missing an authstate
> Fix fromAnyContact Email filters to work with shared addressbooks

- configure.ac
We use detect_handledata_r, which appeared in 1.0.5
> configure: require libchardet 1.0.5

- cunit/times.testc
- imap/imapd.c
- imap/mailbox.c
- lib/times.c
This fixes so that 'reconstruct -G' works in Cassandane (and also for production).
If there date header is ahead of GMT and exactly zero, e.g:
Thu, 01 Jan 1970 10:00:00 +1000
Then the "gmtime" field was set to a massively high number instead of the past.  Oops.
Also, it didn't get reset properly from zero by the reconstruct code in the same way that the append code did, so a reconstruct would zero it again if there was no header in the message.
ALSO: I've added an unrelated commit except that `reconstruct -G` also found it, append-binary needs to re-parse the message after the parse_binary, because the cache structure is slightly different on the second parse - and we want to make sure the structure we store is the correct one for a reconstruct.  Passes the ImapTest.append-binary test …
> Reconstruct times

- cunit/annotate.testc
- imap/append.c
- imap/conversations.c
- imap/conversations.h
- imap/cyr_expire.c
- imap/http_dav.c
- imap/http_jmap.c
- imap/imapd.c
- imap/index.c
- imap/jmap_api.c
- imap/jmap_backup.c
- imap/jmap_mail.c
- imap/jmap_util.c
- imap/mailbox.c
- imap/mailbox.h
- imap/mbdump.c
- imap/mbexamine.c
- imap/mboxlist.c
- imap/mbtool.c
- imap/quota.c
- imap/reconstruct.c
- imap/relocate_by_id.c
- imap/search_expr.c
- imap/sync_support.c
- lib/hashset.c
- lib/hashu64.c
- lib/strarray.c
- lib/xmalloc.h
This is the stuff I was working on a couple of weeks ago and shelved.  The big part is the commit which stores a separate sub-struct for the header data, and an `mbentry_t *` directly inside `struct mailbox`.
Apologies for the one big messy commit which makes a couple of changes all together, I've separated out what I can as practical individual changes.
The IMPORTANT bit is that we can handle gaps in `flagnames` correctly now - it was buggy before (both UUID and pre-UUID I think), and would forget all the names after the first gap.
This all passes Cassandane still.
> Mailbox mbentry

- imap/calalarmd.c
- imap/ctl_conversationsdb.c
- imap/cyr_expire.c
- imap/dav_reconstruct.c
- imap/global.c
- imap/global.h
- imap/httpd.c
- imap/imapd.c
- imap/lmtpd.c
- imap/mailbox.c
- imap/nntpd.c
- imap/pop3d.c
- imap/reconstruct.c
- imap/smmapd.c
- imap/sync_client.c
- imap/sync_reset.c
- imap/sync_server.c
- lib/cyrusdb_twoskip.c
- lib/libcyr_cfg.c
- lib/libcyr_cfg.h
This set of commits creates a list of "delayed actions" deep in libcyrus, where all the libraries can call it.  It then runs them either during shutdown, or you can call them at any time.  By doing this, both mailbox cleanup and twoskip checkpoints can be delayed until after we've replied to the user, meaning that the user doesn't have to wait on background tasks.
an alternative option is to log all these things somewhere and have a maintenance job that reads the log file sync_log style and does the actions, but this seems a nice sweet spot that doesn't require another daemon.
> Delayed actions - don't repack until we've replied to the user!

- imap/http_dav.c
This allows the CardDAV module to be used indepedently of CalDAV.  All Cass tests still pass
> http_dav.c: lookup INBOX when parsing principal URLs, rather than blindly looking up calendar-home-set

- docsrc/imap/reference/manpages/index.rst
- docsrc/operations.rst
So that navigating to http://www.cyrusimap.org/imap/reference/manpages/ works!
It's currently called "[commands](https://www.cyrusimap.org/imap/reference/manpages/commands.html)", which is discoverable via the sidebar links but hard to find by typing in an address.
Not really sure what I expect a reviewer to do with this...
> docs: call manpages index "index"

- imap/http_h2.c
- imap/http_jmap.c
- imap/http_proxy.c
- imap/http_proxy.h
- imap/httpd.c
- imap/httpd.h
[edit from elliefm: There's tests for this in cyrusimap/cassandane/pull/151]
> Proxy JMAP requests in a Murder

- imap/http_dav.c
- imap/mboxname.c
- imap/mboxname.h
This switches back to looking up a "home-set" collection when parsing principal URLs, defaulting to calendar-home-set if CalDAV is enabled, then dropping to addressbook-home-set if enabled, and finally using the root of a user's #drive hierarchy
> CardDAV without CalDAV bis

- .travis.yml
We've gotten used to "silence means success", but these days silence
usually means "travis is out of credit and builds are no longer
running".
This makes success noisy too, so when things get quiet we're probably
out of credits.
> .travis.yml: notify every success on slack

- imap/proxy.c
proxy.c: don't leak prot_waitevent when a connection to a backend has gone away
> prot_waitevent-leak-fix

- imap/imapd.c
This fix is good to backport to 3.0, 3.2 and 3.4 as well.
As discovered in https://bugzilla.mozilla.org/show_bug.cgi?id=1708981
> imapd: flush output when starting output so changes are told immediately

- cunit/annotate.testc
- imap/ctl_cyrusdb.c
- imap/ctl_mboxlist.c
- imap/cyr_expire.c
- imap/http_dav.c
- imap/http_dav_sharing.c
- imap/imapd.c
- imap/jmap_backup.c
- imap/mboxlist.c
- imap/mboxlist.h
- imap/reconstruct.c
- imap/relocate_by_id.c
- imap/sync_support.c
This whole series of commits is (apart from a couple of bugfixes at the top) all about making sure that there's a namespace lock held every time we update the mailboxes.db.  It also wrap a transaction around all the updates related to a single mbentry (N key, I key, ACLs).
This is a precursor to the work to make renames atomic.  We need the namelocks coming in, so a lot of the commits are bugfixes around the namelocking further out in the callers.
> Namespacelock mbentry updates

- configure.ac
Debian 11 (bullseye) is now shipping the Python 3 versions of Sphinx and
GitPython, which aren't detected using the "default" python. This looks
for it under both names.
All this is doing is deciding if the package is available so that
sphinx-build can actually work, so there's no further work required to
link it in or anything.
The downside here is that if the sphinx-build on PATH is the Python 2
version and GitPython is Python 3 (or vice-versa), this could still end
up with the configure "succeeding" and then sphinx-build failing later.
A better test for all of this would be to test sphinx-build with a
minimal document that requires the wanted modules explicitly, and see if
that succeeds (exactly like what the AC_CHECK_ macros do by generating
and compiling a small C program). That's a …
> configure: search for GitPython with Python 2 and 3

- .travis.yml
This is in response to a security breach[1]. The token is generated by
the 'Workspace Owner'(Slack speak) of Slack, which is then encrypted
using the `travis` CLI, like so:
```
travis encrypt "<account>:<redacted>#cyrusdev" --add notifications.slack.rooms
```
Currently uses my account to encrypt, but this can be anyone who has
read/write permissions to the cyrus-imapd repo.
More details about how to setup slack tokens available here[2].
[1] https://travis-ci.community/t/security-bulletin/12081
[2] https://docs.travis-ci.com/user/notifications#configuring-slack-notifications
> travis: Update secure key.

- ptclient/ldap.c
This fixes a bunch of memory errors and leaks in ptloader, found by valgrinding Cassandane.
Notably, they're all in the LDAP PTS module, because this is the only PTS module we have any tests for...
This particular source file is pretty ghastly.  I've tried to make the smallest fixes possible, rather than getting bogged down refactoring for weeks/months...
> ptloader valgrind fixes

- imap/caldav_alarm.c
- imap/ical_support.c
- imap/ical_support.h
Both icaltime_get_tzid and icaltimezone_get_tzid cause libical to return timezone identifiers prefixed with the hardcoded value `/freeassociation.sourceforge.net/`.
This even happens if
* a custom zoneinfo directory is set
* the libical tzid_prefix is set to the empty string
Consequently, both functions should not be used within Cyrus.
We could patch our libical fork in cyruslibs, but this won't help installations that build on upstream libical versions.
Tested in https://github.com/cyrusimap/cassandane/pull/165
> ical_support: do not use icaltimezone_get_tzid

- imap/conversations.c
- imap/conversations.h
- imap/ctl_conversationsdb.c
As discussed today - this allows for an atomic in-place conversationsdb rebuild, which will switch over to byid.  It just wipes every single key and then inserts new records for everything, such that we lose all the highestmodseq information and folder presence information from conversations and mailboxes.
This does mean that updates might be incorrect for the client over this one transition point, but a refresh fixes it, and they're good afterwards - and it's only in the rare case where the change was a record being entirely wiped (i.e. over the weekend) and that changing the result we would have sent to a user... so really approximately never!
> conversations: when recalculating, upgrade to byid

- imap/cyr_synclog.c
- imap/sync_log.h
- imap/sync_support.c
Replication has been bailing out on:
MAILBOX ""
We're not quite sure where those are coming from - so by adding an assertion we'll find out :)
Also, fix the reader so it just skips such bogus entries.
> Sync empty names

- cunit/annotate.testc
- imap/mailbox.c
This makes rename/delete locks work correctly for legacy mailboxes.
I believe this fixes both the failing tests.  At least, it does for me :)
> mailbox: lock by name if legacy_dirs

- imap/calalarmd.c
calalarmd needs to call ical_support_init() to use our own VTIMEZONEs
> Calalarmd use our own VTIMEZONEs

- imap/calalarmd.c
- imap/dav_reconstruct.c
- imap/global.c
- imap/relocate_by_id.c
Timezones are required in almost all Cyrus services, so let's make it simple to not forget their initialization.
We leave it to httpd and lmtpd to initialize libical as these daemon already do their own custom initialization.
Passes the Cassandane test suites.
> global: initialize libical zoneinfo directory in cyrus_init

- imap/httpd.c
HTTP/1.1 requests can also use the Keep-Alive header and we should respond in kind.  Very trivial patch.
> HTTP/1.1 Keep-Alive

- imap/annotate.c
- imap/annotate.h
- imap/imapd.c
• imap/imapd.c: remove unnecessary freestrlist declaration
> imap/annotate: remove unused appendstrlistpat() and comp_pat from struct strlist

- imap/sync_support.c
All fields are anyway zeroed by xzmalloc().
• sync_folder_list_create()
• sync_rename_list_create()
• sync_quota_list_create()
• sync_sieve_list_create()
• sync_seen_list_create()
• sync_annot_list_create()
• sync_action_list_create()
> sync_support.c:sync_*_list_create() - simplify

- imap/jmap_calendar.c
Fixes a bug where a calendar with ACL 'l9' (lookup and freebusy) causes a JMAP session accountCapibilities to report the calendar capability for that account, but Calendar/get is rejected with an 'accountHasNoCalendars' error.
Tested in https://github.com/cyrusimap/cassandane/pull/170
> jmap_calendar: list empty Calendar list if ACL_LOOKUP is set

- imap/imapd.c
This fixes two bugs and one source of confusion in XFER:
* The `name` argument was converted to the wrong namespace before the mboxlist_findall call, so if you specified a user or mailbox name (rather than a pattern or partition name), it wouldn't find anything to do.  This was already fixed in 3.0.15, but since we didn't have any tests for XFER at the time, it wasn't clear whether the same fix was necessary or correct to forward port, so I didn't and forgot about it.  We now have such tests, and it turns out to be necessary and correct!  This is aka #2383 
* If the destination backend did not support using the replication protocol for XFER, the XFER would mostly succeed, but it would try to send a sync restart when it was finished, and hang indefinitely waiting for a response.  We no …
> XFER fixes

- imap/httpd.c
Looks like we usually skip the PROT_EOF_STRING ones when warning about closing connections, so doing the same here.
Closes #3700
> httpd: don't warn for "end of file reached" when closing connection

- imap/cyr_dbtool.c
Fixes a few simple leaks in cyr_dbtool's batch mode, found by valgrinding Cassandane.
Looks like these leaks have existed for ages, but for some reason Cassandane only recently started triggering them -- probably due to the addition of the `run_dbcommand()` APIs that use it.
> cyr_dbtool: fix batch mode leaks

- imap/http_caldav.c
Up until now it only used the userid argument as condition
if the iCalendar data should be personalized, but then
personalized for the authenticated HTTP user.
Passes the current Cassandane calendar test suites.
> http_caldav: use userid argument to personalize iCalendar data

- imap/http_ws.c
- imap/httpd.h
This reverts part of #3712 as txn->conn->ws_ctx was always being set to NULL.  Switching back to using void** solves the issue.  Valgrind is still clean.
> http_ws: properly close WS when receiving a signal

- changes/next/3705-xfer-no-intermediates
- imap/imapd.c
Tests in https://github.com/cyrusimap/cassandane/pull/174
Since 3.5 we haven't been allowing "intermediate" mailboxes, instead requiring that all mailboxes are real mailboxes.
XFER in a murder environment allows this to be gummed up though, because it permits moving individual mailboxes around, leaving their ancestors and children behind.  The origin backend gets an intermediate entry where the mailbox used to be, and the destination backend gets a tree of intermediate entries where the ancestors would have been.  The mupdate master knows where all the "real" mailboxes are, so maybe it's okay in practice, but it breaks our new assumption that there are no more intermediates, which means we'll trip over it forever.
XFER is invoked on the origin backend like this:
`. XFER name destination …
> Don't allow XFER to create intermediates in the user tree

- imap/jmap_mail.c
- imap/jmap_util.c
Fixes a bug in Email/set{update} for shared mailboxes. Root cause identified together with @wolfsage 
The commit message has it all:
The Email/set{update} planer creates a plan for each mailbox where
at least one email is updated, copied or moved. If a user does not
have the required ACLs or quota for a mailbox, then all updated
emails in that mailbox are invalidated in a set error. But updated
emails in other mailboxes that depended on that mailbox are currently
not reported as invalid.
This patch invalidates also updated emails that depend the mailbox
of an erroneous update plan, but do not belong to it.
Also fixes an issue with Email/set{update} not validating boolean values in overwritten `mailboxIds`.
Tested in https://github.com/cyrusimap/cassandane/pull/182
> JMAP Email/set{update}: invalidate updated email ids that belong to erroneous plan

- imap/cyr_expire.c
Define first the type cyr_expire_ctx, then variables from the type.
imap/cyr_expire.c:92:30: warning: tentative definition of variable with internal linkage has incomplete non-array type 'struct cyr_expire_ctx' [-Wtentative-definition-incomplete-type]
static struct cyr_expire_ctx ctx;
^
imap/cyr_expire.c:92:15: note: forward declaration of 'struct cyr_expire_ctx'
static struct cyr_expire_ctx ctx;
^
> imap/cyr_expire.c: fix compiler warning with clang 12

- imap/ctl_conversationsdb.c
- imap/ctl_zoneinfo.c
- imap/cyr_virusscan.c
- imap/message_test.c
- imap/search_test.c
as suggested by clang -Wmissing-variable-declarations
> Make 'verbose' variables static

- imap/httpd.c
as suggested by clang -Wmissing-variable-declarations
> httpd.c: make some variables static

- lib/lock_flock.c
Fixes a problem when flock(2) is used instead of fcnlt(2).
The symbol `debug_locks_longer_than` is required by imap/global.c.
lib/lock_flock.c does not log long locks.
> lib/lock_flock.c: export debug_locks_longer_than

- imap/cvt_cyrusdb.c
- imap/cyr_dbtool.c
- imap/seen_db.c
- lib/cyrusdb_flat.c
- lib/test/run
Remove some referencs to Berkeley DB.
Can now the restriction about the absolute file names in cvt_cyrusdb and cyr_dbtool now be removed?
> Remove some references to Berkeley DB

- lib/libcyr_cfg.h
> libcyr_cfg.h: correctly remove BDB

- docsrc/assets/cyrus-build-devpkg.rst
- docsrc/imap/download/installation/distributions/ubuntu.rst
- docsrc/imap/download/upgrade.rst
Since BDB is now ignored, the documentation shall not suggest any dependency on it, in order to use Cyrus IMAP.
> docsrc: remove requirement of installing libdb(-dev)

- cassandane/Cassandane/Cyrus/JMAPEmail.pm
- cassandane/data/mime/utf8-base64-replacement.eml
- imap/jmap_util.c
Fixes a bug in the JMAP internal utf8 decoder, where replacement characters in a  base64-encoded UTF-8 MIME body could cause the decoder to incorrectly guess the source charset.
Tested in https://github.com/cyrusimap/cassandane/pull/183
> jmap_util: do not guess charset of valid UTF-8 with replacement chars

- cassandane/Cassandane/Cyrus/Replication.pm
- imap/dlist.c
More xsyslog conversions -- as usual for these, please build this, in case your compiler catches something mine didn't.  Thanks
Fixes #3784
> dlist: use xsyslog for IOERRORs

- imap/http_jwt.c
Fixes a niche build problem that occurs when the build directory is not the source directory.  Generated headers are created in the build directory, not the source directory (which might even be read-only in this situation), and so unless the include path is specified explicitly they can't be found.  Found by `make distcheck`.
I have vague plans to fix this properly sometime, but it's big and boring and will touch nearly every single source file, so I keep kicking it down the road.
> http_jwt: fix include of generated header

- cassandane/Cassandane/Cassini.pm
- cassandane/Cassandane/Instance.pm
Single-commit Cassandane bug fixes that don't have an accompanying Cyrus feature branch to become part of.  These were already approved on the Cassandane repo, as:
* https://github.com/cyrusimap/cassandane/pull/179
* https://github.com/cyrusimap/cassandane/pull/184
Here they are for Cyrus, as a single PR to minimise additional overhead.  Please rubber stamp (or just go ahead and merge!)
> imported cassandane-only changes

- imap/mailbox.c
- imap/mboxname.c
This fixes a crasher where there was a tombstone entry with just `%(T ed M 123456789)` and no uniqueid, which caused sync_server to abort rather than just believing that there's no local mailbox.
> Bad tombstone crashfix

- cassandane/Cassandane/Cyrus/Delete.pm
- imap/imapd.c
Two small fixes, found by running cassandane with `mailbox_legacy_dirs: yes` in the `[config]` section.
Part of #3782.  There's more still to be fixed, but this is what I've tracked down so far.
> partial fixes for mailbox_legacy_dirs=yes problems

- cassandane/Cassandane/Cyrus/JMAPEmail.pm
- imap/jmap_mail.c
RFC 2387 defines the `multipart/related` content type, which requires a `type` parameter.
This patch adds that `type` parameter and sets it to the content type of its first child part. At Fastmail, this almost always will be a `text/html` MIME part.
> jmap_mail: add mandatory "type" parameter to RFC 2387 "multipart/related"

- imap/sieve_db.c
This fixes a crasher when running dav_reconstruct.  The problem is
that the mailbox_sieve_commit tries to close the DB, which is still
in a transaction and asserts.
dav_close is this:
```
EXPORTED int dav_close(sqldb_t **dbp)
{
if (reconstruct_db) return 0;
return sqldb_close(dbp);
}
```
Which precisely avoids this issue!  The other users of dav_db (caldav_db,
carddav_db) corretly use dav_close() in their close functions.
> sieve_db: use dav_close rather than sqldb_close

- imap/http_dav.c
http_dav.c: always return 204 (No Content) for pseudo-collections (those with no backing mailbox)
> GET DAV Collection Fix

- imap/dav_db.c
Since d35f0dac07904bef the index is not created for new setups.  The index was however not removed from older setups.
This change does not help for upgrades to 3.4, which upgrades were performed before this change.  For such setups, thas is if you already run 3.4, the command
> for x in $(find /var/imap -name '*.dav'); do sqlite3 $x "DROP INDEX IF EXISTS idx_res_uid"; done
executed under the 'cyrus' user, does perform the change, where '/var/imap' is the configdirectory in imapd.conf .
Fixes https://github.com/cyrusimap/cyrus-imapd/issues/3756.
> dav_db:CMD_DBUPGRADEv10 — DROP INDEX IF EXISTS idx_res_uid

- cassandane/Cassandane/Cyrus/Rename.pm
- imap/mailbox.c
- imap/mboxlist.c
- imap/sieve_db.c
- imap/sieve_db.h
- imap/sync_support.c
The change to sieve_db.c turned out to be unnecessary, since I didn't use it outside of that file.  I intended to use it in sync_support.c, but I thought it made sense to create a single mbname_t rather than using separate mboxname_*() functions that all create and destroy a private mbname_t.
Also, I wasn't sure how to actually check for the presence of INBOX.#sieve on the replica in the Cass test.  I verified that it indeed does exist by hand, but the test should be augmented.
> Sieve user rename fix

- cassandane/Cassandane/Cyrus/JMAPEmail.pm
- changes/next/jmap_emailsearch_trash
- cunit/search_expr.testc
- imap/jmap_mail.c
- imap/search_expr.c
- imap/search_expr.h
Up until now, evaluation of the threadKeyword query criteria did not take the `Seen` state of messages in the "Trash"
mailbox into account. The JMAP specification does not define this special treatment for the Trash mailbox.
This patch updates threadKeyword search to include the `Seen` state of messages within Trash. To preserve former behaviour, queries must explicitly exclude the "Trash" mailbox, using either an `inMailboxOtherThan` or a negated `inMailbox` criteria. For such queries, the `Seen` count of messages with "Trash" is ignored.
Note that this patch only applies to the hard-coded "Trash" mailbox name. Mailboxes with other name and `role=trash` always counted towards the total `Seen` count of a thread.
To make this work for guidsearch,  DNF search expression normalisation also …
> JMAPEmail: include Trash unseen counts in threadKeyword search

- imap/jmap_mail.c
- imap/jmap_mailbox.c
- imap/mboxlist.h
We want both methods to operate on the same set of mboxlist entries. Currently, the gap is a missing check for `mbtypes_unavailable` in Mailbox/query, which might have caused a (non-reproducible) issue a couple of weeks ago. Using the same logic in Mailbox/query and /get should avoid such errors also for future changes.
Passes all JMAP Cassandane tests.
> jmap_mailbox: unify mboxlist callback filters for /query and /get

- imap/http_caldav.c
This fixes a crasher when we find a conflicting iCal UID in DAV DB, but we are unable to look up the offending mailbox record.
In the crasher that we had, the DAV DB record had the mailbox name (not id), but the byname flag was not set, so we tried to lookup the mailbox by id using the name as the id, which failed.
> CalDAV Unique Object Fix

- imap/http_caldav.c
- imap/http_carddav.c
We had a crasher in a CARDDAV:addressbook-query REPORT in which we trying to fetch the CARDDAV:address_data property.  vcard_parse_string() was returning NULL, which we then try to dereference.
The first 2 commits will now return a DAV:propstat with a DAV:status of 501 in such a case rather than crash.
We believe the crash was a result of parsing non-NULL-terminated data, which should be fixed by the last 2 commits.
> Propfind data crasher fix

- imap/sync_support.c
Fixes #3813 
Variables declared `static const` are stored in read-only memory, but the `buf_...()` functions expect to be able to change a buf's in-memory representation, even when they offer `const` as a promise the data itself won't change.  If the buf in question is in read-only memory, they'll crash when they try.
This PR removes the `static` keyword from the one `static const struct buf` that we had -- before we accidentally treat it like any other struct buf and crash!
> Remove 'static const struct buf' tripping hazard

- imap/http_dav.c
This fixes a crasher where we call goto done before namespacelock has been declared, E.g. if parse_xml_body() fails
> MKCOL namespacelock fix

- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
- imap/jmap_api.c
Before, if only the `#calendars` or `#addressbooks` mailboxes where shared, then the account still got reported to share calendars or addressbooks.
> jmap_api: ignore shared calendar/addressbook home for capabilities

- imap/http_dav_sharing.c
Fixes parsing of sharer URIs with escaped characters, which resulted in mailbox lookup failures later in the codepath.
> http_dav_sharing: decode sharer URI before parsing path

- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
- cassandane/Cassandane/Cyrus/JMAPContacts.pm
- cassandane/Cassandane/Cyrus/JMAPCore.pm
- cassandane/Cassandane/Cyrus/JMAPEmail.pm
- cassandane/Cassandane/Cyrus/JMAPSieve.pm
- changes/next/blob-rfc
- imap/jmap_api.h
- imap/jmap_core.c
- lib/imapoptions
This changes Blob/get to Blob/lookup, and adds the new Blob/get and Blob/set logic from the IETF draft.
> jmap_core: update all the Blob APIs to the latest draft-ietf-jmap-blob-04 draft

- cassandane/Cassandane/Cyrus/Caldav.pm
- imap/http_caldav.c
This fixes an issue where the calendar-query wasn't being executed on certain resources because of a bad initialization of 'ical'.
This also adds a calendar-query test which exercises time-range and component filtering, recurrence expansion, and partial event retrieval.
> Caldav calendar query fix

- cassandane/Cassandane/Cyrus/FastMail.pm
- cassandane/Cassandane/Cyrus/List.pm
- cassandane/Cassandane/Unit/TestCase.pm
- imap/annotate.c
- imap/mailbox.c
This fixes most (but not all) of the errors found by running cassandane with "mailbox_legacy_dirs = yes" (#3782).  Specifically, it fixes:
* quota_annot_used getting out of sync when "displayname" annotation is removed during rename
* List "tombstones" tests checking for MBTYPE_DELETED incorrectly, and failing when the MBTYPE_LEGACY_DIRS bit was also set
It also updates the FastMail.rename_deepfolder_intermediates and FastMail.rename_deepfolder_intermediates_rightnow tests to produce a useful error message for the particular failure they're experiencing -- I have no insight to the underlying problem yet, but at least now the errors are comprehensible for future debugging.
We might be able to do the quota_annot_used fix better, perhaps by adding a `delete_cb()` instead of continuing to …
> more mailbox_legacy_dirs fixes

- .gitignore
Ignoring these transient files prevents `git status` from reporting "untracked files" while configure is running.  They're usually cleaned up when configure finishes anyway, which I guess is why we haven't previously noticed them.
My shell prompt includes repository status, and since cassandane and cyrus-imapd are the same repository now, I keep noticing and being distracted by these files popping in and out of existence when I'm doing stuff with cassandane while cyrus builds in another terminal.  And it's gotten annoying enough to just fix. :)
> .gitignore: ignore some transient configure files

- cassandane/Cassandane/Cyrus/Quota.pm
- imap/quota.c
This fixes the use of `quota -f -u` so it doesn't wipe sub quotaroots, as found in Fastmail production.
> Quota f u fix

- imap/ical_support.c
This fixes a bug where PATCH-* properties were being treated as properties to add/update
> ical_spply_vpatch() Fix

- imap/sieve_db.c
Upgrading an empty v12 sieve_scripts table was causing a crash: mboxlist_lookup_allow_all() on a NULL mboxname fails, causing sievedb_upgrade() to fail, causing sqldb_open() to return a NULL DB handle to mailbox_update_dav|sieve()
> DAV DB v12 -> v14 upgrade fix

- cassandane/Cassandane/Cyrus/Quota.pm
Confused myself and thought I'd found a bug in `quota -d`.  Wrote a test to prove it, instead proved it was fine.  But at least we have a new test now.
This tests `quota -d domain` to ensure that both:
* quotas within the specified domain are reported
* quotas in other domains are not
> Quota: test quota -d

- imap/ctl_mboxlist.c
- imap/cyr_expire.c
- imap/jmap_calendar.c
- imap/mboxlist.c
- imap/mboxlist.h
This does some initial rewrites of mboxlist handling for history and updates:
- adds partition, mbtype, uidvalidity to the history entries.  This will come in handy later
- makes sure that the N key and I key updates are atomic by starting a transaction if there isn't one
- refactors the code a bit to support the above
> Mboxlist tooling

- Makefile.am
- imap/rfc822_header.c
Well, one fix, one itch scratched:
* `make dist` was failing because imap/http_caldav.h no longer exists (was renamed to "caldav_util.h"), but it was still listed in a `..._SOURCES` line in Makefile.am.  So make would try to include it in the tarball, not find it, try to build it, not find a rule to build it, and complain that there was no rule...  
* imap/rfc822_header.c is automatically generated, but we keep it in the repository for the reasons described in 4f4c46d388.  Since I updated to buster (and a newer `gperf` that produces slightly different code), every time I make a release, my repository ends up dirty, which confuses me for a moment.  So this time I'm committing the new version to save myself the confusion for a while.  We previously did the same thing in 6ed3e47e95.
> trivial "make dist" fixes

- Makefile.am
Turns out (#3843) our release tarballs have not included man pages for fetchnews, nntpd, and some others, because they're for "optional" features, and when making a release we don't turn on or off the optional features, because we're not building any code and the distribution shouldn't depend on them...
This change makes sure that in maintainer mode (used for releases) the man pages for these features are included in the release tarball, regardless of whether the feature has been "enabled" or not.
When an end user extracts the tarball and runs configure themselves (not in maintainer mode), the pre-generated man pages will be present, ready to be installed if the feature they're for has been enabled.
We plan to make most of these optional features non-optional sooner or later, but right …
> Ensure manpages for optional features are always included in release tarball

- lib/imapoptions
Accidentally removed entirely by bfb0061cf64ff878b27e0d3e8e2d5549c77b563f
(#3484), when it should have been updated with a deprecated-since version
instead.
Fixes #3616
> lib/imapoptions: add deprecated entry for reverseuniqueuids

- cunit/backend.testc
- imap/backend.c
So XFER between versions can recognise the new versions.
This will be cherry-picked to 3.6 and also backported to the older release branches (as far back as 2.4).
> backend: update backend_version for 3.6 and 3.7

- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
- imap/jmap_calendar.c
The formerly implemented rules when to bump an event sequence were outdated and probably never right anyway.
> jmap_calendar: implement proper sequence bumps in CalendarEvent/set

- cassandane/Cassandane/Cyrus/Carddav.pm
This test expects "altnamespace: no", so I've added the :NoAltNamespace magic
> fix Carddav.sharing_rename_sharee

- cassandane/Cassandane/Cyrus/CaldavAlarm.pm
- imap/caldav_alarm.c
calalarmd would spin on a non-terminating recurring event  having an alarm with an absolute trigger, because we would never hit the exit clause (an alarm more than 2 months in the future)
E.g.:
BEGIN:VTODO
CREATED:20211011T104314Z
DTSTAMP:20220201T203307Z
DTSTART;TZID=America/Toronto:20220202T113000
DUE;TZID=America/Toronto:20220202T113000
LAST-MODIFIED:20220201T203257Z
RRULE:FREQ=DAILY
STATUS:NEEDS-ACTION
SUMMARY:D3 pill
UID:8F8917BD-0DD4-4B7B-9245-AF8BBC42E493
X-APPLE-SORT-ORDER:3
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:Reminder
TRIGGER;VALUE=DATE-TIME:20220202T163000Z
UID:C9C19C74-EA8E-4A22-8BD2-C68C970644E0
X-WR-ALARMUID:C9C19C74-EA8E-4A22-8BD2-C68C970644E0
END:VALARM
END:VTODO
> VALARM absolute trigger fix

- imap/caldav_db.c
If Cyrus replicates a calendar event, if first marks the existing
ical_objs entry as expunged, setting alive to 0. This alive status
propagates into the jscal_objs table.
Later on, the jscal_objs handling code only updates an existing
jscal_objs entry, if the contents of the iCalendar data changed.
This caused replication to leave standalone instance entries in
that table as not alive, when on the main store they are alive.
> caldav_db: update jscal_objs table records also if 'alive' changed

- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
- imap/caldav_db.c
iCalendar allows multiple calendar objects with the same
recurrence id embedded within a VCALENDAR. But for JMAP
Calendars these duplicates are not allowed and cause the
jscal_objs table to raise a conflict.
Resolve such write conflicts by ignoring all but the first
recurrence id for all duplicate entries.
In order to gracefully handle any existing database entries,
use UPSERT rather than INSERT or UPDATE.
> caldav_db: resolve duplicate recurrence ids conflicts

- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
- imap/jmap_ical.c
- imap/json_support.h
RFC 8984 states at [4.3.2. ](https://www.rfc-editor.org/rfc/rfc8984.html#section-4.3.2)[recurrenceIdTimeZone](https://www.rfc-editor.org/rfc/rfc8984.html#name-recurrenceidtimezone)
```
Type: TimeZoneId|null (optional, default: null)
[...] This property MUST be set if the recurrenceId property is set. [...]
```
But that's wrong for floating time events.
> Do not reject updates on CalendarEvent standalone instances with floating time

- imap/mboxlist.c
- imap/mboxlist.h
- imap/mboxname.c
- imap/mboxname.h
- lib/imapoptions
It only was committed on the main branch for integration testing.
This reverts commit 92a22afbe7073ba0481e07a5b4f758a021e82a3f.
> Revert "jmap_calendar: add MBTYPE_JMAPNOTIFICATION"

- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
Looks like the recurrenceRule->recurrenceRules JMAP rename was mistakenly applied to a CalDAV query as well, causing this test to fail
> JMAPCalendars: fix rscale_in_jmap_hidden_in_caldav

- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
- imap/http_caldav_sched.c
Before, every change to a scheduled iCalendar component replaced the
PARTSTAT of existing ATTENDEEs to be reset to NEEDS-ACTION. This
patch changes that to only set NEEDS-ACTION if the ATTENDEE either
has no PARTSTAT parameter set.
> caldav_sched: preserve PARTSTAT for rescheduled iTIP messages

- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
- imap/jmap_core.c
- imap/jmap_util.c
A recent change in the blob id parser introduced a null pointer derefence. This patch reverts that regression.
While testing for CalendarEvent, this also revealed an off-by-one error as well as Blob/lookup not returning the latest format for CalendarEvent identifiers.
> Fix Blob/lookup for smart blobs

- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
- imap/jmap_calendar.c
Before, calendar events delivered by Sieve iMIP were reported twice
by CalendarEvent/changes{created}, once in the default schedule
calendar, once in the CalDAV inbox.
> jmap_calendar: do not report CalendarEvent/changes in special mailbox

- imap/caldav_db.c
This fixes a crasher if CMD_SELJSCALOBJS fails and we goto done early
> caldav_db.c: initialize upsert ptrarray early

- imap/jmap_ical.c
- imap/jmap_ical.h
The jmap context attempted to open the managed attachments mailbox
for each ATTACH property, until is succeeded. This can result in
long locks. Now the jmap context remembers if it failed once and
does not attempt to the mailbox anymore.
> jmap_ical: only attempt to open managed attachments mailbox once

- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
- cassandane/Cassandane/Cyrus/TestCase.pm
- imap/caldav_db.c
- imap/jmap_calendar.c
The commit messages say it all, but in summary:
- large numbers of standalone recurrence instances caused the libical string garbage collector invalidate data when writing to caldav.db. We use a string pool now
- CalendarEvent/get for many standalone instances was unnecessarily slow, because it reopened the same index record lots of times. We cache the last-processed iCalendar data now.
> JMAP Calendars: fix bogus and slow handling of standalone recurrence instances

- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
- imap/jmap_calendar.c
- imap/jmap_util.c
- imap/jmap_util.h
The former blobId encoding did not change the blobId when the
iCalendar data changed. But a JMAP blob id must change if the
data changes.
> jmap_calendar: encode message guid in CalendarEvent.blobId

- imap/lmtp_sieve.c
Until we have a good mechanism for specifying/querying a user's scheduling addresses, assume that the script owner is the intended recipient
> processimip: assume that the script owner is indeed a recipient

- cassandane/Cassandane/Cyrus/JMAPContacts.pm
- imap/jmap_contact.c
A user has a vCard containing the following and we were showing an empty contact list because we were only looking for the Apple-specific group properties and not the formalized v4 ones:
KIND:group
MEMBER:urn:uuid:60f60d95-1f33-480c-bfd6-02b93a07aefc
MEMBER:urn:uuid:3e7cfbaf-3199-41bd-8749-38b8d1c89605
> ContactGroup/get fix for v4 vCards

- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
- imap/jmap_calendar.c
This emulates mixed mode for shared calendars:
- alerts and per-user properties act as if in team mode
- schedule addresses act as if in secretary mode
Also disables the tests for the new JMAP Calendars properties and
permissions:
- mayWriteOwn
- mayInviteSelf
- mayInviteOthers
- mayRSVP
- hideAttendees
until it is resolved how they should behave in mixed mode.
> jmap_calendar: always use shared calendar owner schedule addresses

- README.md
This just updates README.md to no longer say it's "3.5".
There'll be another update to this file soon, when 3.6 is released, but for the time being it's still correct to say the current stable version is 3.4.
> README.md: master branch is now 3.7

- configure.ac
- imap/ical_support.h
> Compatibility for missing icalcomponent_get_component_name()

- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
- imap/jmap_calendar.c
Add the ability to patch default alerts as such:
`'Calendar/set',
{
accountId: 'u2151409b',
update: {
'e98fba39-c8e4-408f-b4ce-f1415f9efb38': {
'defaultAlertsWithTime/858F1DFA-9388-11EC-8A10-DF4B5F78611F/trigger/offset':
'-PT4H0M0S',
},
'c2fe31d9-bfe9-4cf0-8e33-0f7cb302039d': {
'defaultAlertsWithTime/bca0a8c5-ab26-41b3-b78e-a969d44d8af9': {
'@type': 'Alert',
trigger: {
'@type': 'OffsetTrigger',
offset: '-PT4H0M0S',
relativeTo: 'start',
},
action: 'display',
},
'defaultAlertsWithTime/cee2d064-1bae-4dbf-8a63-2a5f21afd77b':
null,
},
},
onDestroyRemoveEvents: true,
},
'0',
];`
> Calendar/set{update} patch defaultAlerts

- cassandane/Cassandane/Cyrus/Conversations.pm
- imap/conversations.c
This was found by a user reporting that messages were being merged
despite having a different subject.  It was because the second one
had an x-me-message-id, and the lookup didn't find it - but the
`cids` list still had the value from the earlier references lookup,
which meant that `i == 3` was true but the message-id was wrong.
> conversations: zero out cids list if no match for message-id

- cassandane/Cassandane/Cyrus/Sieve.pm
- imap/itip_support.c
This fixes a bug noted by neilj and alh where TRANSP in iTIP would overwrite what the recipient has set on the object.
Also reworked a bit of code so this works for all major component types, not just VEVENT
> Strip TRANSP property from incoming iTIP messages

- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
- imap/jmap_calendar.c
Before, the iTIP notification contained all standalone instances having that iCalendar UID.
The PR also includes a code-hygiene commit of the CalendarEvent/set{update} code.
> JMAP Calendars: only send iTIP for new or updated instances

- cassandane/Cassandane/Cyrus/JMAPEmail.pm
- imap/jmap_mail.c
Cyrus already determined an email attachment to be a calendar
attachment if its name ends with the .ICS suffix. But names
encoded as extended MIME parameters were not supported.
> jmap_mail: supported extended filenames for calendar attachments

- cassandane/Cassandane/Cyrus/Sieve.pm
- imap/itip_support.c
When the organizer sent an iTIP request with a new overridden instance the attendee's personal data (alarms, transparency) wasn't being inherited from the master component
> Inherit attendee user data from master when creating iTIP override

- perl/imap/IMAP/Admin.pm
The enclosed commit unbreaks cyradm's info command when talking to version 3.2 servers, which omit the quotes around the mailbox name, and can also send unquoted ```NIL``` as can be seen in the following imtest excerpts:
```l00 getannotation user.test-user-32 "*" "value.shared"
* ANNOTATION user.test-user-32 "/vendor/cmu/cyrus-imapd/squat" ("value.shared" NIL)
* ANNOTATION user.test-user-32 "/vendor/cmu/cyrus-imapd/size" ("value.shared" "6007")
```
```l00 getannotation user.test-user-24 "*" "value.shared"
* ANNOTATION "user.test-user-24" "/vendor/cmu/cyrus-imapd/squat" ("value.shared" "true")
* ANNOTATION "user.test-user-24" "/vendor/cmu/cyrus-imapd/size" ("value.shared" "7006")
```
Sending it upstream, since I think it can help someone else's version migration.
> Adapt annotation parsing regexps to version 3.2

- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
- imap/jmap_calendar.c
Creating events before destroying can lead to iCalendar uid clashes
and bogus EXDATE entries for former standalone instances.
> jmap_calendar: destroy first, then create events in CalendarEvent/set

- cassandane/Cassandane/Cyrus/Replication.pm
- imap/mailbox.h
- imap/mboxlist.c
- imap/mboxname.c
This fixes a crash where mailbox opens correctly, but the name in the mbentry doesn't match the name in the mailbox then when we close the mailbox, we can't find the listitem.
> mboxlist: don't truncate over-long mailbox names

- cassandane/Cassandane/Cyrus/Replication.pm
- cassandane/Cassandane/Cyrus/TestCase.pm
- docsrc/imap/reference/manpages/systemcommands/sync_client.rst
- imap/sync_client.c
- imap/sync_support.c
- imap/sync_support.h
I added the "don't bail on error" code a few months back, but if the error caused the connection to be dropped by the replica, we just keep trying over and over on a dead connection.  Instead, if there's an error we should reconnect before moving along to the next user.
> sync_client: in -A mode, reconnect if error

- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
- imap/http_caldav_sched.c
An invitee may set properties on their copy of the calendar event
overrides, but this only should trigger an iTIP REPLY for this
override if its PARTSTAT differs from the main event.
> http_caldav_sched: only send REPLY for overrides if PARTSTAT differs

- docsrc/imap/download/installation/http/jmap.rst
Updates the "JMAP implementation status" section of the Cyrus docs/website to be current.
Need to cherry-pick this to 3.6 once reviewed and merged.
> docs: freshen up jmap implementation status

- cassandane/Cassandane/Cyrus/JMAPEmail.pm
- imap/jmap_ical.c
Before, the Participant scheduleComment et al were only set for
iTIP REPLY. Now they also are set for COUNTER and REFRESH.
> jmap_ical: set Participant schedule properties for invitee iTIP

- cassandane/Cassandane/Cyrus/Sieve.pm
- imap/itip_support.c
This fixes a bug where `processimip :deletecanceled` would delete the entire resource when just a single instance was canceled
> Properly count how many components are canceled via iTIP

- imap/jmap_api.c
- imap/jmap_api.h
- imap/jmap_mail.c
- imap/jmap_mail.h
- imap/jmap_mailbox.c
- imap/jmap_util.c
- imap/jmap_util.h
Introduce mboxid_byrole hash and use it for jmap_mailbox_find_role()
Note that is might be easier to view this by ignoring whitespace
> JMAP mboxid_byrole hash

- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
- imap/jmap_ical.c
- imap/jmap_ical.h
JMAP spec now says: "If (and only if) the server is the source of the
event (see Section XXX), the “updated” property MUST be set to the
current time by the server whenever an event is created or updated."
> jmap_ical: only server-set "updated" property is source of event

- .travis.yml
While the tag was `cyrus-jessie`, we were building `buster`, so named
the tag appropriatedly.
> ci: Travis to use cyrus-buster instead of cyrus-jessie

- cassandane/Cassandane/Cyrus/Sieve.pm
- imap/itip_support.c
This fixes a crasher diagnosed by alh:
deliver_merge_request first finds the old master event:
for (; comp; comp = icalcomponent_get_next_component(ical, kind)) {
prop =
icalcomponent_get_first_property(comp, ICAL_RECURRENCEID_PROPERTY);
if (prop) recurid = icalproperty_get_value_as_string(prop);
else {
recurid = "";
master = comp;
}
hash_insert(recurid, comp, &comp_table);
}
And pops it into comp_table
In the next loop below:
comp = hash_lookup(recurid, &comp_table);
And
/* Remove component from old object */
icalcomponent_remove_component(ical, comp);
icalcomponent_free(comp);
Which would account for a pvl_head failure on a component (the component has been freed!)
> iTIP deliver request crasher fix

- Makefile.am
- sieve/test.c
When jmap is disabled as compile option, build fails with missing includes and failed linking.
> Fix build with jmap disabled

- cassandane/Cassandane/Cyrus/MurderIMAP.pm
- cassandane/Cassandane/Cyrus/MurderJMAP.pm
Turns out Cassandane::Instance breaks really badly if it tries to start up with murder configuration and there's no "mupdate" binary...
This fix simply annotates the MurderIMAP and MurderJMAP tests with the :need_component_murder feature test, so that if the installed Cyrus was built without --enable-murder, they won't try to run (and no Cassandane::Instances will be instantiated).
> cassandane: murder tests require --enable-murder

- cassandane/Cassandane/Cyrus/JMAPBackup.pm
- imap/jmap_backup.c
This fixes a bug where if the same message is destroyed + restored twice, the $restored flag would be missing on the message after the second restore.
> JMAP Backup/restoreEmail fix

- cassandane/Cassandane/Cyrus/Sieve.pm
- imap/itip_support.c
Organizers MUST send the entire per-attendee view of an event in an iTIP REQUEST.
Therefore, any component NOT in the request MUST be removed from the attendee's existing iCalendar resource.
This PR also fixes existing Cass tests to properly include ALL components in each iTIP REQUEST.
> iTIP REQUEST Fix

- cassandane/Cassandane/Cyrus/Rename.pm
- imap/imapd.c
Need an index_init so index_check() has a protstream.
Fixes a bug in RENAME INBOX INBOX.foo if INBOX hasn't been selected.
This bug was reported by Sentry via an assert()
> RENAME INBOX INBOX.foo fix

- imap/backend.c
- imap/cyr_ls.c
- imap/httpd.c
- imap/jmap_mail.c
- imap/lmtp_sieve.c
- imap/vcard_support.c
- imtest/imtest.c
Some sections in the Cyrus codebase implicitly include assumptions that are only guaranteed on the x86 platform. This patch changes these to work on both x86 and arm64. Also includes fixes that showed up when compiling with clang instead of gcc.
The test system used was
Linux xxx 5.10.0-12-arm64 #1 SMP Debian 5.10.103-1 (2022-03-07) aarch64 GNU/Linux
All cunit and Cassandane tests pass on both platforms.
> Support Cyrus build on Debian arm64

- imap/jmap_mailbox.c
Mailbox/set{create} must return all server-set properties
> Mailbox/set{create} server-set properties

- imap/saslserver.c
prevent crash if initial response is incomplete base64
> SASL initial response fix

- cassandane/Cassandane/Cassini.pm
- cassandane/Cassandane/Test/Cassini.pm
- cassandane/cassandane.ini.example
This changes allows environment variables to take precedence over options specified in cassandane.ini
The main use case I imagine for this is where your Cyrus build wrapper installs Cyrus to a prefix named for the version of the build: in this case, it's annoying to have to edit cassandane.ini to update the `[cyrus default].prefix` path every time you want to test a new build.  With environment variables supported as configuration sources, you could have your build wrapper also scaffold a CASSINI_CYRUS_DEFAULT_PREFIX environment variable into place as it does the install, and let Cassandane use that to find Cyrus.
This adds a new occurrence of the string "9100", so if #3975 lands first I'll need to fix it up, or vice-versa.
I plan to backport this to the release branches, so that if I …
> Cassini: check environment for config overrides

- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
- imap/jmap_ical.c
Before, the 'created' timestamp of a recurrence override was not
allowed to differ from the main event. Now, the created property
can be set for new overrides, but the value must not be changed
later. As for main events, a created timestamp in the future is
clamped to server time.
> jmap_ical: allow creation time of override to differ from main event

- cassandane/Cassandane/Cyrus/Carddav.pm
- imap/http_carddav.c
User ran into an issue where they create a contact via Fastmail UI which writes a v3 vCard having UID with a text value uuid.
emClient tries to update this contact via CardDAV as a v4 vCard having a UID with a urn:uuid (with same uuid).
Cyrus would previously reject this thinking the client is trying to change the UID value, but in actuality the default UID value type for v3 is text and for v4 is URL.
> Allow changing text uuid <-> urn:uuid

- cassandane/Cassandane/Cyrus/TestCase.pm
- cassandane/Cassandane/Instance.pm
- cassandane/Cassandane/Unit/TestPlan.pm
Here's how the cleanup option is supposed to work, according to documentation:
https://github.com/cyrusimap/cyrus-imapd/blob/5b2bf0f12955469241a6c75c5d88f1781377c13c/cassandane/doc/running_tests.txt#L155-L160
> Firstly, it immediately cleans up any files left over in /var/tmp/cass/.
This wasn't working consistently, because I guess at some point we changed how we name the instance directories without changing the regex we use to recognise them at cleanup, and so they would only match (and be cleaned up) by accident.
The first commit here fixes the regex to match how these names are created, so that leftovers from previous runs are correctly removed at startup.  Also adds comments cross-referencing both places that need to be updated next time we change either.
It turns out this is …
> cassandane: fix up "cleanup" bugs

- cassandane/Cassandane/Cyrus/JMAPMailbox.pm
The behaviour changed in #3983 but this has been backported to 3.6
> JMAPMailbox: mailbox_counts behaviour change was 3.6

- cassandane/Cassandane/Cyrus/Delete.pm
- imap/mboxlist.c
Previously, a user could DELETE 'INBOX.#sieve' even though it was hidden from LIST
> IMAP: forbid non-admins to delete non-IMAP mailboxes

- imap/jmap_mail_submission.c
Simple fix, assuming there isn't a better code that we should use
> jmap_mail_submission.c: don't use a non-stancdard error code

- cassandane/Cassandane/Cyrus/Delete.pm
- imap/mboxlist.c
This reverts commit 16889c7d3a44c623a2eeea0d57a2293d02c88aa2.
Turns out we still want to be able to delete non-email mailboxes.
> Revert "IMAP: forbid non-admins to delete non-IMAP mailboxes (#3994)"

- perl/imap/IMAP/Admin.pm
Ken's fix for "cyradm: add LIST-EXTENDED and SPECIAL-USE support to listmailbox command" commit https://github.com/cyrusimap/cyrus-imapd/commit/9a94b5af03c2920f0ef2ea8e208257f559e28cec is needed for correct cyradm behavior in both this and cyrus-imapd-2.5 branches. Hope this couple of no brainer pull requests help in saving some upstream time.
>  Cherry-pick Admin.pm: allow LIST command even when support_referrals is false to 3.0 branch

- perl/imap/IMAP/Admin.pm
Ken's fix  for "cyradm: add LIST-EXTENDED and SPECIAL-USE support to listmailbox command" commit  9a94b5af03c2920f0ef2ea8e208257f559e28cec is needed for correct cyradm behavior in both this and cyrus-imapd-3.0 branches. Hope this couple of no brainer pull requests help in saving some upstream time.
> Cherry-pick Admin.pm: allow LIST command even when support_referrals is false to 2.5 branch

- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
- imap/jmap_calendar.c
This applies to CalendarEvent/get:
The iCalendar iterator state keeps the current iCalendar data
in-memory as long as the IMAP uid of the event resource remains
unchanged. But the iterator state was not reset when the iterator
switches to the next calendar mailbox.
Consequently, if the last IMAP uid of the previously processed calendar
matched the first IMAP uid in the new calendar, then CalendarEvent/get
erroneously returned the contents of the former event with only the
calendarIds and iCalendar uid having the correct value.
This patch also bumps the cache version of the JMAP CalendarEvent
cache, so that any cached bogus events are flushed from it.
> jmap_calendar: reset iCalendar iterator state for each calendar

- cassandane/Cassandane/Cassini.pm
- cassandane/Cassandane/Test/Cassini.pm
- cassandane/cassandane.ini.example
Since 407000f0af, Cassandane has refused to start without a cassandane.ini, since its absence usually meant no configuration had been done, and nothing would work correctly.
Since #3979, Cassandane has been able to read configuration values from environment variables.  But it is still mandatory to have a cassandane.ini file somewhere, even if all your config was set in environment variables.
This PR adds a new option, "cassandane.allow_noinifile", which defaults to 'no'.  If it is set to 'yes', then Cassandane allows itself to start up, even though there is no cassandane.ini file to be found.  This means if you want to set up your entire config in the environment, without needing a cassandane.ini file, you can do so as long as CASSINI_CASSANDANE_ALLOW_NOINIFILE=yes is also in your …
> Cassini: option to permit environment-only config

- cassandane/Cassandane/Cyrus/JMAPEmail.pm
- imap/caldav_alarm.c
Actually check awaken mailbox name against \Snoozed mailbox name (NOT Inbox)
Also test awakening into a destroyed mailbox, which should fallback to Inbox
> Check awaken mbox fix

- cassandane/Cassandane/Cyrus/Sieve.pm
- imap/http_caldav_sched.c
- imap/ical_support.c
- imap/itip_support.c
Google sends iTIP replies for RECURRENCE-IDs in UTC, even if DTSTART has a TZID.
This PR supports these replies by normalizing R-IDs to UTC for comparison and adjusts new R-IDs to the TZID of DTSTART.
> Handle Google iTIP Replies

- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
- imap/caldav_alarm.c
- imap/jmap_ical.c
- imap/jmap_util.c
- imap/jmap_util.h
> caldav_alarm: use same alertId encoding as for Event.alerts

- cassandane/Cassandane/Cyrus/Sieve.pm
- sieve/bc_eval.c
sieve_eval_bc() should not be handling implicit keep. Implicit keep is handled by do_action_list() and do_sieve_error().
This fixes an issue where implicit keep was being done on an included script rather than just the toplevel script
> Sieve include and implicit keep fix

- docsrc/imap/support/feedback-meetings.rst
What it says on the tin, just switching over to the mid-year meeting time
I'll need to cherry-pick this back to all the stable branches too
> docs: update weekly meeting time

- imap/conversations.c
Not dirtying the conversation status prevents the updated unseen counts to be written to disk.
> conversations: mark conversation dirty if unseen counts change

- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
- imap/jmap_calendar.c
Before, an event notification was created for any CalendarEvent/set
regardless if the calendar was shared to any user. This caused
notifications to pile up that no user ever sees before they get
expunged.
> jmap_calendar: only create EventNotification for shared calendars

- cassandane/Cassandane/Cyrus/FastMail.pm
- cassandane/Cassandane/Cyrus/RelocateById.pm
- cassandane/Cassandane/Cyrus/SearchSquat.pm
- imap/relocate_by_id.c
This fixes a few edge case and UX bugs in `relocate_by_id`.  It's probably easiest to review by stepping through a commit at a time, since there's a few not-entirely-related changes to the same code in this one PR.
* It would fail to relocate a user who didn't have a xapian active file (#4005), probably due to the user not having been indexed yet.  I've fixed this by having the mappedfile_open call just create the file if it's missing, which seems to be fine -- the newly created active file is empty, so the subsequent loop over its contents does nothing.  I could instead make it skip the xapian work if it's missing, let me know which you prefer.
* If we're not search_engine=xapian, we definitely won't have a xapian active file, but also shouldn't create one.  So it now checks for …
> relocate_by_id fixes

- cassandane/Cassandane/Cyrus/CaldavAlarm.pm
"Australia/Sydney" is only +11 for half the year.  Replace hardcoded compensation with calculated one.
> CaldavAlarm: fix recurring_absolute_trigger tz offset

- imap/relocate_by_id.c
gcc (Debian 10.2.1-6) 10.2.1 20210110 rightly complains with `-Wall` about 
```
imap/relocate_by_id.c: In function ‘main’:
imap/relocate_by_id.c:114:44: error: implicit conversion from ‘enum imapopt’ to ‘enum enum_value’ [-Werror=enum-conversion]
114 |     enum enum_value config_search_engine = IMAPOPT_ZERO;
|                                            ^~~~~~~~~~~~
cc1: all warnings being treated as errors
```
> relocate_by_id: do not implicitly cast from imapopt to enum value

- imap/caldav_util.c
Don't set etag on a NULL pointer
> caldav_get_validators() crasher fix

- imap/relocate_by_id.c
Fixes a typo where an enum was zero-initialised using the wrong enum's constant.  Newer compilers than mine apparently have a warning about it (or an error with -Werror).
Replaces previous fix from #4028, which applied a function call to the typo to produce a correct value.  This fix just directly uses the correct value in the first place.
This should be good, but please compile check it, since my compiler couldn't see the original problem, so I can't definitively prove it's "fixed"
> relocate_by_id: fix typo in initialisation

- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
- imap/http_caldav_sched.c
Before, when determining if a REQUEST should be sent for a changed
iCalendar property, only the value of the old and new properties
were compared. Now also their parameters are included in comparison.
> http_caldav_sched: properties only are equal if parameters match

- lib/util.c
> util: handle null and empty paths in cyrus_mkdir

- cassandane/Cassandane/Cyrus/JMAPEmail.pm
- imap/jmap_mail.c
The code didn't take delayed delete for mailboxes into account.
> jmap_mail: do not create or move emails in deleted mailboxes

- imap/jmap_ical.c
> jmap_ical.c remove useless assignments

- imap/http_tzdist.c
> http_tzdist.c: remove useless assignments

- cassandane/Cassandane/Cyrus/Sieve.pm
- sieve/bc_eval.c
Reverts cyrusimap/cyrus-imapd#3995
Although this PR fixed the issue with "include", it broke the why that IMAP flags were handled during implicit keep.
A new fix is forthcoming.
> Revert "Sieve include and implicit keep fix"

- imap/promstatsd.c
Found by @dilyanpalauzov using Clang's static analyser: if a stats file is successfully `mappedfile_open()`d, but then the subsequent `mappedfile_readlock()` failed, we would end up trying to read uninitialised memory and probably crash.
I'm not sure what it even means if `mappedfile_open()` succeeds and `mappedfile_readlock()` fails (though the `mappedfile_readlock()` will log an IOERROR explaining why)...
With this fix, if it ever happens, we'll just ignore that file this time, rather than crashing.  The resultant metrics report will be under-counted by whatever counts were in that file, but it should self-correct on the next update, assuming the cause was ephemeral.
Fixes #4054
> promstatsd: can't accumulate stats from files that couldn't be locked

- imap/mboxevent.c
This fixes a double free issue
> mboxevent.c: string params steal the string

- Makefile.am
- configure.ac
- imap/mbpath.c
Part of #4072 
This fixes a bare "./configure" (with no arguments) build for the 3.6 branch.  I'm opening the PR against master, since master will also need the same fixes (and then some).  Once it's approved/merged, I'll backport it to 3.6.
This _does not_ completely fix a bare "./configure" build of the master branch.  See linked issue for details.
> fix 3.6 bare "./configure" build

- imap/http_jwt.c
The WARNING section of the EVP_PKEY_base_id manpage in OpenSSL 3 says
that EVP_PKEY_base_id is "only reliable with EVP_PKEYs that have been
assigned an internal key with EVP_PKEY_assign_*", and the usage here of
base_id seems to be without EVP_PKEY_assign usage.
This same warning points to EVP_PKEY_is_a, which seems fine for this
purpose but is part of OpenSSL 3.
> http_jwt: OpenSSL 3 compat EVP_PKEY_base_id

- imap/jmap_api.c
- imap/xapian_wrap.cpp
Fixes two memory leaks that @dilyanpalauzov found, one in the Xapian wrapper, one in the JMAP result references handling code.
> Fix memory leaks issues 4060 4070

- imap/httpd.c
- imap/message.c
- imap/mupdate.c
- imap/nntpd.c
- imap/quota.c
- imap/tls.c
- lib/prot.c
or, as the Clang Static Analyzer calls them, “Dead nested assignments”.
> Remove useless assignments

- cassandane/Cassandane/Cyrus/JMAPEmail.pm
- imap/jmap_mail.c
- imap/search_expr.c
- imap/search_expr.h
Before, a "$seen" keyword filter in Email/query only inspected the
seen flag per mailbox. This contradicts the semantics of the
"$seen" keyword for JMAP Emails, where an email only is seen if
all of its copies in any mailbox have the seen flag set.
Determining the seen state of an email potentially is costly,
as it may require to open each mailbox where a copy of the message
is stored in. To keep the incurred runtime costs low, the patch
uses a query-scoped cache of seen.db entries. At worst, each mailbox
is opened twice during the whole query, doubling the previous
worst time runtime cost of opening each mailbox once.
> jmap_mail: implement JMAP "$seen" keyword semantics in Email/query

- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
- imap/jmap_calendar.c
- imap/jmap_ical.c
- imap/jmap_ical.h
Before, the event timezones got rewritten to IANA timezones
even if the client did only update non-time related properties.
> jmap_calendar: preserve custom timezones in CalendarEvent/set

- cassandane/vg.supp
Tested on GNU Linux Debian 11.3
> cassandane: suppress libnss Valgrind errors on aarch64

- cassandane/Cassandane/Instance.pm
- cassandane/Cassandane/PortManager.pm
Previously, if Cassandane's fake smtp service failed to start for any reason (e.g. the assigned port was already in use), we wouldn't actually notice this.  We would naively record the port we tried to use as the smtp port, and then tests which required the smtp service would connect to whatever was there... with interesting results depending on what, if anything, was listening.
This PR makes sure the smtpd actually starts, and bails out the whole test if it didn't.
There's a couple of other tweaks to make sure that bailing out during `start()` is safe -- without them, Cassandane's internal worker pool state gets confused, and it can't shut itself down properly.
> cassandane: verify that smtp service actually started

- cunit/mboxname.testc
- imap/mboxname.c
Precursor to having tests for #4057 
The fixes in here mboxname.c  are to make the unit tests pass (multiple types of mailboxes all use MBTYPE_COLLECTION), but will be overwritten by #4057
> mboxname.testc: added mboxname_isXXX() tests

- imap/imapd.c
- imap/mboxname.c
- imap/mboxname.h
Consolidates code and improves performance of mboxname_isnonimapmailbox() and mboxname_isnondeliverymailbox() by not creating/destroying an mbname_t for every mailbox type that they check.
Also prohibits IMAP DELETEing toplevel non-IMAP mailboxes (e.g. #sieve, #calendars, #jmap)
Unit tests will be introduced by #4090
> mboxname_isXXXmailbox() rewrite

- cassandane/Cassandane/Cyrus/JMAPEmailSubmission.pm
These tests failed because Cyrus was configured to reject the
Cyrus JMAP extensions capabilites.
> JMAPEmailSubmissions: use JMAP extensions for tests that require it

- imap/caldav_alarm.c
- imap/smtpclient.c
- imap/smtpclient.h
Callers assume that the string returned by smtpclient_get_resp_text
actually contains a descriptive response, but the returned string
could have been empty.
Requires https://github.com/cyrusimap/cyrus-imapd/pull/4097 for proper testing.
> smtpclient: return NULL instead empty SMTP response text

- imap/caldav_alarm.c
- imap/jmap_mail_submission.c
Recent change f5258901cb66e4b0084da9035309630ff26ca17d introduced a NULL-pointer read which now is fixed. Also, both @ksmurchison and @dilyanpalauzov noticed an unnecessary assignment during code review, so let's just remove it.
> JMAP Mail Submission: sanitize recent change to smtpclient_get_resp_text

- cassandane/Cassandane/Cyrus/JMAPEmail.pm
- imap/jmap_mail.c
Switching from uncollapsed to collapsed email queries does not
invalidate the query cache, but may have left the cache state
for collapsed queries uninitialized.
> jmap_mail: initialize collapsed cache if uncollapsed already is set

- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
- imap/caldav_db.c
The recently added jscal_objs table stores calendar event metadata
for both standalone recurrence instances and main events. Up until
now, for both types of events a change to an existing entry was
detected by comparing the guid of the old and new iCalendar string
of the respective VEVENT component. This introduced a bug when
the main VEVENT component in VCALENDAR remains octet-equal to the
old entry, and only its recurrence overrides got changed.
This patch fixes that by comparing recurrence override by the guid
of the respective VEVENT, but comparing main events by the guid of
the whole VCALENDAR component.
> caldav_db: compare guid of VCALENDAR to detect main event changes

- imap/http_dav.c
Fixes a crasher for a DAV:multiget request for /dav/addressbooks
> http_dav.c: can't multiget from a non-mailbox (e.g., /dav/addressbooks/)

- cassandane/Cassandane/Cyrus/CyrusDB.pm
- cassandane/Cassandane/Cyrus/Reconstruct.pm
- cassandane/Cassandane/Instance.pm
- cassandane/Cyrus/HeaderFile.pm
- imap/ctl_cyrusdb.c
- imap/mailbox.c
- imap/reconstruct.c
This improves the safety of upgrades from 3.4 to 3.6+, by making 3.4 fastidious about keeping uniqueid present and up to date (even though 3.4 itself doesn't strictly need it, unlike 3.6+).
Reviewers: please pay close attention to the locking and ordering of the mbentry/mailbox updates.  I think I got it correct, but I'm not totally confident.
* `ctl_cyrusdb -r` will now ensure every mbentry has a uniqueid field at startup.  It will use the one from the cyrus.header if the cyrus.header has one, otherwise it will generate a new uniqueid and save it to both
* `reconstruct` will do the same thing.  This is important for handling the case where an old uniqueid-less mailbox has been restored from backup (though it would also be taken care of by `ctl_cyrusdb -r` at next restart, this can avoid …
> 3.4: ensure mbentries have uniqueids

- cassandane/Cassandane/Cyrus/Carddav.pm
- imap/http_dav.c
Non-get-able hrefs were being reported as the target URL o fthe REPORT method and not the actual href in the body of the multiget
> http_dav.c: properly report bad multiget hrefs

- imap/mboxlist.c
Fixes an edge case in the intermediate mailbox update code, where the parent of the intermediate can not be found.
> mboxlist: do not attempt to read partition of inexistent parent

- imap/imapd.c
This gives a more machine-readable response when we fail due to too many copies of the same message
> Use [LIMIT] response code for IMAP APPEND where appropriate

- cassandane/Cassandane/Cyrus/Sieve.pm
- imap/itip_support.c
- imap/lmtp_sieve.c
Fixes a problem that we have seen in the wild with a CANCEL message being redirected back to the ORGANIZER
> processimip: ignore iTIP send from and to the same address

- cassandane/Cassandane/Cyrus/SearchFuzzy.pm
- imap/search_xapian.c
The reindex code still expected legacy version 1 keys in cyrus.indexed.db. It consequently failed for the current version 2 keys.
> search_xapian: handle version 2 mailbox keys in reindex_mb

- cassandane/Cassandane/Cyrus/Sieve.pm
- imap/caldav_db.c
- imap/jmap_calendar.c
This blindly removes all iTIP messages having the matching iCalendar UID.  The thought is that if the user updates the calendar via JMAP they probably don't need their CalDAV client to see any of the iTIP for that UID, even if they correspond to single instances.
An alternative to deleting these on CalendarEvent/set would be to just set an expiration time on the Scheudling Inbox (e.g. 1-2 weeks)
> Remove iTIP messages on CalendarEvent/set{update,destroy}

- imap/jcal.c
- imap/xcal.c
Latest libical switched from using floats to text strings for GEO property
> Support iCal GEO property as text

- imap/mailbox.c
- imap/message.c
- lib/assert.h
This redefines our `assert()` macro to evaluate as an expression, rather than as a statement.  This makes it syntactically compatible with the C standard one, which means sub-components we link in that expect to have a C standard assert() available do not choke on ours being different.  As far as I know, this is mostly just perl, when building our XS modules.
While in there, I cleaned up an old `#ifdef __STDC__` check, whose else path would have failed to compile anyway, had it ever been hit.
Also had to fix a bunch of miscellaneous lines without semicolons, which the bad macro definition had previously allowed. 😅 
Fixes #4123, I think -- will need someone with perl 5.36 to test and confirm this please.
Once merged, this will be backported to 3.6 and 3.4.
> fix assert() definition

- backup/lcb_append.c
- backup/lcb_internal.h
- backup/lcb_verify.c
- imap/jmap_calendar.c
- imap/tls.c
- imtest/imtest.c
- lib/charset.c
- lib/md5.h
- lib/xsha1.c
- lib/xsha1.h
This PR allows Cyrus to compile with OpenSSL 3.0.
Note that it really only fixes the issues with the MD5 and SHA1 APIs , by using the newer EVP APIs.
The issues with the TLS APIs have been largely avoided at this point by simply commenting out the code that uses legacy APIs.  Someone with a better understanding of DH params and elliptic curves (and the new APIs) will need to fix the rest.
@rsto @elliefm This (rewritten) code compiles both on my laptop with OpenSSL 3.0.2 and my desktop which still has OpenSSL 1.1.1n.  Please try this on your platforms.
> OpenSSL 3.0 fixes

- imap/ctl_cyrusdb.c
- imap/mailbox.c
- imap/mboxlist.c
- imap/mboxlist.h
uniqueid is not one of the fields synchronised by mupdate, which I think means the mbentries for remote mailboxes (i.e. on murder frontends) won't and can't have uniqueids.
This PR builds upon the work from #4100, such that it won't complain about nor try to "fix" missing uniqueids for remote mailboxes.
This PR is for 3.4 only.  I think master/3.6 will need a similar shape of change in `mboxlist.c:_foreach_cb()` following #4096, but I have not thought about the ramifications there yet.
No tests (yet?), cause I haven't figured out how I would prove to myself that it works.  Am open to ideas!
> no uniqueid fix for murder frontends (3.4)

- imap/jmap_contact.c
Previous versions of Contact/get used the dav.db object cache to read
and persist Contact objects. This changed when per-user properties
got added to the Contact object type. While it looks worthwhile to
start using the object cache again, the current dead code breaks
the build with technically true but practically unmet uninitialized
variable warnings.
Fixes #4147
> jmap_contact: remove dead code from getcontacts_cb

- imap/jmap_api.c
Signed-off-by: qyb <qiuyingbo@gmail.com>
more info: https://cyrus.topicbox.com/groups/info/T19bc8d3e0b073fec-M28948f2e1ef90f0c646d8c6f/cannot-get-shared-mailbox-info-in-jmap-session
> use the correct pattern when altnamespace is on

- cassandane/tiny-tests/JMAPCalendars/calendarevent-query-fastpath-position
- imap/jmap_calendar.c
The conditional that sliced the query window by position was backwards,
so any positive position value returned an empty window.
> jmap_calendar: fix position argument for CalendarEvent/query fastpath

- imap/jmap_sieve.c
- imap/lmtp_sieve.c
- imap/sievedir.c
- imap/sievedir.h
- timsieved/actions.c
We had a case where dav_reconstruct tried to create a bytecode file in root
> Sieve: protect against missing/invalid sievedir

- imap/quota.c
The `-n` flag for `quota` was implemented and documented in 23d6ef9, but not actually accepted.
Actual result:
```
$ cyrus/sbin/quota -f -n -q
cyrus/sbin/quota: illegal option -- n
usage: quota [-C <alt_config>] [-d <domain>] [-f] [-q] [-J] [-n] [-u] [mailbox-spec]...
```
Expected result:
```
$ cyrus/sbin/quota -f -n -q
user.test: MESSAGE usage was 0, now 189
…
```
Tested on macOS 12.4.
> quota: accept -n flag

- sieve/tree.c
This plugs the leak exposed by test_imip_reply_no_organizer
> tree.c: don't leak log text

- imap/ical_support.c
*Should* fix a crasher seen in production
> ical_support.c: don't dereference a NULL string

- imap/http_admin.c
- imap/http_applepush.c
- imap/http_caldav.c
- imap/http_carddav.c
- imap/http_cgi.c
- imap/http_dav.c
- imap/http_dav_sharing.c
- imap/http_dblookup.c
- imap/http_ischedule.c
- imap/http_jmap.c
- imap/http_prometheus.c
- imap/http_rss.c
- imap/http_tzdist.c
- imap/http_webdav.c
- imap/httpd.c
This was causing TRACE, and more importantly, *DAV UNLOCK to fail
> HTTP: add missing SEARCH method processors to all namespaces

- imap/mailbox.c
This fixes a crasher where an incorrectly low last_uid could never be
fixed because the append attempt would fail to update the value.
> reconstruct: update last_uid before trying to append if needed

- imap/ctl_zoneinfo.c
This avoids a clang-warning, since readdir() has a `nonnull` attribute.
Closes https://github.com/cyrusimap/cyrus-imapd/issues/4148
> ctl_zoneinfo.c: avoid calling readdir(NULL)

- perl/sieve/scripts/sieveshell.pl
Actual result:
```
% sieveshell localhost
connecting to localhost
Please enter your password: 
> quit
> list
segmentation fault
```
Expected result:
```
% sieveshell localhost
connecting to localhost
Please enter your password: 
> quit
% 
```
sieveshell should exit after receiving a `quit` command, because any further commands will segfault because sieve_logout() invalidates the object.
The problem appeared in #3281 and was already observed earlier in [Debian Bug #962362](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962362) when that patch was still in Debian and not upstreamed yet. The fix is from there, and I am not familiar enough with Perl to judge whether it is the correct fix, but it appears to work.
> sieveshell segfaults after quit command

- changes/next/mbexamine-error-handling
- imap/mbexamine.c
This is part of some work that @rjbs requested.   I'd like to get it merged now because otherwise it'll start to conflict with the long-options work that I'm also doing.
This:
* reports any errors that occur on stderr
* treats invocations that don't find any work to do (i.e. when there are no matches for the provided mailbox pattern) as failures rather than successes
We don't have any existing tests for mbexamine, and I haven't bothered to write any.  I expect this interface to change further when we do the big tool audit/update, so in my mind tests can wait.  Let me know if you disagree!
> mbexamine: tighten up error handling

- imap/mailbox.c
- imap/mboxlist.c
Thinking that this might solve the issue of conv.db being created by name rather than by uuid when replicating a new user INBOX
> Reserve mailbox name (mbentry) before mailbox creation

- cassandane/Cassandane/Cyrus/CyrusDB.pm
- cassandane/Cassandane/Instance.pm
- imap/ctl_cyrusdb.c
- imap/mailbox.c
- imap/mboxlist.c
- imap/mboxlist.h
- imap/mbpath.c
- perl/imap/Cyrus/DList.pm
- perl/imap/Cyrus/HeaderFile.pm
This is a partial forward port of work I did previously for 3.4, as #4100 and #4139, and is part of the solution to #4035 
It contains the `ctl_cyrusdb -r` ("recover") updates, and everything needed to support those updates, and their tests; but it does not contain the `reconstruct` updates, which are more complex and Ken will be pursuing separately.
The updates allow `ctl_cyrusdb -r` to fix up mailboxes.db records for legacy mailboxes (i.e. stored on disk by name) that are missing a uniqueid.  If the mailbox header contains a uniqueid, that value is used; if the header doesn't have one either, then a new one is generated and set in both places.
It does _not_ recover from:
* mbentry and header have uniqueids that differ
* mbentry has a uniqueid but the header does not
because detecting …
> ctl_cyrusdb -r ("recover") uniqueid safety

- cunit/annotate.testc
This fixes a bunch of annotate.testc failures introduced in #4180
I don't think this is the _best_ fix, but it is _a_ fix.  A better fix might be for this to use `mboxlist_createmailbox()` to create the mailboxes it wants, rather than using `mailbox_create()` and `mboxlist_updatelock()` directly -- but maybe calling the deeper APIs directly was a deliberate choice.
> annotate.testc: mailbox_create() caller must supply uniqueid

- cassandane/Cassandane/Cassini.pm
- cassandane/cassandane.ini.dockertests
- docsrc/imap/developer/developer-testing.rst
Fixes a bug where if a parameter in the `[config]` section of cassandane.ini was specified more than once, Cassandane would produce junk imapd.conf files, and then all tests would error out due to master aborting.
Now, if a parameter is specified multiple times, the last value read takes precedence, and a warning is logged saying so.  In verbose mode, all values for the offending item are logged.
In practice, this change only affects the `[config]` section; all other cassandane.ini parameters are read individually, and will continue doing whatever they already did.
> cassandane.ini: don't choke on repeated params

- cassandane/Cassandane/Cyrus/JMAPMailbox.pm
- imap/jmap_mailbox.c
We ignore Notes in /get but forgot to also ignore it in /changes
> Mailbox/changes should ignore Notes mailbox

- cassandane/Cassandane/Cyrus/Quota.pm
- imap/annotate.c
This PR moves the "userrawquota" field from being a private server metadata item to a shared metadata item on the quotaroot, which means that the admin user can view it for any user rather than having to log in as the individual user.
> Move rawquota

- imap/jmap_ical.c
This fixes a regression that got introduced by 59ab8120175a6f3.
Before, the managed attachment resource name matched the blobId
because the JMAP upload handler already set it on the JMAP blob.
Now that the JMAP upload ignores the Content-Disposition header
during upload, it must be set when the attachment is created as
a copy of the JMAP blob.
The JMAPCalendars.calendarevent_set_linkblobid test asserts
that the regression got fixed.
> jmap_ical: set managed attachment resource to Link blobId

- cassandane/Cassandane/Cyrus/JMAPMailbox.pm
- cassandane/tiny-tests/JMAPCalendars/calendarevent-changes-issue2558
- cassandane/tiny-tests/JMAPEmail/email-changes
- imap/jmap_api.c
Before, an invalid sinceState argument was rejected with an
invalidArguments error.
> jmap_api: reject invalid sinceState with cannotCalculateChanges error

- cassandane/Cassandane/Cyrus/List.pm
- imap/imapd.c
If we don't allow children to be created, then the mailbox should have \Noinferiors
> 'special_nochildren' mailboxes should have \Noinferiors attribute

- docsrc/imap/download/upgrade.rst
This updates the upgrade documentation for 3.6 to explain that one should already be running 3.2.10 or 3.4.4 before attempting to upgrade to 3.6.
I would usually just commit this straight to the 3.6 branch, but I'd like some people other than myself to read it and let me know whether it makes sense, or shake out points of confusion or ambiguity, so here's a PR.  Please have a read, and let me know what you think.
(Every future new version will also require an upgrade stopover at 3.2.10/3.4.4, so once we're happy with the wording and this PR is merged, I'll make similar changes on master so they're there ready for 3.8.)
> docs: upgrading to 3.6 requires 3.2.10 or 3.4.4 first

- cassandane/Cassandane/Cyrus/JMAPMailbox.pm
- imap/jmap_mailbox.c
Recent patch db341726d3432b9bc230c803d256bef32e95aea1 made
Mailbox/changes ignore the Notes folder, but subfolders
of Notes showed up in Mailbox/query and get.
> jmap_mailbox: ignore Notes folder and subfolders

- imap/http_caldav.c
Per RFC 5545, Section 3.8.2.5, DURATION > 0, but DURATION == 0 occurs frequently enough in the wild for us to allow it
> Allow zero DURATION (P0D and PT0S)

- cassandane/Cassandane/Cyrus/JMAPContacts.pm
- imap/jmap_contact.c
A group VCARD may contain duplicate members and returning these
in contactIds may cause clients to load the same contact multiple
times. This deduplicates the ids in ContactGroup/get and similarly
deduplicates entries in otherAccountContactIds.
> jmap_contact: deduplicate ContactGroup.contactIds

- cassandane/Cassandane/Cyrus/Metadata.pm
Updates a test (Metadata.shared) that should have been updated by #4203, but was missed
> Metadata: userrawquota is now a shared annotation

- imap/http_caldav_sched.c
- imap/http_jmap.c
- imap/jcal.c
- imap/xcal.c
Backport from master to cyrus-imap-3.6:
* 02393e9456d7d1e5ace89f — https://github.com/cyrusimap/cyrus-imapd/issues/4044
* ac63b9846db220 — https://github.com/cyrusimap/cyrus-imapd/issues/4046
* 6c83c13a3ffc73 — jcal.c, xcal.c: support iCal GEO property as text
> 3.6: use after free

- cassandane/Cassandane/Util/Log.pm
When I'm writing and/or debugging Cassandane tests, I find myself writing temporary output like this all the time:
```
xlog "XXX the whatsit is: " . Dumper $whatsit;
```
Though if I'm debugging, I'm also usually running with high verbosity, which is real noisy, so these lines are often still pretty hard to see.
I made this quick patch for xlog, such that logged lines starting with "XXX" are highlighted in colour, and it was an immediate improvement, so here it is for y'all to benefit from too. :)
> Cassandane::Util::Log: highlight xlogs starting with XXX

- lib/ptrarray.c
This fixes a potential issue highlighted by @dilyanpalauzov in
https://github.com/cyrusimap/cyrus-imapd/pull/4206
ptrarray_fini calls memset to set the ptrarray data to zero,
irrespective if it points to NULL or an allocated buffer.
This is safe under normal conditions, as a ptrarray with null
data is expected to have a member count. It is unsafe if
this condition does not hold.
This patch removes the call to memset altogether, similar to
how fini is implemented for strarray.
> ptrarray: do not memset buffer that gets free()d anyway

- imtest/imtest.c
cherry-pick c512f481cc940b74b7ac41
This backports a fix for a memory leak.
> 3.6 imtest: memory leak

- imap/imapd.c
I think this was a mistake added in bf28aa3fb6 when replacing
IMAPOPT_APPEND_MAXSIZE.
> imap/imapd.c: IMAPOPT_MAXMESSAGESIZE is bytes, not kilobytes

- cassandane/tiny-tests/JMAPCalendars/calendarevent-encode-imip-uri
- cassandane/tiny-tests/JMAPCalendars/calendarevent-set-destroy-itip
- cassandane/tiny-tests/JMAPCalendars/calendarevent-set-standalone-itip
- cassandane/tiny-tests/JMAPCalendars/itip-request-tzid-change
- cassandane/tiny-tests/JMAPCalendars/itip-rsvp-organizer-change
- imap/http_caldav_sched.c
This extends `imip_send()` to include the JMAP id (as `id:`) and ITIP method (as `method:`) fields in IMIP notifications.  I did this by adding these as individual new fields, though...
Michael said:
> Actually, it would be really useful to just have the same thing we have when we include `calendarEvents` in Email/get, which comes from `jmap_calendar_events_from_msg`.
I had a look at this as an option, and both things end up in `jmapical_tojmap_all()` anyway.  So it's not clear to me why `jmap_calendar_events_from_msg()` would be producing additional fields beyond what `imip_send()` already was?
I'd like to add some tests, I'm concerned that recurid seems to always be NULL in what I've looked at so far... but maybe that's expected for IMIP, I dunno.  I'd appreciate some guidance in …
> extend itip message format

- cassandane/tiny-tests/JMAPCalendars/calendarevent-get-empty-apple-location
- imap/jmap_ical.c
Depending on how libical is compiled, it may return NULL for empty values. The JSCalendar converter expected
X-APPLE-STRUCTURED-LOCATION to be a non-empty geo: URI value.
> jmap_ical: handle empty X-APPLE location property
