- cassandane/Cassandane/Cyrus/JMAPCore.pm
- imap/http_caldav.c
- imap/http_carddav.c
- imap/http_webdav.c
- imap/httpd.c
- imap/httpd.h
(this can occur during a user rename if the old auth creds still exist)
This issue has been seen in production and a 503 makes more sense than 500
> HTTP: return 503 if a user autheticates but doesn't have an INBOX

- cassandane/tiny-tests/JMAPCalendars/calendarevent-get-emptyprops
- imap/jmap_ical.c
Similar to 63d0f7ad271353c5c710dd912c4467dd37e09aeb this gracefully handles libical returning NULL for empty TEXT property values.
> jmap_ical: handle empty iCalendar TEXT properties

- cassandane/Cassandane/Cyrus/JMAPEmail.pm
- cunit/conversations.testc
- imap/conversations.c
- imap/conversations.h
- imap/jmap_mail.c
A MIME message uploaded to the `#jmap` and then imported using Email/import still contributed to the $seen counts of the imported email. This could lead to false results in Email queries that made use of the `hasKeyword: $seen` or `xxxInThreadHaveKeyword: $seen` filter criteria.
> JMAP Email/query must ignore $seen keyword for JMAP blobs

- cassandane/tiny-tests/JMAPEmail/email-query-empty-filter-conds
- imap/jmap_api.c
- imap/jmap_mail.c
- imap/jmap_mail_query.c
- imap/jmap_mail_query_parse.c
- imap/search_expr.c
This is a slightly modified version of https://github.com/cyrusimap/cyrus-imapd/pull/4121 which got submitted by @mildred. In contrast to the original pull request it more leniently handles DNF subtrees that double during search expression normalization. In addition, it also aligns evaluation of empty conditions and operator nodes in the Sieve and JMAP handler implementations.
Passes the full Cassandane suite.
> search: improve DNF normalization complexity checks

- imap/index.c
Following the issue #3240, when using \Seen flag with shared seen disable, modseq isn't updated so store command never return the fetch flags. So we force the update of modseq value by calling index_rewrite_record function
This is probably unoptimized patch as we can unify the call of index_rewrite_record with others functions
> Fixing issue #3240 Seen/Unseen Flag not working correctly if sharedseen of a shared mailbox is not set to true

- backup/lcb_compact.c
- cassandane/Cassandane/Cyrus/FastMail.pm
- cunit/libconfig.testc
- doc/legacy/overview.html
- docsrc/imap/concepts/overview_and_concepts.rst
- docsrc/imap/reference/admin/quotas.rst
- imap/autocreate.c
- imap/carddav_db.c
- imap/global.c
- imap/http_caldav.c
- imap/http_caldav_sched.c
- imap/http_carddav.c
- imap/http_client.c
- imap/http_ischedule.c
- imap/imapd.c
- imap/jmap_api.h
- imap/jmap_calendar.c
- imap/jmap_core.c
- imap/jmap_mail.c
- imap/jmap_sieve.c
- imap/lmtpd.c
- imap/lmtpengine.c
- imap/mailbox.c
- imap/mboxevent.c
- lib/imapoptions
- lib/libconfig.c
- lib/libconfig.h
- timsieved/lex.c
- tools/config2header
**Note for reviewers**: 
This will be a nuisance to review, because it's lots of small and repetitive changes that need to be correct, and the compiler can't notice semantic mistakes.  I strongly suggest stepping through one commit at a time.  Please pay particular attention to:
* Do the documentation updates match the code updates?  e.g. if the documentation says "the default unit is kibibytes", does the `config_getbytesize()` call specify `'K'`?
* Did I get the magnitude conversions correct?  Lots of these options used to be measured in KB.  Some of them used KB in the config file only, but multiplied it to bytes internally; some used KB internally too.  They're all bytes internally now.  Quota is measured in KB, so the quota-related options now need to convert _backwards_ from bytes, …
> imapd.conf BYTESIZE smart type

- imap/search_xapian.c
This should hopefully fix the remaining deadlock error I'm seeing in the logs!  Basically, it tries to lock conversations AFTER the xapianactive file is locked, but that reverses the ordering from when we do searches - so instead, always take the lock if we're XAPINDEXed.  Which should hopefully mean that is_indexed doesn't deadlock.  Yay.
[ not to be merged:  this is exploratory work ]
> squatter: lock conversations db in mailbox_begin to fix lock ordering

- imap/jmap_mail.c
This trivially fixes the build for clang version 13.
> jmap_mail: fix tautological "else if" breaking clang builds

- cassandane/tiny-tests/JMAPEmail/email-get-calendarevents
- cassandane/tiny-tests/JMAPEmail/email-get-calendarevents-one-uid-only
- imap/jmap_calendar.c
- imap/jmap_calendar.h
- imap/jmap_mail.c
The purpose of the Email.calendarEvents property is to extract calendar event invitations from the email attachments. If an attached VCALENDAR instead contains calendar components with differing iCalendar UIDs, then this should be handled like a regular attachment and calendarEvents be empty.
> jmap_email: return empty calendarEvents for multiple UIDs

- imap/jmap_calendar.c
because buf_release() calls buf_free().
> jmap_calendar.c: avoid buf_free() after buf_release()

- changes/next/cyr_expire_no_double_newlines
- imap/cyr_expire.c
Format strings for verbosep included a trailing newline character, but verbosep also emits a newline character after the format string got printed. This patch removes the newline characters from format string, so that no empty lines are emitted between verbose log lines.
> cyr_expire: do not emit double newlines for verbose output

- cassandane/tiny-tests/JMAPEmail/email-get-preview-html
- imap/jmap_mail.c
This only affects installations that do not set email preview with external annotators.
HTML content could go verbatim into a supposedly plain text preview. Now, it only gets returned as HTML text which in turn gets rewritten into plain text for preview generation.
> jmap_mail: do not add html body content in plain text preview

- imap/caldav_util.c
- imap/http_caldav.c
- imap/http_caldav_sched.c
- imap/ical_support.c
- imap/itip_support.c
https://github.com/libical/libical/issues/585
Backport of https://github.com/cyrusimap/cyrus-imapd/pull/4278
> 3.6: Last parameter of icalcomponent_vanew() must be NULL, not 0

- imap/http_caldav.c
https://github.com/libical/libical/issues/585
Backport of https://github.com/cyrusimap/cyrus-imapd/pull/4278
> 2.5: Last parameter of icalcomponent_vanew() must be NULL, not 0

- cassandane/testrunner.pl
If you've forgotten to run "make" in the cassandane directory before running testrunner.pl, a bunch of tests will fail due to binary components being missing -- but you won't know that until the run finishes and you get the report.
This makes testrunner.pl look for these files at startup and exit right away with an error message if they're missing, instead of running the tests and wasting twenty minutes
You can test this by running `make -C utils clean` in the cassandane directory to remove the built components, and then run testrunner.pl as usual to see the new error messages.
Fixes #4109
Once reviewed/approved/merged, I'll cherry pick this to the older branches too.
> testrunner.pl: exit early if binary components missing

- cassandane/Cassandane/Cyrus/Flags.pm
- imap/index.c
This fixes https://github.com/cyrusimap/cyrus-imapd/issues/3240 properly for new Cyrus
> index: track changes for modseq bump when setting seen on shared folders

- imap/vcard_support.c
Fixes a bug where encoding wasn't being parsed and we wouldn't output any data
> vcard_support.c: fix parsing v4 data: URIs during v3 conversion

- .github/workflows/main.yml
The build process depends on having access to the release tags to determine the version, and many of our tests need to examine the cyrus version, and will fail in annoying ways if the version is missing or incorrect.  When github actions run from a fork, rather than the main repository, our release tags are probably missing, and so a bunch of tests fail (unless the fork maintainer bothers to keep their fork updated with our release tags for some reason, but they shouldn't have to).
This updates it to fetch git tags directly from the cyrusimap/cyrus-imapd repository, even if the action is running from a fork.
It also updates the multiline run commands to use "shell: bash", which allegedly causes them to be run in bash's fast-fail mode (`set -eo pipefail`).  This should mean that if any …
> github actions: get tags from upstream

- imap/rfc822_header.c
- tools/compile_st.pl
We version control the output file from this command (as `imap/rfc822_header.c`), and having the name of the tempfile used to generate it embedded in the output made it show up as different every time it was regenerated, even though usually the only difference was the name of the tempfile.
Now it will only show up as different when something interesting changed.
The file in question is only regenerated in maintainer mode, so you probably don't notice it unless you're doing releases, but it's been annoying me for years...
> tools/compile_st.pl: strip 'Command-line' from gperf output

- cassandane/Cassandane/Cyrus/Caldav.pm
- cunit/charset.testc
- lib/charset.c
This fixes an issue where embedded newlines in the SUMMARY property would cause us to create a Subject header which would prematurely signal the end of the header section of our constructed message.  This resulted in our message parser never reaching the Content-Disposition header field, thereby NOT parsing our CalDAV resource name and subsequently violating the resource NOT NULL constraint in the ical_objs SQL table.
> Force MIME-encode SUMMARY when creating Subject header field

- imap/mailbox.c
- imap/mailbox.h
For dav_reconstruct, iterate from most recent to least recent index records so that if we find an index record with a lower UID than the DAV DB record for that object (the object has been replaced), we can remove the "stale" index record.
The question is, do we want to do this for normal DAV updates or just on reconstruct?  newrecord->uid < cdara->dav.imap_uid is probably always bogus.
> mailbox.c: remove "stale" index records when reconstructing DAV records

- imap/mailbox.c
#4253 changed mailbox_iter_inti() to initialize iter->recno to 1 rather than zero, but the same wasn't done for mailbox_iter_startuid()
This was causing messages to not get Xapian indexed (amongst other possible bugs) and leading to Cassandane failures
> mailbox_iter_startuid() needs to initialize recno to 1 rather than 0 (zero)

- imap/caldav_alarm.c
This fixes a crasher found in testing
> caldav_alarm.c: don't crash if ATTENDEE doesn't have a PARTSTAT

- cassandane/Cassandane/Cyrus/Carddav.pm
- imap/http_carddav.c
This should fix an issue seen with emClient which sends UID:urn:uuid:urn:uuid:abc and we return a 403 with CARDDAV:no-uid-conflict
> http_carddav.c: strip ALL urn:uuid: prefixes from UID before comparing

- cassandane/Cassandane/Generator.pm
Apparently Cassandane tests can fail randomly when the message-id generator duplicates a message-id within a single test.
The generator only uses 16 bits of randomness, which isn't much.  I thought about using more random bits, but a) that still wouldn't guarantee no repeats, and b) these only need to be unique within a single test anyway.  Instead, I added a monotonic counter to the generator.  Within a single test, each message-id is now guaranteed unique just by virtue of the counter, even if the random number generator spits out two identical numbers within the same clock second.
A neat side effect of using the counter is that the sequence messages were generated in is now encoded into the message-id, which might be useful for postmortem debugging.
> prevent cassandane message id clashes

- cassandane/tiny-tests/JMAPCalendars/calendarevent_set_alerts_owner
- imap/caldav_alarm.c
Cyrus processes calendar alarms in shared calendars by first checking the calendar owner per-user data for alarms, then for each sharee. It then stores the smallest, future UTC time when to check alarms again for the event, where the zero value disables any future alarms.
A bug in this logic caused Cyrus to not fire any alarms for shared calendar events, if the calendar owner had alarms set but none of the sharees.
> caldav_alarm: do not zero out nextcheck if sharee has no alarms

- cassandane/tiny-tests/JMAPCalendars/calendarevent-get-locations-geo
- imap/jmap_ical.c
This isn't strictly necessary, but makes the regression tests run on both the current and upcoming libical release.
> jmap_ical: omit trailing zeros from geo coordinates

- imap/http_dav.c
Handling a sync REPORT can run into a race where dav.db is locked by another process. This patch makes Cyrus not crash on this error but return a server error. Fixing the conditions that lead to the race is a work in progress.
> http_dav: gracefully handle locked dav.db in REPORT

- imap/jmap_api.h
- imap/jmap_calendar.c
- imap/jmap_contact.c
- imap/jmap_mail.c
- imap/jmap_mailbox.c
- imap/jmap_notes.c
Initialization of the jmap_changes struct is left to the handler function first calling jmap_changes_parse. But in at least one occasion this could get skipped with an early return. Since the compiler did not report this during compilation let's better make sure we zero the structs memory properly.
> jmap_api: initialize jmap_changes struct to zero

- cassandane/tiny-tests/JMAPCalendars/calendarevent-get-locations-geo
Makes the test less sensitive to the number of decimal positions returned by libical, which apparently can vary between versions.
This test was failing on my system, where I haven't updated libical recently.  With this change the test now passes.
**Note to reviewers**: please build and run this test to ensure my change hasn't accidentally broken it in the other direction
> JMAPCalendars: fix calendarevent-get-locations-geo match

- cassandane/Cassandane/Cyrus/CaldavAlarm.pm
- imap/caldav_alarm.c
- lib/imapoptions
calalarmd holds a user lock while processing alarms, which could
take too long for high frequently occurring calendar entries.
This disables alarms for such events altogether. A more lenient
solution can be to optimize the codepath that determines the
`nextcheck` column entry.
> caldav_alarm: disable alarms for MINUTELY and SECONDLY recurrences

- cassandane/Cassandane/Cyrus/Carddav.pm
- imap/http_carddav.c
Recent changes in iOS expose this value to users and all the other addressbooks are capitalized.
> http_carddav: capitalize default address name to "Personal"

- cassandane/Cassandane/Unit/RunnerPretty.pm
This makes the cassandane output more readable when viewed on something that's not an 80-char wide fixed-width terminal, without compromising readability on a terminal
(It's mostly for making github actions reports readable)
> RunnerPretty: show test status on left, not right

- imap/http_caldav_sched.c
Fixes a bug where an initial scheduling event (with SEQUENCE:0) would have an iMIP REQUEST sent with SEQUENCE:1
> http_caldav_sched.c: don't bump sequence on initial creation

- cassandane/Cassandane/Cyrus/JMAPMailbox.pm
- cassandane/Cassandane/Cyrus/Specialuse.pm
- imap/jmap_mailbox.c
Adds a test for this behaviour:
> **specialuse_nochildren: \Scheduled \Snooze**
> 
> Whitespace separated list of special-use attributes that may not  contain
> child  folders.   If  set, mailboxes with any of these attributes may not
> have child folders created, and these attributes cannot be added to mail‐
> boxes that already have children..
We thought there might be an edge case allowing creation of mailboxes under the `\Trash` mailbox even though `specialuse_nochildren: \Trash` has been configured.  This test shows that there isn't such an edge case, or at least, not one that's simple to reproduce.
> Specialuse: test specialuse_nochildren create behaviour

- cassandane/Cassandane/Unit/TestCase.pm
- cassandane/tiny-tests/JMAPCalendars/calendarevent-set-updated-scheduled-source
A date assertion with tolerance, to hopefully avoid bogus failures from timing quirks.
There's room for future improvement -- ideally we'd also reject matches if they have different time zones, or if one has a timezone and the other doesn't.  This is commented but not implemented.  The DateTime timezone API looks like a hassle to deal with, so in my mind that detail can wait until we actually need it.
In the time since I started working on this, every transient CI failure that I've personally observed has been due to JMAPCalendars.calendarevent_set_updated_scheduled_source being off by one second.  So I've updated that one test to use this new assertion, with a tolerance of two seconds.
I was originally planning on doing a big audit of all the date matching tests and converting them in a …
> TestCase: add assert_date_matches()

- cassandane/Cassandane/Cyrus/Caldav.pm
- imap/caldav_alarm.c
- imap/caldav_util.c
- imap/http_caldav.c
The base for this PR should be the `cyrus-imapd-3.8` branch, but we don't have that, yet. **Do not merge** this in master.
This patch allows setting CalDAV alarm DAV properties on the calendar home. Version 3.7 erroneously broke this and a complete rewrite of default alarm support in Cyrus is in the works.
In order not to include the current broken state in the upcoming 3.8 release, this patch falls back to treating CalDAV alarm DAV properties like any other "dead" DAV property. This is consistent with version 3.6 and earlier.
> Cyrus 3.8: http_caldav: allow CalDAV alarms on calendar home

- cassandane/Cassandane/Cyrus/Sieve.pm
- sieve/sieve-lex.l
Per RFC 5228:
With the exceptions of strings and comments, the language is limited
to US-ASCII characters.
> sieve-lex.l: reject non-ASCII chars outside of strings and comments

- cunit/backend.testc
- imap/backend.c
Updates `backend_version()` to recognise versions 3.8 and 3.9
> backend: update backend_version() for 3.8 and 3.9

- cassandane/tiny-tests/JMAPEmail/email_query_no_guidsearch_ignore_jmapuploads
- imap/jmap_mail.c
This fixes a bug where a message is returned as a match in Email/query, if this email both exists in a mailbox excluded by an inMailboxOtherThan (e.g. "Trash") and in the jmap upload folder.
> jmap_mail: messages in #jmap folder can never match query

- cassandane/Cassandane/Cyrus/CaldavAlarm.pm
```
```
There was a bug in the counter for this loop that caused the test to loop forever if it happened to start at a time whose minutes value was 52, 53, or 54.  This was because the loop condition would end up checking for `$bymin <` 60, 61, or 62, which it always is because of the `% 60` in the loop body.
There was also a bug in how the test results were examined, which was being masked by the test never reaching the assertion that would expose it.
There's 3 minutes each hour when the bug can be reproduced on master, or the fix can be confirmed on this branch.  I've done both myself; you may wish to do so too.
> CaldavAlarm: fix inf loop in test_disable_high_freq

- cassandane/Cassandane/Cyrus/Flags.pm
- imap/imapd.c
- imap/index.c
- imap/index.h
This has been broken for quite some time, and I stumbled across it while working on a REPLACE implementation #4368
> Fix STORE [+/-]FLAGS.SILENT

- imap/imapd.c
Somehow the string arrays and bitmasks got out of sync
> imapd.c: fix list_data_remote() string arrays to match bitmasks

- cassandane/Cassandane/Cyrus/Sieve.pm
- imap/lmtp_sieve.c
Apparently Google sometimes includes VALARMs in replies, and this causes libical restriction checks to fail
> lmtp_sieve.c: strip VALARMs from iTIP reply before restriction check

- cassandane/Cassandane/Cyrus/JMAPContacts.pm
- imap/jmap_contact.c
This fixes a bug where if a v4 group vCard is updated via JMAP, the VERSION is blindly changed to 3 and X-ADDRESSBOOKSERVER-MEMBER properties are added while MEMBER properties are left behind
> jmap_contact.c: properly update a v4 group vCard

- cassandane/Cassandane/Cyrus/Sieve.pm
Trivial forward-port from 3.2.
Sieve.notify's `:min_version` was bumped by #4290, but that's now been backported as far back as 3.2.  I forgot to fix `:min_version` while backporting, until I got to 3.2, so now I've gotta go forward port it... sigh!
Doing it right this time, by changing on master then backporting from there...
> Sieve: test_notify() works as far back as 3.2

- cassandane/Cassandane/Cyrus/Rename.pm
This test confirms that we rewrite ACLs of shared mailboxes when renaming a user (when reverseacls are enabled)
> Rename.pm: test renaming a user who has had mailboxes shared to them

- imap/http_caldav.c
No reason to send an iTIP reply message if there is nowhere to send it
> http_caldav.c: treat empty organizer email address as non-existent

- cassandane/tiny-tests/JMAPEmail/email-set-destroy
- imap/jmap_mail.c
Fixes an issue discovered by FM UI
> JMAP Email: destroying an already destroyed email should return notFound

- imap/jmap_api.c
- imap/jmap_api.h
- imap/jmap_calendar.c
- imap/jmap_contact.c
- imap/jmap_mail.c
- imap/jmap_mail_submission.c
- imap/jmap_mailbox.c
- lib/util.c
- lib/util.h
This reduces the current JMAP state handling API to the single function jmap_modseq. The former code was the result of multiple refactorings during the initial implementation of JMAP. The result were functions that handled state as opaque JSON strings, C string or as modseqs. This patch changes that to always handle JMAP state as modseq.
> jmap_api: refactor JMAP state API to jmap_modseq function

- .gitignore
- Makefile.am
- changes/next/cyr_expire_jmap
- doc/examples/cyrus_conf/normal-master.conf
- doc/examples/cyrus_conf/normal-replica.conf
- doc/examples/cyrus_conf/normal.conf
- doc/examples/cyrus_conf/small.conf
- docsrc/imap/reference/manpages/systemcommands/jmap_expire.rst
- imap/cyr_expire.c
- imap/cyr_virusscan.c
- imap/ipurge.c
- imap/jmap_calendar.c
- imap/jmap_expire.c
- imap/mailbox.c
- imap/mailbox.h
JMAP Calendars requires to generate a CalendarEventNotification for changes to CalendarEvent objects. These notifications are stored in Cyrus in the `#jmapnotification` mailbox, which may accumulate a large count of notifications over time.
This patch adds a new option to cyr_expire to delete notifications that are older than a user-defined age.
> Expire JMAP notifications using jmap_expire

- cassandane/Cassandane/Cyrus/CaldavAlarm.pm
- imap/annotate.c
- imap/caldav_alarm.c
- imap/caldav_alarm.h
- imap/caldav_db.c
- imap/caldav_db.h
- imap/caldav_util.h
- imap/http_caldav.c
If a user changes the TZ on a floating time event with alarms, we may trigger the (next) alarm too late if the change in TZ has a greater offset from UTC (toward the east).
> calalarmd: Update nextcheck on floating time events when calendar/principal TZ changes

- cassandane/Cassandane/Cyrus/Expunge.pm
- imap/conversations.c
- imap/imapd.c
- imap/index.c
- imap/jmap_backup.c
- imap/mailbox.c
- imap/mboxlist.c
- imap/search_query.c
- imap/search_query.h
- imap/sieve_db.c
Hey Ken,
Here's, I THINK, all the lock ordering fixes that we need.  You can check the logic I used to test them with the top commit on https://github.com/cyrusimap/cyrus-imapd/pull/3179 which I just rebased on top of this, and which does all the LOCKERROR syslogs for cases where we try to lock any index files while not holding a user lock.
I've also rebased this on top of https://github.com/cyrusimap/cyrus-imapd/pull/3859, which already messed with some locking and has been include-in-fastmail for a while.
In my Cassandane tests, this all works with the lock tracking in place.  The big changes are:
1) we take a global blank username lock for shared folders
2) we don't do mailboxes.db locking any more for ACL changes, instead we just lock the owner's user lock for everything - this …
> Lock ordering fixes

- imap/index.c
- imap/mailbox.c
This was completely breaking indexing mailboxes that didn't have UID 1 in them any more, because iter_startuid being called with `1` led to setting iter->recno to zero, and it mailbox_iter_step would return NULL immediately!
Also, if the called UID wasn't in the mailbox, it would replay the previous message, which isn't what we ever want.
> Fix iter-startuid off by one issue

- imap/squatter.c
Twoskip now delays compacting databases until after the locks are released, but squatter wasn't ever calling this, leading to doing all the compacts on shutdown.  In particular, this meant trying to compact lots of cyrus.indexed.db files
> rolling squatter: compact databases

- cassandane/Cassandane/Cyrus/SearchFuzzy.pm
- lib/charset.c
The HTML parser wasn't handling : in tag names, which is legit because you can have namespaces in Outlook-generated emails.  This was found by a user who had an email very much like the test case I added as part of this.  Confirmed fixed by this test.
> Html tag colon

- cassandane/Cassandane/Cyrus/Caldav.pm
- imap/http_dav.c
This fixes a bug where some clients wouldn't allow a sharee to delete events if the sharee didn't also have the right to delete the calendar
> http_dav.c: don't need 'x'/'k' right on cal/abook to advertise [un]bind

- changes/next/4380-backend-version-bump-watermark
- cunit/backend.testc
- imap/backend.c
- imap/mailbox.h
If the backend's banner version looks sensible, but is larger than anything we know about, infer that it supports at least the same MAILBOX_MINOR_VERSION that this server does.
This fixes forever the problem where XFER would downgrade and lose data when sending mailboxes to a backend newer than it recognised; and removes the need to update backend_version(), backport it, and do releases from all the older branches, every time a new Cyrus version is created.
backend_version() still needs to be updated appropriately any time MAILBOX_MINOR_VERSION changes, but only when it changes.
This also simplifies handling of banner versions from 3.0 forward.
This needs to be backported to all the usual branches (including 3.0, 2.5, and 2.4), but that will be the last time it needs to happen.
> backend: forward-safe backend_version()

- imap/jmap_ical.c
This fixes a bug where JSCalendar event id would end up being something like id:"ER-00000000T000000-abcd"
> jmap_ical.c: don't add RECURRENCE-ID property for recurrenceId:null

- cassandane/Cassandane/Cyrus/JMAPMailbox.pm
- imap/jmap_api.c
Just tagging all for whoever feels like reviewing :)  This was triggered by a user breaking replication horribly by the faulty "rename under the DELETED namespace".  We should maybe actually plumb a "kill this with fire" check down a level too in mboxlist_renamemailbox(), but this fix certainly seems right anyway.
My only issue would be whether it somehow breaks "Mailbox/changes", but the other existing tests seem to indicate it's OK!
> Jmap move deleted parent

- imap/annotate.c
- imap/annotate.h
- imap/jmap_backup.c
- imap/sync_support.c
Don't use mboxlist_findall for the mailbox name in replication for annotations.
Should hopefully fix https://github.com/cyrusimap/cyrus-imapd/issues/3771
> Annotatemore mboxname

- imap/search_engines.c
- imap/search_squat.c
- imap/search_xapian.c
The search builder API requires a mailbox for initialization but did not do a proper NULL check of the argument. This could cause the Xapian and Squat search builders to crash.
> search_engines: do not return search builder for null mailbox

- imap/jmap_ical.c
Bogus clients may TEXT-escape geo: URI values in properties such
as X-APPLE-STRUCTURED-LOCATION. Until now Cyrus returned these
bogus values in the Location "coordinates" property. This resulted
in Cyrus rejecting an update on such calendar events, because
the geo: uri was validated during write.
This patch changes Cyrus to sanitize such bogus geo: uri values
and return the sanitized value as Location coordinates. It still
rejects such values on write.
> JMAP Calendars: sanitize geo: coordinates when read from iCalendar

- imap/append.c
- lib/map_shared.c
As mentioned in this morning's call, here's three sanity-check fixes:
1) use a distinct filename per message for all appends
2) check the munmap call result
3) check the GUID of the found file and link it directly if found rather than overwriting the existing spool location
> Append fixes

- cassandane/Cassandane/Cyrus/JMAPMailbox.pm
This proves that a previously reported crasher has been fixed, presumably by 
https://github.com/cyrusimap/cyrus-imapd/commit/adfce43072fc3e03da282a28f63f4b5245cb87c3
> JMAPMailbox.pm: add test_mailbox_set_destroy_twice

- notifyd/notify_log.c
fixes theoretical buffer overrun from too many options
> notify_log: use struct buf

- docsrc/imap/download/installation/http/caldav.rst
- docsrc/imap/reference/manpages/systemcommands/jmap_expire.rst
Couple of typos that are resulting in noise when building docs.
General rule of thumb:  if you edit any RST files, please `make doc` and check that you haven't introduced any new warnings or errors.  RST looks forgiving, like markdown, but it's actually annoyingly fussy, like XML.
I'm not sure how far this needs to be backported, so I'm just hitting it with all the backport labels, and I'll figure it out when I get there...
> docs: fix doc build errors from typos

- imap/cyr_buildinfo.c
Add some version details to the data output by cyr_buildinfo
Build wrappers might use this to detect unexpected version changes
> cyr_buildinfo: add version category with some version details

- imap/user.c
This should fix an issue where mailbox_open_sieve() via dav_reconstruct would try to write to root
> user_sieve_path(): never return "" -- always return a sensible path

- cassandane/Cassandane/Cyrus/Sieve.pm
- changes/next/sieve-date-tzid
- sieve/bc_eval.c
Extend the [current]date :zone argument (RFC 5260) to also accept an IANA TZID, from which we will extract the time zone offset
> Sieve: Accept :zone +/-hhmm OR :zone iana-tzid

- cassandane/Cassandane/Cyrus/LDAP.pm
- cassandane/Cassandane/Cyrus/TestCase.pm
- cassandane/Cassandane/GenericDaemon.pm
- cassandane/Cassandane/Instance.pm
- cassandane/Cassandane/PortManager.pm
- cassandane/Cassandane/Util/TestUrl.pm
This will make tests more resilient when running on servers where other services are using ports cassandane overlaps with.
> Cassandane: Test that we can bind to ports before using them

- cassandane/Cassandane/Cyrus/Sieve.pm
- cassandane/Cassandane/Net/SMTPServer.pm
- imap/lmtp_sieve.c
Can't use addresses like "Foo <foo@example.com>" in SMTP RCPT TO
This is a simple fix, but how to test?  I don't know how to check for SMTP pass/fail in Cassandane
> lmtp_sieve.c: strip phrase from redirect address (addr-spec only)

- imap/jmap_ical.c
Before, an invalid "links" property entry was reported at JSON pointer "links/links/foo" instead of "links/foo".
> jmap_ical: fix JSON pointer for invalid links property

- cassandane/Cassandane/Cyrus/Caldav.pm
- imap/http_caldav.c
This is a bugfix for Fantastical when splitting a recurring event with existing overrides prior to the split.
Tested with Fantastical 3.7.8
> http_caldav.c: Strip overrides that occur before start of RRULE

- cassandane/Cassandane/Cyrus/MurderDAV.pm
- imap/http_dav.c
Fixes a bug proxying PUT.  
Also adds a Cass test for proxying GET, PUT, MOVE, DELETE, PROPFIND, PROPPATCH, MKCALENDAR, REPORT (sync-collection, calendar-multiget).
Still need to add tests for proxying MOVEs across backends, but I don't think we allow a user's calendars to be split across backends.  We could do this with shared calendars across users on different backends, but DAV sharing across backends (the notifications part) isn't supported either.
@elliefm Do you want to backport the fix and tests?
> http_dav.c: Can't check mailbox type when proxying PUT

- cassandane/Cassandane/Cyrus/Caldav.pm
- imap/http_caldav.c
Fixes a crasher when a conditional DELETE collection fails due to an invalid state token
> http_caldav.c: Can't access NULL cdata after precondition failure

- imap/index.c
This fixes the unseen underflow issues found by auditslot.
The only issue here would be if the record is unexpunged, the \Seen flag WON'T be set.
If we think this matters, this PR can be altered to actually update the record on disk, but still skip updating state->numunseen.
> index.c: short-circuit _fetch_setseen() on expunged records

- tools/build-with-cyruslibs.sh
This will make CI builds fail if our changes result in compiler warnings
> tools/build-with-cyruslibs.sh: add -Werror to CFLAGS and CXXFLAGS

- perl/imap/IMAP/Shell.pm
From patch provided by @yaonos
Closes #4440
> IMAP::Shell: fix uninitialized value warning

- cassandane/vg.supp
- imap/lmtp_sieve.c
- imap/tls.c
Here's a simple one while I read yours :)
> Valgrind fixes

- cassandane/Cassandane/Cyrus/Sieve.pm
due to `services => [ ..., 'http' ]` in constructor.
If httpd has been compiled out, the tests can't work because set_up won't be able to start the requested http service, and will error out.  This fix stops these tests from trying to run when they're not going to be able to, and follows on from #4412.
We could fix this more neatly by not requesting the http service in the constructor, and instead only starting the service for the individual tests that need it.  But we don't yet have any syntactic sugar for that, so it'd be messy and annoying, and for not much real benefit.
> Sieve: all tests require :needs_component_httpd

- lib/cyrusdb_twoskip.c
This work came out of a ZFS corruption event at Fastmail (true story) and trying to create an example of the IO patterns for a checkpoint.
This is almost all just optimising codepaths to avoid doing tests which are always false in this case, but there is one significant behaviour change - "opendb" will avoid taking and then releasing locks and just grab the locktype it eventually needs and keep it into the transaction where possible.
> Twoskip tidy

- imap/relocate_by_id.c
By just reading the code I found out, that user_sieve_path() returns pointer to statically allocated data.  In relocate_by_id.c:main() this data is appended into strarray_t *oldpaths, and finally strarray_free(oldpaths); is called.  The latter free()s that statically allocated data.
> relocate_by_id:main() frees statically allocated data

- cunit/charset.testc
- lib/charset.c
This tests and fixes (I think) a bug @robmueller and @wolfsage tracked down from, where the html_attr state wasn't being reset between tags (there's a big writeup in Linear).
I don't know lib/charset especially well, so my confidence isn't high that I haven't missed a detail...
I found a couple of surprising-but-unrelated things while in here, so I've added failing cunit tests for them (as WIP commits).  Do we want to address those too?  If not, I'll just drop those commits.  In the meantime, CI will fail on this PR because of those failing tests...
@rsto I've marked this as a draft for now until we know what (if anything) we want to do with the two WIP commits, but please review now anyway.
> html tag parse fix

- Makefile.am
- cassandane/tiny-tests/JMAPCalendars/calendarevent_set_preserve_icalxprops
- imap/global.c
- imap/global.h
- imap/httpd.c
- imap/httpd.h
- imap/jcal.c
- imap/jcal.h
- imap/jmap_calendar.c
- imap/jmap_ical.c
- imap/jmap_ical.h
- imap/xcal.c
This changes the CalendarEvent/set{update} to preserve unknown iCalendar x-properties of the original iCalendar resource.
While implemented as a Cyrus extension property in the JSCalendar object, this property only is exposed Cyrus-internally.
> JMAP Calendar: preserve iCalendar x-properties in updated event

- Makefile.am
Allow idled to build when configured with --disable-http --disable-jmap --disable-calalarmd
> Makefile.am: unconditionally include json_support.[ch] in libcyrus_imap

- cassandane/Cassandane/Cyrus/Sieve.pm
- cassandane/Cassandane/Cyrus/TestCase.pm
- cassandane/testrunner.pl
This PR adds `:want_foo` and `:want_service_foo` magic to Cassandane::Cyrus::TestCase.  These allow properties controlled by the `want` hash to be set easily on a test-by-test basis.  Previously, you had to either set them in the constructor (affecting the whole suite); or mark individual tests with `:NoStartInstances`, and then tinker around with the options prior to calling `$self->_start_instances()`.
The list of wantable things (and their defaults) is defined as `$want` in `sub new` (unchanged).  The list of recognised service names is defined in Cassandane::ServiceFactory (also unchanged).
I have updated the Sieve test suite to make use of the new behaviour.  This suite particularly needs a http service for some, but not all, of its tests.  With the new attribute magic, the tests …
> cassandane: add :want_foo magic for per-test configuration of test properties

- cassandane/Cassandane/Cassini.pm
This updates the Cassini object to also look for its initialization file at the path defined in the optional CASSINI_FILENAME environment variable.
It has precedence over the standard cassandane.ini locations, but lower precedence than the `--config` command line argument.
Was: _This adds the CASSANDANE_INI variable to the cassandane Makefile. Before, cassandane builds only supported cassandane.ini file locations at one of the standard directories. Now, the location of a custom cassandane.ini file path can be defined before the build._
> cassandane: support custom cassandane.ini path in Makefile

- cassandane/Cassandane/Cyrus/Notify.pm
- imap/imapd.c
- imap/index.c
- imap/index.h
- This PR is best reviewed commit-by-commit.
- The first commit fixes the SQLite UNIQUE constraint noise cause by using IDLE after NOTIFY.
- A couple commits are cleanup and refactor for subsequent commits.
- Most of the remaining commits are fixes/tests for NOTIFY.
- The last commit is an IDLE tweak when polling due to lack of idled (or lack of IDLE on backend) and some code cleanup/reorganization.
> NOTIFY & IDLE fixes

- imap/ctl_mboxlist.c
- imap/http_dav_sharing.h
This change seems to make both FM UI and MacOS happy, as well as Fantastical (still allows r/w on a shared calendar)
> Reconcile DAV Sharing ACLs with JMAP

- cassandane/Cassandane/Cyrus/Sieve.pm
- cunit/binhex.testc
- cunit/imapurl.testc
- imap/cyrdump.c
- imap/imapd.c
- imap/mboxevent.c
- lib/imapurl.c
- lib/imapurl.h
- lib/util.c
- lib/util.h
- perl/imap/IMAP.xs
This fixes a potential memory corruption issue that was highlighted by https://github.com/cyrusimap/cyrus-imapd/pull/4433
> imapurl: refactor toURL to take dynamically growing buf argument

- cunit/binhex.testc
- cunit/imapurl.testc
- imap/cyrdump.c
- imap/imapd.c
- imap/mboxevent.c
- lib/imapurl.c
- lib/imapurl.h
- lib/util.c
- lib/util.h
- perl/imap/IMAP.xs
This backports https://github.com/cyrusimap/cyrus-imapd/pull/4436 to the 3.8 version
> Backport refactored IMAP URL encoding to cyrus-imapd-3.8

- imap/squatter.c
This checks return value from mboxname_from_external() and if it is NULL
or empty string, just inform about the invalid mailbox name instead of
crashing.
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1911689
> Squatter: Don't crash on assert() in lib/cyrusdb_twoskip.c:fetch()->assert(keylen)

- cassandane/Cassandane/Cyrus/Annotator.pm
- imap/append.c
It's misleading to log an error message for `need_rights=<>` which actually indicates that no rights are missing.
> append.c: do not log missing ACL if no rights are missing

- cassandane/Cassandane/Cyrus/JMAPBackup.pm
- cassandane/Cassandane/Unit/TestCase.pm
- cassandane/Cassandane/Unit/TestPlan.pm
- cassandane/testrunner.pl
- cassandane/tiny-tests/JMAPCalendars/calendarevent-get-standalone-instances-multi
- cassandane/tiny-tests/JMAPEmail/email-query-cached-evict
Got curious and discovered many of our "_slow" tests run in ~5 seconds each; this doesn't seem slow enough to be worth the loss of regular regression coverage, so I've removed the "_slow" marker from the fast ones.
"calendarevent_get_standalone_instances_slow" got renamed to "calendarevent_get_standalone_instances_multi" along the way, because it turned out there was already a "calendarevent_get_standalone_instances" (which did the same thing, but only once).  The rest just lost their "_slow" marker.
While I was in there, I got frustrated at the difficulty of running just the slow tests, without everything else too, so I added a --slow-only option for testrunner.pl and plumbed it through.
Bug3072.copy_longset_slow (112 seconds) and ClamAV.remove_infected_slow (21 seconds) are still marked …
> cassandane: slow test improvements

- Makefile.am
- configure.ac
- cunit/mailbox.testc
- imap/mailbox.h
This adds a new test suite, mailbox.testc, containing tests that assert that the various OFFSET_FOO for `struct index_header` and `struct index_record` fields are aligned correctly according to the requirements of the type used to read/write into the file.
This was inspired by someone observing that some `modseq_t` and `quota_t` fields weren't correctly aligned to 8 byte boundaries in version 17 and 18 indexes.  When this branch is based on `master` today, it correctly detects these misaligned fields.  Those fields are already fixed in index version 19, which will land with #4387, so this PR will remain a draft until that lands, at which point I'll rebase and update this for version 19 indexes. [Edit: this has now been done.]
The tests depends on the C11 `alignof` macro (from …
> mailbox offset alignment tests

- cassandane/Cassandane/Cyrus/JMAPTestSuite.pm
- cassandane/Cassandane/Cyrus/JMAPTestSuiteWS.pm
These tests now expect the new behaviour (#4457), so suppress them when Cyrus is older
This will fix the failing CI on the 3.8 branch once it's backported.  It'll need to be backported to every branch whose Cassandane runs JMAPTestSuite.
> JMAPTestSuite: Email:import behaviour changed in 3.8+

- cassandane/Cassandane/Cyrus/JMAPBackup.pm
A too short window length makes the test indeterministic.
> JMAPBackup: increase restore time window length

- imap/search_engines.c
- imap/search_xapian.c
This aligns the lock acquisition order of the SEARCH command and squatter to prevent a deadlock between them running concurrently on the same user and mailbox.
The deadlock occurred when squatter had acquired a lock on conversations.db and wanted to acquire an exclusive lock on xapianactive.db. Meanwhile, SEARCH had acquired a lock on xapianactive.db and wanted to acquire an exclusive lock conversations.db.
This patch aligns their lock acquisition order to prevent this deadlock.
Testing this currently is only done manually. A brute-force test is to runs hundreds of SEARCHes and squatters on the same user to hit the deadlock. A better test is done by use of special-purpose tool that I built that traces the acquired locks of a Cyrus process across its lifetime. I do plan to integrate this …
> Prevent deadlock between SEARCH and squatter

- cassandane/Cassandane/Cyrus/Sieve.pm
- imap/lmtpd.c
Fix for setting \Seen flag on a plus-addressed mailbox.  as->internalseen was being determined by the userid of the sender rather then the userid of the script owner, so we tried to write to seen.db and failed.
> lmtpd.c: internalseen is determined by the owner of the Sieve script

- imap/search_xapian.c
This fixes a potential null pointer read if a mailbox got deleted in between squatter selecting it for search indexing and actually indexing its messages. Returning non-zero error codes will signal the caller of the search backend to skip indexing this mailbox.
Reproducing this condition in a test harness would require synchronizing squatter execution with some arbitrary process, and effectively would add dead code for testing.
Instead, the changes in this pull request have been vetted with manual testing as well as running the full test suites. No issues have shown up.
> Return proper error codes for erroneous search state

- .github/workflows/main.yml
We recently built a new cyrus-buster docker image, with updated dovecot and imaptest builds, to resolve the problem with ImapTest.notify failing every CI run.  The new docker image seems to have gotten an updated git that contains a security fix which complains when the directory ownership looks sketchy -- which, it does when running github actions on docker images! https://github.com/actions/runner/issues/2033
Initially, this was failing on the post-checkout fiddling we were doing to make the git tags available to the build (which needs them for versioning), so the first commit here removes the post-checkout fiddling and instead configures the checkout step to get everything we need in the first place.  But we need the `git describe` command during the build to determine the version …
> github actions: workaround "dubious ownership" failures

- cassandane/Cassandane/Cyrus/Annotator.pm
- imap/append.c
Up until now, the \Seen flag could be set in append without the ACL_SETSEEN permission being assigned to the authenticated user. All other flags already had their required ACLS checked, and this now also is enforced the Seen flag.
This passes all Cassandane and integration tests, which indicates there are no hidden assumptions that build on this.
> append.c: require ACL_SETSEEN when setting \Seen flag

- cassandane/cassandane.ini.dockertests
"ImapTest.urlauth" no longer fails with current imaptest, so we can stop suppressing it.
Before this can merge:
* https://github.com/cyrusimap/cyrus-docker/pull/15 must be merged
* the "cyrus" branch of our imaptest fork must be updated to be based on its "master"  plus our "urlauth" branch (I have already updated its "master" from upstream to correspond with the Dovecot version in the cyrus-docker PR).
* and a new docker image published(???)
Marking this "do not merge" so it doesn't get accidentally merged without the coordinating steps.
Update: coordinating steps are complete, and this has been rebased on master and is ready to go whenever it's reviewed (assuming approved with passing CI)
> cassandane.ini.dockertests: no longer suppress urlauth

- docsrc/imap/developer/developer-testing.rst
Updates the developer testing instructions, which advises building Dovecot and IMAPTest from nightly build tarballs, to explain how you can also build these from git by copying what the docker image build does, which will get you the same tests CI runs.
I didn't provide copy-and-pastable commands here, because it relies on checking out a known commit id on the Dovecot repository, and I don't want to have to try to keep this documentation synchronised.  Instead, I just link to the docker image build script, and advise the reader to copy what it does if they want to do the same thing.
Really, my main purpose in writing this is so that in a few years when we next need to update IMAPTest for CI, I don't get confused by our documentation saying one thing, but our process doing another.  I …
> developer-testing.rst: explain CI imaptest setup

- cassandane/Cassandane/Cyrus/Simple.pm
- imap/imapd.c
`maxmessagesize` was being misinterpreted as kilobytes for APPEND, when it is specified in bytes.  This removes the superfluous multiplication, and adds regression tests.
The bug only exists on 3.6, so this PR is against 3.6 directly, rather than master.  Once it lands, I intend to forward port the regression tests to master, and then back from there to 3.8.
Fixes #4506
> 3.6: maxmessagesize is bytes, not kilobytes

- imap/http_dav.c
Initially found by valgrinding cassandane on 3.8, but reproducible on master.  Not sure why @rsto's master valgrinds didn't find this but mine did.
(Also replaces a hard tab that had somehow snuck in nearby.)
> http_dav: fix meth_mkcol leak when mailbox is remote

- docsrc/imap/download/release-notes/3.8/x/3.8.0-beta1.rst
- docsrc/imap/download/release-notes/3.8/x/3.8.0-beta2.rst
- docsrc/imap/download/release-notes/3.8/x/3.8.0-rc1.rst
- docsrc/imap/download/release-notes/3.8/x/3.8.0.rst
This was an option that existed briefly on a feature branch, but was rebased out before the feature landed.  A reference to it accidentally hung around in documentation, and wound up in release notes.
> docs: remove references to jmap_guesstz_fname

- .github/workflows/main.yml
Splits the cassandane part of the github actions workflow into separate steps:
1. build and check all the cassandane components
2. run cassandane quietly (-f prettier)
3. only if the first cass run failed: rerun with --rerun and -f pretty to get noisy output for only the failing tests
Each named step is folded separately in the web interface, so splitting it like this makes it easier to jump to the detail you care about, without having to scroll through all the output for the entire cassandane run.
Re-running the failed tests and only failing the workflow if there's still failures might also reduce false negatives from transient test failures, which are almost never related to the PR being evaluated anyway.
I have no idea whether this will work or not, but I think I need to create a pull …
> github actions: split cass run into several steps

- docsrc/imap/download/upgrade.rst
we're not doing anything useful with the responses anyway
> docs: remove post-upgrade survey link

- cassandane/Cassandane/Cyrus/JMAPTestSuite.pm
- cassandane/Cassandane/Cyrus/JMAPTestSuiteWS.pm
Noticed while investigating something else that JMAPTestSuite (and JMAPTestSuiteWS) create a lot of defunct squatter processes that don't get cleaned up until cassandane itself exits.  Turns out we were killing the process after each test, but not calling waitpid on it.
This arranges for it to be cleaned up properly, using the already existing mechanism.  Rolling squatter exits with EX_TEMPFAIL when shut down with SIGTERM, so it also needs the custom exited_abnormally that ignores EX_TEMPFAIL (but still dies for any other non-zero exit code).
> JMAPTestSuite: don't leave behind defunct squatter procs

- cassandane/Cassandane/Cyrus/Caldav.pm
- cassandane/Cassandane/Cyrus/TestCase.pm
- imap/http_caldav.c
> http_caldav: do not crash calendar home GET if calendaradmin is set

- cassandane/Cassandane/Unit/RunnerPretty.pm
This colours the summary output that appears at the end of a cassandane run.
The diff looks like new code, but it's actually overriding a method in the superclass (Test::Unit::TestRunner).  The method that's being overridden looked like this:
```
sub print_header {
my $self = shift;
my ($result) = @_;
if ($result->was_successful()) {
$self->_print("\n", "OK", " (", $result->run_count(), " tests)\n");
} else {
$self->_print("\n", "!!!FAILURES!!!", "\n",
"Test Results:\n",
"Run: ", $result->run_count(),
", Failures: ", $result->failure_count(),
", Errors: ", $result->error_count(),
"\n");
}
}
```
So you can see the "new" code does basically the same thing it always did, but with colour injected in appropriate places, and some breaking up and rewrapping of lines that got too long.
> RunnerPretty: colour the summary output too

- cassandane/Cassandane/Cyrus/Sieve.pm
- imap/itip_support.c
Hi Ken, as promised, here's the test case and also a really basic possible solution to it, just to double check my logic.
> Processimip rrule complete

- cassandane/Cassandane/Cyrus/Autocreate.pm
- cassandane/Cassandane/Instance.pm
- cassandane/Cassandane/MasterEntry.pm
- cassandane/Cassandane/Service.pm
This adds a test to verify that autocreate doesn't replace legacy mailboxes, which seems to show that the problem I suspected in #4532 does not exist.
> cass: test that autocreate doesn't replace legacy mailboxes

- Makefile.am
- cunit/annotate.testc
- cunit/hash.testc
- cunit/proc.testc
- cunit/search_expr.testc
- imap/backend.c
- imap/search_expr.c
This fixes a handful of leaks that `make -j4 VG=1 check` detects.  Most of these are trivial but there's a couple of complicated ones:
* search_expr.testc was leaking internal state that's usually cleaned up by `cyrus_done()`, but which is missed in the tests because the way `set_up()` initialises it bypasses installing the done callback.  To fix this one, I tweaked some things to expose search_expr.c's internals to cunit, so that `tear_down()` could then reach in and clean up itself.  But perhaps it would have been better to just add a comment and a suppression rule instead?
* backend.c was leaking an `SSL_SESSION` object when disconnecting from a backend that we had used starttls when connecting to.  This one's a real leak in Cyrus, not just a leak in the tests.  The fix seems simple, …
> fixes for leaks found by valgrinding cunit

- cassandane/Cassandane/Cyrus/Archive.pm
- cassandane/Cassandane/Cyrus/Autocreate.pm
- cassandane/Cassandane/Cyrus/Delete.pm
- cassandane/Cassandane/Cyrus/FastMail.pm
- cassandane/Cassandane/Cyrus/HTTPPTS.pm
- cassandane/Cassandane/Cyrus/JMAPCalendars.pm
- cassandane/Cassandane/Cyrus/LDAP.pm
- cassandane/Cassandane/Cyrus/Metadata.pm
- cassandane/Cassandane/Cyrus/Prometheus.pm
- cassandane/Cassandane/Cyrus/Quota.pm
- cassandane/Cassandane/Cyrus/Replication.pm
- cassandane/Cassandane/Cyrus/Sieve.pm
- cassandane/Cassandane/Test/Core.pm
- cassandane/Cassandane/Unit/TestCase.pm
This adds two new assertion functions to Cassandane: `assert_file_test()` and `assert_not_file_test()`, for assertions based on the `perldoc -f -X` filename tests (i.e. `-e`, `-f`, `-x`, etc) with helpful messages, and then updates a bunch of our tests to use them.
There's a handful of tests that consistently fail when the local month is different from the UTC month, and some of those were using bare file test assertions without descriptive messages, making it hard to track down the cause of the failures.  This PR makes it so those tests will fail with better messages, so that next time I might finally be able to track down and fix whatever is actually causing the failure.
I started working on the test failures as #4500, but this chunk stands on its own, so I'm splitting it out to get it …
> cassandane: improve file test assertions

- Makefile.am
- configure.ac
- docsrc/imap/developer/compiling.rst
We weren't checking whether `xxd` existed, just crossing our fingers and hoping.  If it wasn't available, `configure` would still succeed, but then `make` would fail.  This PR fixes that.
The files we produce with xxd are included pre-generated in our release tarballs, so someone building from a release tarball could have technically not required xxd (as long as they didn't do anything that would cause those files to need to be rebuilt).  I initially tried a more complicated implementation so that such people wouldn't be forced to install xxd, but it was messy and didn't offer much real improvement, so I stripped it back out again.  It's not a difficult dependency to meet.
> configure.ac: detect xxd, error if needed and missing

- cassandane/Cassandane/Cyrus/Delete.pm
- cassandane/Cassandane/Cyrus/Metadata.pm
- changes/next/cyr_expire_noexpire
- cunit/annotate.testc
- docsrc/imap/reference/manpages/systemcommands/cyr_expire.rst
- imap/annotate.c
- imap/cyr_expire.c
This PR includes fixes and enhancements for cyr_expire:
- It fixes a bug in which the `expire/delete/archive` mailbox annotations were only read for a given mailbox, rather than looking its value up in all the parent mailboxes.
- It removes a noisy and unhelpful debug message from logging
- It adds support for non-day durations in the `expire/delete/archive` annotations by use of the Cyrus-config supported duration format. cyr_expire already had included support to read such values, but they could only be set as command line flags.
- It adds the `noexpire_until` annotation that allows to block expiring and deleting until a given future date, or indefinitely.
This PR best is read commit by commit.
> cyr_expire: add noexpire_until annotation

- cassandane/tiny-tests/JMAPCalendars/calendarevent-query
- cassandane/tiny-tests/JMAPCalendars/calendarevent_query_unsupported
- imap/caldav_db.c
- imap/caldav_db.h
- imap/jmap_calendar.c
- imap/jmap_core.c
- lib/sqldb.c
- lib/sqldb.h
CalendarEvent/query filters using any of the AND/OR/NOT operators were not supported using dav.db. This now supports such queries, allowing both for faster lookup and for previously unsupported queries such as OR(uid1,uid2,uid2).
> jmap_calendar: support FilterOperator in dav.db queries

- Makefile.am
- cassandane/Cassandane/Cyrus/SearchFuzzy.pm
- cassandane/Cassandane/Cyrus/TestCase.pm
- cassandane/Cassandane/Instance.pm
- cassandane/Cassandane/Unit/TestCase.pm
- changes/next/squatter_nolock_attachment_text_extraction
- cunit/message_guid.testc
- cunit/strarray.testc
- imap/attachextract.c
- imap/attachextract.h
- imap/httpd.c
- imap/imapd.c
- imap/index.c
- imap/index.h
- imap/message_guid.c
- imap/message_guid.h
- imap/search_engines.c
- imap/search_engines.h
- imap/squatter.c
- lib/dynarray.h
- lib/imapoptions
- lib/strarray.h
This updates squatter to not lock a mailbox while extracting text from attachments. To do so, the attachment extraction module now supports an optional file-system based cache. By default, squatter uses a temporary cache. The newly added experimental squatter argument options v`--attachextract-cache-dir` and `--attachextract-cache-only` allow to use user-defined cache directory, as well as instruct squatter to only lookup extracted attachment text in the cache.
In addition, handling of timeouts when calling the extractor service has changed: rather than attempting to connect up to 4 times, an error now is returned after the first timeout. 
This pull request best is read commit by commit, where the first two commits are refactoring only.
> squatter: do not hold mailbox locks while calling the attachment extract service

- docsrc/conf.py
so that older branches (and future older branches) don't end up with a dead link to release notes they don't have, and don't need to be kept up to date with current dev release notes either
(3.6 and earlier already got this change during release of 3.8.0; this is a forward port from there)
> docsrc/conf.py: use absolute dev release notes link

- cassandane/Cassandane/Cyrus/Info.pm
- cassandane/Cassandane/Cyrus/LDAP.pm
- cassandane/utils/fakeldapd
We've been able to do this since #4522, so here it is
> cassandane: run fakeldapd as a DAEMON rather than a START

- cassandane/Cassandane/Cyrus/List.pm
- imap/imapd.c
- imap/index.c
imapd.c: needs an open mailbox for index_scan(), imapd_index is released before every command is parsed, so we need to reopen the mailbox
> Fix IMAP SCAN on selected mailbox crasher

- cassandane/Cassandane/Cyrus/CaldavAlarm.pm
- imap/caldav_alarm.c
We need to continue to inspect other alarms even if we suppress an alarm with an absolute trigger.
> caldav_alarm.c: don't skip other alarms if one has an absolute trigger

- imap/lmtp_sieve.c
Fix for an existing Cass test.  Not sure when this broke
> lmtp_sieve.c: allow PUBLISH with no ORGANIZER

- cassandane/Cassandane/Cyrus/CyrusDB.pm
- cassandane/Cassandane/Instance.pm
- cunit/aaa-db.testc
- lib/cyrusdb.c
- lib/cyrusdb_skiplist.c
**Reviewers:** this has grown into a collection of small related things rather than a single thing.  Probably easiest to review commit-by-commit.
If `ctl_cyrusdb -r` was not run during Cyrus startup (or failed in a particular way, see further on), then your logs will be full of errors like this from every single Cyrus process:
> DBERROR: read failed, assuming the worst: filename=</path/to/confdir/db/skipstamp> [...]
Would you be able to guess from that that the problem was that you'd forgotten to add `ctl_cyrusdb -r` to your cyrus.conf START section?  Me either!
This PR adjusts the logging such that if the reason the skipstamp file is unreadable is that it doesn't exist, then an informational message is also logged advising the need for `ctl_cyrusdb -r`.  I've kept the new log message …
> better cyrusdb / ctl_cyrusdb -r UX

- imap/cyr_cd.sh
Fixes #4293
(also fixes a typo in a comment)
> cyr_cd.sh: this script is bash, not sh

- cassandane/Cassandane/Cyrus/MurderIMAP.pm
- imap/imapd.c
- imap/mboxlist.c
this commit also removes an extra write to mailboxes.db, since mboxlist_deletemailbox() already sets MBTYPE_DELETED
> imapd.c: make sure we delete XFERed mailboxes from source (issue #4370)

- cassandane/tiny-tests/JMAPEmail/email_parse_inmemory_blob
- imap/jmap_mail.c
> jmap_mail: do not dereference NULL pointer in Email/parse

- cassandane/tiny-tests/JMAPCalendars/calendarevent-participantreply-simple
- cassandane/tiny-tests/JMAPCalendars/calendarevent-participantreply-standalone
- imap/jmap_calendar.c
Solves the problem of attendees getting mail bombed when one changes their partstat via CalendarEvent/participantReply
> jmap_calendar.c: don't send updates to attendees when one changes their partstat

- imap/http_caldav_sched.c
when generating iMIP messages.
> imip_send_sendmail: render the COMMENT field in the html+text alternatives

- lib/auth_krb.c
> lib/auth_krb.c: there is no HAVE_BDB

- cassandane/Cassandane/Cyrus/Replication.pm
- changes/next/bring-back-sync-client-connect-once
- docsrc/imap/reference/manpages/systemcommands/sync_client.rst
- imap/sync_client.c
- imap/sync_support.c
- lib/imapoptions
`sync_client` has a `-o/--connect-once` option that's supposed to make it fail if the connection to the replica fails, rather than retrying the connection until it succeeds.  It was accidentally broken a while ago during a refactor.
This PR adds the behaviour back, adds a regression test, and fixes some documentation details that were out of date.
> bring back sync_client --connect-once

- imap/lmtp_sieve.c
backport of 18bd7d23e7456a57e8db14ac1ecde40ada7e033d
> 3.6 lmtp_sieve: fix use of uninitialized variable

- cassandane/Cassandane/Cyrus/Flags.pm
Regression test for #4611
(It's just a copy of `test_seen_sharedmb_nosharedseen` above it, but with `sharedseen => true` instead of `false`)
> Flags: add test_seen_sharedmb_sharedseen

- cunit/cunit.pl
This disregards the ordering in Makefile.am (which is unimportant) and arranges suites to run in alphabetic order (which is readable)
> cunit.pl: add suites to project in sorted order

- docsrc/exts/sphinxlocal/sitemap.py
The default ordering of `env.found_docs` seems to be unstable in newer Sphinx versions, resulting in sitemap.xml changes every single time the website builder runs, even if nothing actually changed.
With this list now processed in sorted order, sitemap.xml shouldn't change unless we've actually added, removed, or renamed documents.
> sitemap.py: sort work list for a stable sitemap.xml

- sieve/sieve-lex.l
```
CC       sieve/libcyrus_sieve_lex_la-sieve-lex.lo
../sieve/sieve-lex.l:489:14: error: call to undeclared library function 'strncasecmp' with type 'int (const char *, const char *, unsigned long)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
if (!strncasecmp(cp, "hex:", 4)) {
^
../sieve/sieve-lex.l:489:14: note: include the header <strings.h> or explicitly provide a declaration for 'strncasecmp'
1 error generated.
```
> sieve-lex.l: fix undeclared function strncasecmp() warning

- cassandane/Cassandane/Cyrus/Sieve.pm
- changes/next/deprecate_sieve_notify
- docsrc/imap/reference/manpages/systemcommands/sieved.rst
- docsrc/imap/rfc-support.rst
- sieve/bc_emit.c
- sieve/bytecode.h
- sieve/interp.c
- sieve/interp.h
- sieve/sieve-lex.l
- sieve/sieve.y
- sieve/sieved.c
- sieve/tree.c
This removes parsing and generating bytecode for the legacy and notify and denotify actions, but will still execute them in already compiled bytecode.
The only outstanding question is if `sieved -s` should spit out legacy notify/denotify actions or replace denotify with a comment and update notify to use enotify syntax.
DO NOT merge this until the Fastmail UI has been updated to using enotify syntax.
> Sieve: remove support for legacy notify & denotify actions

- cassandane/Cassandane/Cyrus/ID.pm
- cassandane/Cassandane/Cyrus/Notify.pm
- cassandane/Cassandane/Cyrus/Simple.pm
- imap/imapd.c
- imap/imapd.h
The goal is, during an IMAP session, to keep track of interesting behavior, and then log it all at the end.  This reduces the need to put syslog lines in all over the place, and also reduces the need to correlate the lines to get a total picture of the session activity.
The real driver here is answering "Which IMAP clients use feature XYZ?"  If they identify with `ID` and we log that along with the behaviors seen, we can then:
* gather all the logs over a week or two
* group them by client id (by "name")
* union all the did-see-feature-X flags
* the end!
This means:
* making a new struct to track seen behaviors
* populating it as the session continues
* log it at session end
* reset it before new session begins
> track the behavior seen by clients

- cassandane/Cassandane/Cyrus/Fetch.pm
- imap/index.c
- imap/index.h
FETCH of BINARY, BINARY.PEEK, or BINARY.SIZE are supposed to fail and report `[UNKNOWN-CTE]` if the requested message section has an unknown Content-Transfer-Encoding.  For FETCH, we were failing and reporting "No matching messages".  For UID FETCH, we were succeeding(!) but not outputting the requested section.
We already detected and returned the `IMAP_NO_UNKNOWN_CTE` error condition in `index_fetchsection()`, but the result was discarded by `void index_fetchresponses()` on the way back up the stack, and never sent to the client.
This PR changes `index_fetchresponses()` to return `int`, and plumbs the error through  so that `cmd_fetch()` can eventually send the correct response back to the client.  It also ensures that if some part of the fetch has failed, other parts succeeding do not …
> fix FETCH BINARY response for unknown CTE

- cassandane/Cassandane/Message.pm
- cassandane/Cassandane/Test/DateTime.pm
- cassandane/Cassandane/Util/DateTime.pm
Continuation of #4500 which github has become confused about
This fixes a bug whereby if you ran Cassandane when your local time month differed from the UTC month, a bunch of tests would fail due to expected timestamps not matching actual timestamps.  That is, if your local time is ahead of UTC, these tests would fail early in the morning on the first day of the month.  If your local time is behind UTC, it would be late at night on the last day of a the month.
This mostly only affected me, since my local TZ is far enough from UTC that the affected window overlaps my usual work hours.
Turns out the bug was in Cassandane's own `to_rfc3501()` function.  It looks like `to_rfc822()` was once afflicted by a similar bug, which was fixed a long time ago, but `to_rfc3501()` was overlooked at the …
> fix cass local month race bug

- cassandane/tiny-tests/JMAPEmail/email_get_bodyvalues_crlf
- cassandane/tiny-tests/JMAPEmail/email_get_bodyvalues_nulbyte
- cunit/charset.testc
- imap/cyr_ls.c
- imap/http_rss.c
- imap/index.c
- imap/jmap_mail.c
- imap/jmap_mailbox.c
- imap/jmap_notes.c
- imap/jmap_util.c
- imap/jmap_util.h
- imap/mboxname.c
- imap/message.c
- lib/charset.c
- lib/charset.h
Sometimes we see HTML emails containing body parts with NUL bytes, e.g. 
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html;charset=utf-8
<html><body>hello=00 world</body></html>
This currently makes Cyrus truncate this body value at the first occurrence of a NUL byte.
I'm not entirely convinced NUL is legit in HTML, looking at its current definition of the [PLAINTEXT state](https://html.spec.whatwg.org/multipage/parsing.html#plaintext-state) and the ilk. But in any case we should do what everyone else is doing, which is omitting these bytes from the decoded body.
This PR just does that.
> JMAP Email: ignore NUL bytes in Email/get bodyValues

- cassandane/tiny-tests/JMAPEmail/email_get_createdmodseq
- imap/conversations.c
- imap/conversations.h
- imap/jmap_mail.c
This gives us a stable sort when multiple external messages are appended very quickly, giving them the same internaldate.
This is being added without a new version number, as it extends a data structure in a backwards and forwards compatible way.  If not set, the CREATEDMODSEQ field will be zero, which is fine.  This will still lead to correct sorting for newly added emails on any thread.  The only slight weirdness might be if an existing message in a thread gets moved or copied into a new folder, which will lead to it getting a createdmodseq value, and hence sorting to the end for that internaldate. This will be very rare, and a convdb rebuild will fix it.
> conversations: sort thread by createdmodseq if same internaldate

- docsrc/imap/download/release-notes/3.6/x/3.6.0-beta1.rst
- docsrc/imap/download/release-notes/3.6/x/3.6.0-beta2.rst
- docsrc/imap/download/release-notes/3.6/x/3.6.0-beta3.rst
- docsrc/imap/download/release-notes/3.6/x/3.6.0-rc1.rst
- docsrc/imap/download/release-notes/3.6/x/3.6.0-rc2.rst
- docsrc/imap/download/release-notes/3.6/x/3.6.0.rst
- docsrc/imap/rfc-support.rst
Mention IMAP SAVEDATE and OBJECTID extensions.
Based on `git diff cyrus-imapd-3.4..cyrus-imapd-3.6 imap/imapd.c`.
The CARDDAV:address-data conversions are implemented in b39dddff2e5bf72528752de and f232075061cdede1a93292.
- update rfc-support.rst on current CardDAV implementation.
> Update 3.6.0 release notes

- cassandane/Cassandane/Cyrus/Expunge.pm
- imap/conversations.c
- imap/imapd.c
- imap/index.c
- imap/jmap_backup.c
- imap/mailbox.c
- imap/mboxlist.c
- imap/search_query.c
- imap/search_query.h
- imap/sieve_db.c
Backport of #4359 for 3.6, because we need a164795dc to fix #4611.
Most of this cherry-picked reasonably cleanly, the only commits I'm not confident about are the last two:
* imapd: always refresh index on SEARCH
This was 74a6462be, and updated the combined SEARCH/ESEARCH code from #4321, which 3.6 doesn't have.  I think I've distilled the essence out correctly for the older code, but I'm not sure.
* search_query: need_expunge is bogus
Not sure if I want this on 3.6, it doesn't seem locking-related, more of a while-we're-in-here-anyway.  I'm a little concerned that it "weirds CONVMULTISORT".
> 3.6: backport "lock ordering fixes"

- cassandane/tiny-tests/JMAPCalendars/calendar_changes_shared
- imap/jmap_calendar.c
This changes the Calendar/changes code to report any unshared calendar ids in the current modseq window as destroyed, rather than omitting them from the response.
This is required so that clients can remove calendar ids from their shared account cache, in case such calendars get unshared for the authenticated user.
As for Mailbox/changes, this has the drawback that calendar ids of calendars hidden to the authenticated user get reported.
> JMAP Calendars: report unshared calendars as destroyed

- imap/tls.c
In set_cert_stuff() the parameters are xstrdup()ed once again.
> tls.c:tls_init_clientengine() memory leak

- cassandane/Cassandane/Config.pm
- cassandane/Cassandane/Cyrus/Info.pm
- imap/cyr_info.c
`cyr_info` was overlooked when adding BYTESIZE support, leading to `abort()` on the unrecognised option type when the `conf`, `conf-all`, or `conf-default` sub-commands were executed.
The fix itself is trivial -- `OPT_BYTESIZE` just needs to be handled the same as `OPT_DURATION` in these functions (`do_conf()` and `do_defconf()`).  The greater part of this PR is in updating our tests to detect this class of problem in the future.
We used to have a test for `cyr_info conf` that would have exposed the crash, but our config handling changed at some point, the test was disabled rather than updated, and so we no longer had such a test.  The changes here bring that test back and update it for current reality, as well as add similar tests for `cyr_info conf-all` and `cyr_info conf-default`.
If …
> cyr_info BYTESIZE suppport

- cassandane/Cassandane/Cyrus/JMAPTestSuite.pm
- cassandane/Cassandane/Cyrus/JMAPTestSuiteWS.pm
- cassandane/Cassandane/Cyrus/TestCase.pm
- changes/next/jmaptestsuite-squatter-race
- imap/squatter.c
This PR adds support for rolling squatter running as a wait daemon.  Which is to say, when invoked from the DAEMON section of cyrus.conf, `squatter -R` now behaves correctly when the wait=y cyrus.conf parameter is present.
It also adds the ability for Cassandane test suites to request such a squatter setup, rather than needing to arrange to start and stop squatter themselves, and updates JMAPTestSuite and JMAPTestSuiteWS to use this feature.
There was a race condition whereby some no-op JMAP-TestSuite tests would fail when run under valgrind.  They were finishing and returning before squatter had fully started (specifically, it hadn't installed its signal handlers yet).  The test being over, Cassandane would signal squatter to shut down, squatter would exit immediately due to the …
> squatter: support running as a wait daemon

- cassandane/Cassandane/Cyrus/Conversations.pm
- changes/next/conversations-basecid-on-copy
- imap/conversations.c
- imap/conversations.h
- imap/ctl_conversationsdb.c
- imap/jmap_backup.c
- imap/mailbox.c
- imap/message.c
OK - this turned out to be surprisingly complex!
Rob M reported to me that a user was seeing blank messages in the Fastmail UI.  Symptom was "Email/query returns emailIds that Email/get says notFound for".
I discovered that there were messages with a missing basecid - the same GUID was in two separate folders, and in one it had a basecid, in the other not.  This was for a split conversation.  I quickly realised that the fix I put in a while back for copying the CID for the same GUID wasn't also copying the basecid.
So, I fixed that - but realised to get the basecid, we needed to store it in every G key.  So I added that (only if you have uuid folders, I figured that was better than doing some odd/even version magic).
Then I found more issues when testing.  Turns out, if there was more …
> Conversations correct basecid

- cassandane/Cassandane/Cyrus/Rename.pm
- changes/next/xrename-command
- imap/imapd.c
Found with a Fastmail user rename failing due to parse errors in Mail::IMAPTalk with a very odd folder name.  I figure we may as well astring quote them!  Makes for a more useful output.
> Make RENAME not spit out all the intermediate folder names

- docsrc/imap/reference/admin/sieve.rst
Commit 175cb0ff0f232 added:
```
+* Regular Expression Extension `Draft RFC <http://tools.ietf.org/html/draft-ietf-sieve-regex-01>`_ 
+* Checking mailbox status and accessing mailbox metadata :rfc:`5490` +* Notify Extension :rfc:`5435`
+* IMAP flag Extension `Draft imap flags RFC <http://tools.ietf.org/html/draft-ietf-sieve-imapflags-05>`_ 
+* Body Extension `Draft body extension RFC <http://tools.ietf.org/html/draft-ietf-sieve-body-02>`_ 
+
+Note that the final RFCs of these last sieve extensions have significant changes that are not currently supported.
```
RFC 5232 Sieve: Imap4flags Extension and RFC 5173 Sieve: Body Extension are implemented since at least c2676ba133ed507, that is year 2015. The removed text means the IETF-drafts cited above.
This change shall be backported to …
> admin/sieve.rst: update on former drafts

- imap/lmtp_sieve.c
It is executed already at the beginning of the function.
> lmtp_sieve:sieve_imip() skip a buf_reset(&imip->err) call

- sieve/bc_parse.c
In bc_eval.c after bc_test_parse() the value of test.type is read, so it must be initialized, for instance to BC_ILLEGAL_VALUE.
> sieve/bc_test_parse() always set test->type

- imap/imapd.c
- imap/imapd.h
This adds client behavior logging for ENABLE of QRESYNC, CONDSTORE, or IMAP4rev2.
> client behavior: expand logging for uses of ENABLE

- imap/jmap_mailbox.c
After `break`, `return` and `goto`  ELSE does nothing.
> jmap_mailbox:_mboxquery_cb() memory leak

- cassandane/tiny-tests/JMAPCalendars/calendar-set-shared-sort-order
- imap/http_dav_sharing.h
- imap/jmap_calendar.c
Fixes an issue where sharing via DAV (Apple clients) wouldn't allow JMAP clients to update calendar properties, e.g. sortOrder
> DAV Sharing: add ACL_WRITE for read-only so JMAP account isReadOnly=false

- imap/imapd.c
Probably this code was copied from GETANNOTATION, and one instance of that command name got left in the new code.  Also, probably this code path is never entered, but… it should still be correct!
> imapd.c: fix command name in GETMETADATA error

- imap/cyr_buildinfo.c
When building without sieve (`./configure --disable-sieve`), compilation fails on imap/cyr_buildinfo.c because of missing headers and, in turn, missing symbols.
This simple patch (a bunch of #ifdefs) fixes the issue.
(Perhaps it's nonsense to build without sieve, I don't know, but I wanted actually just the CalDAV functionality + the minimum necessary requirements).
> Fix build with disabled sieve

- .github/workflows/main.yml
This adds the output of `cyr_buildinfo` to the "report cyrus version" section of CI.
It's not normally useful, but may be when diagnosing CI weirdnesses in the future.
> github actions: report cyr_buildinfo details

- perl/imap/Makefile.PL.in
- tools/fixsearchpath.pl
This fixes a couple of problems that were making `cyradm` not work on my system:
IMAP.so (for Cyrus::IMAP) needs to be linked with the regex library, but wasn't.
The boilerplate added to perl scripts by `tools/fixsearchpath.pl` (to detect and compensate when Cyrus has been installed with a `DESTDIR`) was assuming `$bindir` contains the full path, when it actually just contains the path relative to `$prefix`.  As a result, it was mistaking `$prefix` for `DESTDIR`, trying to compensate for it, and then being unable to find its dependencies.  The fix is to use the full `"$prefix$bindir"` path where the full path is expected.
I guess we've never really noticed this because we don't use `cyradm`, and others are probably installing to a standard prefix that perl already knows to look in, in …
> small cyradm fixes

- configure.ac
This will make compiler warnings more visible by default.
> configure.ac: add AM_SILENT_RULES([yes])

- imap/lmtp_sieve.c
- imap/lmtpd.c
Otherwise when `processimip` calls `caldav_store_resource()` → `strip_vtimezones()` → `zoneinfo_lookup()` the timezones are never found.  Then the known timezones are not stripped from the iCalendar object.
> lmtp_sieve.c:sieve_imip() call `zoneinfo_open(NULL)` during initialization

- cassandane/tiny-tests/JMAPEmail/email_query_sieve_8bit_header
- cunit/charset.testc
- imap/message.c
- lib/charset.c
- lib/charset.h
This fixes an issue with malformed MIME headers where implementations store arbitrary UTF-8 strings without encoding them as defined in RFC 2047. This impacts JMAP Email/query filters during Sieve evaluation.
Such headers already were handled leniently for stored messages, e.g. ones having a cache record. Now messages without cache record also allow undecoded UTF-8 values.
> JMAP Sieve: do not decode valid UTF-8 strings in MIME headers

- cassandane/tiny-tests/JMAPCalendars/itip_ignore_invalid_timezone
- imap/http_caldav.c
- imap/http_ischedule.c
- imap/ical_support.c
- imap/ical_support.h
- imap/lmtp_sieve.c
- imap/zoneinfo_db.c
Sometimes a client send iTIP requests containing invalid VTIMEZONE definitions such as
BEGIN:VTIMEZONE
TZID:UTC
END:VTIMEZONE
Cyrus is perfectly capable of making sense of this VTIMEZONE, so let's leniently accept bogus VTIMEZONEs in iTIP messages if they can be mapped to an IANA timezone. This only applies for iTIP, such iCalendar data still gets rejected during PUT and import.
> lmtp_sieve: ignore VTIMEZONE errors for IANA timezones

- cassandane/Cassandane/Cyrus/Caldav.pm
- imap/mboxevent.c
This wasn't caught by the initial Cass test because it wasn't requesting the DAV UID for the event
> mboxevent.c: properly handle DAV URLs with percent-encoded UTF-8 chars

- cassandane/Cassandane/Cyrus/JMAPTestSuite.pm
- cassandane/Cassandane/Cyrus/JMAPTestSuiteWS.pm
There's a few tests that JMAP-TestSuite skips when it detects the backend is Cyrus, but Cassandane still has to set up and then tear down a Cyrus instance for these tests because it doesn't know they'll be skipped.
This PR gives knowledge of that to Cassandane, so it too can skip them.
> cassandane: skip tests that JMAP-TestSuite will have skipped anyway

- .github/workflows/main.yml
- cassandane/doc/README.deps
Quick fix to get CI working again.  The better fix would be to have the docker image pull libxml-simple-perl from apt.
> cassandane needs XML::Simple

- cassandane/Cassandane/Cyrus/SearchSquat.pm
- cassandane/Cassandane/Cyrus/TestCase.pm
- changes/next/4660-squatdb-fixes
- imap/search_engines.h
- imap/search_squat.c
- imap/squat_build.c
Fixes three bugs found in the Squat search backend while investigating #4660  
1) Reindexes were always incremental, regardless of whether or not the `-i` option was passed to squatter.  The `flags` argument handling has been fixed.
2) Messages parts that weren't supposed to be indexed were indexed anyway due to state not being set/checked/cleared properly in `begin_part()`/`append_text()`/`end_part()`.  The affected text was indexed into the wrong document if you were lucky, or corrupted the index if you weren't.  The state management has been fixed by making sure to check and clear `d->doc_name`.
3) `doc_ID_map` started at zero, but its callers and bounds checks expected it to start at 1, leading to accesses past the end of the valid data, and the assertion failure from the original …
> various squat fixes

- imap/mailbox.c
This fixes a `#jmap` folder bug when we are zeroing CIDs.
> mailbox_update_webdav: don't create resource names if no filename

- cassandane/tiny-tests/JMAPCalendars/calendar-set-defaultalerts
- imap/jmap_calendar.c
This fixes a bug where updating just one of the Calendar defaultAlertsWithTime and defaultAlertsWithoutTime properties resulted in erasing the contents of the other.
> jmap_calendar: fix bug erasing default alerts on update

- imap/http_carddav.c
(also plug charset leak in carddav_put())
> http_carddav.c: write a propfind_addrdata() variant to use libicalvcard

- imap/mbexamine.c
It is a danger if really type mismatch.
> Drop needless cast for time_t

- imap/search_expr.c
It is unsafe, especially, sizeof(void*) < sizeof(uint64_t). Change to cast through uintptr_t instead.
> prevent to cast from pointer to uint64 directly

- imap/jmap_contact.c
This is dependent on https://github.com/libical/libical/pull/584/commits/7991a1b24786cec871664e380064afba17f2098a
@rsto please review the libicalvcard change as well
> jmap_contact.c: libicalvcard will escape comma in JSCOMPS separator

- imap/cyr_cd.sh
`function` keyword is not required to declare functions.
Additionally, prevent to overwrite global scope variables.
> cyr_cd.sh: change to POSIX sh style

- imap/imapd.c
- imap/message.c
- imap/partlist.c
- imap/quota.c
- imap/squat_build.c
- lib/arrayu64.c
- lib/bitvector.c
- lib/bufarray.c
- lib/dynarray.c
- lib/ptrarray.c
- lib/strarray.c
- lib/xmalloc.c
- lib/xmalloc.h
Adds an `xzrealloc()` function that's like `xrealloc()` but also zeroes out the newly allocated bytes if the allocation grew in size.  n.b. It needs one more argument than regular `xrealloc()`, so it's not a drop-in replacement.
> add xzrealloc

- cassandane/Cassandane/Cyrus/Carddav.pm
- imap/carddav_db.c
- lib/vparse.c
- lib/vparse.h
N and NICKNAME are structured and multivalued properties respectively, so the components are stored in a strarray_t, NOT a char*.  By blindly trying to use entry->v.value we were always storing empty values in DAV DB for these properties.
The addressbook-query test validates the fix.
> carddav_db.c: actually store N and NICKNAME values

- imap/relocate_by_id.c
From missing a header,  `basename()` may be recognized as return type `int`.
> <libgen.h> is required for basename(3)

- imap/jmap_expire.c
Full details in #4689.  tl;dr: on Linux, `basename()` behaves differently depending on whether or not libgen.h was included.  We want the POSIX behaviour, not the GNU behaviour.
> jmap_expire: need libgen.h for POSIX basename behaviour

- cassandane/Cassandane/Cyrus/SearchSquat.pm
- imap/search_query.c
The squat backend returns false positives for unindexed messages, but filtering these messages has been broken.
This patch fixes that based on a contribution of @gbulfon. Thanks!
Fixes #4692
> search_query: fix filtering unindexed messages in squat backend

- imap/jmap_expire.c
- imap/mboxname.c
- imap/telemetry.c
- ptclient/ldap.c
Change to use `TIME_T_FMT` for `tv_sec` (time_t), and fix to zero prefix for `tv_nsec` and `tv_usec`.
Use `unsigned long long` for HEX format of `time_t`, `int` may be short.
> fix print format for timespec and timeval

- imap/search_engines.c
This was lost in ba7fc3ab14f0a843df3f95ec1249115fa7744c54 when refactoring to allow better lock handling.
> search_engines: fix batching

- cassandane/Cassandane/Cyrus/Conversations.pm
- docsrc/imap/reference/manpages/systemcommands/ctl_conversationsdb.rst
- imap/ctl_conversationsdb.c
This allows us to zero out just a single CID, rather than everything - it's to help fix up the "same email, multiple CIDs" bug that we currently have - we can just nuke each of those cids.
Ideally you'd give a list of CIDs to zero, but that's a bunch more work to build, and this will be fast enough because usually it's just a couple of CIDs for each user.  Zeroing EVERYTHING is much slower and breaks the mailbox for a bit.
> Convdb zero singlecid

- cassandane/Cassandane/Cyrus/Caldav.pm
- configure.ac
- imap/cyr_buildinfo.c
- imap/ical_support.c
This changes the libical parser to silently discard invalid CONTROL characters from iCalendar data. Before, it silently accepted such invalid bytes and Cyrus then served invalid data to CalDAV clients.
This requires https://github.com/libical/libical/pull/651
> ical_support: configure libical to omit CONTROL characters

- cassandane/Cassandane/Cyrus/JMAPMailbox.pm
- imap/jmap_mailbox.c
- imap/mboxlist.c
This is actually two fixes!
First, I discovered that an entire important test was being killed with a `return;` at the top!  Ouch.  I discovered this when trying to add to it.
I had to fix that test, during which I discovered a bug with isSubscribed == false, so there's a fix for that.
Then the actual fix, which was discovered when testing with the TMail client - our server wasn't bumping the state string for the mailbox when changing the isSubscribed value.
> Subscriptions bump folderstate

- cassandane/Cassandane/Cyrus/Flags.pm
- imap/mailbox.c
- lib/xmalloc.h
This fixes a crash that can occur during cleanup up after copy/append failures when the mailbox on which the copy/append failed happened to have custom userflags.  Seen in the wild a couple of times at Fastmail.  @wolfsage found a way to reproduce it, which the Cassandane test is based on.  The cause of the crash turned out to be memory corruption resulting from calling the `xzfree()` macro -- which evaluates its `ptr` argument multiple times -- with an argument containing side effects.
It also hardens up the `xzfree()` macro somewhat to hopefully prevent this sort of thing in the future.  With the compiler options I use, the original misuse is now detected at compile time as a `sequence-point` warning, due to the comparison in the assert expression having an undefined evaluation order. …
> fix userflags corruption crash

- imap/mboxlist.c
- imap/mboxname.c
- imap/quota.c
- imap/quota.h
- imap/quota_db.c
- imap/user.c
- lib/imapoptions
If the config is set, or there is a file with the username in the directory, then abort if any attempt is made to call `nextmodseq` or `nextuidvalidity`, instead only sync_server writes are allowed.
This branch also fixes two bugs found by this test already.
> Add a 'replicaonly' config option and directory

- imap/ctl_conversationsdb.c
If we're already over the limits, there's nothing we can do about it short of removing messages, which this tool doesn't do.
When I rebuilt Fastmail users after fixing the CID/THRID mismatch, some failed to complete due to this error.
> ctl_conversationsdb: ignore limits when rebuilding

- imap/mailbox.c
When I call  dav_reconstuct user  syslog emits
> dav_reconstruct_user: user FAILED Message %d no longer exists
`%d` is literally contained in the log.  dav_db.c:dav_reconstruct_user() calls dav_db.c:_dav_reconstruct_mb():
```c
case MBTYPE_CALENDAR:
case MBTYPE_COLLECTION:
case MBTYPE_ADDRESSBOOK:
addproc = &mailbox_add_dav;
…
if (!r) r = addproc(mailbox); //⇔ same as mailbox_add_dav(mailbox)
```
and mailbox.c:mailbox_add_dav() calls
```c
while ((msg = mailbox_iter_step(iter))) {
const struct index_record *record = msg_record(msg);
r = mailbox_update_dav(mailbox, NULL, record);
if (r == IMAP_NO_MSGGONE) {
if (record->internal_flags & FLAG_INTERNAL_EXPUNGED) {
/* Already expunged */
continue;
}
…
}
} // while
return r;
```
So when the last record is “gone”, mailbox_add_dav() and …
> mailbox.c:mailbox_add_dav() - return no error for already expunged messages

- imap/imapd.c
- imap/imapd.h
Over lunch with a few implementers it was asked if any clients use these extensions.  I told them that we can and will gather some data.
> imapd.c: log client use of BINARY and CATENATE

- imap/imapd.c
Expecting that this will become a standard since its a WG doc
> imapd.c: move LIST-METADATA into the "standard" section of extensions

- .github/workflows/main.yml
because I don't remember what version this runs, and this way nobody has to, it's right there in the report
> github-actions: report debian version

- changes/next/pcre2-support
- configure.ac
- docsrc/assets/cyrus-build-devpkg.rst
- docsrc/assets/cyrus-build-reqpkg.rst
- docsrc/imap/developer/compiling.rst
- docsrc/imap/download/upgrade.rst
- imap/cyr_buildinfo.c
- lib/util.h
- ptclient/test3.c
- sieve/bc_eval.c
- sieve/comparator.h
- sieve/sieve.y
* Adds pcre2 support based on #4545, but without removing legacy pcre support
* Updates pcre/pcre2 checks to use pkg-config, which should fix #4711 
* Prefers pcre2 over pcre if both are available
Fixes: #3861 #4711
> add pcre2 support

- cassandane/Cassandane/Cyrus/Master.pm
- changes/next/master-ready-file
- configure.ac
- docsrc/imap/reference/manpages/systemcommands/master.rst
- lib/imapoptions
- master/master.c
This makes master(8) write out a ready file at the same time as it logs its "ready for work" message.  For things that want to know when master is ready to start servicing clients, monitoring the ready file (perhaps with inotify) should be a bit cleaner than tailing syslog looking for the message.
Adds `master_ready_file` to imapd.conf, defaulting to `{configdirectory}/master.ready`.  Also adds a `-r ready_file` option to master to override the configured path.
Adds cassandane tests for the case where the ready file does not yet exist, and the case where it already exists.  No test for the `-r ready_file` option, because it would take a lot to plumb that through.
> master ready file

- cassandane/Cassandane/Cyrus/Sieve.pm
- cunit/buf.testc
- lib/glob.c
- sieve/sieve.y
This fixes a crash seen in the wild at Fastmail when Cyrus is built with PCRE2 rather than PCRE.
Looks like the PCRE2 `pcre2_regcomp()` has different behaviour from the POSIX or PCRE1 `regcomp()` when the pattern fails to compile.  In this case the PCRE2 version doesn't touch its regex_t argument.  If it wasn't already initialized otherwise, it will remain uninitialized, and a later call to `pcre2_regfree()` will crash.
That means we need to be sure to initialise regex_t objects, not rely on `regcomp()` to do it.
> fix pcre2 crash when regex_t uninitialised

- cassandane/Cassandane/Cyrus/Annotator.pm
- cassandane/Cassandane/Cyrus/Conversations.pm
- cassandane/Cassandane/Cyrus/Delete.pm
- cassandane/Cassandane/Cyrus/Delivery.pm
- cassandane/Cassandane/Cyrus/Expunge.pm
- cassandane/Cassandane/Cyrus/FastMail.pm
- cassandane/Cassandane/Cyrus/Flags.pm
- cassandane/Cassandane/Cyrus/ID.pm
- cassandane/Cassandane/Cyrus/JMAPCore.pm
- cassandane/Cassandane/Cyrus/JMAPMailbox.pm
- cassandane/Cassandane/Cyrus/Master.pm
- cassandane/Cassandane/Cyrus/Metadata.pm
- cassandane/Cassandane/Cyrus/Notify.pm
- cassandane/Cassandane/Cyrus/Quota.pm
- cassandane/Cassandane/Cyrus/Reconstruct.pm
- cassandane/Cassandane/Cyrus/Replication.pm
- cassandane/Cassandane/Cyrus/SearchFuzzy.pm
- cassandane/Cassandane/Cyrus/SearchSquat.pm
- cassandane/Cassandane/Cyrus/Sieve.pm
- cassandane/Cassandane/Cyrus/TestCase.pm
- cassandane/Cassandane/Instance.pm
- cassandane/tiny-tests/JMAPCalendars/calendarevent-ignore-orphaned-ical-rows
- cassandane/tiny-tests/JMAPEmail/email-set-update-too-many-mailboxes-lowlimit
- cassandane/tiny-tests/JMAPEmail/searchsnippet-search-maxsize
This reduces the amount of boilerplate needed to check for syslog messages from Cassandane tests.
* Adds an optional pattern parameter to `getsyslog()`, so you can filter the lines without an extra step
* Adds `assert_syslog_matches()` and `assert_syslog_does_not_match()` for the common case where you just want to check whether syslog does or does not contain any lines matching some pattern.
* Updates existing tests to use the new features where it makes sense to
Note that the new assertions call `getsyslog()` themselves, so they're _not_ useful if you want to check for multiple patterns at once, because the first call will read all the available lines, and the subsequent calls won't find any.  For that sort of thing you should still use `getsyslog()` directly to read the lines, then …
> improve cassandane getsyslog

- imap/mailbox.c
- imap/sync_support.c
This fixes a crasher found in Fastmail production with forcesync and a higher modseq on the replica (likely caused by user moves)
> Fix forcesync

- imap/http_dav.c
- imap/http_err.et
- imap/ical_support.c
- imap/vcard_support.c
respond with 422 (Unprocessable Content)
> DAV propfind: don't crash if we fail to transform iCal/vCard data

- imap/pop3d.c
Works around some Thunderbird bug.  Based on patch provided and tested in #4717 by @yaonos
Fixes: #4717
> pop3d: try to not split ".\r\n" across packet boundary

- lib/glob.c
broken by ba43ab2462adca1a6f2dbfc54d967f02bd1dcb33, reported by @yselkowitz in comment on #4741
> glob: fix missing include

- .gitignore
- cmulocal/ax_cxx_compile_stdcxx.m4
- cmulocal/ax_cxx_compile_stdcxx_11.m4
- cmulocal/ipv6.m4
- configure.ac
This fixes up a bunch of configure details that were misdetected due to test programs with warnings failing to compile because of `-Werror` (rather than because of the feature being unavailable)
> fix configure.ac problems under -Werror

- docsrc/imap/developer.rst
- docsrc/imap/developer/coverage.rst
Adds documentation for producing test coverage reports
@rsto I seem to remember you asked for this; here it is, at last :)
> docs: coverage reports

- imap/http_carddav.c
- imap/index.c
- imap/vcard_support.c
Also, don't return ETag on CardDAV PUT if we stripped
This PR is required when compiled against libicalvcard with:
https://github.com/libical/libical/pull/584/commits/771beabb5f28fa72b84b1b5dd6b11b3494fff00a
which now inserts X-LIC-ERR for non-fatal parse errors and continues to parse.
This allows us to parse and accept vCards with bogus properties such as REV:REV even if they already exist on disk.
> vCard: strip any X-LIC-ERR properties

- imap/jmap_calendar.c
This is required for libxml2 2.12.0 and above.
Missing piece in PR #4745.
Revealed when compiled with --enable-jmap.
> Add libxml/parser.h include (2)

- cassandane/Cassandane/Cyrus/Delete.pm
- cassandane/Cassandane/Instance.pm
- imap/mailbox.c
Skip the hierarchy walk component of `mailbox_delete_cleanup()` when the mailbox being deleted uses UUID storage (which has no hierarchy on disk).  This prevents it inadvertently trying to delete the single character hash directories and then logging spurious "Remove of supposedly empty directory %s failed" messages when they're inevitably not empty.  At Fastmail, this message is currently spuriously logged around 100,000 times a day...
> mailbox: no hierarchy walk when deleting uuid mailboxes

- imap/tls_th-lock.c
`./configure --without-openssl && make` produces
```
External dependencies:
openssl:            no
…
CC       imap/libcyrus_imap_la-tls_th-lock.lo
imap/tls_th-lock.c:11:10: fatal error: openssl/ssl.h: No such file or directory
11 | #include <openssl/ssl.h>
|          ^~~~~~~~~~~~~~~
```
This change permits compiling Cyrus IMAP after `./configure --without-openssl && make`, when `ssl.h` is missing.
> tls_th-lock.c: compile without ssl.h

- imap/promstatsd.c
The message so far read
cyrus/promstatsd[17284]: Prometheus metrics are not being tracked.  Set prometheus_enable in imapd.conf
and I added that setting to my imapd.conf, which didn't solve the problem. Further investigation resulted in detecting that the parameter actually is called "prometheus_enabled" and not "prometheus_enable".
Let's fix the error message to avoid others falling into the same trap.
> fix typo in promstatsd error message

- configure.ac
- imap/xapian_wrap.cpp
Xapian development version 1.5 changed the flag names of CJK word break segmentation. This patch adapst our Xapian wrapper to use the new names but keeps falling back using the previous ones for older installations.
Note that this only matters when using any of the 1.5 development versions, the flag names are not part of any stable Xapian API so far.
See https://github.com/xapian/xapian/commit/13295e9142f56911d4876fb92271df348759c34b
> xapian_wrap.cc: adapt word break flags to Xapian API change

- cassandane/Cassandane/Cyrus/SearchFuzzy.pm
The XSNIPPETS and XCONVMULTISTANDARD commands in Cyrus got deprecated, so don't keep our test using it.
> SearchFuzzy.pm: do not use non-standard XSNIPPETS command

- cunit/message.testc
- imap/message.c
This fixes a bug introduced in e14ef0ad88303450 in which an invalid first Received header value might lead to a less recent Received header value being read.
> message.c: only attempt to read first Received header date

- cassandane/Cassandane/Cyrus/Fetch.pm
- cassandane/Cassandane/Cyrus/InProgress.pm
- cassandane/Cassandane/Cyrus/Search.pm
- changes/next/imap-partial
- cunit/imparse.testc
- docsrc/imap/rfc-support.rst
- imap/append.c
- imap/append.h
- imap/imapd.c
- imap/imapd.h
- imap/imapparse.c
- imap/index.c
- imap/index.h
- imap/jmap_mail.c
- imap/jmap_mailbox.c
- imap/search_query.c
- imap/search_query.h
- lib/imapoptions
- lib/imparse.c
- lib/imparse.h
This PR mainly adds support for IMAP PARTIAL and INPROGRESS extensions but also does some code reorganization and adds an optimization for SEARCH with a sequence set at the toplevel of the criteria.
This PR is best reviewed commit-by-commit
> IMAP PARTIAL and INPROGRESS support

- imap/httpd.h
not in “Almost Standards Mode”.  Cf. https://hsivonen.fi/doctype/
This hides a warning on the browsers’ console for Cyrus IMAP generated webpages.
> Generate HTML content in “Standards Mode”

- imap/http_admin.c
- imap/http_caldav.c
- imap/http_caldav_sched.c
- imap/http_carddav.c
- imap/http_webdav.c
- imap/httpd.c
This permits rendering of the webpages and iMIP messages nicely in dark mode.
In http_rss.c I have not changed it, as [I cannot get it running](https://github.com/cyrusimap/cyrus-imapd/issues/4616).
If the task of jmap_mail:_html_concat_div() is to prepare HTML-mails for rendering in an embedded element, and the html email has `<html style='color-scheme: dark light'>` then to me it seems that the color-scheme information will be lost.
In jmap_mail.c:_emailbodies_to_html() there is one more occurrence of `<html`.
> Add «style='color-scheme:dark light'» to some HTML output

- cassandane/Cassandane/Cyrus/Simple.pm
- cassandane/utils/syslog.c
- changes/next/toggleable-debug
- imap/global.c
- imap/imapd.c
- lib/imapoptions
- lib/libconfig.c
- lib/libconfig.h
- lib/signals.c
This adds an API such that `config_debug` (aka "debug:" in imapd.conf) can be toggled on and off at runtime, and hooks up a signal handler such that SIGUSR1 will toggle it.  The test case tests this with `imapd`, but it should work the same for any Cyrus process (specifically, any process that calls both `cyrus_init()` and `signals_add_handlers()`).
You can already crudely toggle debug logging by changing debug: in imapd.conf and sending master a SIGHUP, but that a) affects all Cyrus process, b) only after they restart and reread the config, and c) also picks up other unrelated config changes.  This PR allows toggling debug logging on or off for a specific process, while that process is already running, and without reloading the config generally.
SIGUSR1 is already used by cunit (for test …
> runtime toggleable debug logging

- imap/xapian_wrap.cpp
It was checked before and within the function call, whether val is empty.
> xapian_wrap.cpp:parse_doclangs() check for val.empty() only once

- Makefile.am
I noticed that some commands do not have their manpages pre-generated in troff (i.e. the `man` format) in the dist tarballs, even though their HTML version is included. This PR adjusts the Makefile so the missing manpages are also included in troff and not just HTML.
> Fix missing troff format for some manpages in dist tarballs

- imap/ctl_mboxlist.c
backport of 3be3f16999d724b44c1f009f2eb9c3fe06458825
> 3.6 ctl_mboxlist don't free static data 

- cassandane/tiny-tests/Sieve/implicit-keep-target-stop
- sieve/bc_eval.c
An error will skip filing into a custom implicit keep target
> Sieve: a STOP action should not be an error (exit the processing loop directly)

- .github/workflows/main.yml
GH actions now run on twice as many virtual CPUs (thanks @dilyanpalauzov):
https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/
If we take the opportunity to double our cassandane job count, do our CI runs get noticeably faster? [Looks like they do](https://github.com/cyrusimap/cyrus-imapd/actions) -- our runs usually take ~27 minutes, but the ones for this PR are consistently taking ~20.
> github actions: increase cassandane job count

- .gitignore
- Makefile.am
- changes/next/global-lock
- docsrc/imap/reference/manpages/systemcommands/cyr_withlock_run.rst
- imap/cyr_withlock_run.c
- imap/global.c
- imap/global.h
- imap/mboxname.c
- imap/mboxname.h
- imap/user.c
- imap/user.h
- lib/command.c
- lib/command.h
- lib/imapoptions
This addresses https://github.com/cyrusimap/cyrus-imapd/issues/1763, which has been outstanding for a LONG time, but I'm finally getting to it because I was working on mailbox locking recently, and the user locks and mailbox locks are now consistent enough that it's possible to put this structure into place.
Also, I finally figured out how to make this work sensibly - it's pretty cool - because new locks ALWAYS go on the front of open_mboxlocks, and you can't change a lock from shared to exclusive - it's safe to have shared locks while running this kind of snapshot command - so I could insert the GLOBAL lock before the first exclusive lock of any type, and remove it if it's the front lock, and it guarantees coverage of all writes.  Super simple.  And reads can keep running.
One could also …
> Global lock

- cassandane/Cassandane/Cyrus/Conversations.pm
- cassandane/Cassandane/Cyrus/Quota.pm
- imap/conversations.c
- imap/mailbox.c
- imap/mailbox.h
- imap/mboxlist.c
We found an issue in Fastmail production where a user had done:
1) `rename user.A.foo user.B.foo`
followed by
2) `rename user.B.foo user.A.foo`
Which had caused conversations to be all broken because we weren't correctly detecting this case in the mailbox_rename_nocopy (uuid paths) case.
This PR adds a test for the case, then code to make it work (and yes, I did tdd this!)
> Rename between users

- cassandane/Cassandane/Cyrus/CaldavAlarm.pm
- cassandane/Cassandane/Cyrus/Replication.pm
- cassandane/Cassandane/Cyrus/TestCase.pm
- changes/next/replicaonly
- imap/calalarmd.c
- imap/caldav_alarm.c
- imap/mboxname.c
- imap/user.c
- imap/user.h
- lib/imapoptions
This adds both tests for replicaonly mode (disabled for the tests which MUST actually screw with the replica to test splitbrain recovery!), and support to calalarmd to skip processing for users who are in replicaonly mode.
> Calalarmd replicaonly

- cassandane/Cassandane/Cyrus/JMAPMailbox.pm
- imap/jmap_api.c
\Scheduled has '-anyone' identifier to remove r/w rights which when inherited by #jmap prevents setting \Expunged flag
> jmap_api.c: ignore rights on \Scheduled when adjusting #jmap

- imap/itip_support.c
mbtype isn't a simple bitfield!
> itip_support.c: fix pick_scheddefault_cb()

- cassandane/Cassandane/Config.pm
- cassandane/Cassandane/Test/Config.pm
- cunit/libconfig.testc
While investigating an error (which turned out to be not a Cyrus problem), I found a bunch of shortcomings in how we test bitfields in imapd.conf.
> cassandane bitfield fixes

- cassandane/testrunner.pl
It needs to filter on enable_wanted_properties too, otherwise things like :want_service_http aren't processed, so $self->{caldav} won't be set up leading to this error:
Perl exception: Can't call method "GetEvents" on an undefined value
at Cassandane/Cyrus/Sieve.pm line 5560.
... when testrunner.pl is run with -f xml
> Cassandane testrunner.pl: Fix XML formatter

- imap/cyr_expire.c
- imap/mboxlist.c
- imap/mboxlist.h
- imap/mboxname.c
- imap/mboxname.h
- imap/sync_reset.c
- imap/sync_support.c
This fixes the bumping of RACLMODSEQ on replicas when changes are synced in.  Without this, replicaonly breaks on mailbox creation and deletion if there's shared folders.
We do sync the RACLMODSEQ value along with the mailbox when it syncs, so it's correct not to bump it separately in the update_entry code.
Note: this code also includes and assert that it always gets called with `silent` if replicaonly, which is a nice extra protection and helped with debugging.
> replicaonly: add silent RACL updates and batch them to sync

- cassandane/Cassandane/Cyrus/SearchSquat.pm
- imap/search_expr.c
- imap/search_expr.h
- imap/search_query.c
This was originally fixed in #4698, except it turns out there was additional complexity required that was missed because our tests were inadequate.
The search is split into indexed and unindexed subexpressions.  The indexed subexpression is run through the search engine backend, and the unindexed subexpression is then applied as a filter over the returned results.
The squat engine returns all unindexed messages in its matched set, expecting the post-processing phase to filter them further.  This has been broken (#4692) for a while, because nowadays the post-processing phase doesn't apply the indexed subexpression that squat expects it to, only the unindexed subexpression.
The original fix in #4698 failed to recognise the search having previously been split into separate subexpressions. …
> re-fix filtering unindexed messages in squat backend

- imap/tls.c
This reverts commit a3523d4067c502a52cb7ee859c1493d1a980b7e0.
imapd does crash sometimes, when it handles the TLS connection.  https://github.com/cyrusimap/cyrus-imapd/issues/4785 describes such reports from different users.
In such cases Cyrus can log “no shared cipher in SSL_accept() -> fail” or “unexpected eof while reading in SSL_accept() -> fail”.
The recommendation at https://github.com/openssl/openssl/issues/23031#issuecomment-1879632721 also states, than doing `SSL_SESSION_free()` during remove_session_cb() is wrong.  If there were leaks, there is probably another case where there is a missing SSL_SESSION_free() call but this place is not right.
• backport to 3.10 and 3.8
> Revert "tls.c: need to free SSL_SESSION when removing it from cache"

- imap/index.c
[https://www.rfc-editor.org/rfc/rfc8970.html#name-formal-syntax](url)
> index.c: PREVIEW message attribute MUST be a qstring/literal, NOT an atom

- cassandane/Cassandane/Cyrus/Idle.pm
- cassandane/Cassandane/Cyrus/Info.pm
- cassandane/Cassandane/Instance.pm
IMAPTalk v4.06 now send CAPABILITY command immediately after LOGIN so we lose the LOGIN response
> Idle.pm: pull SESSIONID from procinfo rather than LOGIN response

- cassandane/Cassandane/Cyrus/UIDonly.pm
- cassandane/tiny-tests/UIDonly/fetch
- cassandane/tiny-tests/UIDonly/qresync
- cassandane/tiny-tests/UIDonly/store
- cassandane/tiny-tests/UIDonly/unsolicited
The UIDFETCH data gets returned to the callback as a hash in v4.06 but is an array in v4.04
> UIDonly.pm: account for IMAPTalk +/- v4.06 differences

- imap/search_query.c
_subquery_run_one_folder() can be called with an existing folder so we don't have the chance to set min_uid to last_uid + 1
This bug only appeared with using Xapian for search
> search_query.c: min_uid might start at zero

- imap/http_dav.c
- imap/http_jmap.c
- imap/jmap_api.c
- imap/mboxlist.c
- imap/mboxlist.h
- imap/sync_support.c
I couldn't see an easy way to test this, but code reading showed the mistake, and the Fastmail tests will capture it.
We want to NOT be silent for the non-replication cases, so this change plumbs that through, and removes the confusing 'sync' from the function name since it's used outside the replication code now.
> rename mboxlist_sync_setacls to mboxlist_setacls and add silent flag

- imap/mboxlist.c
- lib/auth_pts.c
- lib/auth_unix.c
Here's the tiny fixes - the pts thing I mentioned, plus a rewrite to stop parsing `group:` as usernames and a use of strarray_find rather than open-coding it in auth_unix.c
> Tiny group fixes

- imap/jmap_mail.c
This fixes a crasher found in FM production, where subpart was NULL.
I'm not sure if this is correct.  Other options would be "return the msg->rfc822part" or "return an error".  Definitely leaving part as NULL isn't right though.
> jmap_mail: if no rfc822 subpart, use regular part

- sieve/sieve-lex.l
I cannot get the warning disappear by any other way.
> sieve-lex.l: fix warning for using function without prototype

- imap/sync_support.c
Fixes a bug found by @wolfsage whereby make_flags would just keep overwriting its own buffer if there were multiple flags to log.  Unlike `snprintf`, `buf_printf` _does_ append rather than overwrite.
If this function is ever called, the `static struct buf`'s internal buffer will be "still reachable" at process exit.  There isn't a good way to clean this up.  I think valgrind doesn't complain about "still reachable" leaks with the configuration we use.  
I've run cunit and the cassandane Replication tests under valgrind without complaint, so maybe it doesn't mind, or maybe no tests exercise this code path. That being the case, better review this one carefully 😅
> sync_support: fix logging multiple flags

- cassandane/Cassandane/Cyrus/TestCase.pm
- cassandane/tiny-tests/JMAPEmail/email_query_sieve_some_in_thread_have_keyword
- imap/message.c
This fixes a bug that has shown up when evaluating JMAP Email queries in Sieve for split conversations.
The some/all/noneInThreadHaveKeyword filter criteria failed, because message_extract_cids returned the conversation id of the first split of all splits in the conversation. This patch changes it to return the very last split which is going to be the one that this message will end up in (unless the message starts a new split).
> message: return newcid annotation values in message_extract_cids

- cassandane/data/mime/utf8-domain.bin
- cassandane/tiny-tests/JMAPEmail/email_get_utf8_domain
- changes/next/parseaddr_utf8_domain
- cunit/parseaddr.testc
- imap/mailbox.h
- lib/parseaddr.c
Email addresses having non-ASCII UTF8 domain parts up until now were parsed incorrectly, leading to truncated email addresses being stored in the mailbox cache and returned in JMAP and IMAP.
This fixes the email address parser to parse such domains and bumps the mailbox minor cache version number.
> Parse email addresses with non-ASCII UTF8 domain parts

- cunit/conversations.testc
- imap/conversations.c
- imap/conversations.h
- imap/mailbox.c
It will be synced anyway; we sync_log the affected mailboxes; and this stops it being accidentally bumped by the replica if the message changes are synced out of order.
> conversations: don't update xconvmodseq on replicas

- cassandane/Cassandane/Cyrus/Replication.pm
- cassandane/tiny-tests/Replication/full_rename
- imap/sync_support.c
- imap/sync_support.h
This set of commits is a test and the code - it adds all the listed mailboxes on both master and replica.  It also fixes any multiple-mailbox sync to always include all the mentioned users, and then check for and either rename or remove any mailbox based on tombstone.
It doesn't solve the XXX case of "mailbox exists on replica and is entirely unknown to master", but that's not a regression.
> Sync user repair

- changes/next/imap_jmapaccess
- docsrc/imap/rfc-support.rst
- imap/imapd.c
- lib/imapoptions
Implementation of 
[https://www.ietf.org/archive/id/draft-ietf-extra-jmapaccess-08.html](url)
without a JMAPACCESS capability (as discussed at IETF 119)
> imapd.c: add support for JMAPACCESS capability and response code

- imap/mailbox.c
- imap/mboxlist.c
- imap/mboxlist.h
- imap/sync_reset.c
Fixes two more replicaonly issues seen in production today!
> Replicaonly reset

- cassandane/tiny-tests/JMAPEmail/email_query_utf8punct_term
- imap/xapian_wrap.cpp
The Xapian wrapper already returned NULL for ASCII query terms that just consisted of punctuation characters. But a query term containing Unicode punctuation codepoints such as EN DASH (U+2013) was parsed as CJK text, returning an empty, always falsible, query instead of NULL.
This issue just showed up for Email/query using uidsearch, but the new test checks all three codepaths: uidsearch, guidsearch and Sieve.
> xapian_wrap: return NULL query for empty CJK terms

- docsrc/imap/download/installation/manage-dav.rst
- docsrc/imap/rfc-support.rst
- imap/http_proxy.c
- imap/httpd.c
- imap/httpd.h
- imtest/imtest.c
As it is removed upstream from cyrus-sasl: https://github.com/cyrusimap/cyrus-sasl/commit/60f2b06ca13f8f1390a11139083104e5a52e1ab0.
Looking at the changes, should SCRAM be mentioned at `imtest/imtest.c:2706:printf("             (\"basic\", \"digest\", \"negotiate\")\n");`?
> Remove support for NTLM

- docsrc/imap/rfc-support.rst
- imap/http_proxy.c
- imap/httpd.c
- imtest/imtest.c
The actual Digest code was removed in #4680
> httpd/imtest: remove any mention of Digest authentication

- docsrc/imap/concepts/deployment/authentication_and_authorization.rst
- docsrc/imap/concepts/overview_and_concepts.rst
… as the former are removed from upstream Cyrus SASL.
https://github.com/cyrusimap/cyrus-sasl/commit/5436909b1d47142ba0961de31bc984bbd544bd80
https://github.com/cyrusimap/cyrus-sasl/commit/2ce03b618ad60338e8f9094f5b7ba7ee0aef40bf
In fact I am not sure if this substitution is correct - if SCRAM or any other current  mechanism requires storing password in clear text - and if the paragraphs are relevant.
> docsrc: Replace CRAM-MD5 and DIGEST-MD5 with SCRAM

- lib/imparse.h
Apparently the build server (CI) skips netnews.
```    
CC       netnews/readconfig.o
In file included from /git/cyrus/cyrus-imapd/netnews/readconfig.c:77:
/git/cyrus/cyrus-imapd/lib/imparse.h:47:5: error: unknown type name ‘uint32_t’
47 |     uint32_t low;
|     ^~~~~~~~
/git/cyrus/cyrus-imapd/lib/imparse.h:48:5: error: unknown type name ‘uint32_t’
48 |     uint32_t high;
|     ^~~~~~~~
make[2]: *** [Makefile:5603: netnews/readconfig.o] Error 1
make[2]: Leaving directory '/git/cyrus/cyrus-imapd/build-gcc'
make[1]: *** [Makefile:7698: all-recursive] Error 1
```
> imparse.h: include <stdint.h>

- cassandane/Cassandane/Cyrus/JMAPEmailSubmission.pm
- cassandane/Cassandane/Cyrus/MaxMessages.pm
- cassandane/Cassandane/Unit/TestCase.pm
- cassandane/testrunner.pl
* Adds a hook to Cassandane such that test suites can decide at runtime whether some test should run or not
* Adds such checks to MaxMessages and JMAPEmailSubmission to skip tests that are known to hang in verbose mode when running in verbose mode
> cassandane: general-purpose runtime skip hook

- cassandane/Cassandane/Cyrus/JMAPContacts.pm
- cassandane/tiny-tests/JMAPContacts/contact_set_avatar_v4
- cunit/charset.testc
- cunit/xsha1.testc
- imap/http_caldav_sched.c
- imap/jmap_contact.c
- imap/jmap_core.c
- imap/jmap_mail.c
- imap/message.c
- lib/charset.c
- lib/charset.h
This fixes a bug where setting an avatar with JMAP Contact/set on an existing vCard 4.0 card resulted in the vCard having a b-encoded PHOTO value. But PHOTO must have a data: URI value in vCard 4.0
> jmap_contact: encode vCard v4.0 blobs as data: URI

- cassandane/tiny-tests/Sieve/deliver_multiple_users
> Add Sieve.deliver_multiple_users

- imap/mboxevent.c
because `buf_release()` does call `buf_free()`.
> imap/mboxevent.c: do not call buf_free() after buf_release()

- cassandane/tiny-tests/JMAPEmail/email_import_received_at
- imap/jmap_mail.c
- imap/message.c
- imap/message.h
This updates Email/import to set the receivedAt property to:
- the Email/import receivedAt argument, if present
- the value of the X-Deliveredinternaldate header, if present
- the value of the first valid Received header
- the value of the Date header, if present
- the current time, if none of the above are present or valid
> JMAP Email: update Email/import logic for receivedAt property

- Makefile.am
- changes/next/proxy_protocol
- docsrc/assets/man-imapdproxyd.rst
- docsrc/assets/man-imtest.rst
- docsrc/assets/man-lmtpd.rst
- docsrc/imap/reference/manpages/systemcommands/httpd.rst
- docsrc/imap/reference/manpages/systemcommands/nntpd.rst
- docsrc/imap/reference/manpages/systemcommands/pop3d.rst
- docsrc/imap/reference/manpages/systemcommands/pop3proxyd.rst
- docsrc/imap/reference/manpages/systemcommands/timsieved.rst
- imap/global.c
- imap/global.h
- imap/haproxy.c
- imap/haproxy.h
- imap/httpd.c
- imap/imapd.c
- imap/lmtpd.c
- imap/nntpd.c
- imap/pop3d.c
- imtest/imtest.c
- timsieved/timsieved.c
https://github.com/haproxy/haproxy/blob/master/doc/proxy-protocol.txt
Currently just plumbed into httpd since it can be tested with curl.
I'm also not sure if -P is the best choice for the command line switch, but don't have any other ideas.
> Add support for HAProxy protocol

- cassandane/tiny-tests/JMAPEmail/email_query_punct_no_text
- imap/xapian_wrap.cpp
This fixes a regression in 0c282379154a776099a83f120311a973c628eb55 Punctuation-only terms only should be ignored in unstructured search parts, such as bodies and subjects.
> xapian_wrap: ignore punct-only terms only in unstructed search parts

- docsrc/imap/concepts/features/virtual-domains.rst
The default "unixhierarchysep" changed from "." to "/" in 3.0. Update the commands shown in the virtual domains documentation to reflect this, helping users by reducing confusion and unexpected behavior when following the examples.
> Update separator in virtual domain example commands

- docsrc/imap/developer/developer-testing.rst
Otherwise `make -Ccassandane` fails:
```
…
./sprinkle.pl syntax OK
Can't locate Config/IniFiles.pm in @INC (you may need to install the Config::IniFiles module) (@INC entries checked: . /usr/local/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi-ld /usr/local/lib/perl5/site_perl/5.38.2 /usr/local/lib/perl5/5.38.2/x86_64-linux-thread-multi-ld /usr/local/lib/perl5/5.38.2) at Cassandane/Cassini.pm line 46.
BEGIN failed--compilation aborted at Cassandane/Cassini.pm line 46.
Compilation failed in require at Cassandane/Config.pm line 45.
BEGIN failed--compilation aborted at Cassandane/Config.pm line 45.
Compilation failed in require at ./start-instance.pl line 48.
BEGIN failed--compilation aborted at ./start-instance.pl line 48.
make: *** [Makefile:74: start-instance.pl_syntax] Error 2
… …
```
> doc/ developer-testing.rst: install more things from CPAN needed by cassandane

- changes/next/deprecate-backups
- docsrc/imap/reference/admin/backups.rst
- docsrc/imap/reference/manpages/systemcommands/backupd.rst
- docsrc/imap/reference/manpages/systemcommands/ctl_backups.rst
- docsrc/imap/reference/manpages/systemcommands/cyr_backup.rst
- docsrc/imap/reference/manpages/systemcommands/restore.rst
Updates documentation to mark the experimental Cyrus Backups system as deprecated.
This one will need to be backported, so it only contains the documentation changes.  There will be a separate PR later to remove the feature from master.
> deprecate cyrus backups

- cassandane/Cassandane/Cyrus/ACL.pm
- cassandane/Cassandane/Cyrus/Admin.pm
Adds some regression tests to ensure `username` and `username@somedomain` are always properly differentiated with respect to `admins:` and mailbox ACL access rights, because we don't seem to have any existing tests for this
> regression tests for username vs username@somedomain access controls

- docsrc/imap/concepts/overview_and_concepts.rst
change listaclmamilbox to listaclmailbox which is the correct command in the exemple
> typo:(overview_and_concepts.rst) fix typo

- docsrc/assets/setup-postfix.rst
- docsrc/imap/reference/manpages/systemcommands/smmapd.rst
https://www.postfix.org/socketmap_table.5.html says after socketmap:unix:PATH follow colon and a map name.  The map name is sent in the request, as described in the prelude of imap/smmapd.c, but skipped by smmapd.
> docsrc/setup-postfix: fix for socketmap

- imap/sync_server.c
It is void since b19edfa642b2201dedcd98b35c437843ae63048c.
> sync_server: remove -f parameter

- imap/http_jmap.c
JMAP blobs are untyped and storing the client-supplied media type may result in Cyrus message blobs having a wrong Content-Type header. This changes the JMAP blob upload handler to store blobs as `application/octet-stream` content, unless the uploaded blob is of type `message/rfc822` and the blob passes our checks for valid messages of that type.
> JMAP: store uploaded blobs as application/octet-stream

- cassandane/tiny-tests/JMAPEmail/email_get_utf8_domain
- imap/jmap_util.c
- lib/charset.c
- lib/charset.h
26a11165390c9cb25c6c72dd08bea24d2c9d2c1d fixed the Cyrus email address parser to accept non-ASCII characters in email address domain names, as required by RFC 6532.
However, until it is clear how to present Internationalized Domain Names (RFC 5890) to JMAP clients, Cyrus will stick to only returning their ASCII representation in the EmailAddress object. JMAP clients still can obtain the Unicode representation by fetching the raw headers of the Email.
> jmap_mail: convert Unicode email domains to ASCII in Email/get

- .github/workflows/main.yml
This updates our CI workflow to fetch the latest copy of Mail::IMAPTalk each time it runs, instead of relying on the version embedded in the docker image.
It also reports the Mail::IMAPTalk version in the "report version information" step (which now occurs after the module has been updated)
> github actions: fetch Mail::IMAPTalk each time

- cassandane/tiny-tests/JMAPCalendars/calendarevent_parse_repair_broken_ical
- cassandane/tiny-tests/JMAPCalendars/calendarevent_parse_singlecommand
- imap/jmap_calendar.c
- imap/jmap_ical.c
- imap/jmap_ical.h
This updates CalendarEvent/parse to optionally parse iCalendar data even if it violates some iCalendar requirements. All these violations were seen in real iCalendar data. This patch only allows parsing such data and converting it to JSCalendar. It does not allow adding such broken iCalendar data via CalDAV or iMIP.
> JMAP: add `repairBrokenIcal` argument to CalendarEvent/parse

- cassandane/Cassandane/Cyrus/MaxMessages.pm
- imap/mailbox.c
IMAP_NO_OVERQUOTA is used for IMAPOPT_QUOTAWARNPERCENT
This will replace #4915 which will be reverted
> mailbox.c: use the correct error code for over message quota

- cassandane/Cassandane/Cyrus/Simple.pm
- imap/message.c
- lib/stristr.c
- lib/stristr.h
This fixes an off-by-one read when monkey-patching a `Content-Transfer-Encoding` header value from `BINARY` to `BASE64`.
Once approved, this should get backported this to at least 3.10 but I'm not sure I need to open a new PR for that?
> Fix invalid read for BINARY content-transfer-encoding header

- imap/search_engines.c
Fixes a bug in which attachment extraction ran multiple times for the same message.
> search_engine: don't reindex message for every attachment

- docsrc/imap/rfc-support.rst
- sieve/interp.c
That is, if some capability is `0LL << … /* currently unsupported */` consider it as not implemented.
Probably in https://github.com/cyrusimap/cyrus-imapd/pull/3050 I marked these as IMPLEMENTED, because the capabilities were mentioned somehow.
> rfc-support.rst: Updates for Sieve based on `sieve/interp.h`

- changes/next/imap_jmapaccess
- imap/imapd.c
- imap/promdata.p
Changes based draft-ietf-extra-jmapaccess-09
> imapd.c: change JMAPACCESS from resp code to capability + command

- imap/annotate.c
- imap/cyr_expire.c
- imap/quota.c
- imap/sync_support.c
Found one more missing "silent" codepath!  This is for mailboxes that are already DELETED namespace, so invisible.
Bron.
> cyr_expire: silent delete for cleaning up DELETED mailboxes

- cassandane/tiny-tests/CaldavAlarm/suppress_duplicates
- changes/next/calalarmd_suppress_duplicates
- cunit/ical_support.testc
- imap/caldav_alarm.c
- imap/ical_support.c
- lib/imapoptions
Suppress duplicate calendar alarms in calalarmd. At most one alarm notification is sent for any given alarm action, point in time and calendar event.
Some broken calendar client implementations seem to append the exact same alarm every time they update the event, resulting in duplicate alarms being triggered.
This feature is optional and enabled by default.
This PR also includes duplicate suppression in recurrence rules. This is an internal fix only.
> caldav_alarm: suppress duplicate alarms

- cassandane/Cassandane/Generator.pm
- cassandane/Cassandane/IMAPMessageStore.pm
- cassandane/tiny-tests/Replication/userflags
- changes/next/replicate-userflags
- imap/sync_support.c
This means that even unused ones will be replicated, which will make for a more consistent user experience when a replica gets promoted to primary
> replicate user-defined flags on MAILBOX

- cunit/charset.testc
- lib/charset.c
This updates charset_extract to also insert whitespace for any text following HTML elements that until now were considered "phrasing", such as `<em>`, `<span>`, etc. Inserting whitespace emulates content between these elements being separated by CSS.
For example, before this change HTML text like `foo<em>bar</em>` got extracted as "foobar", now it results in "foo bar".
> charset.c: also insert whitespace after "phrasing" HTML elements

- Makefile.am
- backup/restore.c
- cassandane/Cassandane/Config.pm
- cassandane/Cassandane/Cyrus/FastMail.pm
- cassandane/Cassandane/Cyrus/Mboxgroups.pm
- cassandane/Cassandane/Cyrus/TestCase.pm
- cassandane/tiny-tests/Replication/mboxgroups
- cassandane/tiny-tests/Replication/shared_folder
- changes/next/mboxgroups
- imap/global.c
- imap/httpd.c
- imap/imapd.c
- imap/mailbox.c
- imap/mailbox.h
- imap/mboxevent.c
- imap/mboxevent.h
- imap/mboxlist.c
- imap/mboxlist.h
- imap/sync_support.c
- imap/sync_support.h
- lib/auth.c
- lib/auth.h
- lib/auth_krb.c
- lib/auth_krb5.c
- lib/auth_mboxgroups.c
- lib/auth_pts.c
- lib/auth_unix.c
- lib/imapoptions
This takes groups into Cyrus.  I want to add a JMAP-style management interface as well, but that's for v2.
It also adds additional pusher info to push a list of all users who can see the change, for handy pusher/notify extensions.
> auth_mboxgroups: a new in-cyrus group mechanism

- changes/next/remove_imap_xmove
- imap/imapd.c
- imap/imapd.h
Do not merge until we are certain that no major clients still use XMOVE rather than MOVE (I think we are certain).
> imapd.c: remove support for XMOVE

- .github/workflows/main.yml
- docsrc/imap/developer/major-releasing.rst
Few small things here:
* Upgrade to `actions/checkout@v4`, which should fix a warning about "Node.js 16" being deprecated
* Use a wildcard for specifying the release branches, so we don't need to update the list every new release
* Rationalise the `push` and `pull_request` triggers
The last point should prevent:
* double CI runs when pushing to PR branch on main repo (due to "push" and "pull_request" events both firing)
* CI runs for unpublished branches on forks with actions enabled (Fixes #4922)
But still allow:
* CI runs for PRs against official branches (drafts included)
* CI runs for pushes directly to official branches
> github actions: finesse triggers, update actions/checkout

- cassandane/tiny-tests/JMAPCalendars/calendarevent_set_create_no_reply_exdate
- imap/http_caldav_sched.c
Fixes a bug where creating a JMAP calendar event having an EXDATE as well as the user as an attendee causes an iTIP REPLY to be sent, even if the PARTSTAT of that attendee is NEEDS-ACTION.
> http_caldav_sched.c: do not send REPLY for EXDATEs on event creation

- cassandane/tiny-tests/JMAPCalendars/calendarevent_query
- imap/jmap_api.c
This fixes `jmap_filter_parse()` to reject filters whose "conditions" is not an array.
> jmap_api: reject non-array query filter conditions

- .github/workflows/main.yml
Updates github actions to fetch the release tags from the upstream repository if the repository the action is running on is not the upstream repository.
This solves Cassandane test failures on forks that have actions enabled but do not have up to date release tags.  It could also be solved on the fork by updating the release tags, but the cause and solution aren't obvious, so just automate it to avoid confusion.
> github actions on forks

- cassandane/Cassandane/Instance.pm
- imap/imapparse.c
- imap/imapparse.h
- imap/mupdate-client.c
The mupdate protocol uses LITERAL+ like syntax in both directions.  This got broken when we made `getxstring()` strict about only accepting it from clients (per RFC 7888: "The non-synchronizing literal form MUST NOT be sent from server to client."), resulting in murder backends being unable to synchronise their mailboxes.db with the mupdate server.  `ctl_mboxlist -m` would fail with an error like "couldn't do LIST command on mupdate server" when parsing the mailboxes from the LIST response.  Our tests didn't detect this because they only run `ctl_mboxlist -m` at startup, when there aren't any mailboxes yet, and the LIST response is empty.
* Adds an additional `ctl_mboxlist -m` run to the post-test shutdown checks for any instances that are configured as a murder backend.
* Adds an …
> imapparse: accept client LITERAL+ for mupdate

- cassandane/tiny-tests/JMAPContacts/card_query_shared
The JMAPContacts.card_query_shared test had a syntax error which caused the test runner to ignore it. This got fixed in https://github.com/cyrusimap/cyrus-imapd/commit/2146b170f0ba67a7e88ddd856fff0d1b9feac055 and now it turns out that test was broken.
This patch fixes the test.
> JMAPContacts: fix card_query_shared shared test

- imap/sync_support.c
This fixes a bug where updating a script on a pre-sieve mailbox server resulted in an empty script on a sieve-mailbox replica (#4947 ).  
This had to be tested manually with different versions of Cyrus.
> sync_sieve_upload() always initialize buffer with script content

- imap/jmap_calendar.c
Errors during writing the CalendarEvent cache in /get always were meant to be ignored, but an error when starting the write transaction still led to aborting the JMAP request.
This patch updates that to also ignore, but report, such errors.
> jmap_calendar.c: ignore cache errors in CalendarEvent/get

- configure.ac
Replication was experimental in 2.3, but I don't think that's the case anymore...
For one thing, it's our preferred upgrade path!
This came up here: https://cyrus.topicbox.com/groups/devel/T0f354b019bc535c8-M9ec692e090ac3eda33feea56
> configure.ac: replication is not 'experimental'

- cassandane/tiny-tests/JMAPContacts/contact_copy_phonetic
- cassandane/tiny-tests/JMAPContacts/contact_get_phonetic
- cassandane/tiny-tests/JMAPContacts/contact_set_phonetic
- imap/jmap_contact.c
Apple macOS Contacts.app allows to store phonetic information for First Name, Middle Name, Last Name and Company. These are stored in the vCard with the X-PHONETIC prefix.
This patch adds the "phoneticFirstName, "phoneticMiddleName", "phoneticLastName" and "phoneticCompany" properties to the Contact type to support these vCard properties in JMAP.
> jmap_contact.c: support X-PHONETIC extension properties

- cassandane/Cassandane/Cyrus/JMAPEmail.pm
- cassandane/tiny-tests/JMAPEmail/email_query_sieve_some_in_thread_have_keyword_utf8_subject
- imap/message.c
Fixes a bug where the subject of a message without cache record is compared in its word-encoded form to the normalized conversation subject. This primarily impacted Sieve jmapquery filters using one of the thread keyword filter conditions.
> message.c: decode Subject header before comparing with conversations

- imap/sync_support.c
This avoids opening and closing the per-mailbox annotations file all the time!
> replication: hold annotations open for printrecords

- docsrc/imap/developer/compiling.rst
As DIGEST-MD5 is gone, installing its libsasl2 plugin, sasl2/libdigestmd5.so, should not be necessary any more.
On Debian libsasl2-modules installs apart from libdigestmd5.so and libcrammd5.so also liblogin.so.  However libsasl2-modules is still required in the documentation on the line before the deleted herein line.
On Fedora cyrus-sasl-md5 does include only libcrammd5.so and libdigestmd5.so.
If there are no github-side RPM-based tests, this change cannot be tried out.
> compiling.rst: remove RPM packages for SASL DIGEST-MD5

- lib/imapoptions
As these are anyway rendered as such in the `man` and `html` output for `imapd.conf`.
> imapoptions: do not spell explicitly the default values

- changes/next/skipuser
- imap/sync_support.c
This allows skipping replication on one particular user, both rolling and by hand (while using the channel name - you can bypass it by syncing with the IP instead)
This came up after a server failure at Fastmail - it would have been very handy to keep rolling replication going without futzing with the one broken user.  This gives us a tool for this.
> sync: add support for a skipuser touchfile

- docsrc/imap/developer/developer-testing.rst
It is no longer busted on recent perls, as of 0.026.
> developer docs: remove note about Test::Unit problems

- cassandane/tiny-tests/JMAPContacts/contact_copy_preserve_xprops
- cassandane/tiny-tests/JMAPContacts/contact_set_preserve_xprops
- imap/jmap_api.c
- imap/jmap_api.h
- imap/jmap_contact.c
This updates the `Contact/copy` method of the non-standard Contact object type to preserve arbitrary x-properties in the copied vCard.
It adds the `vCardProps` property as defined in https://www.rfc-editor.org/rfc/rfc9555.html#name-vcardprops to the Contact object type The implementation is for Cyrus-internal use only and `Contact/set` and `Contact/get` reject this property as unknown.
Also contained in this PR is a related, minor fix:  `Contact/set` now replaces rather than adds the non-standard phonetic contact properties.
> JMAP Contacts: preserve x-properties in Contact/copy

- cassandane/Cassandane/Cyrus/HTTPPTS.pm
- cassandane/Cassandane/Cyrus/LDAP.pm
- cassandane/Cassandane/IMAPMessageStore.pm
- cassandane/data/directory.ldif
- cassandane/tiny-tests/FastMail/touch_raclmodseq
- changes/next/groupracl
- docsrc/imap/reference/manpages/systemcommands/ptexpire.rst
- imap/imapd.c
- imap/mboxlist.c
- imap/mboxlist.h
- lib/imapoptions
- ptclient/http.c
- ptclient/ldap.c
- ptclient/ptexpire.c
This is a little skanky, but "PTS" is basically a key to list lookup protocol, so I'm using it in reverse to map a group to its members.
(This pairs with an MR in Fastmail hm to add the same thing to our lookup)
> Group racl

- configure.ac
I recently tried building 3.10.0-rc2 but got the following error from icu_wrap.cpp:
<details><summary>Click to expand error message</summary>
```
CXX      imap/libcyrus_imap_la-icu_wrap.lo
In file included from /usr/include/unicode/uenum.h:25,
from /usr/include/unicode/ucnv.h:52,
from imap/icu_wrap.cpp:50:
/usr/include/unicode/localpointer.h:561:26: error: parameter declared 'auto'
561 | template <typename Type, auto closeFunction>
|                          ^~~~
/usr/include/unicode/localpointer.h:573:76: error: template argument 2 is invalid
573 |     explicit LocalOpenPointer(std::unique_ptr<Type, decltype(closeFunction)> &&p)
|                                                                            ^
/usr/include/unicode/localpointer.h:583:78: error: template argument 2 is invalid …
```
> Fix 3.10.0-rc2 build failure when building against ICU 75 caused by AX_CXX_COMPILE_STDCXX_11 update

- cassandane/Cassandane/Cyrus/Prometheus.pm
- changes/next/prom-usage-stats
- docsrc/imap/reference/admin/monitoring.rst
- docsrc/imap/reference/manpages/systemcommands/promstatsd.rst
- imap/prometheus.c
- imap/prometheus.h
- imap/promstatsd.c
- lib/imapoptions
- master/master.c
We found that the Prometheus "usage" report (which reports user and mailbox counts, and quota commitments) is relatively expensive to produce, as it needs to iterate the mailboxes and quota databases.  It is not appropriate to run at the default 10s frequency used by the other reports.
This PR splits the `prometheus_update_freq` imapd.conf option into three new ones: `prometheus_service_update_freq`, `prometheus_master_update_freq`, and `prometheus_usage_update_freq`, so that these reports can be updated at different frequencies.
* `prometheus_service_update_freq` defaults to 10s, like `prometheus_update_freq` did
* `prometheus_master_update_freq` defaults to 0, in which case `prometheus_service_update_freq` will be used instead
* `prometheus_usage_update_freq` defaults to 0, in which …
> prometheus: per-report update frequencies

- doc/legacy/changes.html
- docsrc/imap/download/release-notes/2.0/2.0.x.rst
- docsrc/imap/reference/manpages/systemcommands/mkimap.rst
See also https://github.com/cyrusimap/cyrus-imapd/pull/3263.
> docsrc/: Typos i → I

- imap/telemetry.c
The syslog RFC 5424 states that LOG_NOTICE should be used for "normal but significant conditions". USAGE logs aren't significant conditions on the system since they aren't actually conditions at all; they are a way to view numerical metrics on resource usage on a particular action.
> imap/telemetry: log rusage at LOG_INFO

- sieve/interp.c
> interp.c: protect against duplicate case values (zero)

- cassandane/tiny-tests/FastMail/mailbox_rename_long_chain
- cassandane/tiny-tests/FastMail/mailbox_rename_switch_ab
- imap/mailbox.c
- imap/sync_support.c
Even if replication didn't catch each step of the way - we need this to work.  This adds two case tests, and fixes replication for this case
> FastMail: test that rename a->c, b->a, c->b works

- docsrc/imap/download/release-notes/3.2/x/3.2.0.rst
https://lists.andrew.cmu.edu/pipermail/cyrus-devel/2019-June/004488.html
“squatter -F increases index size” is likely fixed in 3.2.
On 3.0 `squatter -F` can increase the Xapian database, as discussed last June.
> RelNotes: 2854 (squatter -F) is fixed in 3.2

- docsrc/imap/rfc-support.rst
- lib/imapoptions
As of RFC 6154 Section 2 an IMAP server that supports the SPECIAL-USE extension MAY include any or all of the following attributes in responses to the non-extended IMAP LIST command…
The option `specialusealways` alters exactly the behaviour of the unextended LIST command.  Describing the behaviour of `specialusealways` in terms of the undocumented XLIST command is suboptimal.
https://github.com/cyrusimap/cyrus-imapd/issues/2410
> Clarifications specialusealways: 1

- .github/workflows/main.yml
This will supposedly permit us to kick off CI workflow runs manually, without needing a push to a PR or official branch to trigger it.  It might be useful when reviewing ancient PRs that haven't had a CI run before.
Note that the [documentation](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/manually-running-a-workflow) says that to use this trigger, "your workflow must be in the default branch".  I think this means there's no useful way to test whether this works (or is useful to us) except just merge it to master and see what happens.
There's a bunch of options for further configuring this trigger, but they haven't sounded useful to me just from reading about them.  I figure for now we just turn it on and see what we get by default, and …
> github-actions: add workflow_dispatch trigger

- cassandane/Cassandane/Unit/FormatPretty.pm
- cassandane/Cassandane/Unit/FormatTAP.pm
- cassandane/Cassandane/Unit/FormatXML.pm
- cassandane/Cassandane/Unit/Formatter.pm
- cassandane/Cassandane/Unit/Runner.pm
- cassandane/Cassandane/Unit/RunnerXML.pm
- cassandane/Cassandane/Unit/TestPlan.pm
- cassandane/testrunner.pl
This adds support to Cassandane for producing multiple formats of output from a single run, as long as they won't be fighting over stdout.  In practice, this means "tap", "pretty", and "prettier" still cannot be used together, but "xml" can be used alongside any of them.  This will become more useful if we add more non-stdout formats in the future (perhaps "json"), but this PR doesn't do that.
There's a bunch of internal architectural changes here, but the main outwardly-visible one should be that you can now specify the `-f <format>` argument to testrunner.pl multiple times.  The other is that the `--rerun` behaviour after test failures now works independently of output format(s).
**Reviewers**: Please pull this branch and run Cassandane in any of the ways you usually would.  If you can …
> cassandane: support multiple output formats per run

- imap/itip_support.c
This fixes a bug where creating an override for an event where the VTIMEZONE doesn't include X-LIC-LOCATION would result in the RECURRENCE-ID missing TZID
> deliver_merge_reply(): use icaltimezone_get_location_tzid()

- imap/jmap_api.h
- imap/jmap_core.c
Per https://datatracker.ietf.org/doc/draft-ietf-jmap-portability-extensions/
> http_jmap.c: add "urn:ietf:params:jmap:core:backendInfo" capability

- imap/message.c
Fixes a bug in which cached bodystructures having a cache version less than the current version 13 failed to parse.
> message.c: fix reading cached bodystructure for "message/global"

- changes/next/deprecate_sieve_sasl_send_unsolicited_capability
- lib/imapoptions
- timsieved/parser.c
It comply with [RFC 5804 A Protocol for Remotely Managing Sieve Scripts](https://tools.ietf.org/html/rfc5804) this option must be off.
> lib/imapoptions: deprecate sieve_sasl_send_unsolicited_capability

- cassandane/Cassandane/Unit/TestPlan.pm
- cassandane/testrunner.pl
Makes Cassandane check for various bad tiny-tests conditions at startup.  This is mostly useful for detecting mistakes while backporting changes to older versions that don't have tiny tests at all, or don't use them as much as as master does.  It might also be helpful when implementing new tiny-tests suites if you're not just converting an existing suite using the tool.
It complains about:
* test suites that try to Cassandane::Tiny::Loader a nonexistent directory
* multiple test suites that Cassandane::Tiny::Loader the same directory
* tiny-tests directories that no test suite calls Cassandane::Tiny::Loader on
* tiny-tests directories that don't contain any tests
It's implemented as a sanity check within Cassandane::Unit::TestPlan, not within Cassandane::Tiny, because its main purpose is …
> TestPlan: check for bad/orphaned tiny-tests

- sieve/bytecode.h
- sieve/sieved.c
Backport of d126b8e5a4e640cc2.
> 3.2 - Sieve "include": :once and :optional flags in bytecode were being parsed in reverse

- configure.ac
`./configure` possibly printed `no` twice:
```
checking whether g++ supports C++11 features by default... yes
checking for Xapian cjk word tokenization... no
no
configure: Your Xapian does not support CJK word tokenization. CJK ngram tokenization will be used instead.
```
> configure.ac: print result for “Checking for Xapian cjk word tokenization…” only once

- cassandane/tiny-tests/JMAPCalendars/calendarevent_guesstz_etc_gmt
- imap/jmap_ical.c
A negative UTC offset converts to an Etc/GMT timezone with positive offset. The code and its test got it the other way round.
> jmap_ical: fix inverse sign when guessing Etc/GMT+X timezone

- backup/lcb_compact.c
- backup/lcb_indexw.c
- cunit/ical_support.testc
- cunit/timeofday.c
- imap/cyr_ls.c
- imap/http_cgi.c
- imap/http_dav_sharing.c
- imap/http_jmap.c
- imap/httpd.c
- imap/ical_support.c
- imap/jmap_backup.c
- imap/jmap_mail.c
- imap/jmap_mail_submission.c
- imap/jmap_notif.c
- imap/jmap_sieve.c
- imap/mbtool.c
- imap/relocate_by_id.c
- imap/sieve_db.c
- lib/times.c
I spent some time a few months ago trying to track down a variety of build failures on armel, armhf, and some others platforms affected by Debian's transition to providing a 64-bit time_t on these 32-bit platforms (#4876, #4887), but eventually stalled out on a stack smashing problem that seemed to be coming from within libical.  @rjbs and I decided that it wasn't worth spending more time chasing the problem around since it makes no sense to run an IMAP service on these sort of devices anyway.
This PR is a distillation of the useful changes I made while investigating.
> misc fixes from building on 32-bit architectures with 64-bit time_t

- imap/http_caldav.c
This allows by clicking on the component name to mark the checkbox.
> CalDAV admin page: link component names to checkbox

- master/master.c
When the master process receives SIGINT, it shall recycle all children and then exit.  If the signal is recieved while waitpid() in reap_child() is executed, waitpid() returns 0, the child exit status is not consumed and the centry is not updated.
Later on, the janitor utilizes 100% the CPU by iterating over its slots, to see if the process, whose centry was not updated, is in the meantime terminated.  The child is in fact terminated, but due the interruption of waitpid() the master process never updates its internal status for the child.
> master:reap_child() survive SIGINT

- cassandane/Cassandane/Unit/TestPlan.pm
Extends the tiny-tests sanity checks from #5011 to complain about extra tiny-tests directories in unexpected places.  This would have prevented the problem that #5030 fixed
> check for unexpected extra tiny-tests directories

- imap/cyr_dbtool.c
Not complete, as I don't quite understand what `-t` and `-T` are supposed to achieve (something about transactions). Also, I haven't actually tested that `-c` and `-M` even work (`-n` does, which is what I wanted). ALSO, `-c` sounds kinda destructive enough that it should perhaps be an explicit `convert` action and maybe shouldn't be neatly documented at all, but anyway, here we are!
> cyr_dbtool: document flags

- Makefile.am
- cassandane/Cassandane/Cyrus/JMAPQuota.pm
- cassandane/tiny-tests/JMAPQuota/quota-changes
- cassandane/tiny-tests/JMAPQuota/quota-get
- cassandane/tiny-tests/JMAPQuota/quota-query
- imap/http_jmap.c
- imap/jmap_api.c
- imap/jmap_api.h
- imap/jmap_core.c
- imap/jmap_quota.c
- imap/promstatsd.c
- imap/quota.c
- imap/quota.h
- imap/quota_db.c
> jmap_quota.c: Implement JMAP quotas per RFC9425

- Makefile.am
This file is an Automake file, which means we can use 4-space indents like the rest of our code.  We were already doing this in some places in this file; now we do it throughout.
The exceptions are the snippets of Makefile syntax, where hard tabs are required by make.
Obsoletes #3438
> Makefile.am: 4-space indents, except where we can't

- imap/index.c
- imap/jmap_mail.c
- imap/jmap_mail_query.c
- imap/search_engines.c
- imap/search_engines.h
- imap/search_expr.h
- imap/search_part.h
- imap/search_squat.c
- imap/search_xapian.c
- imap/xapian_wrap.cpp
- imap/xapian_wrap.h
The current Xapian wrapper code in `imap/xapian_wrap.cpp` is anything but idiomatic or modern C++ code. https://github.com/cyrusimap/cyrus-imapd/pull/2818 highlights some of that, but we didn't act on it timely and the code now is stale. It also didn't help that the code changes are all in a single commit.
This PR attempts to sanitize the C++ code in smaller steps. As a baseline of what constitutes "sane C++" code, we'll start with the [clang-tidy](https://clang.llvm.org/extra/clang-tidy/) linter with the `bugprone` check category.
I am using this with Debian LLVM version 14.0.6.
> Resolve clang-tidy warnings for Xapian wrapper

- imap/message.c
Fixes a bug introduced by a2684ec50c63b2e7a965702d4ef83a5387c7a2d5 which made the message cache parser errouneously expect a cached envelope for message/global, causing to an invalid memory read.
Also see 22efff1aa2aa48a71350edd9f926ddff9e109f9a
> message.c: only read message/global envelope if cache version >= 13

- cassandane/Cassandane/Cyrus/TestCase.pm
- cassandane/tiny-tests/CaldavAlarm/supported_components
- changes/next/caldav_alarm_supported_components
- imap/caldav_alarm.c
- lib/imapoptions
This adds the `caldav_alarm_support_components` imapd.conf option to define if alarms should be sent for VEVENT, VTODO, or both. The default is to send alarms for both.
Before this change, VALARMs were processed for any iCalendar component type that libical deems to be a "real" component, that is one of: VEVENT, VTODO, VJOURNAL, VFREEBUSY, VAVAILABILITY, VPOLL, VPATCH, VQUERY, VAGENDA. In practice, RFC 5545 only defines VEVENT and VTODO to contain VALARM components and the temporal semantics for relative alarm triggers would be undefined for the other component types anyway.
Restricting supported components explicitly to VEVENT and VTODO seems to make configuration more clear than some general scheme.
> caldav_alarm: support suppressing alarms for VEVENT or VTODO

- cassandane/tiny-tests/JMAPCalendars/calendarevent_get_alert_acknowledged_far_future
- cassandane/tiny-tests/JMAPCalendars/calendarevent_get_locations_dtend
- cassandane/tiny-tests/JMAPCalendars/calendarevent_set_preserve_non_iana_dtend_timezone
- imap/jmap_ical.c
This fixes bugs that show when updating CalendarEvent objects where the updated iCalendar data contains a DTEND property having a non-IANA TZID that differs from the DTSTART timezone identifier.
In addition, this patch also replaces use of libical's `icaltime_is_valid_time` with own value checking, as libical arbitrarily restricts the year part of datetimes to be less than 3000.
> jmap_ical.c: fix JSCalendar conversion for DTEND with non-IANA timezones

- sieve/bc_eval.c
- sieve/message.c
- sieve/message.h
- sieve/sieve_interface.h
make by_value non-static, so that libcyrus_sieve can be used to interpret bytecode in multi-threaded environment.
I use `sieve_eval_bc()` in a multi-threaded application.
> sieve_eval_bc:B_REDIRECT make the function reentrant

- changes/next/lmtp-ratelimit
- imap/imap_err.et
- imap/imapd.c
- imap/lmtp_err.et
- imap/lmtpd.c
- imap/lmtpengine.c
- imap/nntpd.c
- imap/pop3d.c
- lib/proc.c
- lib/proc.h
We're running into issues in Fastmail production where a single mailbox locked up for a crazy amount of time can cause starvation by having hundreds of lmtp processes waiting on locks.
We could test for locks, but it's OK to have a few waiting - we should just tell the rest to try again later.  This re-uses the
proc_checklimit in lmtpd to check the limits for each userid before trying to lock their conversations.db, and returns a useful 451 code to the sender saying that there are too many connections for this user.
We'll probably set something like a 10 process limit for our servers, which allows for all the MXes to send one and a few spares still open.
> Lmtp ratelimit

- cassandane/Cassandane/Cyrus/Master.pm
- changes/next/master-babysit-retry
- master/master.c
I recently moved sync_client to be managed by Cyrus rather than a separate "monitorsync" script.
Likewise, we have other things started under the DAEMON block which are supposed to run forever at Fastmail:
pusher, calalarmd, squatter, idled, bayesrpcd and one day again: promstatd.
This change means that if we hit the restart limit, we retry every 10 seconds forever for anything with the 'babysit' flag - which includes all daemons.  We only try once per 10 seconds unless we get a clean 10 seconds, in which case it resets back to allowing 5 failures with immediate restart.  This should stop it causing a totally crazy amount of restarts.
Finally: I added the string "ERROR" to the messages about hitting the limits, which will help with Fastmail's log tracking.
> Master babysit retry

- Makefile.am
- changes/next/htmladminpage
- imap/http_cal_abook_admin.js
- imap/http_caldav.c
- imap/http_carddav.c
This removes also the final new line in `http_cal_abook_admin.js`.
If `http_cal_abook_admin_js.h` does end with a new line, then the resulting http_cal_abook_admin_js.h:http_cal_abook_admin_js[] does end with `0x00, 0x0a`.  That is the second parameter passed to
```c
buf_printf(body, http_cal_abook_admin_js,
CYRUS_VERSION, http_cal_abook_admin_js_len);
```
does not end in `\0` and this leads to compiler warning, if in lib/util.h:buf_printf() has `__attribute__((format(printf, 2, 3)))`
> Caldav/Carddav admin html page: enable editing collection’s description

- imap/http_caldav_sched.c
When an `\n` from an iCalendar property value is converted in http_caldav_sched.c:imip_send_sendmail() to HTML, the function used to send to the MSA `\n  <br>`.  That is: a single LF without CR.  This does not work any more, the MSA replies:
```
smtpclient: unexpected response to EOT: code=421 text=4.5.0 Bare linefeed (LF) not allowed
smtpclient: Bad protocol during DATA
```
This change sends in such cases `\r\n` instead of `\n`.
> iTIP: convert \n from iCalendar to “\r\n  <br>” to the MSA

- imap/http_caldav_sched.c
When the email address (property value) and name (CN= property parameter) of an attendee/organizer coincide, print only the email address.
> http_caldav_sched.c:imip_send_sendmail: print less redundant information in the text/plain part about attendees

- imap/lmtpd.c
- imap/mupdate.c
This broke the clang-14 build with `-Werror` enabled, failing with a `[-Werror,-Winvalid-noreturn]` error.
> lmtpd.c: don't declare shut_down function twice

- cassandane/tiny-tests/Caldav/invite_change_time
This adds a couple of regression tests that assert that changing the temporal properties of a VEVENT generally triggers an iTIP message. This includes changing the timezone of DTSTART or DTEND, even if the new timezone has the same UTC offset as the old one.
The one exception is changing from DTEND to DURATION does not trigger iTIP, if the new event duration has the same time span as the old one. See Caldav.invite_switch_duration_to_dtend for that.
> Caldav.pm: add iTIP regression test for event timezone changes

- cassandane/tiny-tests/Caldav/invite_plusaddr
- cassandane/tiny-tests/JMAPCalendars/calendarevent_set_plusaddr_itip
- imap/caldav_alarm.c
- imap/caldav_db.c
- imap/caldav_util.c
- imap/calsched_support.c
- imap/http_caldav.c
- imap/http_caldav_sched.c
- imap/http_ischedule.c
- imap/ical_support.c
- imap/ical_support.h
- imap/index.c
- imap/itip_support.c
- imap/jmap_backup.c
- imap/jmap_calendar.c
- imap/jmap_ical.c
- imap/lmtp_sieve.c
- lib/strarray.c
- lib/strarray.h
This solves the original user issue using a plus address to create a scheduling event over JMAP.  I need to audit the rest of the JMAP and CalDAV code to handle percent encoded addresses.
> iTIP with URL (percent) encoded addresses

- cassandane/Cassandane/PortManager.pm
- cassandane/Cassandane/Test/Cassini.pm
- cassandane/Cassandane/Test/MessageStoreFactory.pm
- cassandane/cassandane.ini.example
- cassandane/genmail3.pl
- cassandane/imap-append.pl
This is higher and less likely to clash with other things
> PortManager: start at port 29100

- imap/http_carddav.c
as carddav_parse_path() does not allow it.
> CardDAV: remove DELETE from supported-method-set for Default address book

- imap/http_cal_abook_admin.js
Do not create collection URLs with two `-` in a row, or with a leading `-`.  The former happens for name=atreatreaurdeaurntetdauaiuea, the latter for base address http://127.0.0.1/dav/calendars/user/a@b .
> http_cal_abook_admin.js: no new collection URLs with leading `-`

- imap/spool.c
The static function imap/spool.c:parseheader() is called from only one place.
The passed parameters headname, contents and rawvalue from that place are not NULL, so there is no need to check within parseheader() if these parameters are NULL.
> spool.c:parseheader() - remove unnecessary checks for NULL

- imap/ctl_zoneinfo.c
- imap/cyr_synclog.c
- imap/cyr_virusscan.c
- imap/dav_reconstruct.c
- imap/fud.c
- imap/httpd.c
- imap/imapd.c
- imap/lmtpd.c
- imap/mupdate.c
- imap/nntpd.c
- imap/pop3d.c
- imap/smmapd.c
- imap/sync_server.c
- lib/assert.h
- master/service.h
- notifyd/notifyd.c
- perl/sieve/lib/request.c
- ptclient/ptloader.c
- timsieved/timsieved.c
This is a redo of #3737 by @dilyanpalauzov (thanks!)
Adds `__attribute__((noreturn))` to a number of choice places detected by GCC's `-Wsuggest-attribute=noreturn` option.  In particular, it adds it to the places where GCC's suggestion is correct.  Most of these are `usage()`, `shut_down()`, and `service_abort()`, but there's a few others.
The advantage of adding this attribute to functions that intentionally never return is that GCC can now tell us when functions that _should_ return _don't_.  There's a few of those, and this PR does not address them, because they're not critical problems, and they'll need more care than I'm investing right now to deal with properly.  At the time of writing, these are:
* mupdate: `mupdate_client_start()` thread body loops forever (eventually terminated …
> add attribute noreturn where useful

- imap/lmtpengine.c
On some platforms this produces strings like "Unknown error: 0", "Undefined error: 0", etc
Based on a patch from @ksmurchison and discussion in #3035 and #3826
> lmtpengine: don't rely on error_message(0) for success string

- imap/http_caldav.c
This way client software can show to the user when server-side scheduling is disabled.  The client software can then offer to send iMIP messages.
While `_scheduling_enabled()` calls
> annotatemore_lookupmask_mbox(mailbox, DAV_ANNOT_NS "<" XML_NS_CYRUS ">scheduling-enabled", "", &buf);`
this function executes
> annotatemore_lookup_mbe(mbentry, DAV_ANNOT_NS "<" XML_NS_CYRUS ">scheduling-enabled", "", &buf);`
The difference is, that the former also invokes
```c
/* and because of Bron's use of NULL rather than "" at FastMail... */
if (value->len == 0)
r = _annotate_lookup(mboxname, mboxid, uid, entry, NULL, value);
```
I do not understand how this NULL is supposed to work at FastMail.
> CalDAV OPTIONS: do not announce `calendar-auto-schedule` when CY:scheduling-enabled is `F`

- changes/next/dispayname_on_principal-property-search_report
- imap/http_dav.c
When calling [REPORT principal-property-search](https://tools.ietf.org/html/rfc3744#section-9.4) and the search criterion is `DAV:displayname`, take the `displayname` from the annotatitonsDB, if available.
```sh
curl -XREPORT -H"content-type:application/xml" -uaaa:bbb --data-binary @- <<EOF https://SERVER/dav/principals/user
<principal-property-search xmlns="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav">
<apply-to-principal-collection-set/>
<property-search>
<prop>
<displayname/>
</prop>
<match>aaa</match>
</property-search>
<prop>
<c:calendar-user-address-set/>
<c:calendar-home-set/>
<c:calendar-user-type/>
<displayname/>
</prop>
</principal-property-search>
```
> http_dav.c:principal_search() utilize DAV:displayname from the annotations

- imap/http_dav.c
Prior to this change
```
curl -XPROPPATCH -Hcontent-type:application/xml -uggg@mydomain.org:ggg --data-binary @- <<EOF http://server/dav/calendars/user/ggg@mydomain.org/Default/
<propertyupdate xmlns="DAV:" >
<set>
<prop>
<schedule-calendar-transp xmlns="http://cyrusimap.org/ns/"><transparent/></schedule-calendar-transp>
<schedule-calendar-transp xmlns="urn:ietf:params:xml:ns:caldav"><transparent/></schedule-calendar-transp>
<schedule-calendar-transp xmlns="http://apple.com/ns/ical/"><transparent/></schedule-calendar-transp>
</prop>
</set>
</propertyupdate>
EOF
```
returned
```xml
<?xml version="1.0" encoding="utf-8"?>
<multistatus xmlns="DAV:" xmlns:X9835="http://cyrusimap.org/ns/" xmlns:X27CD="urn:ietf:params:xml:ns:caldav" xmlns:XB875="http://apple.com/ns/ical/">
<response> …
```
> PROPPATCH: use right namespace prefix in response

- imap/http_caldav.c
This prevents accepting some invalid schedule-calendar-transp changes, like on the Scheduling Outbox, or with not exactly one parameter.  For example this was accepted:
```
curl -XPROPPATCH -Hcontent-type:application/xml -ume:pw --data-binary @- <<EOF http://server/dav/calendars/user/me/Default
<propertyupdate xmlns="DAV:">
<set>
<prop>
<schedule-calendar-transp xmlns="urn:ietf:params:xml:ns:caldav"><transparent/><opaque/></schedule-calendar-transp>
</prop>
</set>
</propertyupdate>
EOF
```
> proppatch_caltransp() - reject more invalid input

- imap/lmtp_sieve.c
- lib/imapoptions
- lib/libconfig.c
defaultdomain cannot be NULL, it defaults to `internal`. I see no way how can config_defdomain be NULL.  When I set in imapd.conf
> defaultdomain:
master logs “empty option value on line 7 of configuration file”, “exiting”.
Here the documentation is adjusted to the implementation.
> imapoptions: reword default value for calendar_user_address_set

- imap/http_cgi.c
environ is freed below and then in the next iteration of `service_main()` → `get_clienthost()` → `getnameinfo()` can call systemd’s nss-resolve:`getenv()`.
Fixes https://github.com/cyrusimap/cyrus-imapd/issues/5072.
> http_cgi.c:service_main() avoid use after free(environ)

- imap/httpd.c
- imap/imapd.c
- imap/nntpd.c
- imap/pop3d.c
- timsieved/parser.c
Tested with openssl s_client.  Properly fails if the client tries to use an unknown/incorrect ALPN string.  Continues to accept connections that don't use ALPN
> Add ALPN support for all IANA registered protocols

- cassandane/Cassandane/Cyrus/Search.pm
- imap/imapparse.c
This is prevents a crash when in unselected state and is also not allowed per the ABNF:
`esearch-source-opts =  "IN" SP "(" source-mbox [SP
"(" scope-options ")"] ")"`
> imapparse.c: don't allow empty Esearch source-opts

- imap/http_ws.c
txn->conn->resp_body_chunk() is already a h1/h2-specific function
> http_ws.c: use a common send callback

- imap/http_caldav.c
Fixes a crasher when the PROPFIND url is /dav/calendars
> Only allow PROPFIND calendar-timezone[-id] on calendar[-home-set]

- cunit/slowio.testc
One of the slowio cunit tests fails under valgrind because it expects a thing to happen instantly but valgrind slows it down.  This makes it not expect to be fast when running under valgrind.
> slowio.testc: don't expect lightning fast response under valgrind

- .gitignore
- Makefile.am
- cassandane/Cassandane/Cyrus/LibCyrus.pm
- cassandane/Cassandane/Instance.pm
- cassandane/cassandane.ini.example
- doc/examples/libcyrus/example_libcyrus.c
- doc/examples/libcyrus/example_libcyrus_min.c
- lib/auth.h
- lib/bitvector.h
- lib/command.h
- lib/cyr_qsort_r.c
- lib/cyr_qsort_r.h
- lib/glob.c
- lib/glob.h
- lib/md5.h
- lib/procinfo.c
- lib/procinfo.h
- lib/tok.h
- lib/xsha1.c
- lib/xsha1.h
- libcyrus.pc.in
- libcyrus_imap.pc.in
Cyrus installs a bunch of its headers so that other software can compile against the various libcyrus* libraries.  But if you try that it doesn't work, because of various problems in the headers that come of us assuming our code is always compiled from within the cyrus-imapd source tree.
This PR fixes some, but not all, of those issues.  It also adds example source files for calling the working parts of the Cyrus libraries, and adds a LibCyrus test suite to Cassandane to make sure they do actually compile and link correctly.
There's a lot more to fix in this space, but nobody's really asking for it anymore, and I ran out of steam months ago.  Here's a cleaned-up version of the former work in progress so we at least get some benefit from it, and future efforts to fix this stuff will …
> installed headers don't compile

- configure.ac
- imap/caldav_alarm.c
- imap/http_caldav.c
- imap/http_tzdist.c
- imap/ical_support.c
- imap/ical_support.h
- imap/itip_support.c
- imap/jcal.c
- imap/jmap_ical.c
- imap/xcal.c
Also handles the by_* arrays being renamed as part of the icalrecur-by-ref work
> Add compatibility layer to support libical icalrecur by ref and by value

- cassandane/tiny-tests/Caldav/options
- imap/http_caldav.c
This fixes a crash for OPTIONS /dav/calendars and adds tests that should've been part of the original PR
> http_caldav: only lookup annotation on real mailboxes

- cassandane/Cassandane/Cyrus/LibCyrus.pm
- cassandane/cassandane.ini.example
The LibCyrus tests compile and then run some example code, but attempting to run the compiled code will fail when Cassandane's rootdir is on a filesystem that is mounted noexec.
This PR makes these tests skip trying to run the compiled code if it looks like it won't be executable.  Detecting the noexec mount option requires the program `findmnt` -- if it's not installed, the noexec mount option won't be detected, and the tests will expect to be able to execute (and then fail if they can't).
Tested by mounting a new tmpfs partition with the `noexec` option, and then configuring cassandane.ini use a directory on that partition for its `rootdir`
> LibCyrus: don't run compiled examples if not executable

- cunit/backend.testc
- cunit/vg.supp
The backend.testc tests are leaking like this:
```
==346751== 4,608 bytes in 2 blocks are possibly lost in loss record 241 of 242
==346751==    at 0x48407B4: malloc (vg_replace_malloc.c:381)
==346751==    by 0x400423B: malloc (rtld-malloc.h:56)
==346751==    by 0x400423B: _dlfo_mappings_segment_allocate (dl-find_object.c:217)
==346751==    by 0x400423B: _dl_find_object_update_1 (dl-find_object.c:671)
==346751==    by 0x400423B: _dl_find_object_update (dl-find_object.c:805)
==346751==    by 0x400BD37: dl_open_worker_begin (dl-open.c:735)
==346751==    by 0x5320FC9: _dl_catch_exception (dl-error-skeleton.c:208)
==346751==    by 0x400B1C5: dl_open_worker (dl-open.c:782)
==346751==    by 0x5320FC9: _dl_catch_exception (dl-error-skeleton.c:208)
==346751==    by 0x400B5B7: _dl_open …
```
> suppress leaked sasl state from backend tests

- docsrc/imap/download/getcyrus.rst
These tools both appear really most sincerely dead.
> docs: remove korreio and cyrus-utils links

- cassandane/Cassandane/Config.pm
- cassandane/Cassandane/Cyrus/Master.pm
- cassandane/Cassandane/Instance.pm
- master/master.c
This means we can wrap a "is shutdown finished" check on the ready file as well
> master: unlink ready file on shutdown

- imap/xapian_wrap.cpp
These language code never were detected correctly, because they erroneously were compared lowercase against mixed-case strings.
Fixes #5118
> xapian_wrap.cpp: fix language code checks for "zr-hant" and "sr-me"

- docsrc/imap/developer/cyrusworks.rst
We no longer use Travis, we use GitHub Actions.
> docs: stop mentioning Travis CI

- cassandane/Cassandane/Cyrus/Info.pm
- lib/proc.c
- lib/proc.h
- master/master.c
Quoth @wolfsage:
> Say for example lmtpd repeatedly crashes for a user and then stops crashing. Now that user can't get **any** mail delivered since cyrus thinks the user now has too many active lmtpd connections!
> 
> Probably, when master records that a child has crashed, it should remove that child's pid from the cyrus proc dir…
Service processes clean up their own proc entry on clean shutdown, but they can't do that if they've crashed out.  This PR makes master detect this case and clean it up itself.
> clean up proc entries for crashed services

- cassandane/tiny-tests/JMAPEmail/email_get_bodypart_type_invalid
- cassandane/tiny-tests/SearchFuzzy/noindex_multipartheaders
- imap/message.c
Set an invalid content type header to "application/octet-stream" in the Cyrus-internal bodypart structure, rather than keeping it unset. This prevents later uses of this bodypart to assume it's of default type "text/plain".
> message.c: parse invalid content type as "application/octet-stream"

- imap/xapian_wrap.cpp
* xapian_snipgen_doc_part() utilize range-based for loop
* write_db_versions() accept versions as const
> xapian_wrap: in struct xapian_doc to use objects instead of pointers

- lib/assert.c
If we're configured to abort on fatal errors, log the assertion failure message before calling abort so that the message doesn't get lost.
Requested by @lerlacher-fm
> assert: log message before aborting

- imap/jmap_calendar.c
If the lines
```c
match->ical_uid = xstrdup(jscal->cdata.ical_uid);
match->utcstart = xstrdup(jscal->dtstart);
```
are moved just before `ptrarray_append(rock->matches, match);`, then two `free()` here can be skipped.
> jmap_calendar:eventquery_cb() memory leak

- cassandane/Cassandane/Cyrus/Prometheus.pm
- imap/httpd.c
- imap/imapd.c
- imap/lmtpengine.c
- imap/mupdate.c
- imap/nntpd.c
- imap/pop3d.c
- imap/sync_server.c
- timsieved/parser.c
sending a cleartext response to the client on failure is nonsense
> shut_down() the service if TLS negotiation fails

- imap/chk_cyrus.c
I have these mailboxes on my system:
```
user.me.Junk (\HasChildren)
user.me.Junk.Learn (\NonExistent \HasChildren)
user.me.Junk.Learn.Ham (\HasNoChildren)
user.me.Junk.Learn.Spam (\HasNoChildren)
```
As far as I understand it's perfectly valid to have a nonexistent parent in imap.
However, when I run `chk_cyrus` it gets a fatal error on `user.me.Junk.Learn`:
```
$ chk_cyrus -M user.me.Junk.Learn
Examining mailbox: user.me.Junk.Learn
bad mailbox user.me.Junk.Learn in chkmbox
fatal error: fatal error
```
I investigated and found that the fatal error was `IMAP_MAILBOX_NONEXISTENT`. It seems to me that shouldn't be a fatal error in `chk_cyrus`.
This PR has 2 small commits:
1. One of them prints the error out. With just this commit the output of `chk_cyrus` becomes:
```
$ chk_cyrus -M …
```
> chk_cyrus: Fix fatal error on nonexistent mailboxes

- imap/mbexamine.c
At the moment mbexamine stops when called with a (non-existent) intermediate mailbox.
This patch is especially useful if there are intermediate folders and mbexamine is called with wildcards.
fixes #5098
> make mbexamine handle (non-existent) intermediate mailboxes

- doc/legacy/overview.html
- docsrc/imap/reference/admin/access-control/identifiers.rst
- lib/imapoptions
Adds to https://github.com/cyrusimap/cyrus-imapd/pull/5104.
> Remove option auth_mech: krb (Kerberos 4)

- cassandane/Cassandane/Unit/TestCase.pm
This overrides Test::Unit::Assert's `assert_matches()` and `assert_does_not_match()` with our own, so we can get less confusing default failure messages.  The "$string did not match $pattern" from Test::Unit::Assert is very hard to read when $string contains multiple lines (such as a response object, caught exception, ical string, chunk of syslog, etc).
For multiline strings (that is, strings containing a newline followed by any non-newline), the new failure message says "[multiline string]" instead of the string.  In particular, this avoids cluttering up the exception stack with a string that might itself be an exception stack!  The actual string is logged, so it's still available if you want it.
For single line strings (including strings whose only newline is at the end), the string is …
> TestCase: override assert_matches with better default fail msg

- imap/http_proxy.c
- imap/httpd.c
- imap/httpd.h
Mostly just for completeness, and makes doing GET requests via telnet simpler when debugging.
Also, I can leverage this when starting to implement HTTP over QUIC - the ngtcp2 QUIC library has a sample/test HTTP/0.9 over QUIC client
> httpd.c: Add support for HTTP/0.9

- cunit/sieve.testc
> cunit/sieve.testc:notify() fix

- imap/mboxname.c
If we're at the top of the tree and we try to `mbpath -p ..`, we have no mbname pointer anymore, so don't try to call mbname_userid() on it.
> mbname_from_path: Don't crash with '..' at top of tree

- cassandane/Cassandane/Cyrus/Master.pm
- cassandane/Cassandane/Cyrus/TestCase.pm
- master/master.c
Fixes `Internal error: assertion failed (aborting): master/master.c: 340: c->proc_handle == NULL` error when DAEMON process exits abnormally
> fix master crash when DAEMON process exits abnormally

- .github/workflows/main.yml
- cassandane/Cassandane/Instance.pm
- cassandane/Cassandane/PortManager.pm
The key thing here is less that we're making the tests better — which is up for debate — but that it makes it the tests run with less weird Docker fiddling.
> avoid docker ipv6 nonsense

- cassandane/cassandane.ini.dockertests
Some trial runs show that these are all passing now.
> dockertests cassandane: skip nothing!

- imap/http_caldav_sched.c
found by compiling with -Wformat=2
> http_caldav_sched: fix typos in xsyslog calls

- Makefile.am
- configure.ac
- docsrc/imap/developer/releasing.rst
- tools/config2header
Adds a new option for configure: `--enable-release-checks`
With this option, configure/make will error out for these conditions:
* imapoptions entries that are marked UNRELEASED
* missing dependencies required to build the documentation
* files other than the template in changes/next
Without the option, these conditions are just warnings or ignored as usual.
I expect to use this option only in the final stages of building new public releases, to double check that everything is taken care of.  Between releases, this stuff doesn't matter and/or is the expected state of affairs, so the option isn't useful most of the time.
> add --enable-release-checks configure option

- imap/jmap_ical.c
Recent libical icalparameter_get_xvalue returns NULL if the parameter value actually isn't an x-enum value. This patch changes reading RELTYPE as either an IANA-enum or X-enum value, rather than special-casing a few known relation types when setting the relatedTo property in JSCalendar.
> jmap_ical: use verbatim RELTYPE parameter value

- cassandane/tiny-tests/JMAPMailbox/mailbox_changes_create_delete
- imap/jmap_mailbox.c
Bug reported by Neil in Fastmail tracker - if a folder was created and deleted between synces, it was being returned as "created" still.
> Created mailbox check

- imap/conversations.c
- imap/imapd.c
- imap/sync_support.c
- imap/user.c
There's two issues here:
1) basecid inconsistency causing TEMP/REAL mismatch
2) poor inbox detection on user rename causing bigger issues.  The second one is ALSO a known Fastmail issue on user rename, such that we do a full conversations rebuild after renaming.  This will fix that.
The reason these weren't detected earlier is that `ctl_conversationsdb -A` ONLY works on databases which support fetchnext, which skiplist doesn't, so we didn't notice these until switching to make twoskip the default.
> Fix conversations issues

- changes/next/caldav-alarm-path
- imap/caldav_alarm.c
- lib/imapoptions
I want to make $CONFDIR a tmpfs with a symlink farm for Fastmail, but the default db path is in the top level, so we need a way to specify that the database is elsewhere.
> caldav_alarm: add explicit path option

- cassandane/Cassandane/Cyrus/Conversations.pm
- changes/next/clearmodseq
- docsrc/imap/reference/manpages/systemcommands/ctl_conversationsdb.rst
- imap/conversations.c
- imap/conversations.h
- imap/ctl_conversationsdb.c
- imap/global.c
- imap/global.h
- imap/mailbox.c
- imap/mboxname.c
- imap/mboxname.h
This adds a --clearmodseq command to ctl_conversationsdb to allow cleaning up giant modseqs that are messing with Apple.
Due to the way replication works with this, we'll have to run it on all replicas, and since it writes, we're going to have to take down the replicas to run it too :(  Otherwise we'll just copy the new highestmodseq back!
> Clearmodseq

- imap/sync_support.c
The parser for replication can't handle there being intermediate records in the sync_cache.  We have fixed this at Fastmail by restarting the server to clear the cache, but better to just never cache it (and delete the record if there's one there)
> sync_support: don't cache intermediate records

- lib/cyrusdb_twoskip.c
This mirrors the code in commit/abort after unlocking.  We're about to replace *db with data from the new DB, so free up the memory.
> twoskip: free transaction after repack

- cassandane/tiny-tests/Caldav/invite_lots_of_attendees
- imap/http_caldav_sched.c
When the organizer gets stomped it can result in binary data being used when building the JSON structure which results in an 'Invalid UTF-8 string' error.
The stomping of the organizer value seems consistent if the iTIP request contains a large number of ATTENDEEs, but the JSON failure is random depending on what data the stomped organizer contains.
So, this is a hard problem/fix to write a test for.
> http_caldav_sched.c: fix for organizer getting stomped in sched_request()

- docsrc/overview/cyrus_bylaws.rst
Sphinx warns if the width of the underline falls short of the header text!
> docs: eliminate a sphinx warning from underlining

- changes/next/docs-sphinx-rtd-theme
- configure.ac
- docsrc/imap/developer/compiling.rst
Now that we're using the "sphinx_rtd_theme" them rather than a custom one (#5191), we need configure to notice and report when the dependency is missing, like the other documentation dependencies.
> configure.ac: want sphinx_rtd_theme for doc builds

- docsrc/overview/cyrus_bylaws.rst
This just backports changes to the team into v3.12.  I didn't want to Just Merge this because I don't know the v3.12 management process yet.  Apply at will!
> update board/bylaws/team in v3.12 branch

- docsrc/overview/cyrus_bylaws.rst
I'd like to get this on the live "core" site, which means applying it to v3.10.
> update board/bylaws/team in v3.10 branch

- cassandane/tiny-tests/JMAPEmail/email_query_emailaddress
- imap/xapian_wrap.cpp
Quotes signify phrase search in free text queries but were not supported in email queries since we supported querying for sub-parts of an email address. This reintroduces phrase search for email queries.
> xapian_wrap.cpp: support phrase search for email addresses

- cassandane/tiny-tests/JMAPEmail/email_import_zerobyte
- imap/message.c
Before, the parse continued but set incorrect header and body offsets for the body part. This resulted in log spam noting the discrepancy between the file size and header+body offsets, as well as a bogus in-memory MIME body structure.
> message.c: reject to parse MIME headers with NUL byte

- .github/workflows/main.yml
- cassandane/cassandane.ini.dockertests
...but keep --sysctl net.ipv6.conf.all.disable_ipv6=0
> import new testing from master branch to 3.6

- imap/user.c
uniqueid shouldn't be NULL, but if it is we shouldn't crash!
> user: protect against NULL uniqueid

- imap/backend.c
This is really annoying me!  On my windows box with WSL, it tries to connect to `bogus:0` and has slow resolution failures for every JMAP test because JMAP will connect to the smtp server in order to fetch capabilities.
This patch just checks for port == "0" which is always bogus, and returns before calling out to `getaddrinfo` so it doesn't wait.
> backend: don't even try to connect if port == "0"

- com_err/et/com_err.c
- com_err/et/error_message.c
- com_err/et/et_name.c
- com_err/et/init_et.c
- imap/conversations.c
- imap/imapd.c
This fixes a few build issues that compiling with clang-14 and clang-18 with `-Wall -Werror` were found by me and @rjbs . Known to build on x86-64 and aarch64.
> Make Cyrus build with clang `-Werror`

- imap/sync_support.c
I messed this up when creating the MR, uncache is good, but we have to do it before freeing the name.
> sync_support: uncache BEFORE freeing memory

- changes/next/notify_action_string
- sieve/script.c
These strings are largely useful for debugging, not end user consumption.
(This commit message was written by Ricardo Signes, replacing the previous internal Fastmail commit message.  The code change is by Bron Gondwana.)
> Don't send the "action strings" when notifying

- cassandane/Cassandane/Cyrus/TestCase.pm
HTTP::Tiny 0.83+ defaults to enabling SSL certificate verification.  The Net::DAVTalk modules can't currently configure SSL properly, so tests with a https service configured (ALPN.https_*) fail during setup when HTTP::Tiny is 0.83 or newer.
HTTP::Tiny 0.86+ adds an environment variable for restoring the old default behaviour of not verifying SSL certificates.
This PR sets the environment variable temporarily during setup to stop these tests failing.
Better fix to follow later, once Net::DAVTalk has been updated.
> TestCase: workaround for HTTP::Tiny behaviour change

- imap/jmap_ical.c
The conditional that validates the priority property value to be in the valid range from 0..9 had an error, effectively accepting any JSON value as a valid priority value. Any non-integer JSON value resulted in priority 0 to be set.
This patch keeps accepting any JSON integer value as priority (contrary to RFC8984 requiring it to be in the 0..9 range), but now rejects any non-integer JSON value.
Fixes #5226
> jmap_ical.c: reject non-integer priority value

- imap/httpd.c
> curl -H"Accept:text/vcard;version=4;version=5;charset=a;charset=b" -D- -upetr:pass http://127.0.0.3/dav/calendars/user/petr/
should actually be rejected as invalid.
> httpd.c.c:parse_accept() memory leak

- cassandane/tiny-tests/JMAPCalendars/calendarevent_set_participants_patch_empty_xprop
This test fails without [7cc73de8911e06d3da3cf5a503e5c8864c4391de](https://github.com/cyrusimap/libical/commit/7cc73de8911e06d3da3cf5a503e5c8864c4391de) and succeeds with it.
> Add JMAPCalendars.calendarevent_set_participants_patch_empty_xprop

- cassandane/Cassandane/Cyrus/TestCase.pm
- cassandane/tiny-tests/JMAPCore/echo_tls
Newer HTTP::Tiny turns on SSL certificate verification by default, which meant tests using HTTPS were failing.  This was previously worked around in #5227.
There have since been updates to Mail::JMAPTalk and Net::DAVTalk to pass through our SSL_options, so if the new versions of those are installed we can skip the workaround and do it properly instead, with certificate verification enabled.
Also added a simple test that exercises JMAP-over-HTTPS, because this was broken just like DAV-over-HTTPS was, just not visibly so because nothing used it.
> cass: support newer HTTP::Tiny, Net::DAVTalk, Mail::JMAPTalk

- cassandane/Cassandane/Cyrus/FastMail.pm
- cassandane/tiny-tests/JMAPEmail/email_query_unicodefdfx
Skip some tests that can't succeed if Cyrus was built without CLD2 and/or wslay
Though I'm not certain that JMAPCore.eventsource failing without wslay isn't showing us a bug.  What do we think?  It sets `Last-Event-Id => 0` and then explicitly expects a 200 response, but instead gets a 204 No content
> cass: annotate some tests with dependencies

- imap/index.c
- imap/message.c
This fixes crashers with parsing malformed MESSAGE/RFC822
> message: make some strcmps "safe"

- imap/conversations.c
- imap/conversations.h
- imap/ctl_conversationsdb.c
As discussed this morning, this should do two things:
1) avoid us finding a diff when only the basecid is different in G keys
2) replace binary gunk with human readable output
I did NOT make cyr_dbtool ungunk the binary output because that's not needed for this immediate issue.
> Ctl conversations basecid

- lib/util.c
gcc-12 leniently allows this without block scope but clang-14 fails.
> util.c: use block scope to declare variables in switch case

- lib/util.h
This way we can build with -Wpedantic again.
> util.h: xsyslog_ev: Don't use GNU extension in macro definition

- cassandane/tiny-tests/JMAPEmail/email_import_zerobyte
- imap/message.c
This reverts commits f56c25f7fa5eb77668e8d3ba706ca87d0c93ad56 and 0f137e7ab8dfbfaa14b0113cc8def0cc9eb2d94d to avoid reconstruct failing for messages that contain NUL bytes. We'll come up with a proper fix in https://github.com/cyrusimap/cyrus-imapd/pull/5253
> Revert "message.c: reject to parse MIME headers with NUL byte"

- cassandane/Cassandane/Cyrus/Annotator.pm
- cassandane/utils/annotator.pl
- changes/next/annotate-only-email
- imap/append.c
- imap/sieve_db.c
The annotator exists so that installations can update email messages to have extra flags or annotations.  Because "everything" is an email, it was also running on sieve scripts and other non-emails.  This was probably harmless on many installations, but not intended.
This branch updates the annotator to run only on messages being appended to mailboxes of type `e`.
It also fixes a bug in `sieve_db`, wherein we only set the authstate for the `onSuccessActivateScript` side effect, not the rest of script creation.
> append.c: only call out to annotator on email

- imap/http_carddav.c
- imap/http_rss.c
This fixes items missed in https://github.com/cyrusimap/cyrus-imapd/pull/5267 which fixed the mboxlist pathname detection for caldav but not carddav or rss.
> fix remaining mboxlist usage

- cassandane/Cassandane/Cyrus/Mboxgroups.pm
- docsrc/imap/reference/admin/access-control/identifiers.rst
- imap/imapd.c
**Reviewers: suggest reading this commit by commit**
* Adds basic documentation for the new `auth_mech: mboxgroups` authorization mechanism.
This was the only place any authorization mechanisms were documented, so I've added it here.  I'm not convinced this is the _best_ place to document authorization mechanisms generally, but I also don't want to undergo a major restructure of the documentation, so this'll do.  I tidied up the existing stuff a little while I was in there.
* Makes IMAP GETUSERGROUP command admin-only.  With this, a normal user could see any other user's groups, or any group's membership.  That felt wrong so I fixed it.
* Adds tests for the group management commands, cause I needed to figure out how they worked anyway
Closes #5252
> document mboxgroups

- imap/mboxlist.c
This might be closing the barn door after a horse has bolted, but it's useful to know when things were subscribed or unsubscribed!
> mboxlist: auditlog subscriptions

- cassandane/Cassandane/Instance.pm
- cunit/leaksanitizer.suppress
- cunit/parse.testc
- cunit/syslog.c
- cunit/vg.supp
- imap/search_expr.c
- imap/search_expr.h
- tools/build-with-cyruslibs.sh
This is mostly intended to be used in tandem with https://github.com/cyrusimap/cyrus-docker/pull/29/files but can stand on its own.
If you compile cyrus with `-fsanitize=address` and then run `LSAN_OPTIONS=suppressions=leaksanitizer.suppress make check` all tests pass minus those few skipped.
If you compile cyrus with `-fsanitize=undefined`, `make check` will pass but throw some warnings. To get it to fail, compile with `-fsanitize=undefined -fsanitize-undefined-trap-on-error` or use `halt_on_error=1 make check`.
When running cassandane with such a build, LSAN_OPTIONS and UBSAN_OPTIONS will be configured to send log files somewhere cassandane can see them, and cass will detect/report any detected log entries as failures (similar to how testrunner --valgrind works).
There's lots of work to …
> Sanitizer builds

- cunit/squat.testc
SquatInt32 is signed, so it can't encode > 2^31-1. SquatInt64 is also signed, so cannot encode > 2^63-1.
> squat.testc: Remove tests for invalid sizes for given encodings

- cunit/binhex.testc
It casts a (char *) to (uint16_t *), so pointers must be 2-byte aligned or we are in undefined territory.
> binhex.testc: bin_to_lchex requires 2-byte alignment on buffer

- imap/ical_support.c
Even though size is 0, it's still undefined behaviour to call it with a null pointer.
> ical_support: Don't call memcmp with a null pointer

- imap/jmap_ical.c
sha1hexstr() returns a pointer to the keybuf arg, so if we want to use id in a higher scope, keybuf must also exist in a higher scope.
> jmap_ical.c: Don't use stack variable out of scope

- cassandane/tiny-tests/JMAPEmail/email_set_create_encoding
- imap/jmap_mail.c
Before, Email/set{create} rejected body parts of type "message/rfc822" if the body value contained a CR or LF octet that is not part of a CRLF sequence. Now, bare CR or LF get rewritten to CRLF when converting the Email object to MIME.
This already is the case for "text/plain" attachments. Typically, CRLF sequences in attachments of these content types got inadvertently rewritten to bare LF during download or in text editors.
> jmap_mail.c: rewrite CR & LF to CRLF in message/rfc822 attachments

- lib/twom.c
This fixes some issues found with twom in production:
* full disk can cause the mmap to create 16k of blanks then fail to write the headers!  Use write instead for initial header and dummy
* readonly database can read a dirty file after a crash, meaning that it returns errors, always open RDWR and mmap readwrite.
Plus just makes the dump format a bit more regular.
> Twom fixes

- cassandane/tiny-tests/JMAPEmail/email_query_vcard_with_utf8_default
- imap/index.c
A MIME body part having Content-Type: text/vcard without the charset parameter would otherwise be decoded as US-ASCII, leading to any non-ASCII UTF-8 octets being replaced with the UTF-8 replacement character.
> index.c: use "utf-8" as default charset for vCard data

- lib/twom.c
Here's another twom fixup that does the better thing!  It was simpler than I expected.
This uses the level0 math and skips "broken" pointers at higher levels to give a clean read despite not having repaired the file.
There's an argument for repairing IFF the file wasn't actually opened read-only.  Right now it only does the repair when it goes for an exclusive lock.
> Twom readonly ok

- .github/workflows/main.yml
This will run the cunit tests under ubsan to find quick problems in cunit tests.
Later we can get cassandane running an ubsan build as well, but that will take some work to get it clean.
> Add ubsan `make check` build for CI

- docsrc/imap/concepts/overview_and_concepts.rst
- docsrc/imap/reference/admin/access-control/identifiers.rst
Follows on from #5271 
* Adds a link target to the new `auth_mech: mboxgroups` documentation, so that the 3.12 release notes will be able to link to it
* Makes the "overview and concepts" page not embed the entire "access control identifiers" page, just the first section of it.  This fixes a duplicate link target error that came up once the link target above was added
> small mboxgroups doc fixes

- cassandane/Cassandane/Cyrus/Conversations.pm
- imap/mailbox.c
This fixes a crasher we have with a user who's copying from their Archive folder to the Archive folder over and over in FM production.
> Copy to self refcount

- cassandane/tiny-tests/JMAPContacts/card_get_prodid
- imap/jmap_contact.c
vcardproperty_get_prodid() will return NULL if the property contains VALUE=X because the value type isn't TEXT and is stored in a different field of struct vcardvalue.
This patch treats VALUE=X as a text string
> jmap_contact.c: properly handle VALUE=X param on text-valued properties

- docsrc/imap/support/feedback-bugs.rst
Security reports should go to our private mailing list because of their sensitive nature.
> feedback-bugs.rst: Add link to security mailing list

- imap/http_client.h
- imap/httpd.h
- imap/jmap_mail_submission.c
Trying to build cyrus-imapd on macOS (12.5–15.2) fails with a compiler error `unknown type name 'ulong'` in imap/http_client.h and imap/httpd.h (even with no HTTP features enabled). That type does not appear to be defined anywhere in the source code.
Checking on Linux, it appears to be a Linux-specific thing, in my case coming from the following part of /usr/include/x86_64-linux-gnu/sys/types.h:
```c
#ifdef __USE_MISC
/* Old compatibility names for C types.  */
typedef unsigned long int ulong;
```
Using that typedef does not seem to add any value, replace it by the standard type.
> Fix compile error on macOS: unknown type name 'ulong'

- cassandane/Cassandane/Config.pm
- cassandane/Cassandane/Cyrus/Conversations.pm
- cassandane/Cassandane/Cyrus/CyrusDB.pm
- cassandane/Cassandane/Cyrus/HTTPPTS.pm
- cassandane/Cassandane/Cyrus/Info.pm
- cassandane/Cassandane/Cyrus/LDAP.pm
- cassandane/Cassandane/Cyrus/Mboxgroups.pm
- cassandane/Cassandane/Cyrus/Metadata.pm
- cassandane/Cassandane/Cyrus/Reconstruct.pm
- cassandane/Cassandane/Cyrus/Rename.pm
- cassandane/tiny-tests/Metadata/cvt_cyrusdb
- cassandane/tiny-tests/SearchFuzzy/audit_unindexed
- cassandane/tiny-tests/SearchFuzzy/reindex_mb_uniqueid
Remove all the 'twoskip' hard-coded values (this should basically be a NOOP since it sets the same defaults; but you can more easily change them in cassandane.ini without having the affected tests behave badly.
> Cassandane: use config for all DB types

- cassandane/Cassandane/Cyrus/Shared.pm
- cassandane/Cassandane/Cyrus/Subscriptions.pm
- cassandane/Cassandane/Instance.pm
- cassandane/Cassandane/Mboxname.pm
- cassandane/Cassandane/Test/Mboxname.pm
- cassandane/Cassandane/Util/Words.pm
- changes/next/5146-shared-subs
- imap/mboxlist.c
- lib/cyrusdb_flat.c
**Reviewers**: I'd suggest stepping through this one commit by commit
* Fixes #5146 by more strictly checking boundaries when converting between mboxlist dbnames and keys.
* Adds a new Cassandane suite "Shared" with tests for subscribing to shared mailboxes.  I expect we'll accumulate other shared mailbox tests here over time.
* Bumps the subscriptions database version number from 2 to 3, and makes the upgrade-on-open path fix any broken v2 entries it finds.  It fixes the bad subscriptions by string manipulation -- it does _not_ check whether those mailboxes actually exist, nor whether the subscribed user has access to them.  I don't think this is a problem, as I believe you can ordinarily be subscribed to mailboxes that don't exist, or which you cannot see, and you just won't see them, …
> fix shared mailbox subscription bug when one user is prefix of other

- cassandane/Cassandane/Cyrus/JMAPCore.pm
- cassandane/tiny-tests/JMAPCore/user_counters
- imap/jmap_core.c
contactsModSeq should pair with contactsFolder*, not contactFolder*.
submission counters were missing.
Add tests to show they all work and contain numerical values.
> UserCounters/get: Report all fields correctly and as intended

- cassandane/Cassandane/Cyrus/Conversations.pm
- lib/twom.c
This fixes a bug where aborting a twom transaction followed by closing the database leaves a dangling mmapped region as long as the process still is running.
The bug is the result of truncating the file->size field in the recovery1 function. If the file has previously been mmapped to a larger region than that new size, the munmap following a db_close leaves the remaining region mapped for the process.
> twom.c: don't truncate file->size during recovery

- cassandane/Cassandane/Instance.pm
Noticed this in the cleanup logs from running Cassandane after a previous run had had failures:
```
Cleaning up old basedir /dev/shm/cass/0245170103ubsanlogs
```
Whoops! :)
> Instance: fix missing / in sanitizer logs path

- cunit/command.testc
- imap/append.c
- imap/mailbox.c
- imap/mboxkey.c
- imap/prometheus.c
- imap/seen_db.c
- imap/sievedir.c
- lib/cyrusdb_quotalegacy.c
- lib/util.c
- lib/xunlink.c
- lib/xunlink.h
We almost always ignore this case anyway. Swallowing it here prevents some `syserror=<No such file or directory>` pollution in unrelated log lines.
With this change, if you DO care to differentiate between "file has been unlinked" and "file didn't exist anyway", you need to use unlink directly (and check/log errors yourself!)
Fixes some call sites to not do redundant logging or ENOENT checking
> xunlink: clear errno and return 0 on ENOENT

- cunit/aaa-db.testc
- imap/search_xapian.c
- lib/twom.c
Fixes a bug that surfaced when trying to reindex a Xapian database during compaction. The root cause is that the twom backend does not create the parent directory of a database file when create-opening a database, but creating that parent directory is expected by the cyrusdb API. In addition to fixing the bug, this PR adds a cunit test that asserts create-opening databases in inexistent directories for all database backend implementations.
> twom.c: return NOTFOUND when creating a db in an inexistent dir

- Makefile.am
otherwise it doesn't get distributed, and Cyrus can't be compiled from a source tarball because files are missing.
Looks like xxhash.h is only used to inline a bunch of stuff straight into twom.c, it's not a general-purpose library header.  So it goes into the same foo_SOURCES section as twom.c, and not one of the foo_HEADERS sections.
---
The way you test this sort of thing from a git tree is:
```
$git clean -xfd
$autoreconf -is
$./configure --enable-maintainer-mode
$ make distcheck
```
(Notice that this bypasses all of your usual build environment scripting and stuff! So you'll probably need to add the cyruslibs "bin" directory to your PATH temporarily, and perhaps some other things, so that the `make distcheck` step can succeed without false negatives.)
Among other things, `make …
> Makefile.am: needs to know about xxhash.h

- imap/sync_support.c
- imap/sync_support.h
Remove unused functions sync_send_restore() and sync_msgid_remove().
> imap/sync_support: make some functions static

- lib/util.c
so that `message_parse_mapped()` can be called concurrently and each thread can log via `charset_decode_sha1()` “ignoring invalid base64 characters”.
Besides, there is no point to have the variable `buf` static here.
> xsyslog_fn(): make `struct buf buf` non-static

- imap/http_caldav.c
- imap/http_dav.c
- imap/http_dav_sharing.c
Rationale: when an admin user sends PROPPATCH, then the annotations set by the mailbox owner shall be updated.  This permits the admin user to modify WebDAV properties without fighting with the annotations database directly or asking for the user’s password.
Admitted, not all cases for PROPPATCH are handled here.
> proppatch_todb(): do not mask the annotations for admins user

- imap/http_caldav.c
and enforce that the submitted value is valid.
This allows setting for the CY:scheduling-enabled property only the values `F`, `f`, `NO`, `No`, `no`, and `nO`, as all other values are irrelevant in _scheduling_enabled().  By applying also https://github.com/cyrusimap/cyrus-imapd/pull/5060 it is ensured that whoever sets the property, it will be stored for the user "", as only this user is checked by _scheduling_enabled().
As can be seen in the code, this property is stored by `proppatch_todb_nomask()`.
> http_caldav.c: make property scheduling-enabled live

- imap/sync_support.c
We might abort if this returns non-zero, so let's make sure to loudly log why we're returning non-zero...
> sync_support: stronger logging in sync_mailbox_compare_update

- changes/next/0000-TEMPLATE
Adds a Documentation section to the changes template file.  This will hopefully:
* prompt us to find and update/create documentation as part of our development work
* make it easy for the person writing release notes months later to cross-reference that documentation
> 0000-TEMPLATE: add Documentation section

- cunit/command.testc
- imap/append.c
- imap/mailbox.c
- imap/mboxkey.c
- imap/prometheus.c
- imap/seen_db.c
- imap/sievedir.c
- imap/squat_build.c
- imap/sync_log.c
- lib/cyrusdb_quotalegacy.c
- lib/xunlink.c
- lib/xunlink.h
(This also makes a related change in imap/append.c.)
Recently, xunlink was changed to restore errno after a call if the result was ENOENT, on the theory that we use xunlink when we know the file might not exist, and that we should treat ENOENT like success.  "If we care about the result, we should use unlink, not xunlink!" we said, at the time.
Unsurprisingly, we've now found a case where we care.  During append, we try to remove any file that might be in our way.  If this works, it means there *was* a file, and we report an error.  Unfortunately, when xunlink changed, it seemed like there was *always* a file, because we started to get 0 instead of ENOENT.
This is not a perfect fix, since it will now treat (say) EACCES as "there was nothing to delete".
This just addresses one or two …
> xunlink: return +1 when nothing removed because ENONET

- Makefile.am
Removes a bunch of brittleness from Makefile.am by not applying feature-conditional logic to man pages.  Closes #4797.
Adds a couple of newer man pages to what's installed/distributed which had been overlooked previously.
> always build/install/distribute manpages

- imap/lmtpd.c
The autocreate_inbox function checks for "anonymous" userid before calling autocreate_user but the latter function also contains a check for "anonymous" userid. Remove the check in autocreate_inbox and leave it to autocreate_user to reject the "anonymous" userid.
Fixes #2539
> lmtpd.c: remove redundant check for "anonymous" userid

- docsrc/overview/cyrus_bylaws.rst
Selsky has not been working on Cyrus in a long time, and says he can be removed from the core dev list.
> cyrus_bylaws.rst: remove Matthew Selsky from core devs

- tools/config2rst
> config2rst: do not double-indent topmost section text

- configure.ac
This is largely to simplify our prereq detection.  Also, Python v2 is dead as heck.
> require Python 3 for building the docs

- lib/imapoptions
This option got introduced for version "2.3.17" but it seemingly never got implemented. The commit ref that introduced it is ced20b69d8064480d05e6f40da4093584b4c4ae9
Fixes #2948
> imapoptions: deprecate unused "postspec" option

- imap/http_dav.c
propfind_by_collection returned 0 despite any unexpected error making it return early.
Fixes #3258
> http_dav.c: do not suppress unexpected errors in PROPFIND

- master/master.c
See issue #5309 for a full discussion.
Pending SIGCHLD signals (and others too) can be ignored by pselect if one of the waited sockets is ready, or if the timeout is 0 (on some systems), causing shutdown to fail.
> Fix for deadlock on shutdown

- imap/reconstruct.c
Reconstructing mailboxes with the undocumented 'm' command line flag isn't implemented since over 20 years.
Fixes #3068
> reconstruct: remove dead code of unsupported 'm' flag

- imap/append.c
- lib/twom.c
- lib/util.c
- lib/util.h
This fixes a bug where append thinks it has copied the file into place, but it was fsyncing the content (which copyfile already did) rather than the directory
> cyrusdb_copyfile: sync the directory after copying file

- lib/map_nommap.c
- lib/map_shared.c
- lib/map_stupidshared.c
This reverts the changes from https://github.com/cyrusimap/cyrus-imapd/pull/4840 which turns out to leak mmaps!  You can't just munmap a different length than you passed to mmap.
Instead, we're going to find the actual bugs and fix them as we hit them.
> Buf mmap fix length

- docsrc/imap/developer/releasing.rst
This is obsolete.  There is now a marker for "this is latest release".
> docs: remove "order of operations" for release

- cassandane/tiny-tests/JMAPContacts/cardgroup_set_update
- imap/jmap_contact.c
If the card is a group, cdata will be overwritten by membership lookups
> jmap_contact.c: /set{update} needs a copy of vCard UID and URL

- .github/workflows/main.yml
- cassandane/Makefile
We don't actually need to do a syntax test as part of make all.  It can be its own thing, run on demand.  My thinking is that it should be run by the human or robot running the tests, based on whether they think they're likely to *save* or *lose* time by compiling everything up front.  For a two-test run, `make syntax` is probably a waste.  For all the tests, it's just noise.  (On my MacBook Air M2, it takes 7s.)
The next step will be to make `cyd test` run `make syntax` iff there are no positive test specifiers given.  (That is: run it for `cyd test` and `cyd test !Foo` but not `cyd test Bar`.)
> cassandane/Makefile: do not run the syntax test by default

- cassandane/tiny-tests/JMAPEmail/email_set_create_memo_no_splitconv
- imap/message.c
Messages with the '$memo' flag are meant to store notes associated with another email. Such messages must not cause the conversation to split, as otherwise the note and its related email would end in separate threads.
> message.c: do not split conversations for messags with '$memo' flag

- imap/annotate.c
- imap/append.c
- imap/attachextract.c
- imap/autocreate.c
- imap/ctl_cyrusdb.c
- imap/dav_db.c
- imap/fetchnews.c
- imap/mailbox.c
- imap/mailbox.h
- imap/mboxlist.c
- imap/mboxname.c
- imap/relocate_by_id.c
- imap/search_xapian.c
- imap/seen_db.c
- imap/sievedir.c
- imap/sync_log.c
- imap/user.c
- lib/cyrusdb.c
- lib/cyrusdb_flat.c
- lib/cyrusdb_quotalegacy.c
- lib/cyrusdb_skiplist.c
- lib/mappedfile.c
- lib/proc.c
- lib/twom.c
- lib/util.c
- lib/util.h
I was originally planning to just use renameat in mappedfile, but on reflection I built an API wrapper for rename, and used that everywhere (except twom; which tries not to use the rest of cyrus libs for portability)
> use renameat and fsync(dirfd) for ALL renames

- cassandane/tiny-tests/JMAPEmail/email_query_inmailbox_before
- imap/jmap_mail.c
Found in production at Fastmail - if you search in a folder that has never had any messages via JMAP, it will resolve the query expression to OP_FALSE, then diligently open every single mailbox, load the index, and check every message against OP_FALSE to see if it matches.
There's a slight efficiency inside index.c at least, that it knows the message can never match and doesn't load in everything, but still - better to just bail!
> Search non conversations mailbox

- imap/mailbox.c
Right now we're doing ONE message at time, which is super inefficient
> mailbox: fix expunge limit

- changes/next/cyr-expire-options
- imap/cyr_expire.c
- lib/imapoptions
1) expire_by_savedate (default true)
If set, check the savedate rather than gmtime on records to decide
whether to expunge them
2) expire_keep_flagged (default false)
If set, never expunge messages with the \Flagged system flag set.
> cyr_expire: add config options to control expunging

- imap/http_admin.c
- imap/http_applepush.c
- imap/http_caldav.c
- imap/http_carddav.c
- imap/http_cgi.c
- imap/http_dav.c
- imap/http_dav_sharing.c
- imap/http_dblookup.c
- imap/http_ischedule.c
- imap/http_jmap.c
- imap/http_prometheus.c
- imap/http_rss.c
- imap/http_tzdist.c
- imap/http_webdav.c
- imap/jmap_admin.c
- imap/jmap_backup.c
- imap/jmap_blob.c
- imap/jmap_calendar.c
- imap/jmap_contact.c
- imap/jmap_core.c
- imap/jmap_mail.c
- imap/jmap_mail_submission.c
- imap/jmap_mailbox.c
- imap/jmap_mdn.c
- imap/jmap_notes.c
- imap/jmap_quota.c
- imap/jmap_sieve.c
- imap/jmap_vacation.c
https://github.com/cyrusimap/cyrus-imapd/pull/5332 aims to add clang-format formatting rules for the Cyrus codebase. The JMAP and DAV code in Cyrus uses static struct literals to initialize a couple of common data structures. We want to keep these consistently formatted for every entry, but clang-format seems not be able to apply consistent struct literal formatting across nested struct lists.
This patch disables clang-formatting for the code areas that area known to produce inconsistent struct literal formats in the JMAP and DAV code.
> clang-format: disable formatting for JMAP and DAV API struct literals

- .github/workflows/main.yml
The default --format is now "pretty", so if we want "prettier" on the first run, we must say so explicitly.
> GitHub Action: pass --format to first-pass cyd test

- imap/dav_db.c
- imap/mboxlist.c
This fixes an issue found at Fastmail where dav_reconstruct -a was wiping the dav contents for a user who had renamed to an alphabetically earlier name, because it was wiping the database when trying to iterate the later name - and finding the same path by uniqueid.
> Cyr 1785 dav reconstruct only valid users

- cassandane/Cassandane/Config.pm
It was (accidentally?) changed from twoskip to skiplist by f75c3e8584f03ca1eb322ae36b5de5787c70cc52
Skiplist doesn't properly support shared access (bug?), so it's a poor choice for conversations_db.
I think we'll probably want to switch most of these defaults to twom soon, but I'll leave that for a separate PR.
> cassandane: use twoskip for conversations_db

- cassandane/tiny-tests/JMAPEmail/email_set_create_subject_with_address
- cunit/charset.testc
- imap/caldav_util.c
- imap/carddav_db.c
- imap/dav_util.c
- imap/http_jmap.c
- imap/jmap_mail_submission.c
- imap/jmap_notes.c
- imap/jmap_notif.c
- imap/message.c
- imap/sieve_db.c
- lib/charset.c
- lib/charset.h
- sieve/bc_eval.c
The current charset_encode_mimeheader function encodes its input differently depending on if the header value contains an email address or not.
- If it finds email addresses, it Q-encodes only the display name of the adress and appends the email address as-is. Any *trailing* non-email address content is discarded, but any non-email address content *in-between* valid addresses is kept as-is. For such input, this function currently produces invalid address-list headers.
- If instead if does not find an email address, then it encodes the entire header using Q-encoding.
This patch moves the address-list encoding into its own function, charset_encode_addrheader:
- The charset_encode_mimeheader from now on always encodes its given value in entirety in Q-encoding.
- The charset_encode_addrheader …
> charset.c: split address-specific encoding from encode_mimeheader

- imap/jmap_contact.c
Fixes a regression introduced in 19aec717541fe03c3c29d5032256256e49701afb
> jmap_contact.c: cache X-ABADR group names case-insensitively

- cassandane/Cassandane/Unit/Formatter.pm
Adds the finished time to the summary printed at the end of the run.  This will apply to all output formats that use the base class `finished()` and `print_summary()`, which at the moment is "pretty", "prettier", and "tap", but not "xml".
That is, the "Finished:" line has been added, like this:
```
Time:  3 wallclock secs ( 0.02 usr  0.01 sys +  1.44 cusr  1.18 csys =  2.65 CPU)
Finished: 11:25:14
OK (13 tests)
```
If I step away and then come back to finished Cassandane results, it's not always clear to me whether they are the results I wanted, or if I actually forgot to start it and I'm just seeing leftovers from the previous run.  Having the finish time in the output removes that ambiguity.
I could add the start time here too if anyone thinks it would be useful, but I don't want to …
> cass: print finished time

- Makefile.am
This makes it so if you've configured with --enable-release-checks, then warnings from sphinx-build will be fatal errors that disrupt the build.
CI already complains about this stuff, so that we don't introduce documentation bugs during normal PRs. But release notes for new releases don't get run through CI until after they've already been pushed, so this gives a similar kind of protection for those.
> fatal sphinx-build warnings when release checks enabled

- cunit/cyrunit.h
- imap/cyr_ls.c
- imap/http_caldav.c
- imap/http_carddav.c
- imap/http_tzdist.c
- imap/httpd.c
- imap/imapd.c
- imap/index.c
- imap/jmap_contact.c
- imap/lmtpengine.c
- imap/promstatsd.c
- imap/sync_support.c
- imap/xcal.c
- imtest/imtest.c
- lib/times.c
- master/service.c
- sieve/sieve.y
This PR shushes individual `-Wformat-nonliteral` warnings in places where we have no choice but to use a non-literal format string.  The intent is that we'll be able to compile with `-Wformat=2` to more aggressively detect misused printf-style functions, and only get errors from actual (new) problems.  I was also able to fix a couple of things that were detected with the higher warning level, so it's already doing its job.
In one location (master), it removes a previous suppression of `-Wformat-security`.  This line isn't actually generating a `-Wformat-security` warning, so I removed the suppression to avoid masking future problems.  promstatsd has a similar piece of code without the suppression, so I have given it the same suppressions and comment.
I have temporarily added `-Wformat=2` …
> shush known format-nonliteral warnings

- imap/append.c
- imap/mailbox.c
- imap/mailbox.h
- imap/sync_support.c
- imap/unexpunge.c
- lib/mappedfile.c
- lib/twom.c
- lib/util.c
- lib/util.h
Change cyrus_mkdir to use fsync'd mkdir, and also directly fsync the directories being created when creating a new file for mappedfile.
I didn't go back and patch skiplist, but it gets twoskip via mappedfile, and twom and cyrus.index file creation are explicit
> Fsync mkdir

- imap/tls.c
SSL_SESSION_get_time_ex() is Y2038-safe replacement for SSL_SESSION_get_time(), introduced in openssl 3.3+
> SSL_SESSION_get_time() is deprecated, use SSL_SESSION_get_time_ex() with openssl 3.3+

- imap/imapd.c
- imap/imapd.h
Also, sorts STATUS items by RFC number
The omission was noted by Daniel Eggert @ Apple.
> imapd.c: Add support for STATUS APPENDLIMIT (RFC 7889)

- cassandane/Cassandane/Cyrus/TestCase.pm
- cassandane/tiny-tests/Replication/rename_old_synccache
- imap/sync_support.c
This fixes a couple issues seen in Fastmail production with renames
One issue is rename A -> C -> B; depending which user is the initiating userid in sync_do_user, it locks that one first; leading to lock inversion issues.
Also, the tombstone check can wind up adding same folder, same partition to the rename list, which the replica will reject!
> Sync rename lock order

- cassandane/Cassandane/Cyrus/JMAPCore.pm
- cassandane/Cassandane/Unit/TestCase.pm
- cassandane/tiny-tests/JMAPCore/get_session
- cassandane/tiny-tests/JMAPMailbox/mailbox_set_name_toolong
- imap/jmap_mail.c
- imap/jmap_mail.h
- imap/jmap_mailbox.c
- Mailbox-specfic limits moved from jmap_mail.c to jmap_mailbox.c
- maxSizeMailboxName enforced in _mboxset_args_parse()
- emailsListSortOptions renamed to emailQuerySortOptions
> jmap_mailbox.c: add maxMailboxDepth & maxSizeMailboxName to accountCapabilities

- changes/next/deprecate-tls-server-dhparam
- lib/imapoptions
This is no longer needed by OpenSSL >= 3.0.
As noted by Dilyan Palauzov
> imapd.conf: Deprecate the 'tls_server_dhparam' option.

- cassandane/Cassandane/Cyrus/ALPN.pm
- cassandane/Cassandane/Cyrus/Alpaca.pm
- cassandane/Cassandane/Cyrus/StartTLS.pm
- changes/next/cyr-1846-allowstarttls
- imap/httpd.c
- imap/imapd.c
- imap/lmtpengine.c
- imap/mupdate.c
- imap/nntpd.c
- imap/pop3d.c
- imap/sync_server.c
- imap/tls.c
- imap/tls.h
- lib/imapoptions
- timsieved/actions.c
- timsieved/lex.c
This also only allows HTTP upgrade to TLS on backends in a Murder
> Gate STARTTLS (and its variants) with allowstarttls option

- cassandane/Cassandane/Cyrus/Info.pm
- imap/cyr_info.c
Makes `cyr_info conf-lint` not complain about e.g. `http_sasl_mech_list: PLAIN`
Fixes #5424
> cyr_info: recognise service-prefixed sasl keys in conf-lint

- cassandane/Cassandane/Cyrus/JMAPSieve.pm
- cassandane/tiny-tests/JMAPSieve/too_many_createdids
- imap/jmap_api.c
- imap/jmap_api.h
- imap/jmap_core.c
- imap/jmap_err.et
clientIds hash table sized based on the request arguments
> jmap_api.c: limit size of client-provided createdIds

- cassandane/Cassandane/Cyrus/UIDbatches.pm
- changes/next/imap-uidbatches
- docsrc/imap/rfc-support.rst
- imap/imapd.c
- imap/imapd.h
- imap/promdata.p
- lib/imapoptions
This PR will track the progress of [draft-ietf-mailmaint-imap-uidbatches](https://datatracker.ietf.org/doc/draft-ietf-mailmaint-imap-uidbatches/)
I sent the output of the Cass test to Daniel and he says it looks correct.  I'd like to get this on a FM server so he can test against it.
> imapd.c: Implement IMAP UIDBATCHES

- cassandane/tiny-tests/JMAPEmail/email_query_cache_collapsed_threads
- imap/jmap_mail.c
When you "Email/query" with collapseThreads = true, we store in the cache info necessary for both collapsed and uncollapsed results.
When you "Email/query" with collapseThreads = false, we were not storing info necessary for collapsed threads results, so subsequent requests that hit the cache but have collapseThreads = true would return 0 items.
Fix that by always computing both
> Email/query: Always track collapsed matches so query cache is consistent

- configure.ac
The call to `func("abc", ...)`, if run, would have qsorted the bytes of the string literal "abc", which is undefined behaviour.
When building with -Wwrite-strings and -Werror (as we usually do), the attempt to write to a string literal is a compile-time error. The check misinterprets this as function nesting being unavailable.
This fixes it to call func correctly, with a modifiable buffer, preventing the unrelated compiler error.
> configure.ac: make 'function nesting' check safer

- cunit/libconfig.testc
- imap/caldav_alarm.c
- imap/caldav_util.c
- imap/global.c
- imap/global.h
- imap/httpd.c
- imap/httpd.h
- imap/jmap_vacation.c
- imap/mboxevent.c
- imap/nntpd.c
- lib/libconfig.c
- lib/libconfig.h
- sieve/interp.c
- tools/config2header
This was a mess of `unsigned long` and `unsigned long long`, which we've been getting away with on amd64 where both types are 64 bits wide, but it's not portable: `unsigned long` may be only 32 bits, which breaks sieve_extensions.
We expect bitfields to be 64 bits wide, so be explicit.
> libconfig: use explicit uint64_t for bitfields

- imap/http_admin.c
This is all freed a few lines later by the call to deinit_piarray()
Based on a patch by @MASHtm in #5420
> http_admin: fix double-free in action_proc()

- cassandane/Cassandane/Cyrus/Reconstruct.pm
- imap/mailbox.c
Found this while rewriting the read/write code on a separate branch.  Figured it made sense to get this fix into master first.
> mailbox.c: fix a v10 repack bug and plug a memory leak

- docsrc/imap/developer/major-releasing.rst
- docsrc/imap/developer/releasing.rst
The way we update the website has changed as of earlier this year, so I've updated the documentation to describe the new process.  I've also updated a handful of other details while I was at it, so the documented process more closely reflects what I actually do.
> docs: update release process documentation

- imap/http_rss.c
- imap/jmap_mail.c
- imap/jmap_mail_query.c
The MIME parser in almost all cases guarantees the body part media type to be set, but it does not for invalid MIME messages that already are on disk. This is a known issue that needs to get fixed in "reconstruct" first.
Also see https://github.com/cyrusimap/cyrus-imapd/pull/5254
> jmap_mail.c: use safe string comparison for body part types

- imtest/imtest.c
Before this change the output of `sivtest` contained
```
{0+}
C:
```
now it is
```
C: {0+}
```
> imtest: fix output for `C: {0+}`

- cassandane/Cassandane/Cyrus/Master.pm
- cassandane/Cassandane/Instance.pm
- cassandane/utils/fakesaslauthd
- cunit/libconfig.testc
- cunit/unit.c
- cunit/vg.supp
- imap/idlemsg.c
- imap/mupdate-slave.c
- master/master.c
This improves a few aspects of the master binary's file and filesystem handling:
* When opening or creating `pidfile`, `pidfile_lock`, and `error_log` during startup (i.e. probably as root), don't permit symlinks to be followed.
* Don't chdir to the cores directory until after dropping privileges.
And in general:
* No need to chmod unix domain sockets
> master: tighten up pidfile/etc handling

- cassandane/Cassandane/Cyrus/JMAPTestSuite.pm
- cassandane/Cassandane/Cyrus/JMAPTestSuiteWS.pm
... and same for JMAPTestSuiteWS.  These tests [have been updated](https://github.com/fastmail/JMAP-TestSuite/pull/40) and no longer pass on 3.12 or earlier
> JMAPTestSuite: suppress t:core:jmap-session-resource before 3.13

- cassandane/Cassandane/Cyrus/Simple.pm
- imap/imapd.c
Fixes #5481
I don't see a good way to test this.  It is possible to coerce Cassandane and Mail::IMAPTalk into using AUTHENTICATE instead of LOGIN, but then Mail::IMAPTalk doesn't expose the details of the SASL transaction, so I can't interrogate whether the initial response was actually used or not.
> imapd: fix typo in SASL-IR capability

- .github/workflows/main.yml
This gives us a valgrind report per test, rather than a single confusing report for the entire run.  It takes longer to run in the usual case, but when something does fail, the error report is easier to understand.
Is the longer run time tolerable?
> github-actions: valgrind 'check-discrete' rather than 'check'

- imap/imapd.c
- imap/imapd.h
- imap/imapparse.c
Also, logs ANNOTATE use with APPEND, STORE, SEARCH, SELECT
> imapd.c: split logging of client use of ANNOTATE (message) and GET/SETANNOTATION (mailbox)

- cassandane/Cassandane/Cyrus/Reconstruct.pm
- imap/mailbox.c
- imap/mailbox.h
- imap/reconstruct.c
reconstruct will still report repack errors,
but the new cyrus.index will not be written to disk
> reconstruct.c: implement use of --dry-run (-n) with --set-version (-V)

- imap/haproxy.c
Fix compiler warning:
```
CC       imap/libcyrus_imap_la-haproxy.lo
../imap/haproxy.c: In function 'haproxy_read_hdr':
../imap/haproxy.c:22:35: warning: initializer-string for array of 'char' truncates NUL terminator but destination lacks 'nonstring' attribute (13 chars into 12 available) [-Wunterminated-string-initialization]
22 |     static const char v2sig[12] = "\x0D\x0A\x0D\x0A\x00\x0D\x0A\x51\x55\x49\x54\x0A";
|                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Well, it now uses 13 bytes to store the data, instead of 12 bytes, which is probably aligned to 16 bytes on 16bit systems, or even 32 bits on 32 bit systems.
> haproxy.c: v2sig - fix compiler warning

- .github/workflows/main.yml
This is ready for review.
It makes the ci builds be explicit rather than using the matrix combination strategy with exceptions for different options.
It also names the builds explicitly so the names are clearer/more descriptive
> Ci unroll matrix

- .github/workflows/main.yml
- cassandane/Cassandane/Unit/FormatPretty.pm
- cassandane/testrunner.pl
When cassandane tests fail in CI, it can be hard to see which ones failed:
* at the "run cassandane quietly" stage, the failing tests are lost in a sea of OKs
* at the "rerun cassandane failures noisily" stage, they're lost in a sea of detailed error logging
This PR adds a "no_ok" formatter parameter for suppressing success results, and implements it for FormatPretty (i.e. `pretty` and `prettier`).  Formatters that don't recognise it (`tap`, `xml`) will ignore it.  Call `testrunner.pl` with `--no-ok` to enable this behaviour.
`cyd test` doesn't yet know about `--no-ok` and will reject it as an invalid argument, so to use the new testrunner option with cyd, for now you'll need to smuggle it through as a non-option argument.  The main.yml workflow has been updated to do this for the "run …
> cassandane: option to suppress success output (only show errors and failures)

- cunit/ical_support.testc
The content of http_cal_abook_admin.js  is used in list_addressbooks():
```c
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wformat-nonliteral"
/* format string comes from http_cal_abook_admin_js.h */
buf_printf(body, http_cal_abook_admin_js, CYRUS_VERSION, http_cal_abook_admin_js_len);
#pragma GCC diagnostic pop
```
In the past I have seen compiler warnings, when http_cal_abook_admin_js does not end with `\0`.
With this change, if http_cal_abook_admin.js does not end in `\0`, then `make check` fails.
> cunit/ical_support: verify the last byte of http_cal_abook_admin.js is 0

- imap/caldav_alarm.c
- imap/mailbox.c
- imap/mailbox.h
- master/master.c
We used to do a check if conversations were enabled, which required a mailboxes.db lookup, for EVERY record in some tight loops.  This caches the value while still meaning that release commands also release the conversation state
> mailbox: cache conversationsdb state, including lack of

- imap/index.c
- imap/index.h
- imap/reconstruct.c
- lib/util.c
This adds a index_warmup before we take the lock on each mailbox, ensuring that the user's files are freshly cached and won't cause page faults!
(It also means that cyrus.cache will be loaded by the IMAP XWARMUP command)
> Warmup mailbox

- imap/sync_support.c
This fixes an issue where if a replica got left for too long without wiping folders, they just sit around forever logging "no tombstone" errors.  We want a way to clean them up, and the "no-copyback" option to sync_client is good for that.
> sync_support - if running with no_copyback, delete excess folders from replica

- imap/global.c
Every single program that loads config with debug off will currently log "debug logging turned off", which feels sort of ironic.  Also, it's annoying for processes that might run *really* often, like `mbpath`.  Let's set the debug level quietly to whatever was configured, then log when it's toggled during runtime.
> global.c: only start logging debug toggle after initial setup

- cunit/dynarray.testc
- lib/dynarray.c
- lib/dynarray.h
To use `dynarray_append()`, you need to already have the object you want to append to the array.  If you don't, you need to construct one in scratch space somewhere, so it can be copied into place by `dynarray_append()`, and then (shallowly) discard the scratch space copy.
This PR adds `dynarray_append_empty()`, which allocates a new, empty, slot in the array, and gives you back a pointer to it so you can construct its value in place.  For trivial objects the difference is academic, but for complex objects it avoids the memcpy and simplifies the memory management.
It also updates `dynarray_append()` to return the index of the new element.  This will let you know where the thing you added is, which will be useful for more complicated data models using dynarrays as backing store.  I've …
> dynarray append improvements

- cassandane/tiny-tests/Caldav/import_export
- cassandane/tiny-tests/Caldav/import_export_no_declined
- imap/http_caldav.c
If supplied, this param will cause events DECLINED by the user to be ommitted from the export
> http_caldav.c: add support for bulk export (GET) noDeclined query param

- cassandane/Cassandane/Cyrus/Pop3.pm
... otherwise we may call status before pop3 has committed its changes and the test will fail.
> cass: pop3 tests: Wait for QUIT to finish its work

- Makefile.am
- bench/cyrdbbench.c
There's a handful of programs that are built by `make check`, but which have nothing to do with running the unit tests.  As far as I can infer, they were probably set up this way so they'd be compiled but never installed.  That being the case, this PR makes them `noinst_PROGRAMS` instead of `check_PROGRAMS`.
Side effect: these programs will now be built by `make` or `make all`, not only `make check`.
Also fixes a typo in `bench/cyrdbbench` that I stumbled across while figuring out what it was for.
> clean up stray check programs

- lib/dynarray.c
Spent ages chasing a weird bug in a thing I'm working on, only for it to turn out that my statically initialised dynarray now had membsize==0, because it had been dynarray_fini'd on cleanup at the end of the previous unit test, and all accesses to it in the next unit test were calculating bogus offsets.  Ouch!
* ensure_alloc now asserts that membsize > 0.  Pretty much everything that needs membsize comes through here on the way in, so I didn't add assertions everywhere, just in ensure_alloc.
* dynarray_fini now preserves the membsize field.   This leaves the dynarray in the same state as dynarray_init: member size is known, but nothing is allocated.  It's now safe to re-use a dynarray after dynarray_fini, though I think the only time you'd expect to do so is in unit tests for modules that …
> more small dynarray tweaks

- imap/index.c
Fixes a crash in `cyr_virusscan`, which came in with #5392.  The crash was detected by the ClamAV tests, but they don't currently run in CI.
Looking at callers to `index_open()` and `index_open_mailbox()`, `cyrdump` probably would have crashed here too, since it also passes NULL to the init argument.
(To have the ClamAV tests run locally, install libclamav-dev (or equivalent) and rebuild, the rest is automatic.)
> index: init might be NULL

- imap/mboxlist.c
- imap/sync_support.c
This both fixes the case when deleting mailboxes that they were being written without I keys, and fixes the sync_support code to both skip sending bad records, and avoid crashing on receiving them.
> N key without I value safety

- cunit/aaa-db.testc
- lib/twom.c
As promised - a test.  It fails when run with the previous fix reverted:
```
Test: mboxlist ...[backend=skiplist] [backend=flat] [backend=twom] [backend=twoskip] passed
Test: foreach ...[backend=skiplist] [backend=flat] [backend=twom] FAILED
1. ./cunit/aaa-db.testc:1079  - CU_ASSERT_PTR_NULL(results) [backend=twom]
Test: foreach_changes ...[backend=skiplist] [backend=flat] [backend=twom] [backend=twoskip] passed
Test: binary_keys ...[backend=skiplist] [backend=flat] [backend=twom] [backend=twoskip] passed
```
The tests also found a bug in fetchnext, which I fixed as well.
> Twom test and fix fetchnext

- imap/imapd.c
If we don't release the lock, mboxlist_createmailboxcheck() will assert() when calling conversations_open_mbox()
> imapd.c: release index before sending COPY response

- cassandane/tiny-tests/Caldav/move_across_users
- imap/http_dav.c
One more assertion failure found in FM production.  Needs to be an event with per-user alarms (or other per-user properties) so the annotations database is opened before the second user is locked for us to catch it reliably, but this was a lock inversion
> Dav lock move

- cassandane/tiny-tests/List/list_return_uidvalidity
- imap/statuscache_db.c
Fixes an assert when doing a LIST RETURN STATUS over a selected mailbox and not asking for anything which loads the mailbox data.
> Status crasher

- imap/jmap_mail.c
Before, it freed the context any time decref got called and the refcount got zero or already was zero.
> jmap_mail.c: free jmapseen context when refcount goes zero

- imap/global.c
- master/masterconf.c
Even with "debug: no" in config, I was seeing a lot of syslog debugging
getting sent.  The problem seems to have been that the logmask was not
being set reliably.  This fixes that by doing a few things:
1.  The logmask-setting has been hoisted into
debug_update_log_suppression, which can be called outside the
config_toggle_debug_cb -- meaning we can call it during initial
setup.
2.  The logmask-setting now avoids explicit bit flipping in favor of the
somewhat clearer LOG_UPTO macro.  (syslog priorities are numbered
backward, so it really means "at least this priority" the way humans
would understand it.)
3.  We update log suppression immediately after loading config.
Previously, this wasn't happening, because we loaded config before
calling debug_toggle.
> global.c: change how we set logmask

- cassandane/Cassandane/Cyrus/TestCase.pm
Fixes:
> Use of uninitialized value in string at Cassandane/Cyrus/TestCase.pm line 602, <GEN2> line 1.
> TestCase: fix warning when no lsan_suppressions

- cassandane/Cassandane/Cyrus/Master.pm
- cassandane/Cassandane/Instance.pm
Direct unconditional use of getsyslog was causing this test to fail when the syslog replacement was unavailable (e.g. due to having compiled with source fortification enabled).
> Master: fix babysit syslog check

- cassandane/tiny-tests/Caldav/invite_shared_with_attachment
- imap/caldav_util.c
- imap/http_dav.c
Otherwise, annotate_anydb_islocked() can fail on an event update
> caldav_util.c: don't write lock (use a txn) when reading per-user cal data

- cassandane/tiny-tests/JMAPEmail/email_set_create_memo_ignore_convsubject
- imap/message.c
This patch disables checking the conversation subject if the "$memo" keyword is set on a message. It never makes sense to start a new conversation for a memo, it always belongs to the conversation on which it got set. This already worked in the general case, but in particular calendar invitation emails can change their subjects and attaching memos to their conversation could fail.
> message.c: do not match conversation subject if $memo keyword is set

- .gitignore
- Makefile.am
- cassandane/Cassandane/Cyrus/Master.pm
- cassandane/Cassandane/MasterEvent.pm
- changes/next/master-cron-events
- cunit/cron.testc
- cunit/master-cronevent.testc
- cunit/master-event.testc
- cunit/unit-timezones.h
- cunit/unit.c
- cunit/unit.h
- doc/examples/cyrus_conf/cmu-backend.conf
- doc/examples/cyrus_conf/murder-backend.conf
- doc/examples/cyrus_conf/murder-frontend.conf
- doc/examples/cyrus_conf/normal-master.conf
- doc/examples/cyrus_conf/normal-replica.conf
- doc/examples/cyrus_conf/normal.conf
- doc/examples/cyrus_conf/prefork.conf
- doc/examples/cyrus_conf/small.conf
- docsrc/imap/reference/manpages/configs/cyrus.conf.rst
- lib/cron-lex.l
- lib/cron-parse.y
- lib/cron.c
- lib/cron.h
- master/cronevent.c
- master/cronevent.h
- master/event.c
- master/event.h
- master/master.c
**Reviewers:** The diffs will make more sense when read commit-by-commit.
This PR adds cron-style scheduling of cyrus.conf EVENTS.  It takes a bit of a walk on the way there, the highlights are:
* rips all the existing event handling out of master.c and into a testable module (with minimal changes), and adds tests for it
* updates the new module to have a saner interface, and fixes some old bugs
* adds a parser for cron-style date/time specifications
* adds a new cronevent module based around the new parser
* updates master to support cronevents alongside the existing events
* changes the at=hhmm event handling to use the cronevent stuff under the hood (the at=hhmm cyrus.conf syntax is still supported, so no action is needed during upgrade)
The cron parser is based on the syntax described …
> cron-style scheduling of cyrus.conf EVENTS

- cassandane/Cassandane/Cyrus/Conversations.pm
- cassandane/Cassandane/Cyrus/Master.pm
- cassandane/tiny-tests/Sieve/snooze
- cassandane/tiny-tests/Sieve/snooze_bad_tzid
This fixes a few more tests that were failing in various ways when syslog was unavailable.
Found by compiling with -D_FORTIFY_SOURCE=3 (which has the side of effect of making syslog unavailable) then running Cassandane to see what failed, rather than by code audit.
> more cassandane syslog fixes

- imap/xapian_wrap.cpp
C++ <list> is a linked list but we want elisions to be in contiguous memory for efficiency.
> xapian_wrap.cpp: use vector instead of list for elisions

- cassandane/Cassandane/Instance.pm
- docsrc/imap/reference/manpages/systemcommands/cyr_dbtool.rst
- imap/cyr_dbtool.c
This fixes transaction and batch support.  Right now, '-T' is not compatible with batch; so we can't take a shared lock.
> cyr_dbtool: better handling of transaction AND batch

- cassandane/Cassandane/Cyrus/TestCase.pm
- cassandane/Cassandane/Instance.pm
After a test run, sometimes I want to very quickly find the main instance for the Foo.bar_baz test.  This is a bit of a pain.
This commit should make it a bit less of a pain.  When the test represented by &Cassandane::Cyrus::Foo::test_bar_baz is run, the /tmp/cass/XXXXX directory for its main instance will now have a `description` file that contains "Foo.bar_baz".
We can improve upon this in the future, but this should help to start.
> Cassandane: put a "description" file in most instance base dirs

- cassandane/tiny-tests/JMAPContacts/cardgroup_query
- imap/jmap_contact.c
We remove this from the filter before processing so we don't waste cycles doing a text match against that field, so we need to restore it for the response.
> jmap_contact.c: restore kind=>group filter in /query response

- cassandane/Cassandane/Cyrus/Info.pm
- changes/next/cyr-2103-sanity-check-dup-partitions
- cunit/libconfig.testc
- docsrc/imap/reference/manpages/systemcommands/cyr_info.rst
- imap/cyr_info.c
- lib/hash.c
- lib/hash.h
- lib/libconfig.c
- lib/libconfig.h
- master/master.c
#5573 reports that, when Cyrus is configured with mail and search indexes being stored in the same directory, like this:
```
defaultpartition: default
partition-default: /var/spool/imap
defaultsearchtier: default
defaultsearchpartition-default: /var/spool/imap
```
... then compacting the xapian indexes will remove all the mail and metadata files.  Seems like xapian, at least, expects total control over the directories it's configured to use.  Given that, Cyrus shouldn't be allowed to start up in this configuration.
I don't think it makes sense for _any_ of the `*partition-*` settings to share directories with one another.  Even if some combination doesn't currently break, I don't believe we expect these to overlap, so that combination might break in the future.
This PR adds a sanity check …
> config partition sanity checker

- Makefile.am
- cassandane/Cassandane/Cyrus/Delivery.pm
- cunit/auditlog.testc
- imap/auditlog.c
- imap/auditlog.h
- imap/backend.c
- imap/duplicate.c
- imap/httpd.c
- imap/imapd.c
- imap/jmap_util.c
- imap/jmap_util.h
- imap/lmtp_sieve.c
- imap/lmtpengine.c
- imap/mailbox.c
- imap/mailbox.h
- imap/mboxlist.c
- imap/pop3d.c
- imap/smmapd.c
**Reviewers:** I suggest reading this commit-by-commit.
This adds an auditlog API, providing a handful of real (type-checked!) functions for the various patterns we auditlog, and updates all existing audit logging to use it.  I think we will find it is much easier to use and maintain than syslog or xsyslog were.
The output should be mostly unchanged, except that:
* trace-id is now audit logged as `r.tid=<...>` if it was set  (see #5614)
* the `unlink` and `unlinkarchive` lines from `mailbox_cleanup_uid()` are now `remove-spool` and `remove-archive` respectively, so they don't get conflated with the `unlink` lines from `mailbox_commit()`
* some fields may be output in a different order from before
* some extra fields may be output that weren't before
* some inconsistencies have been …
> add an auditlog api

- cassandane/tiny-tests/JMAPCalendars/calendar_set_extendedprops
- cassandane/tiny-tests/JMAPMailbox/mailbox_set_extendedprops
- imap/jmap_api.h
- imap/jmap_calendar.c
- imap/jmap_mailbox.c
This will allow the server to signal to the client via /changes that it needs to sync the resource
> JMAP: bump modseq when "updating" externally stored properties

- imap/conversations.c
- imap/conversations.h
- imap/jmap_api.c
- imap/jmap_api.h
- imap/mailbox.c
- imap/message.c
This ensures that we catch the "calalarmd holds conversations open" bug if it happens again!
I have slipstreamed in my two "make it compile on Ubuntu 24.04 on WSL" commits as well.
> Cyr 2196 abort if conversations open

- cassandane/Cassandane/Cyrus/Conversations.pm
- cassandane/tiny-tests/Metadata/msg_replication_exp_bot
- cassandane/tiny-tests/Metadata/msg_replication_exp_rep
- cassandane/tiny-tests/Metadata/msg_replication_mod_bot_msh
- cassandane/tiny-tests/Metadata/msg_replication_mod_bot_msl
- cassandane/tiny-tests/Metadata/msg_replication_new_bot_mse_guh
- cassandane/tiny-tests/Metadata/msg_replication_new_bot_mse_gul
- cassandane/tiny-tests/Metadata/msg_replication_new_rep
- cassandane/tiny-tests/Replication/replication_repair_zero_msgs
- cassandane/tiny-tests/Replication/rolling_retry_wait_limit
- cassandane/tiny-tests/Replication/splitbrain
- cassandane/tiny-tests/Replication/splitbrain_bothexpunge
- cassandane/tiny-tests/Replication/splitbrain_masterexpunge
- cassandane/tiny-tests/Replication/splitbrain_replicaexpunge
- cassandane/tiny-tests/Replication/userflags
- imap/imapd.c
It's never going to be a good idea to run commands that can't be run in readonly when you're on a replica server.
> imapd: treat 'replicaonly' the same as 'readonly'
